import test from 'node:test';import assert from 'node:assert/strict';
import {newSave,heroData,skillRank,skillPoints,trainSkill,evolveSkill,validateSave,skillGate,SaveStore} from '../src/state.js';
import {HEROES} from '../src/data.js';import {rankCost,trainedCost,earnedSkillPoints,EVOLUTIONS,abilityProfile,abilityStats} from '../src/ability-progression.js';
import {performTechnique,techniqueResource} from '../src/technique-cast.js';import * as T from 'three';
test('All 23 actives have ten reachable gated ranks and two separate evolutions',()=>{let count=0;for(const [id,hero]of Object.entries(HEROES))for(const n of hero.skills.filter(n=>n.active)){count++;assert.equal(n.max,10);assert.equal(n.rankLevels.length,10);assert.ok(n.rankLevels[9]<=30);assert.equal(EVOLUTIONS[n.id].length,2);const s=newSave(id),h=heroData(s);for(let rank=skillRank(s,n.id)+1;rank<=10;rank++){h.level=n.rankLevels[rank-1]-1;assert.match(skillGate(s,n.id),/level/);h.level=30;const before=skillPoints(s);trainSkill(s,n.id);assert.equal(before-skillPoints(s),rankCost(n,rank));}assert.throws(()=>trainSkill(s,n.id));for(const p of EVOLUTIONS[n.id]){evolveSkill(s,n.id,p.id);validateSave(s);assert.equal(h.evolutions[n.id],p.id);}assert.throws(()=>evolveSkill(s,n.id,'fake'));}assert.equal(count,23);});
test('Every upgrade changes a displayed and real effect; late costs increase',()=>{for(const h of Object.values(HEROES))for(const n of h.skills.filter(n=>n.active)){for(let r=1;r<10;r++){assert.notDeepEqual(abilityStats(n.id,r),abilityStats(n.id,r+1),n.id+' '+r);for(const value of Object.values(abilityProfile(n.id,r)))if(typeof value==='number')assert.ok(Number.isFinite(value));}assert.ok(rankCost(n,10)>rankCost(n,7));assert.ok(rankCost(n,7)>rankCost(n,3));}});
test('Late hero can specialize two equipped abilities but cannot master every spell',()=>{const s=newSave('ashwright'),h=heroData(s);h.level=30;for(const id of ['fireball','quench'])while(skillRank(s,id)<10)trainSkill(s,id);assert.equal(skillPoints(s),19);assert.equal(earnedSkillPoints(30),65);trainSkill(s,'body');assert.ok(skillPoints(s)>0);const all=HEROES.ashwright.skills.filter(n=>n.active).reduce((a,n)=>a+trainedCost(n,10,HEROES.ashwright.starter.includes(n.id)),0);assert.ok(all>71*2);});
test('Legacy save keeps skills, gear and resources; new points are retroactive once',()=>{const s=newSave('ashwright'),h=heroData(s);h.level=12;h.skills={fireball:3,quench:3,body:4};delete h.evolutions;const gear=JSON.stringify(s.inventory),funds=s.supplies;validateSave(s);const first=skillPoints(s);validateSave(s);assert.equal(skillPoints(s),first);assert.deepEqual(h.skills,{fireball:3,quench:3,body:4});assert.equal(JSON.stringify(s.inventory),gear);assert.equal(s.supplies,funds);assert.deepEqual(h.evolutions,{});});
test('Early evolution, level-gate bypass and invalid evolution saves are rejected',()=>{const s=newSave('ashwright'),h=heroData(s);assert.throws(()=>evolveSkill(s,'fireball','sun'));h.skills.fireball=10;assert.throws(()=>validateSave(s));h.level=30;h.evolutions.fireball='bad';assert.throws(()=>validateSave(s));h.evolutions.fireball='sun';validateSave(s);s.battle={};assert.throws(()=>evolveSkill(s,'fireball','corona'));assert.throws(()=>trainSkill(s,'quench'));});
function harness(hero='ashwright'){const s=newSave(hero);heroData(s).level=30;const actor=(team,x=0)=>({team,pos:new T.Vector3(x,0,0),hp:10,stats:{hp:1000,damage:30},weapon:'bow',character:{attack(){}},stamina:10});const h=actor('hero'),enemies=Array.from({length:12},(_,i)=>actor('enemy',i*.35)),allies=[actor('ally',1),actor('ally',2)],g={store:{data:s},hero:h,enemies,allies,battle:{},heroStats:()=>({hp:1000,stamina:100,damage:100,healFactor:1,supportRadius:8}),world:{height:()=>0},fx:{technique(){},emit(){},roots(){},ring(){},ward(){}}},events=[],bursts=[],shots=[],zones=[],c={g,zones,later:(t,fn)=>events.push(fn),shoot:(o,t,p)=>shots.push(p),hit:(e,n)=>e.hp-=n,burst:(pos,r,d)=>bursts.push({r,d}),zone:(pos,r,time,damage,owner,kind,heal)=>{const z={r,time,damage,kind,heal};zones.push(z);return z;}};return {s,h,g,c,events,bursts,shots,zones};}
test('Both fireball evolutions have distinct targeting, damage, timings and resource costs',()=>{const a=harness();heroData(a.s).evolutions.fireball='corona';performTechnique(a.c,'fireball',10,a.g.enemies[0],new T.Vector3());a.events.forEach(fn=>fn());assert.deepEqual(a.bursts,[{r:9,d:180}]);assert.equal(a.zones[0].damage,32);assert.equal(a.shots.length,0);assert.ok(a.g.enemies[1].knock.length()>0);const b=harness();heroData(b.s).evolutions.fireball='sun';performTechnique(b.c,'fireball',10,b.g.enemies[0],new T.Vector3());b.events.forEach(fn=>fn());assert.equal(b.shots.length,1);assert.equal(b.shots[0].damage,420);assert.equal(b.shots[0].furnace.radius,6);assert.deepEqual(techniqueResource('fireball',10,'sun'),{cost:30,cooldown:10});});
test('All 46 evolutions execute finite actual mechanics rather than description-only branches',()=>{for(const [hero,data]of Object.entries(HEROES))for(const n of data.skills.filter(n=>n.active))for(const path of EVOLUTIONS[n.id]){const t=harness(hero);heroData(t.s).evolutions[n.id]=path.id;performTechnique(t.c,n.id,10,t.g.enemies[0],new T.Vector3());t.events.forEach(fn=>fn());for(const a of [t.h,...t.g.enemies,...t.g.allies])assert.ok(Number.isFinite(a.hp),n.id+path.id);assert.ok(t.shots.length||t.bursts.length||t.zones.length||t.h.dash||t.h.protect||t.h.buff||t.h.haste||t.g.enemies.some(e=>e.marked||e.rooted),n.id+path.id);for(const z of t.zones)assert.ok(Number.isFinite(z.damage)&&Number.isFinite(z.time));}});
