import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {FootstepTracker,FOOT_CONTACTS,groundSurfaceAt,armorFoley} from '../src/footsteps.js';
import {Foley,SPELL_FAMILIES,impactMaterial,soundPosition} from '../src/foley.js';
import {SPELLS} from '../src/data.js';import {newSave,validateSave} from '../src/state.js';
function footsteps(clip,seconds,speed,rate=1){const tracker=new FootstepTracker(),duration=clip==='Running_A'?.8:1.06666672,events=[];let t=0;for(let i=0;i<seconds*120;i++){t+=1/120;for(const e of tracker.update({clip,time:t*rate%duration,duration,dt:1/120,speed,grounded:true}))events.push({...e,t});}return events;}
test('Feet follow two measured contacts per clip cycle, with alternating feet and no gallop timer',()=>{for(const [clip,speed,rate]of [['Walking_A',2.2,1],['Running_A',5.4,1.2]]){const events=footsteps(clip,8,speed,rate),expected=clip==='Walking_A'?15:24;assert.ok(Math.abs(events.length-expected)<=1);for(let i=1;i<events.length;i++){assert.notEqual(events[i].foot,events[i-1].foot);assert.ok(events[i].t-events[i-1].t>.3);}assert.ok(events.every(e=>FOOT_CONTACTS[clip].some(m=>m.foot===e.foot&&m.phase===e.phase)));}});
test('Idle, blocked movement, jumps and pauses cannot continue emitting step sounds',()=>{const f=new FootstepTracker(),base={clip:'Running_A',duration:.8,speed:5,grounded:true,dt:.016};f.update({...base,time:.1});assert.equal(f.update({...base,time:.14,speed:0}).length,0);assert.equal(f.update({...base,time:.53,grounded:false}).length,0);assert.equal(f.update({...base,time:.14,dt:0}).length,0);assert.equal(f.update({...base,time:.53,enabled:false}).length,0);assert.equal(f.update({...base,time:.1,clip:'1H_Melee_Attack_Chop'}).length,0);});
test('A jump produces one landing contact instead of two feet and a catch-up burst',()=>{const f=new FootstepTracker(),base={clip:'Jump_Idle',time:0,duration:1,speed:4,dt:.1};f.update({...base,grounded:true});for(let i=0;i<6;i++)assert.equal(f.update({...base,grounded:false}).length,0);const landed=f.update({...base,grounded:true});assert.equal(landed.length,1);assert.equal(landed[0].kind,'land');assert.equal(f.update({...base,grounded:true}).length,0);});
test('Surfaces follow paving, the dirt road, vegetation, river height and actual raised supports',()=>{assert.equal(groundSurfaceAt('plain',0,0,0),'stone');assert.equal(groundSurfaceAt('plain',0,0,-35),'dirt');assert.equal(groundSurfaceAt('plain',24,0,-35),'grass');const z=-90,x=12+Math.sin(z*.045)*15;assert.equal(groundSurfaceAt('river',x,-2,z),'water');assert.notEqual(groundSurfaceAt('river',x,0,z),'water');assert.equal(groundSurfaceAt('river',x,0,z,'bridge'),'wood');assert.equal(groundSurfaceAt('river',x,-2,z,'rock'),'stone');assert.equal(groundSurfaceAt('snow',40,0,-40),'snow');assert.equal(groundSurfaceAt('quarry',40,0,-40),'stone');});
test('Clothing, leather and plate select distinct movement and impact material',()=>{assert.equal(armorFoley('hearth'),'plate');assert.equal(armorFoley('trail'),'leather');assert.equal(armorFoley('spellweave'),'cloth');assert.equal(impactMaterial({type:'knight'}),'armor');assert.equal(impactMaterial({type:'hollow',stats:{armor:2}}),'body');assert.equal(impactMaterial({character:{visual:{userData:{armorKind:'trail'}}}}),'body');});
test('Every spell has an elemental sound and all cues ship in bounded local audio banks',()=>{const m=JSON.parse(fs.readFileSync('public/sfx/foley.json'));for(const id of Object.keys(SPELLS)){assert.ok(SPELL_FAMILIES[id]);assert.ok(m.clips['cast-'+id]);assert.equal(m.clips['cast-'+id].family,SPELL_FAMILIES[id]);}for(const surface of ['stone','dirt','grass','water','wood','snow'])assert.equal(m.clips['step-'+surface].variants.length,5);for(const w of ['sword','spear','hammer','bow','crossbow'])for(const material of ['armor','body','stone','wood'])assert.ok(m.clips['hit-'+w+'-'+material].variants.length>=3);let bytes=0;for(const b of Object.values(m.banks)){assert.equal(fs.statSync('public/sfx/'+b.file).size,b.bytes);bytes+=b.bytes;}assert.ok(bytes<3e6);for(const c of Object.values(m.clips))for(const v of c.variants)assert.ok(v.offset>=0&&v.duration>0&&v.offset+v.duration<=m.banks[c.bank].seconds+.001);});
test('Distant army effects attenuate and stereo direction follows the listener',()=>{const l={x:0,z:0,yaw:0};assert.equal(soundPosition(l,{x:45,z:0}).gain,0);assert.ok(soundPosition(l,{x:0,z:25}).gain<.2);assert.ok(soundPosition(l,{x:8,z:0}).pan>0);assert.ok(soundPosition({...l,yaw:Math.PI},{x:8,z:0}).pan<0);});
test('New footstep control accepts old saves and validates new preferences',()=>{const s=newSave();assert.equal(s.settings.footsteps,.65);delete s.settings.footsteps;assert.doesNotThrow(()=>validateSave(s));s.settings.footsteps=0;assert.doesNotThrow(()=>validateSave(s));for(const invalid of [-1,1.1,NaN,Infinity]){s.settings.footsteps=invalid;assert.throws(()=>validateSave(s));}});

test('An existing offline cache cannot hide the new online combat sound manifest',async t=>{t.mock.method(globalThis,'fetch',async url=>({ok:true,json:async()=>({banks:{},release:String(url).includes('?release=')?'current':'old-cached'})}));const f=new Foley({ctx:{}});assert.ok(await f.ready);assert.equal(f.manifest.release,'current');});
test('Offline sound startup uses the precached manifest when the versioned request has no network',async t=>{t.mock.method(globalThis,'fetch',async url=>{if(String(url).includes('?'))throw Error('offline');return {ok:true,json:async()=>({banks:{},release:'precached'})};});const f=new Foley({ctx:{}});assert.ok(await f.ready);assert.equal(f.state,'ready');assert.equal(f.manifest.release,'precached');});
