import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {newSave,validateSave,makeItem,heroData} from '../src/state.js';
import {MISSIONS} from '../src/data.js';import {newSiegeState,validateSiegeState,SIEGE_GATE_Z,SIEGE_OUTPOSTS,siegeRally,siegePressure,siegeInterval,siegeConfig,migrateSiegeCheckpoint} from '../src/siege-rules.js';
import {LOGISTICS_RANKS,upgradeLogistics,commandBreakdown} from '../src/command-economy.js';import {standardIncome} from '../src/regiments.js';import {settleBattle} from '../src/battle-rewards.js';import {newBattleLedger} from '../src/battle-record.js';import {rewardVisual} from '../src/reward-visuals.js';
test('Castle logistics deducts exact cost, has campaign gates, persists, and cannot be bought in battle',()=>{const s=newSave();upgradeLogistics(s);assert.equal(s.supplies,80);assert.equal(s.castleLogistics,1);assert.throws(()=>upgradeLogistics(s));s.supplies=100000;assert.throws(()=>upgradeLogistics(s));for(let i=2;i<=5;i++){s.completed=Array.from({length:LOGISTICS_RANKS[i].unlock},(_,n)=>n);const money=s.supplies;upgradeLogistics(s);assert.equal(s.supplies,money-LOGISTICS_RANKS[i].cost);}assert.throws(()=>upgradeLogistics(s));assert.equal(validateSave(JSON.parse(JSON.stringify(s))).castleLogistics,5);const old=newSave();delete old.castleLogistics;assert.equal(validateSave(old).castleLogistics,0);const busy=newSave();busy.battle={};assert.throws(()=>upgradeLogistics(busy));});
test('Passive standards stack strongest three; death removes income and logistics multiplies every source',()=>{const g={allies:[.15,.375,.2,.25].map(commandRate=>({unit:'banner',stats:{commandRate},dead:false})),enemies:[]};assert.equal(standardIncome(g),.825);g.allies[1].dead=true;assert.equal(standardIncome(g),.6);const d=commandBreakdown({standardIncome:.6,castleIncome:.52,camp:true,research:[{id:'logistics',complete:true}]});assert.ok(Math.abs(d.total-2.424)<1e-8);assert.equal(commandBreakdown(null).total,.75);});
test('All siege routes are halved and four forward rallies progress without teleporting the hero',()=>{assert.equal(Math.abs(SIEGE_GATE_Z+17),945);for(const m of MISSIONS.filter(m=>m.mode==='siege')){const st=newSiegeState(m);assert.doesNotThrow(()=>validateSiegeState(st,m));assert.equal(siegeRally({siege:st}).z,-30);st.outposts[1]=true;assert.equal(siegeRally({siege:st}).z,SIEGE_OUTPOSTS[1].z+8);st.outposts.push(true);assert.throws(()=>validateSiegeState(st,m));assert.ok(siegeInterval(m,6)<siegeInterval(m,1));assert.ok(siegeConfig(m).hp.keep>=2100);assert.equal(siegePressure(m,1200),6);}});
test('Extended-field chest positions survive battle settlement and reload',()=>{const s=newSave();s.completed=[0];const ledger=newBattleLedger(1);ledger.chests=[{id:'deep-field',rarity:1,pos:{x:0,y:3,z:-1940},secured:true,rewards:{supplies:10,salvage:2,items:[makeItem('bow',1,1)]}}];settleBattle(s,{id:24,reportID:'deep-field',time:800,wave:6,gate:100,maxGate:100,core:650,ledger,research:[],siege:newSiegeState(MISSIONS[24])},true);assert.doesNotThrow(()=>validateSave(s));const bad=structuredClone(s);bad.lastBattle.chests[0].pos.z=-50000;assert.throws(()=>validateSave(bad));});
test('Unlock visual resolves to matching troop, map, actual earned item, and future rank',()=>{const s=newSave();const report=settleBattle(s,{id:0,reportID:'visuals',time:120,wave:3,gate:100,maxGate:100,core:650,ledger:newBattleLedger(1),research:[]},true);const item=report.items[0];assert.equal(rewardVisual(s,{kind:'item',id:item.id}).item.id,item.id);assert.equal(rewardVisual(s,{kind:'territory',id:'24'}).mission,24);assert.deepEqual(rewardVisual(s,{kind:'unit',id:'bow'}),{type:'unit',id:'bow'});assert.equal(rewardVisual(s,{kind:'lesson',id:'ranks',rank:7}).rank,7);assert.ok(report.tutorial.cards.some(c=>c.kind==='territory'&&c.id==='1'));assert.ok(report.tutorial.cards.some(c=>c.kind==='item'&&c.id===item.id));});
test('Time pressure cannot reach fortress intensity at the first road camp, and reaches six at the fortress',()=>{const m=MISSIONS[32];assert.equal(siegePressure(m,1000,false,-150),2);assert.equal(siegePressure(m,1000,false,-425),3);assert.equal(siegePressure(m,1000,false,-650),4);assert.equal(siegePressure(m,1000,false,-825),5);assert.equal(siegePressure(m,1000,false,-950),6);});

test('Short-road migration preserves castle damage, army, progress and local fortress distances exactly once',()=>{const m=MISSIONS[24],siege={...newSiegeState(m),version:2,frontier:-1907},old={siege,hero:{pos:{x:0,y:3,z:-1900}},holdPoint:{x:0,z:-1100},allies:[{hp:90,pos:{x:3,y:0,z:-1100}}],enemies:[{hp:80,pos:{x:-2,y:0,z:-1905}}],ledger:{chests:[{pos:{x:1,y:0,z:-1888}}]}};old.siege.hp.gate=400;old.siege.outposts[0]=true;const next=migrateSiegeCheckpoint(old,m);assert.equal(next.hero.pos.z,-955);assert.equal(next.enemies[0].pos.z,-960);assert.equal(next.siege.hp.gate,400);assert.equal(next.allies[0].hp,90);assert.ok(next.siege.outposts[0]);assert.equal(next.siege.version,3);assert.deepEqual(migrateSiegeCheckpoint(next,m),next);assert.equal(old.hero.pos.z,-1900);validateSiegeState(next.siege,m);});
