import test from 'node:test';import assert from 'node:assert/strict';
import {RESEARCH,startResearch,cancelResearch,advanceResearch,battleUnitStats,battleDefenseStats,validateBattleResearch} from '../src/research.js';
import {newSave,validateSave} from '../src/state.js';import {unitStats,defenseFiringStats} from '../src/data.js';
const battle=()=>({research:[],command:100,recentRecruits:[]});
test('Research uses four timed battle slots without spending Command or permanent resources',()=>{const s=newSave(),b=battle(),before=JSON.stringify(s);for(const id of ['longbow','shield','gate','windlass'])startResearch(b,s,id);assert.equal(b.research.length,4);assert.equal(b.command,100);assert.equal(JSON.stringify(s),before);assert.throws(()=>startResearch(b,s,'longbow'));s.completed=[0,1,2,3,4];assert.throws(()=>startResearch(b,s,'runic'));});
test('Research progresses concurrently and applies only after its full battle time',()=>{const b=battle(),s=newSave();startResearch(b,s,'longbow');startResearch(b,s,'shield');assert.deepEqual(advanceResearch(b,24),[]);assert.equal(battleUnitStats('bow',1,b).reach,unitStats('bow',1).reach);assert.deepEqual(advanceResearch(b,1),['longbow']);assert.equal(b.research[1].remaining,10);assert.equal(battleUnitStats('bow',1,b).reach,31.25);assert.equal(battleUnitStats('bow',1,b).cost,50);assert.deepEqual(advanceResearch(b,10),['shield']);assert.deepEqual(advanceResearch(b,200),[]);});
test('Canceling unfinished work frees a slot and restarting loses previous progress',()=>{const b=battle(),s=newSave();startResearch(b,s,'gate');advanceResearch(b,15);cancelResearch(b,'gate');assert.equal(b.research.length,0);startResearch(b,s,'gate');assert.equal(b.research[0].remaining,40);advanceResearch(b,40);assert.throws(()=>cancelResearch(b,'gate'));});
test('Every research effect modifies its intended troop or defense and never changes base stats',()=>{const s=newSave();s.completed=Array.from({length:15},(_,i)=>i);for(const [id,d]of Object.entries(RESEARCH)){const b=battle();startResearch(b,s,id);advanceResearch(b,d.seconds);if(id==='shield'){assert.equal(battleUnitStats('shield',1,b).hp,150);assert.equal(battleUnitStats('shield',1,b).damage,19.2);assert.equal(battleUnitStats('shield',1,b).cost,40);}if(id==='pike')assert.equal(battleUnitStats('pike',1,b).damage,Math.round(unitStats('pike',1).damage*135)/100);if(id==='runic')for(const unit of ['lantern','pyre','frost','dawn']){assert.equal(battleUnitStats(unit,1,b).healFactor,1.25);assert.equal(battleUnitStats(unit,1,b).hp,Math.round(unitStats(unit,1).hp*1.15));}if(id==='gate')assert.equal(battleDefenseStats('gate',1,null,b).hp,1494);if(id==='windlass')for(const unit of ['tower','ballista','cannon','mortar'])assert.equal(battleDefenseStats(unit,5,'longwatch',b).interval,defenseFiringStats(unit,5,'longwatch').interval/1.2);if(id==='payload')for(const unit of ['ballista','cannon','mortar'])assert.equal(battleDefenseStats(unit,1,null,b).damage,defenseFiringStats(unit,1).damage*1.25);if(id==='wards')for(const unit of ['frost','storm','sanctuary']){assert.equal(battleDefenseStats(unit,1,null,b).range,Math.round(defenseFiringStats(unit,1).range*120)/100);assert.equal(battleDefenseStats(unit,1,null,b).damage,defenseFiringStats(unit,1).damage*1.25);}}
 assert.equal(unitStats('shield',1).hp,120);assert.equal(unitStats('bow',1).cost,45);assert.equal(defenseFiringStats('gate',1).hp,1245);});
test('Research unlocks follow territory progress, and new battles have no inherited bonuses',()=>{const s=newSave();assert.throws(()=>startResearch(battle(),s,'pike'));s.completed=[0];assert.doesNotThrow(()=>startResearch(battle(),s,'pike'));assert.throws(()=>startResearch(battle(),s,'runic'));assert.equal(battleUnitStats('bow',1,battle()).reach,25);assert.equal(battleDefenseStats('gate',1,null,battle()).hp,1245);});
test('Research validation rejects duplicate slots, impossible timers, unknown projects and corrupted shortcuts',()=>{for(const change of [b=>b.research=[{id:'unknown',remaining:10,complete:false}],b=>b.research=[{id:'longbow',remaining:Infinity,complete:false}],b=>b.research=[{id:'longbow',remaining:20,complete:true}],b=>b.research=[{id:'longbow',remaining:0,complete:false}],b=>b.research=Array.from({length:5},()=>({id:'gate',remaining:20,complete:false})),b=>b.recentRecruits=['bow','bow'],b=>b.recentRecruits=['unknown']]){const b=battle();change(b);assert.throws(()=>validateBattleResearch(b));}assert.doesNotThrow(()=>validateBattleResearch({}));});
test('Current and legacy suspended saves retain earned gear while research resumes exactly',()=>{const s=newSave(),gear=JSON.stringify(s.inventory);s.battle={...battle(),id:0,wave:1,nextWave:30,gate:100,maxGate:1245,core:650,time:12,hero:{pos:{x:0,y:0,z:-27},hp:100,focus:100,stamina:100},enemies:[],allies:[]};startResearch(s.battle,s,'longbow');advanceResearch(s.battle,12);s.battle.recentRecruits=['bow','shield'];const restored=validateSave(JSON.parse(JSON.stringify(s)));assert.equal(restored.battle.research[0].remaining,13);assert.equal(JSON.stringify(restored.inventory),gear);assert.deepEqual(restored.battle.recentRecruits,['bow','shield']);delete s.battle.research;delete s.battle.recentRecruits;assert.doesNotThrow(()=>validateSave(s));});
