import test from 'node:test';import assert from 'node:assert/strict';
import {MISSIONS} from '../src/data.js';
import {missionUnlocked,missionWon,nextCampaignMission,territoryIncome} from '../src/campaign.js';
import {isSiege,siegeConfig,siegePressure,siegeInterval,siegePacket,newSiegeState,validateSiegeState} from '../src/siege-rules.js';
import {newSave,completeMission,validateSave} from '../src/state.js';
import {newBattleLedger,validateBattleReport} from '../src/battle-record.js';
import {settleBattle} from '../src/battle-rewards.js';
test('Every optional rescue attacks a castle; the 24 core missions remain defenses',()=>{assert.equal(MISSIONS.filter(m=>m.kind==='settlement'&&isSiege(m)).length,8);assert.ok(MISSIONS.filter(m=>m.kind==='main').every(m=>m.mode==='defense'));assert.equal(MISSIONS[23].name,'The Last Dawn');assert.equal(MISSIONS[23].biome,'plain');assert.equal(MISSIONS[23].seed,MISSIONS[0].seed);assert.equal(MISSIONS[23].bossName,'The Hollow King');});
test('Final fortress is required between defense 23 and the last defense',()=>{const s=newSave();s.completed=Array.from({length:22},(_,i)=>i);assert.equal(nextCampaignMission(s,MISSIONS).id,22);assert.ok(!missionUnlocked(s,MISSIONS[32]));assert.ok(!missionUnlocked(s,MISSIONS[23]));completeMission(s,22);assert.equal(nextCampaignMission(s,MISSIONS).id,32);assert.throws(()=>completeMission(s,23));completeMission(s,32);assert.deepEqual(s.fortresses,[32]);assert.equal(s.completed.length,23);assert.equal(s.ending,null);assert.equal(nextCampaignMission(s,MISSIONS).id,23);completeMission(s,23);assert.ok(s.ending);assert.equal(s.completed.length,24);assert.doesNotThrow(()=>validateSave(s));});
test('A previously completed campaign stays completed and all earned rescues are preserved',()=>{const s=newSave();s.completed=Array.from({length:24},(_,i)=>i);s.settlements=[24,25];delete s.fortresses;validateSave(s);assert.ok(missionWon(s,MISSIONS[23]));assert.ok(missionUnlocked(s,MISSIONS[23]));assert.equal(nextCampaignMission(s,MISSIONS).id,23);assert.equal(territoryIncome(s),70);assert.deepEqual(s.fortresses,[]);});
test('Reinforcement frequency and packet size increase with time and the breach',()=>{for(const m of MISSIONS.filter(isSiege)){let rate=0;for(let tier=1;tier<=6;tier++){const current=siegePacket(m,tier)/siegeInterval(m,tier);assert.ok(current>rate);rate=current;}assert.equal(siegePressure(m,0),1);assert.equal(siegePressure(m,0,true),2);assert.equal(siegePressure(m,9999),6);assert.ok(siegeInterval(m,6)<siegeInterval(m,1)*.65);assert.ok(siegeConfig(m).limit<=58);}assert.ok(siegeConfig(MISSIONS[32]).hp.keep>siegeConfig(MISSIONS[31]).hp.keep);assert.ok(siegeInterval(MISSIONS[32],6)<siegeInterval(MISSIONS[31],6));});
test('Fortress saves preserve damage and reject impossible health or pressure',()=>{const m=MISSIONS[24],state=newSiegeState(m);state.hp.gate=0;state.destroyed=1;state.damage=siegeConfig(m).hp.gate;state.heroDamage=state.damage;state.pressure=2;validateSiegeState(state,m);const copy=structuredClone(state);assert.deepEqual(copy,state);for(const bad of [{...state,pressure:8},{...state,hp:{...state.hp,keep:NaN}},{...state,damage:-1},{...state,nextSpawn:Infinity}])assert.throws(()=>validateSiegeState(bad,m));assert.throws(()=>validateSiegeState(state,MISSIONS[0]));});
test('Siege reports settle once, rescue pays future tribute, and final fortress does not pay tribute',()=>{const s=newSave();s.completed=[0];const siege=newSiegeState(MISSIONS[24]);siege.hp.gate=0;siege.hp.keep=0;siege.destroyed=2;siege.damage=1180;siege.heroDamage=1180;const b={id:24,reportID:'siege-rescue',time:215,wave:4,gate:1200,maxGate:1200,core:650,research:[],ledger:newBattleLedger(1),siege};const report=settleBattle(s,b,true);assert.equal(report.siege.destroyed,2);assert.equal(report.rescued,true);assert.equal(report.income,0);assert.equal(territoryIncome(s),28);assert.doesNotThrow(()=>validateBattleReport(report));const money=s.supplies;settleBattle(s,b,true);assert.equal(s.supplies,money);s.completed=Array.from({length:23},(_,i)=>i);const reward=completeMission(s,32);assert.equal(reward.income,0);assert.equal(s.settlements.length,1);assert.equal(territoryIncome(s),28);});

test('Later assaults provide deployment funds without changing recurring Command income',()=>{assert.equal(siegeConfig(MISSIONS[24]).command,55);assert.equal(siegeConfig(MISSIONS[32]).command,180);let prior=0;for(const m of MISSIONS.filter(isSiege)){assert.ok(siegeConfig(m).command>=prior);prior=siegeConfig(m).command;}assert.ok(prior<=220);});
