import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.argv.includes('--playwright-module')?process.argv[process.argv.indexOf('--playwright-module')+1]:'playwright'));
const base=process.env.GAME_URL||'http://127.0.0.1:4178',out='work/qa-armor';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]}),context=await browser.newContext({viewport:{width:1280,height:720},hasTouch:true}),page=await context.newPage(),errors=[],report={url:base,checks:[],errors};page.on('pageerror',e=>errors.push(e.message));const check=(n,v=true)=>{assert.ok(v,n);report.checks.push(n);console.log('PASS',n);};
try{
 await page.goto(base);await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#new-game').click();await page.locator('#begin-oath').click();while(await page.locator('#story-next').isVisible())await page.locator('#story-next').click();
 await page.evaluate(async()=>{const g=window.__oathfire,{makeItem}=await import('/src/state.js'),{ARMOR_DROPS}=await import('/src/armor.js');g.store.commit(s=>{s.guide.active=false;s.supplies=100000;s.salvage=10000;for(const kind of ARMOR_DROPS){const i=makeItem('armor',0,1,()=>.4,kind);i.id='qa-'+kind;s.inventory.push(i);}});g.ui.open('equipment');});
 check('Armory exposes four separate equipment slots',await page.locator('[data-action="equipment-slot"]').count()===4);
 await page.locator('[data-action="equipment-slot"][data-id="armor"]').click();check('Armor filter lists seven patterns and hides weapons',await page.locator('[data-action="item"]').count()===7&&(await page.locator('.inventory').innerText()).includes('Starwoven'));
 const initial=await page.evaluate(()=>{const g=window.__oathfire;return {weapon:g.store.data.heroes.warden.equipped.weapon,armor:g.store.data.heroes.warden.equipped.armor,hp:g.hero.hp};});
 await page.locator('[data-action="item"][data-id="qa-ember"]').click();check('Trying on armor previews the candidate without equipping it',await page.evaluate(old=>{const g=window.__oathfire;return g.ui.preview.armor.armorKind==='ember'&&g.hero.character.armor.armorKind==='hearth'&&g.store.data.heroes.warden.equipped.armor===old;},initial.armor));
 check('Comparison shows real fire resistance and charged damage',(await page.locator('.armor-comparison').innerText()).includes('0% → 25%')&&(await page.locator('.armor-benefits').innerText()).includes('12% charged'));
 await page.locator('[data-action="equip"][data-id="qa-ember"]').click();check('Equipping updates world armor while preserving weapon and current health',await page.evaluate(b=>{const g=window.__oathfire;return g.hero.character.armor.armorKind==='ember'&&g.store.data.heroes.warden.equipped.weapon===b.weapon&&g.hero.hp===b.hp;},initial));
 await page.screenshot({path:out+'/01-cinderforged.png'});
 for(let i=0;i<6;i++)await page.locator('[data-action="forge"][data-id="qa-ember"]').click();await page.locator('[data-action="rune"][data-value="ember"]').click();await page.locator('[data-action="temper"][data-value="sunder"]').click();
 check('Armor-specific rune and temper text matches their actual effects',(await page.locator('.armor-benefits').innerText()).includes('44.5% incoming fire')&&(await page.locator('.armor-benefits').innerText()).includes('24.2% charged'));
 check('Forge updates worn and preview construction immediately',await page.evaluate(()=>{const g=window.__oathfire;return g.hero.character.armor.plus===6&&g.ui.preview.armor.plus===6;}));
 // Measure the running combat system with equal armor values to isolate the passive effects.
 const combat=await page.evaluate(async()=>{const g=window.__oathfire,{heroStats}=await import('/src/state.js');g.beginMission(0);g.ui.open('pause');g.combat.clear();g.battle.nextWave=999;for(const e of [...g.enemies,...g.allies]){e.character.dispose();if(e.phys)g.physics.removeActor(e.phys);}g.enemies=[];g.allies=[];
 const h=g.hero,e=g.spawnEnemy('knight',{x:0,y:0,z:-29},{training:true,hp:100000,stats:{hp:100000,armor:0}}),a=g.spawnAlly('bow',{x:0,y:0,z:-21});
 const equip=kind=>{const item=g.store.data.inventory.find(i=>i.type==='armor'&&i.armorKind===kind);item.base=12;item.rarity=0;item.affix=null;item.plus=0;item.rune=null;item.temper=null;item.awakened=false;g.store.data.heroes.warden.equipped.armor=item.id;g.refreshHero();h.hp=heroStats(g.store.data).hp;h.stamina=80;h.invuln=0;h.protect=0;h.guarding=false;h.riposte=0;h.buff=0;h.empowered=0;};
 const incoming=(kind,fire)=>{equip(kind);const old=h.hp;g.combat.hit(h,120,e,{fire});return old-h.hp;};
 const damage={normal:incoming('hearth',true),fire:incoming('ember',true),physical:incoming('ember',false)};
 const guard=kind=>{equip(kind);h.guarding=true;h.guardTime=1;h.facing=Math.PI;const old=h.stamina;g.combat.hit(h,120,e);return old-h.stamina;};damage.block=guard('hearth');damage.bastion=guard('bastion');
 const ally=kind=>{equip(kind);e.hp=100000;g.combat.hit(e,100,a,{projectile:true});return 100000-e.hp;};damage.allyNormal=ally('hearth');damage.allyBuffed=ally('marshal');a.pos.z=-15;damage.allyOutside=ally('marshal');
 const charged=(kind,heavy)=>{equip(kind);e.pos.copy(h.pos);e.pos.z-=1.8;h.cooldown=0;h.stamina=100;g.view.yaw=0;e.hp=100000;e.invuln=0;e.sunder=0;g.combat.clear();g.combat.attack(h,heavy);g.combat.update(1);return 100000-e.hp;};damage.heavy=charged('hearth',true);damage.emberHeavy=charged('ember',true);damage.light=charged('hearth',false);damage.emberLight=charged('ember',false);
 const heal=kind=>{equip(kind);h.hp=10;g.store.data.potions=3;g.potion();return h.hp-10;};damage.potion=heal('hearth');damage.dawnPotion=heal('dawn');
 // Fixed simulation steps test live recovery, including guard's deliberately low regeneration.
 const recovery=(kind,guard=false)=>{equip(kind);g.combat.clear();g.ui.close();g.input.clear();g.input.guard=guard;h.stamina=0;h.focus=0;h.cooldown=0;h.attacking=false;g.battle.nextWave=999;g.enemies=[e];e.training=true;g.allies=[];for(let i=0;i<60;i++)g.tick(1/60);g.ui.open('pause');return {focus:h.focus,stamina:h.stamina};};damage.recovery=recovery('hearth');damage.caster=recovery('spellweave');damage.scout=recovery('trail');damage.scoutGuard=recovery('trail',true);
 return damage;});report.combat=combat;
 check('Fire armor reduces fire damage while physical hits stay unchanged',combat.fire<combat.normal&&combat.physical===combat.normal);
 check('Bastion reduces actual block stamina consumption',combat.bastion<combat.block);
 check('Command aura buffs troops at its extended radius but not outside it',combat.allyBuffed===110&&combat.allyNormal===100&&combat.allyOutside===100);
 check('Cinderforged boosts charged strikes without boosting quick strikes',combat.emberHeavy>combat.heavy&&combat.heavy>0&&combat.light===combat.emberLight);
 check('Dawnkeeper increases actual healing draught recovery',combat.potion===100&&combat.dawnPotion===120);
 check('Starwoven improves focus recovery during live battle ticks',Math.abs(combat.caster.focus-4.55)<.01&&Math.abs(combat.recovery.focus-3.5)<.01);
 check('Wayfarer improves resting stamina recovery but not guarding recovery',Math.abs(combat.scout.stamina-22.5)<.01&&Math.abs(combat.scoutGuard.stamina-2)<.01);
 const models=await page.evaluate(async()=>{const g=window.__oathfire,{ARMOR_DROPS}=await import('/src/armor.js'),C=g.hero.character.constructor,result={};for(const kind of ARMOR_DROPS){const item=g.store.data.inventory.find(i=>i.armorKind===kind);result[kind]=[];for(let plus=0;plus<=10;plus++){const c=new C('Knight',{weapon:'sword',design:'warden',armor:{...item,plus}});c.update(.1,{speed:4});let vertices=0;c.root.traverse(o=>{if(o.geometry)vertices+=o.geometry.attributes.position.count;});const bone=c.sockets.upperlegl.quaternion.clone();c.update(.16,{speed:4});result[kind].push({vertices,moving:1-Math.abs(bone.dot(c.sockets.upperlegl.quaternion))>.00001,skinned:c.body.every(b=>b.isSkinnedMesh&&b.geometry.attributes.skinWeight.count>0)});c.dispose();}}return result;});report.models=models;
 check('All six armor patterns animate with the full body skeleton',Object.values(models).every(arr=>arr.every(m=>m.moving&&m.skinned)));
 check('Every armor forge level changes visible geometry',Object.values(models).every(arr=>new Set(arr.map(m=>m.vertices)).size===11));
 check('Each pattern has a distinct constructed silhouette',new Set(Object.values(models).map(arr=>arr[0].vertices)).size===6);
 await page.evaluate(()=>{const g=window.__oathfire;g.input.guard=false;g.returnHome();g.ui.inventoryFilter='armor';g.ui.item='qa-marshal';g.ui.open('equipment');});await page.locator('[data-action="equip"][data-id="qa-marshal"]').click();
 await page.evaluate(async()=>{const g=window.__oathfire,{ARMORS}=await import('/src/armor.js');g.store.commit(s=>{for(const i of s.inventory)if(i.armorKind)i.base=ARMORS[i.armorKind].base;});g.refreshHero();g.ui.draw();});
 await page.setViewportSize({width:844,height:390});await page.waitForTimeout(250);await page.locator('.item-info').scrollIntoViewIfNeeded();await page.waitForFunction(()=>!document.querySelector('.toast'));await page.screenshot({path:out+'/02-mobile-comparison.png'});
 check('Real landscape viewport has no horizontal menu overflow',await page.evaluate(()=>innerWidth===844&&innerHeight===390&&document.querySelector('#menu-content').scrollWidth<=document.querySelector('#menu-content').clientWidth+1));
 check('Armor action buttons stay within the landscape content pane',await page.locator('[data-action="equip"][data-id="qa-marshal"]').evaluate(e=>{const r=e.getBoundingClientRect(),p=document.querySelector('#menu-content').getBoundingClientRect();return r.left>=p.left&&r.right<=p.right;}));
 await page.evaluate(()=>window.__oathfire.checkpoint());const save=await page.evaluate(()=>window.__oathfire.store.export());await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').click();
 check('Equipped pattern and resources survive reload',await page.evaluate(raw=>{const before=JSON.parse(raw).campaign,g=window.__oathfire,s=g.store.data;return s.heroes.warden.equipped.armor==='qa-marshal'&&g.hero.character.armor.armorKind==='marshal'&&s.supplies===before.supplies&&s.salvage===before.salvage&&JSON.stringify(s.inventory)===JSON.stringify(before.inventory);},save));
 // Screenshots show the actual rendered gear, never a painted mockup.
 await page.setViewportSize({width:1280,height:720});await page.evaluate(()=>{const g=window.__oathfire;g.ui.inventoryFilter='armor';g.ui.item='qa-spellweave';g.ui.open('equipment');});await page.locator('.item-info').scrollIntoViewIfNeeded();await page.waitForTimeout(200);await page.waitForFunction(()=>!document.querySelector('.toast'));await page.screenshot({path:out+'/03-starwoven.png'});
 await page.locator('[data-action="item"][data-id="qa-bastion"]').click();await page.locator('.item-info').scrollIntoViewIfNeeded();await page.waitForTimeout(200);await page.screenshot({path:out+'/04-bastion.png'});
 check('No browser runtime errors',errors.length===0);
}catch(e){report.failure=e.message;console.error(e.stack);await page.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
