import {createRequire} from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {newSave} from '../src/state.js';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright'),base=process.env.GAME_URL||'http://127.0.0.1:4179',out=process.env.QA_OUT||'work/qa-assault';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=metal']}),page=await browser.newPage({viewport:{width:844,height:390}}),report={checks:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);console.log('PASS',name);};
try{
 const save=newSave();save.guide.active=false;save.guide.seen.push('prologue');save.completed=Array.from({length:23},(_,i)=>i);
 await page.goto(base);await page.waitForFunction(()=>window.__oathfire?.ready);await page.evaluate(async s=>{const g=window.__oathfire;g.store.import(JSON.stringify(s));await g.start(null,true);g.ui.close();g.testTick=g.tick.bind(g);g.tick=()=>{};g.beginMission(0);g.battle.nextWave=10000;g.world.towerObjects.forEach(t=>t.cooldown=10000);for(const a of [...g.allies])g.combat.kill(a,null);g.physics.teleport(g.hero.phys,{x:6,y:0,z:-40});g.hero.pos.set(6,0,-40);g.physics.step();},save);
 report.targeting=await page.evaluate(()=>{const g=window.__oathfire,e=g.spawnEnemy('hollow',{x:0,z:-40});g.physics.step();g.ai(e,1/60);const ignoresNearby=g.combat.target(e,22)===null&&e.gateTarget&&e.velocity.z>0;g.combat.hit(e,1,g.hero,{silent:true});const heroReprisal=g.combat.target(e,22)===g.hero;const a=g.spawnAlly('shield',{x:2,z:-43});g.combat.hit(e,1,a,{silent:true});const allyReprisal=g.combat.target(e,22)===a;g.combat.kill(a,null);const resumes=g.combat.target(e,22)===null;const hunter=g.spawnEnemy('longbow',{x:0,z:-45});const hunts=g.combat.target(hunter,35)===g.hero;g.combat.kill(e,null);g.combat.kill(hunter,null);return{ignoresNearby,heroReprisal,allyReprisal,resumes,hunts};});
 for(const[n,ok]of Object.entries(report.targeting))check('Enemy intent: '+n,ok);
 report.castle=await page.evaluate(()=>{const g=window.__oathfire,e=g.spawnEnemy('archer',{x:0,z:-37},{cooldown:0}),before=g.battle.gate,shot=g.combat.stats.projectiles;g.physics.step();g.ai(e,1/60);for(let i=0;i<24;i++)g.combat.update(1/60);const beforeContact=g.battle.gate===before;for(let i=0;i<150;i++)g.combat.update(1/60);const afterArrow=g.battle.gate;g.combat.kill(e,null);const melee=g.spawnEnemy('hollow',{x:0,z:-27},{cooldown:0});g.physics.step();for(let i=0;i<600;i++){melee.cooldown=Math.max(0,melee.cooldown-1/60);g.ai(melee,1/60);g.physics.step();g.physics.position(melee.phys,melee.pos);g.combat.update(1/60);}const afterMelee=g.battle.gate;g.combat.kill(melee,null);return{before,beforeContact,afterArrow,afterMelee,meleePos:melee.pos.toArray(),gatePos:g.gatePos.toArray(),meleeRange:melee.stats.range,meleeVelocity:melee.velocity.toArray(),projectiles:g.combat.stats.projectiles-shot};});
 check('Castle-directed archers fire real projectiles before doing damage',report.castle.beforeContact&&report.castle.projectiles>0&&report.castle.afterArrow<report.castle.before);
 check('Unprovoked melee soldiers strike the castle',report.castle.afterMelee<report.castle.afterArrow);
 const start=await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(0);g.battle.nextWave=0;g.battleTick(.01);return{wave:g.battle.wave,spawned:g.enemies.length,total:g.battle.assault.entries.length,duration:g.battle.assault.duration};});report.start=start;check('A wave opens with a small vanguard, not its whole army',start.wave===1&&start.spawned<=4&&start.total>start.spawned&&start.duration>=60);
 const gap=await page.evaluate(()=>{const g=window.__oathfire;for(const e of [...g.enemies])if(!e.dead)g.combat.kill(e,null);g.battleTick(2);return{wave:g.battle.wave,pending:g.battle.assault.cursor<g.battle.assault.entries.length,mode:g.mode};});check('Clearing the opening group does not skip the rest of the wave',gap.wave===1&&gap.pending&&gap.mode==='play');
 const stream=await page.evaluate(()=>{const g=window.__oathfire,packets=[];for(let t=0;t<130&&g.battle.assault.cursor<g.battle.assault.entries.length;t++){const cursor=g.battle.assault.cursor;g.battleTick(1);if(g.battle.assault.cursor>cursor)packets.push({time:g.battle.assault.elapsed,count:g.battle.assault.cursor-cursor});if(g.battle.assault.cursor<g.battle.assault.entries.length)for(const e of [...g.enemies])if(!e.dead)g.combat.kill(e,null);}g.battleTick(20);return{packets,wave:g.battle.wave,alive:g.enemies.filter(e=>!e.dead).length};});report.stream=stream;check('More packets arrive throughout the assault and surviving tail troops hold the wave open',stream.packets.length>=6&&stream.packets.at(-1).time>=60&&stream.wave===1&&stream.alive>0);
 await page.evaluate(()=>{const g=window.__oathfire;for(const e of [...g.enemies])if(!e.dead)g.combat.kill(e,null);g.battleTick(8.1);g.battleTick(23);g.checkpoint();});
 const before=await page.evaluate(()=>{const g=window.__oathfire;return{assault:JSON.stringify(g.store.data.battle.assault),enemies:g.store.data.battle.enemies.map(e=>({id:e.id,type:e.type,boost:e.assaultBoost,hp:e.hp})),wave:g.battle.wave};});check('The next wave begins only after the tail is cleared',before.wave===2);
 await page.evaluate(async()=>{const g=window.__oathfire;g.store.import(g.store.export());await g.start(null,true);});
 const restored=await page.evaluate(()=>{const g=window.__oathfire;return{assault:JSON.stringify(g.battle.assault),enemies:g.enemies.map(e=>({id:e.id,type:e.type,boost:e.assaultBoost,hp:e.hp}))};});
 check('Save/resume preserves schedule cursor, enemy identity, health and assault strength',before.assault===restored.assault&&JSON.stringify(before.enemies)===JSON.stringify(restored.enemies));
 for(const [w,h]of[[844,390],[667,375]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>window.__oathfire.ui.hud(0));check('Reinforcement countdown is visible and contained at '+w,await page.locator('#combat-wave').evaluate(e=>{const r=e.getBoundingClientRect();return e.textContent.includes('Reinforcements')&&r.right<=innerWidth&&r.bottom<=innerHeight;}));await page.screenshot({path:out+'/assault-hud-'+w+'.jpg',quality:86});}
 report.boss=await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(4);g.battle.wave=2;g.spawnWave();const early=g.enemies.some(e=>e.type==='boss');for(const e of [...g.enemies])if(!e.dead)g.combat.kill(e,null);while(g.battle.assault.cursor<g.battle.assault.entries.length){g.spawnReinforcements(120);for(const e of [...g.enemies])if(!e.dead&&e.type!=='boss')g.combat.kill(e,null);}const bosses=g.enemies.filter(e=>!e.dead&&e.type==='boss'),music=g.battle.bossTheme;g.battleTick(.01);const waits=g.mode==='play';for(const e of bosses)g.combat.kill(e,g.hero);g.battleTick(.01);return{early,bosses:bosses.length,music,waits,win:g.store.data.lastBattle?.win,celebration:!document.querySelector('#victory-transition').hidden};});
 check('Boss arrives with the final reinforcements and starts its music',!report.boss.early&&report.boss.bosses===1&&report.boss.music);
 check('Final wave requires all enemies defeated before the success transition',report.boss.waits&&report.boss.win&&report.boss.celebration);
 check('No browser or rendering runtime errors',report.errors.length===0);
}catch(e){report.failure=e.stack;console.error(e.stack);process.exitCode=1;await page.screenshot({path:out+'/failure.jpg',quality:88}).catch(()=>{});}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
