import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.argv.includes('--playwright-module')?process.argv[process.argv.indexOf('--playwright-module')+1]:'playwright'));
const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]}),page=await browser.newPage({viewport:{width:844,height:390}}),errors=[],report={checks:[],scenarios:[],errors};page.on('pageerror',e=>errors.push(e.message));const check=(name,ok)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS',name);};
try{await page.goto(process.env.GAME_URL||'http://127.0.0.1:4180');await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#new-game').click();await page.locator('#begin-oath').click();await page.locator('#story-skip').click();
 // Step real AI, Rapier collision sweeps and projectiles while the render loop is paused.
 for(const scenario of [{id:'shield',x:82,z:-130},{id:'bow',x:-78,z:-140},{id:'pike',x:55,z:-170}]){const r=await page.evaluate(async scenario=>{const g=window.__oathfire;g.beginMission(0);g.ui.open('army');g.battle.nextWave=9999;for(const a of g.allies){a.character.dispose();g.physics.removeActor(a.phys);}g.allies=[];g.combat.clear();g.store.data.completed=Array.from({length:15},(_,i)=>i);g.battle.command=220;g.recruit(scenario.id);const e=g.spawnEnemy('brute',{x:scenario.x,z:scenario.z}),a=g.allies[0],start=a.pos.distanceTo(e.pos),hp=e.hp;let steps=0,closest=start,firstDamage=null;
 for(;steps<60*110&&!e.dead;steps++){g.time+=1/60;for(const u of g.allies){u.cooldown=Math.max(0,u.cooldown-1/60);g.ai(u,1/60);}g.physics.step();for(const u of g.allies){g.physics.position(u.phys,u.pos);u.character.root.position.copy(u.pos);u.character.update(1/60,{speed:u.speed,grounded:u.phys.grounded});}g.combat.update(1/60);closest=Math.min(closest,a.pos.distanceTo(e.pos));if(e.hp<hp&&firstDamage==null)firstDamage=steps/60;}
 const first={start,closest,damage:hp-e.hp,seconds:steps/60,firstDamage,position:a.pos.toArray()};e.dead=true;const next=g.spawnEnemy('hollow',{x:-scenario.x*.6,z:-85}),distance=a.pos.distanceTo(next.pos);for(let step=0;step<60*12;step++){for(const u of g.allies){u.cooldown=Math.max(0,u.cooldown-1/60);g.ai(u,1/60);}g.physics.step();for(const u of g.allies)g.physics.position(u.phys,u.pos);g.combat.update(1/60);}return {...scenario,...first,reacquired:a.targetID===next.id,newStart:distance,newDistance:a.pos.distanceTo(next.pos),speed:a.speed};},scenario);report.scenarios.push(r);console.log(JSON.stringify(r));check(scenario.id+' crosses the wide field and attacks without hero orders',r.firstDamage!==null&&r.closest<35);check(scenario.id+' reacquires enemies on the opposite flank',r.reacquired&&r.newDistance<r.newStart-12);}
 const orders=await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(0);g.ui.open('army');g.battle.nextWave=9999;const a=g.allies[0],e=g.spawnEnemy('hollow',{x:80,z:-140});g.setOrder('hold');g.ai(a,1/60);const hold=a.order==='hold'&&!a.targetID;g.recruit('bow');const fresh=g.allies.filter(a=>a.unit==='bow');fresh.forEach(a=>g.ai(a,1/60));const auto=fresh.every(a=>a.order==='assault'&&a.targetID===e.id);g.setOrder('follow');g.physics.teleport(g.hero.phys,{x:25,y:0,z:-38});g.physics.position(g.hero.phys,g.hero.pos);const start=a.pos.distanceTo(g.hero.pos);for(let i=0;i<600;i++){g.ai(a,1/60);g.physics.step();g.physics.position(a.phys,a.pos);}return {hold,auto,follow:a.order==='follow'&&a.pos.distanceTo(g.hero.pos)<start-8};});check('Hold guards its position and new recruits still attack',orders.hold&&orders.auto);check('Follow regroups existing troops near the hero',orders.follow);
 const defenses=await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(0);g.ui.open('army');const s=g.store.data;s.completed=Array.from({length:15},(_,i)=>i);const layout=JSON.stringify(s.defenseLayout);let passed=[];g.world.towerObjects[0].cooldown=4;g.world.towerObjects[0].special=11;let preserved=false;for(const id of ['tower','ballista','cannon','frost','mortar','sanctuary','storm']){g.battle.command=220;const slot=g.battle.layout.findIndex(x=>x!==id);g.fieldDefense(id,slot);if(id==='tower')preserved=g.world.towerObjects[0].cooldown===4&&g.world.towerObjects[0].special===11;if(g.world.towerObjects[slot].id===id&&g.world.towerObjects[slot].level===s.defenses[id]&&JSON.stringify(s.defenseLayout)===layout)passed.push(id);}g.battle.gate=0;g.world.setGate(false);g.battle.command=220;g.fieldDefense('tower',g.battle.layout.findIndex(x=>x!=='tower'));const broken=g.battle.gate===0&&g.gatePos.z===5;let repairBlocked=false;try{g.fieldDefense('gate');}catch{repairBlocked=true;}g.returnHome();return {passed,preserved,broken,repairBlocked,castle:g.world.towerObjects.map(t=>t.id).join(',')===JSON.parse(layout).join(',')};});check('All seven emplacement types refit at their owned ranks',defenses.passed.length===7);check('Refitting preserves the other emplacements’ cooldowns',defenses.preserved);check('Refitting cannot resurrect a fallen gate',defenses.broken&&defenses.repairBlocked);check('Returning home restores the permanent castle arrangement',defenses.castle);
 check('No AI or physics runtime errors',errors.length===0);
}catch(e){report.failure=e.message;console.error(e.stack);process.exitCode=1;}finally{fs.mkdirSync('output/menus',{recursive:true});fs.writeFileSync('output/menus/command-report.json',JSON.stringify(report,null,2));await browser.close();}
