import{createRequire}from'node:module';import fs from'node:fs';import assert from'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),base=process.env.GAME_URL||'http://127.0.0.1:4179',out=process.env.QA_OUT||'output/equipment-280';fs.mkdirSync(out,{recursive:true});
const b=await chromium.launch({headless:true,args:['--use-angle=metal']}),p=await b.newPage({viewport:{width:1000,height:720}}),report={checks:[],errors:[]};p.on('pageerror',e=>report.errors.push(e.message));const check=(n,v)=>{assert.ok(v,n);report.checks.push(n);console.log('PASS',n)};
try{
 await p.goto(base+'/art-studio.html');await p.waitForFunction(()=>window.__atelier);
 const model=await p.evaluate(async()=>{const Character=window.__atelier.current.constructor,{armorStyle}=await import('/src/equipment-style.js'),{weapon,equipmentShield,compactRigid}=await import('/src/art.js'),{Box3,Vector3}=await import('/node_modules/three/build/three.module.js'),rows=[],weapons=[];const item=(type,rarity,extra={})=>({id:type+'-'+rarity,type,rarity,level:20,plus:0,affix:null,armorKind:'hearth',...extra});
 for(const role of ['warden','ashwright','ranger'])for(let rarity=0;rarity<7;rarity++){
 const type=role==='warden'?'sword':role==='ashwright'?'hammer':'bow',c=new Character('Knight',{design:role,rank:10,weapon:type,weaponItem:item(type,rarity),armor:item('armor',rarity),shieldItem:item('shield',rarity)});c.update(.1,{speed:4.5});const q=c.sockets.upperlegl.quaternion.clone();c.update(.17,{speed:4.5});const a=c.equipmentAppearance,b=c.atelier;rows.push({role,rarity,rank:a.rank,expected:armorStyle(c.armor).rank,pieces:b.pieces,cloth:b.clothHex,glowing:a.glowing,skinned:c.body.every(m=>m.isSkinnedMesh),moves:1-Math.abs(q.dot(c.sockets.upperlegl.quaternion))>.00001});c.dispose();}
 for(const type of ['sword','spear','hammer','bow','staff'])for(let rarity=0;rarity<7;rarity++){
 const g=compactRigid(weapon(type,1,undefined,null,null,item(type,rarity)));g.updateMatrixWorld(true);const bounds=new Box3().setFromObject(g);weapons.push({type,rarity,size:bounds.getSize(new Vector3()).toArray(),...g.userData});const geos=new Set(),mats=new Set();g.traverse(o=>{if(o.geometry&&!o.geometry.userData.shared)geos.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])mats.add(m);});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());}
 const families=[];for(const armorKind of ['hearth','bastion','trail','spellweave','ember','dawn','marshal']){const c=new Character('Knight',{design:'warden',armor:item('armor',5,{armorKind})});families.push({armorKind,color:c.atelier.clothHex,glow:armorStyle(c.armor).glow,vertices:c.body.reduce((n,m)=>n+m.geometry.attributes.position.count,0)});c.dispose();}
 return {rows,weapons,families};});report.models=model;
 check('All 21 hero/rarity combinations use equipped rarity, independently of hero level',model.rows.every(r=>r.rank===r.expected));check('All armor tiers retain full skeletal movement',model.rows.every(r=>r.skinned&&r.moves));
 for(const role of ['warden','ashwright','ranger']){const rows=model.rows.filter(r=>r.role===role);check(role+' has seven distinct liveries and added construction',new Set(rows.map(r=>r.cloth)).size===7&&rows[6].pieces>rows[0].pieces);}
 check('All seven armor families retain separate colors',new Set(model.families.map(f=>f.color)).size===7);
 for(const type of ['sword','spear','hammer','bow','staff']){const w=model.weapons.filter(w=>w.type===type);check(type+' gains oversized Mythic/Godly construction',Math.max(...w[6].size)>Math.max(...w[0].size)*1.4&&w[5].glowing&&w[6].glowing);}
 for(const role of ['warden','ashwright','ranger']){await p.selectOption('#role',role);for(const rarity of ['0','4','5','6']){await p.selectOption('#rarity',rarity);await p.waitForTimeout(300);await p.screenshot({path:out+'/'+role+'-'+rarity+'.jpg',quality:85});}}
 await p.goto(base);await p.waitForFunction(()=>window.__oathfire?.ready);await p.locator('#new-game').click();await p.locator('#begin-oath').click();await p.locator('#story-skip').click();
 await p.evaluate(async()=>{const g=window.__oathfire,{makeItem}=await import('/src/state.js');g.store.commit(s=>{s.guide.active=false;for(const rarity of [0,4,5,6])for(const type of ['armor','sword','hammer','bow','staff','spear','shield']){const i=makeItem(type,rarity,20,()=>.4,'hearth');i.id='qa-'+type+'-'+rarity;i.affix=null;i.weaponPattern=({sword:'hearthblade',spear:'stormlance',hammer:'forgehammer',bow:'starsong',staff:'pyrecrown'})[type];s.inventory.push(i);}});g.ui.open('equipment');});
 for(const r of [0,4,5,6]){
  await p.evaluate(r=>{const g=window.__oathfire;g.ui.open('equipment');g.ui.action('equipment-slot','armor');g.ui.action('item','qa-armor-'+r);},r);
  await p.locator('[data-action="equip"][data-id="qa-armor-'+r+'"]').click();
  check('Equip '+r+' changes the actual worn model and preview',await p.evaluate(r=>{const g=window.__oathfire;return g.hero.character.armor.id==='qa-armor-'+r&&g.ui.preview.equipmentAppearance.rarity===r&&g.hero.character.equipmentAppearance.rarity===r;},r));
 }
 await p.evaluate(async()=>{const g=window.__oathfire,{equipItem}=await import('/src/state.js');g.store.commit(s=>{equipItem(s,'qa-sword-6');equipItem(s,'qa-shield-6');});g.refreshHero();});
 check('Equipped weapon and shield use their own rarity instead of hero level',await p.evaluate(()=>{const c=window.__oathfire.hero.character;return c.held.userData.rarity===6&&c.heldShield.userData.rarity===6;}));
 const mobile=[];
 for(const [width,height]of [[844,390],[667,375],[390,844]]){await p.setViewportSize({width,height});if(width<height&&await p.locator('#portrait-continue').isVisible())await p.locator('#portrait-continue').click();await p.evaluate(()=>{const g=window.__oathfire;g.ui.open('equipment');g.ui.action('equipment-slot','armor');g.ui.action('item','qa-armor-6');});await p.waitForTimeout(450);await p.screenshot({path:out+'/equipped-'+width+'.jpg',quality:85});mobile.push(await p.evaluate(()=>{const m=document.querySelector('#model-stage').getBoundingClientRect(),panel=document.querySelector('#menu-content');return{w:innerWidth,h:innerHeight,stage:m.toJSON(),overflow:panel.scrollWidth-panel.clientWidth};}));}
 report.mobile=mobile;check('Landscape and portrait equipment menus retain a visible model and no horizontal overflow',mobile.every(x=>x.stage.width>140&&x.stage.height>140&&x.overflow<=2));
 const actions=await p.evaluate(async()=>{const g=window.__oathfire,{equipItem}=await import('/src/state.js'),{Vector3,Box3}=await import('/node_modules/three/build/three.module.js');g.ui.close();g.ui.open('pause');const c=g.hero.character,original=g.hero.phys.body.handle,rows=[];for(const type of ['sword','hammer','spear','staff','bow']){g.store.commit(s=>equipItem(s,'qa-'+type+'-6'));g.refreshHero();for(let n=0;n<90;n++)c.update(1/60,{});c.root.updateMatrixWorld(true);const bounds=new Box3(),v=new Vector3();c.held.traverse(o=>{if(o.isMesh){const a=o.geometry.attributes.position;for(let k=0;k<a.count;k++)bounds.expandByPoint(v.fromBufferAttribute(a,k).applyMatrix4(o.matrixWorld));}});c.attack(type,false,0,.6);c.update(.2,{});const q=c.sockets.upperarmr.quaternion.clone();c.update(.15,{});const light=1-Math.abs(q.dot(c.sockets.upperarmr.quaternion))>.00001;c.attack(type,true,0,.8);c.update(.2,{});const heavy=c.actionName;rows.push({type,light,heavy,floor:bounds.min.y-g.hero.pos.y,physicsSame:g.hero.phys.body.handle===original});}return rows;});report.actions=actions;
 check('All five Godly weapons keep working full-body attacks and the same physics actor',actions.every(a=>a.light&&a.physicsSame));check('Oversized held weapons stay above the ground at rest',actions.every(a=>a.floor>-.06));
 await p.evaluate(()=>{const g=window.__oathfire;g.ui.close();g.store.commit(s=>s.settings.firstPerson=true);});await p.waitForTimeout(250);check('First-person weapon retains equipped rarity and active magic aura',await p.evaluate(()=>{let found=false;window.__oathfire.view.fp.traverse(o=>{if(o.userData.rarity===6&&o.userData.glowing)found=true;});return found&&window.__oathfire.view.fp.visible;}));
 await p.evaluate(async()=>{const g=window.__oathfire,{equipItem}=await import('/src/state.js');g.store.commit(s=>{s.settings.firstPerson=false;equipItem(s,'qa-staff-5');equipItem(s,'qa-armor-5');equipItem(s,'qa-shield-4');});g.refreshHero();g.checkpoint();});const save=await p.evaluate(()=>window.__oathfire.store.export());await p.reload();await p.waitForFunction(()=>window.__oathfire?.ready);await p.locator('#continue-game').click();
 check('Reload preserves equipped Mythic/Godly items and their appearance',await p.evaluate(raw=>{const g=window.__oathfire,s=JSON.parse(raw).campaign;return JSON.stringify(g.store.data.inventory)===JSON.stringify(s.inventory)&&g.hero.character.equipmentAppearance.rarity===5&&g.hero.character.held.userData.rarity===5;},save));
 await p.evaluate(()=>{const g=window.__oathfire;g.ui.open('equipment');g.ui.action('equipment-slot','armor');g.ui.action('item','qa-armor-6');});const memory=await p.evaluate(async()=>{const g=window.__oathfire,{equipItem}=await import('/src/state.js'),rows=[];for(let n=0;n<20;n++){g.store.commit(s=>{equipItem(s,'qa-sword-'+(n%2?6:0));equipItem(s,'qa-armor-'+(n%2?6:0));});g.refreshHero();g.ui.preview.update(.01,{});g.view.render(true);rows.push({...g.view.renderer.info.memory});}return rows;});report.memory=memory;check('Repeated gear swaps do not accumulate GPU geometries',memory[19].geometries<=memory[3].geometries+2);
 check('No browser runtime errors',report.errors.length===0);
}catch(e){report.failure=e.stack;process.exitCode=1;console.error(e.stack);await p.screenshot({path:out+'/failure.jpg',quality:85}).catch(()=>{});}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await b.close();}
