import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]}),context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true}),page=await context.newPage(),out=process.env.QA_OUT||'output/expansion-qa',report={checks:[],errors:[]};fs.mkdirSync(out,{recursive:true});page.on('pageerror',e=>report.errors.push(e.message));const check=(n,b=true)=>{assert.ok(b,n);report.checks.push(n);console.log('PASS',n);};
try{await page.goto(process.env.GAME_URL||'http://127.0.0.1:4179');await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#new-game').tap();await page.locator('#begin-oath').tap();await page.locator('#story-skip').tap();
await page.evaluate(()=>{const g=window.__oathfire;g.store.data.guide.active=false;g.ui.open('campaign');});
check('Illustrated map has 24 main destinations and eight optional settlements',await page.locator('.atlas-node').count()===32);await page.screenshot({path:out+'/atlas-844.png'});
const pan=await page.evaluate(()=>{const g=window.__oathfire,map=document.querySelector('.atlas-scroll');map.scrollLeft=240;map.scrollTop=160;const before=[map.scrollLeft,map.scrollTop];g.ui.action('map-select','12');const after=document.querySelector('.atlas-scroll');return before[0]===after.scrollLeft&&before[1]===after.scrollTop;});check('Selecting a destination preserves the map position',pan);
check('Locked missions explain the prerequisite',await page.locator('.atlas-detail .primary').isDisabled());
await page.evaluate(async()=>{const {WEAPON_PATTERNS}=await import('/src/weapon-patterns.js'),{makeItem,heroData}=await import('/src/state.js'),g=window.__oathfire;g.ui.close();g.store.commit(s=>{s.completed=Array.from({length:24},(_,i)=>i);s.supplies=s.salvage=100000;heroData(s).level=20;for(const [id,d]of Object.entries(WEAPON_PATTERNS)){const i=makeItem(d.type,3,15);i.weaponPattern=id;i.name=d.name;i.plus=5;s.inventory.push(i);}});g.ui.open('equipment');});
const models=await page.evaluate(async()=>{const {WEAPON_PATTERNS}=await import('/src/weapon-patterns.js'),{equipItem,heroData}=await import('/src/state.js'),g=window.__oathfire,out=[];for(const id of Object.keys(WEAPON_PATTERNS)){const item=g.store.data.inventory.find(i=>i.weaponPattern===id&&i.rarity===3);g.ui.inventoryFilter='weapon';g.ui.screen='detail';g.ui.item=item.id;g.ui.draw();g.ui.previewForTab();const preview=g.ui.preview.root.userData.pattern;g.store.commit(s=>equipItem(s,item.id));g.refreshHero();const held=g.hero.character.held?.userData;out.push({id,preview,held,pattern:g.hero.character.weaponItem.weaponPattern});}return out;});report.models=models;check('All 15 item previews use the equipped weapon identity',models.every(x=>x.preview===x.id&&x.pattern===x.id&&x.held.pattern===x.id));
await page.evaluate(()=>{const g=window.__oathfire,i=g.store.data.inventory.find(i=>i.weaponPattern==='emberbrand'&&i.rarity===3);g.ui.item=i.id;g.ui.screen='detail';g.ui.detailTab='overview';g.ui.draw();g.ui.previewForTab();});await page.waitForTimeout(450);await page.screenshot({path:out+'/armory-844.png'});
check('Selected weapon has stats, active power and an equip action',await page.locator('.weapon-key-stats').count()===1&&await page.locator('.signature-power.active').count()===1);
await page.locator('[data-action="detail-section"][data-id="forge"]').first().tap();const delta=await page.evaluate(async()=>{const {itemValue}=await import('/src/state.js'),g=window.__oathfire,i=g.store.data.inventory.find(i=>i.id===g.ui.item),before=itemValue(i),next=itemValue({...i,plus:i.plus+1}),text=document.querySelector('.item-info').textContent;return {id:i.id,before,next,text};});check('Forge displays exact before and after damage',delta.text.includes(delta.before+' → '+delta.next));await page.locator('[data-action="forge"]').tap();check('Forge applies the displayed next value',await page.evaluate(async d=>{const {itemValue}=await import('/src/state.js');return itemValue(window.__oathfire.store.data.inventory.find(i=>i.id===d.id))===d.next;},delta));
for(const size of [{width:667,height:375},{width:390,height:844}]){await page.setViewportSize(size);if(size.width<500)await page.locator('#portrait-continue').tap();await page.screenshot({path:out+'/armory-'+size.width+'.png'});check('Armory stays within the '+size.width+'px viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.__oathfire.ui.open('campaign'));await page.screenshot({path:out+'/atlas-'+size.width+'.png'});check('Map detail remains usable at '+size.width+'px',await page.evaluate(()=>{const r=document.querySelector('.atlas-detail').getBoundingClientRect();return r.right<=innerWidth+1&&r.width>200;}));await page.evaluate(()=>{const g=window.__oathfire;g.ui.open('equipment');g.ui.action('equipment-slot','weapon');g.ui.action('item',g.store.data.inventory.find(i=>i.weaponPattern==='emberbrand'&&i.rarity===3).id);});}
await page.setViewportSize({width:844,height:390});
const foes=await page.evaluate(async()=>{const {ENEMIES}=await import('/src/data.js'),g=window.__oathfire;g.ui.close();g.beginMission(23);g.battle.nextWave=9999;const rows=[];for(const id of Object.keys(ENEMIES).filter(x=>x!=='boss')){const e=g.spawnEnemy(id,{x:20,y:0,z:20});rows.push({id,meshes:e.character.body.length,weapon:e.weapon});}for(let i=0;i<240;i++)g.tick(1/60);return rows;});report.enemies=foes;check('Every enemy archetype spawns and animates',foes.length===15&&foes.every(x=>x.meshes>0));await page.screenshot({path:out+'/battle.png'});
const mechanics=await page.evaluate(async()=>{const {enemySpecial,enemyRangedAttack}=await import('/src/enemy-mechanics.js'),{equipItem}=await import('/src/state.js'),{triggerWeaponPower}=await import('/src/weapon-powers.js'),g=window.__oathfire;g.beginMission(23);g.battle.nextWave=9999;const point=g.hero.pos.clone().add({x:0,y:0,z:-5}),spawn=id=>g.spawnEnemy(id,{x:point.x,y:point.y,z:point.z});const e=spawn('hollow'),herald=spawn('herald'),mender=spawn('mender');e.hp=10;enemySpecial(g,herald,10);enemySpecial(g,mender,10);const results={herald:e.buff>0,heal:e.hp>10};const tank=spawn('bulwark');tank.facing=0;g.hero.pos.copy(tank.pos).add({x:0,y:0,z:2});let hp=tank.hp;g.combat.hit(tank,100,g.hero,{});const front=hp-tank.hp;tank.hp=hp;g.hero.pos.z=tank.pos.z-2;g.combat.hit(tank,100,g.hero,{});results.shield=hp-tank.hp>front*2;const reaver=spawn('reaver');reaver.hp=1;enemySpecial(g,reaver,1);results.rage=reaver.buff>0&&reaver.haste>0;const b=spawn('bomber');enemyRangedAttack(g,b,g.hero);results.bomb=g.combat.events.length>0;
const powers=[];for(const i of g.store.data.inventory.filter(i=>i.rarity===3&&i.weaponPattern)){g.store.commit(s=>equipItem(s,i.id));g.refreshHero();g.hero.weaponPowerAt=0;e.dead=false;e.hp=e.stats.hp;g.time+=11;const cast=['pyrecrown','tidecaller'].includes(i.weaponPattern),active=triggerWeaponPower(g,e,{heavy:true},cast);if(!['hearthblade','watchpike','forgehammer','ashbow','pilgrimstaff'].includes(i.weaponPattern))powers.push({id:i.weaponPattern,active,cooldown:g.hero.weaponPowerAt>g.time,second:triggerWeaponPower(g,e,{heavy:true},cast)});}results.powers=powers;return results;});report.mechanics=mechanics;check('Herald buffs, mender healing, shield direction, reaver rage and bomb windup operate',mechanics.herald&&mechanics.heal&&mechanics.shield&&mechanics.rage&&mechanics.bomb);check('All ten signature powers trigger and enforce cooldown',mechanics.powers.length===10&&mechanics.powers.every(p=>p.active&&p.cooldown&&!p.second));
const saved=await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.checkpoint();return JSON.stringify(g.store.data.inventory);});await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').tap();check('New equipment identities and forge levels survive reload',await page.evaluate(s=>JSON.stringify(window.__oathfire.store.data.inventory)===s,saved));check('No browser runtime errors',report.errors.length===0);
}catch(e){report.failure=e.stack;console.error(e.stack);process.exitCode=1;await page.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
