import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),browser=await chromium.launch({headless:true,args:['--use-angle=metal']}),errors=[],checks=[];
fs.mkdirSync('output/frontier',{recursive:true});const page=await browser.newPage({viewport:{width:844,height:390}});page.on('pageerror',e=>errors.push(e.message));
const check=(name,value)=>{checks.push({name,value});assert.ok(value,name);console.log('PASS',name);};
try{
 await page.goto(process.env.GAME_URL||'http://127.0.0.1:4179');await page.waitForFunction(()=>window.__oathfire?.ready);await page.evaluate(async()=>{const g=window.__oathfire;await g.start('warden');g.ui.close();g.store.commit(s=>{s.completed=[0];s.guide.active=false;s.heroes.warden.level=2;});g.audio.music?.setPaused(true);g.beginMission(24);g.ui.open('pause');});
 const start=await page.evaluate(()=>{const g=window.__oathfire;return {hero:g.hero.pos.toArray(),gate:g.siegeTargets.find(t=>t.part==='gate').pos.toArray(),terrain:g.world.minZ,parts:g.siegeTargets.map(t=>({id:t.part,z:t.phys.collider.translation().z,nav:t.nav.z,model:t.model.getWorldPosition(g.hero.pos.clone()).z})),campCount:g.world.siegeCampFlags.length};});fs.writeFileSync('output/frontier/layout.json',JSON.stringify(start,null,2));check('Starts beside friendly gate; enemy fortress is 15x farther',Math.abs(start.hero[2]+27)<1&&Math.abs(start.gate[2]+1906.05)<2);check('All fortress colliders and navigation translated together',start.parts.every(t=>Math.abs(t.z-t.nav)<.01&&t.z< -1900));check('Four capture camps on extended physical ground',start.campCount===4&&start.terrain< -1990);
 await page.evaluate(()=>{const g=window.__oathfire;g.ui.close();g.ui.hud(1);});await page.screenshot({path:'output/frontier/start.png'});
 check('Income HUD is always visible',await page.locator('#combat-command-rate').innerText().then(t=>t.includes('+0.60/s')));
 await page.evaluate(()=>{const g=window.__oathfire;g.battle.command=220;g.recruit('banner');g.recruit('banner');g.recruit('banner');g.recruit('banner');});await page.waitForTimeout(200);check('Only three standards contribute, anywhere on field',await page.evaluate(()=>Math.abs(window.__oathfire.battle.standardIncome-.45)<.001));
 await page.locator('#command-income-detail').click();check('Tappable source breakdown opens',await page.locator('#dialog').innerText().then(t=>t.includes('Dawn standards')&&t.includes('0.45/s')));await page.locator('#income-close').click();
 await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.store.commit(s=>{s.supplies=500;});g.ui.open('defenses');});await page.locator('[data-action="castle-logistics"]').click();await page.screenshot({path:'output/frontier/logistics.png'});await page.locator('[data-action="upgrade-logistics"]').click();check('Command lodge costs Supplies and upgrades permanently',await page.evaluate(()=>{const s=window.__oathfire.store.data;return s.castleLogistics===1&&s.supplies===220;}));
 await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(24);g.battle.command=220;});await page.waitForFunction(()=>document.getElementById('combat-command-rate').textContent.includes('+0.68/s'));check('Castle income applies to siege, including full cap label',await page.locator('#combat-command-rate').innerText().then(t=>t.includes('+0.68/s')&&t.includes('FULL')));
 await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.beginMission(0);g.victory();g.ui.unlocks.show();g.ui.unlocks.review.cards=[{kind:'unit',id:'bow'},{kind:'territory',id:'24'},{kind:'lesson',id:'equipment'},{kind:'territory',id:'1'}];g.ui.unlocks.review.cursor=0;g.ui.unlocks.draw();});
 check('Troop reveal renders the actual Longbow model',await page.evaluate(()=>window.__oathfire.ui.preview.design==='bow'));
 await page.waitForTimeout(700);await page.screenshot({path:'output/frontier/unlock-troop.png'});await page.locator('[data-unlock="next"]').click();check('Siege reveal shows campaign map marker, no hero',await page.evaluate(()=>!!document.querySelector('[data-location="24"]')&&!window.__oathfire.ui.preview&&!document.querySelector('#unlock-model-stage')));await page.waitForTimeout(700);await page.screenshot({path:'output/frontier/unlock-map.png'});await page.locator('[data-unlock="next"]').click();
 check('Equipment reveal renders earned armor geometry',await page.evaluate(()=>{const p=window.__oathfire.ui.preview;return !!p.itemId&&p.root.children.length>0&&!p.design;}));await page.waitForTimeout(300);await page.screenshot({path:'output/frontier/unlock-armor.png'});
 await page.setViewportSize({width:667,height:375});for(let i=0;i<4;i++){await page.evaluate(i=>{const u=window.__oathfire.ui.unlocks;u.review.cursor=i;u.draw();},i);check('Phone reveal '+i+' fits without scroll',await page.evaluate(()=>{const c=document.querySelector('.unlock-copy');return c.scrollHeight<=c.clientHeight+1;}));}
 check('No runtime errors',errors.length===0);
}catch(e){console.error(e);fs.writeFileSync('output/frontier/failure.txt',e.stack+'\n'+errors.join('\n'));process.exitCode=1;}finally{fs.writeFileSync('output/frontier/qa.json',JSON.stringify({checks,errors},null,2));await browser.close();}
