import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.argv.includes('--playwright-module')?process.argv[process.argv.indexOf('--playwright-module')+1]:'playwright'));
const base=process.env.GAME_URL||'http://127.0.0.1:4178',out='work/qa-inspection';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]}),page=await browser.newPage({viewport:{width:1280,height:720},hasTouch:true}),errors=[],report={url:base,checks:[],errors};page.on('pageerror',e=>errors.push(e.message));const check=(name,ok=true)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS',name);};
try{
 await page.goto(base);await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#new-game').click();await page.locator('#begin-oath').click();await page.locator('#story-skip').click();await page.locator('#army-button').click();
 check('Army opens with health, damage and complete selected-soldier stats',await page.locator('.combat-stat').count()===9&&await page.locator('[data-stat="hp"] b').innerText()==='120');
 await page.locator('[data-action="inspect-army"][data-id="lantern"]').click();check('Inspect stats changes both the panel and the animated soldier',await page.locator('.inspection-detail').getAttribute('data-type')==='lantern'&&await page.evaluate(()=>window.__oathfire.ui.preview.design==='lantern'));
 check('Lantern healing reveals amount, radius and cooldown',(await page.locator('.unit-abilities').innerText()).includes('14 health')&&(await page.locator('.unit-abilities').innerText()).includes('Every 3 s')&&(await page.locator('.unit-abilities').innerText()).includes('10 m'));
 check('Inspect scrolls the detail heading into view',await page.locator('.inspection-title').evaluate(e=>{const r=e.getBoundingClientRect(),p=document.querySelector('#menu-content').getBoundingClientRect();return r.top>=p.top-1&&r.bottom<=p.bottom;}));
 await page.locator('[data-tab="troops"]').click();await page.locator('[data-action="unit"][data-id="shield"]').click();check('Future linked-shield perk is clearly locked at rank I',await page.locator('.ability-locked').innerText().then(s=>s.includes('UNLOCKS AT RANK V')));
 const before=await page.evaluate(()=>{const s=window.__oathfire.store.data;return {units:JSON.stringify(s.units),defenses:JSON.stringify(s.defenses),supplies:s.supplies};});
 await page.locator('[data-action="rank"][data-value="5"]').click();check('Selecting rank V updates real stats and activates its previewed perk',await page.locator('[data-stat="hp"] b').innerText()==='188'&&await page.locator('[data-stat="armor"] b').innerText()==='20'&&await page.locator('.ability-locked').count()===0&&await page.evaluate(()=>window.__oathfire.ui.preview.rank===5));
 check('Owned and preview ranks are explicitly compared',(await page.locator('.rank-comparison').innerText()).includes('Owned I → Preview V')&&(await page.locator('.rank-comparison').innerText()).includes('120 → 188'));
 await page.waitForFunction(()=>!document.querySelector('.toast'));await page.screenshot({path:out+'/01-shieldward-rank-v.png'});
 // Audit all 230 rank detail renders without repeating model construction for every text check.
 const audit=await page.evaluate(async()=>{const {UNITS,DEFENSES,unitStats}=await import('/src/data.js'),g=window.__oathfire,result={units:0,defenses:0,failures:[]};for(const id of Object.keys(UNITS))for(let rank=1;rank<=10;rank++){g.menu='troops';g.ui.unit=id;g.ui.previewRank=rank;g.ui.draw();const st=unitStats(id,rank),hp=Number(document.querySelector('[data-stat="hp"] b').textContent),damage=Number(document.querySelector('[data-stat="damage"] b').textContent);if(hp!==st.hp||damage!==st.damage||document.querySelectorAll('.combat-stat').length!==9||/undefined|NaN/.test(document.querySelector('#menu-content').textContent))result.failures.push(id+rank);result.units++;}for(const id of Object.keys(DEFENSES))for(let rank=1;rank<=10;rank++){g.menu='defenses';g.ui.defense=id;g.ui.previewRank=rank;g.ui.draw();if(id!=='gate'&&document.querySelector('[data-stat="health"] b').textContent!=='Protected'||/undefined|NaN/.test(document.querySelector('#menu-content').textContent))result.failures.push(id+rank);result.defenses++;}return result;});report.audit=audit;check('All 150 soldier ranks and 80 defense ranks display valid values',audit.units===150&&audit.defenses===80&&audit.failures.length===0);
 check('Inspecting ranks does not spend currency or train units/defenses',await page.evaluate(b=>{const s=window.__oathfire.store.data;return s.supplies===b.supplies&&JSON.stringify(s.units)===b.units&&JSON.stringify(s.defenses)===b.defenses;},before));
 await page.evaluate(()=>{const g=window.__oathfire;g.store.commit(s=>{s.completed=Array.from({length:15},(_,i)=>i);s.defenses.tower=5;s.defenses.ballista=5;s.guide.active=false;});g.ui.open('defenses');g.ui.defense='tower';g.ui.draw();g.ui.previewForTab();});
 check('Longwatch preview includes doctrine-adjusted range and cadence',await page.locator('[data-stat="range"] b').innerText()==='31.2 m'&&await page.locator('[data-stat="interval"] b').innerText()==='1.68 s');await page.locator('[data-action="doctrine"][data-value="suppression"]').click();check('Switching doctrine immediately updates range and cadence',await page.locator('[data-stat="range"] b').innerText()==='22.1 m'&&await page.locator('[data-stat="interval"] b').innerText()==='1.12 s');
 await page.locator('[data-action="defense"][data-id="ballista"]').click();await page.locator('[data-action="doctrine"][data-value="pinning"]').click();check('Pinning shows its 15 percent damage tradeoff',await page.locator('[data-stat="damage"] b').innerText()==='90.95');
 const combat=await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(0);g.ui.open('pause');g.battle.nextWave=999;g.combat.clear();for(const e of g.enemies){e.character.dispose();if(e.phys)g.physics.removeActor(e.phys);}g.enemies=[];const e=g.spawnEnemy('knight',{x:-13,y:0,z:-30},{training:true}),t=g.world.towerObjects.find(t=>t.id==='tower'),b=g.world.towerObjects.find(t=>t.id==='ballista');g.battleTick(0);const first={damage:g.combat.projectiles.find(p=>p.owner.defense==='tower')?.damage,interval:t.cooldown,pinning:g.combat.projectiles.find(p=>p.owner.defense==='ballista')?.damage,ballistaInterval:b.cooldown};return first;});report.combat=combat;
 check('Displayed doctrine values match actual fired projectiles and cooldowns',combat.damage===19&&Math.abs(combat.interval-1.12)<.00001&&combat.pinning===90.95&&combat.ballistaInterval===4);
 await page.evaluate(()=>{const g=window.__oathfire;g.battle.gate=987;g.battle.core=610;g.ui.open('defenses');g.ui.defense='gate';g.ui.draw();g.ui.previewForTab();});check('Gate details show live remaining health and beacon health',await page.locator('[data-stat="currentHp"] b').innerText()==='987'&&await page.locator('[data-stat="beacon"] b').innerText()==='610 / 650');
 await page.locator('[data-action="defense"][data-id="sanctuary"]').click();check('Support defenses label healing instead of weapon damage',(await page.locator('[data-stat="damage"]').innerText()).includes('HEALING')&&(await page.locator('.unit-abilities').innerText()).includes('four wounded'));
 await page.locator('[data-action="defense"][data-id="mortar"]').click();check('Lobber details explain range blind spot and blast radius',(await page.locator('[data-stat="range"]').innerText()).includes('minimum: 9 m')&&(await page.locator('.unit-abilities').innerText()).includes('within 4 m'));
 await page.setViewportSize({width:844,height:390});await page.locator('[data-action="defense"][data-id="storm"]').click();await page.locator('[data-action="rank"][data-value="10"]').click();await page.locator('.inspection-detail').scrollIntoViewIfNeeded();await page.waitForFunction(()=>!document.querySelector('.toast'));await page.screenshot({path:out+'/02-mobile-storm-stats.png'});
 check('Actual landscape viewport has readable-width stat columns and no overflow',await page.evaluate(()=>innerWidth===844&&innerHeight===390&&document.querySelector('#menu-content').scrollWidth<=document.querySelector('#menu-content').clientWidth+1&&[...document.querySelectorAll('.combat-stat')].every(e=>e.clientWidth>=120&&e.scrollWidth<=e.clientWidth+1)));
 await page.locator('.unit-abilities').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/03-mobile-storm-ability.png'});
 await page.evaluate(()=>{const g=window.__oathfire;g.ui.open('army');});await page.locator('[data-action="inspect-army"][data-id="shield"]').click();check('Army inspection shows surviving squad health',await page.locator('.field-status').innerText().then(t=>t.includes('3 Shieldward')&&t.includes('360 / 360')));
 await page.screenshot({path:out+'/04-mobile-army-stats.png'});const save=await page.evaluate(()=>{const g=window.__oathfire;g.checkpoint();return JSON.stringify({d:g.store.data.doctrines,r:g.store.data.defenses,b:g.store.data.battle.id,i:g.store.data.inventory});});await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').click();check('Inspection update preserves equipment, doctrine, ranks and suspended battle',await page.evaluate(before=>{const g=window.__oathfire,s=g.store.data;return JSON.stringify({d:s.doctrines,r:s.defenses,b:g.battle.id,i:s.inventory})===before;},save));
 check('No browser runtime errors',errors.length===0);
}catch(e){report.failure=e.message;console.error(e.stack);await page.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
