import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.argv.includes('--playwright-module')?process.argv[process.argv.indexOf('--playwright-module')+1]:'playwright'));
const base=process.env.GAME_URL||'http://127.0.0.1:4178',out='work/qa-journey';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]}),page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],report={url:base,checks:[],errors};page.on('pageerror',e=>errors.push(e.message));const check=(n,v=true)=>{assert.ok(v,n);report.checks.push(n);console.log('PASS',n);};
try{
 await page.goto(base);await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#new-game').click();await page.locator('#begin-oath').click();await page.locator('#story-next').waitFor();await page.screenshot({path:out+'/01-opening.png'});
 check('Opening introduces Veyr and the beacon oath',(await page.locator('#dialog').innerText()).includes('Marshal Veyr'));
 const physics=await page.evaluate(()=>window.__oathfire.metrics.physicsSteps);await page.waitForTimeout(250);check('Narrative pauses world simulation',await page.evaluate(n=>window.__oathfire.metrics.physicsSteps===n,physics));
 await page.locator('#story-next').click();check('Personal stakes explain why Hearthwatch matters',(await page.locator('#dialog').innerText()).includes('My brother'));await page.locator('#story-next').click();await page.locator('#story-next').click();await page.waitForFunction(()=>window.__oathfire.hero.phys.grounded);
 await page.keyboard.down('KeyD');await page.waitForTimeout(2000);await page.keyboard.up('KeyD');await page.mouse.move(650,350);await page.mouse.down({button:'right'});await page.mouse.move(770,350,{steps:8});await page.mouse.up({button:'right'});
 await page.keyboard.press('KeyJ');await page.waitForTimeout(700);await page.keyboard.down('KeyJ');await page.waitForTimeout(650);await page.keyboard.up('KeyJ');await page.waitForTimeout(950);await page.keyboard.press('KeyQ');await page.waitForTimeout(400);await page.keyboard.press('Space');await page.waitForTimeout(650);
 report.training=await page.evaluate(()=>window.__oathfire.store.data.guide);console.log('GUIDE',JSON.stringify(report.training));check('Normal controls complete movement, camera, quick/charged attack, spell and jump lessons',await page.evaluate(()=>['move','look','light','heavy','cast','jump'].every(id=>window.__oathfire.store.data.guide.done.includes(id))));
 await page.locator('#journey-action').click();await page.locator('[data-action="unit"][data-id="bow"]').click();check('Regiments menu includes fifteen inspectable choices',await page.locator('[data-action="unit"]').count()===15);await page.locator('#close-menu').click();await page.locator('#journey-action').click();await page.locator('[data-action="defense"][data-id="tower"]').click();check('Eight defenses and four emplacement choices are present',await page.locator('[data-action="defense"]').count()===8&&await page.locator('[data-action="refit"]').count()===4);await page.locator('[data-action="defense"][data-id="storm"]').click();check('Locked plans explain the exact campaign milestone',(await page.locator('#menu-content').innerText()).includes('Westwind Downs'));await page.locator('#close-menu').click();
 await page.setViewportSize({width:844,height:390});await page.waitForTimeout(200);await page.screenshot({path:out+'/02-mobile-guide.png'});check('First defense has an explicit world button',await page.locator('#mission-shortcut').isVisible());await page.locator('#mission-shortcut').click();await page.screenshot({path:out+'/03-mobile-briefing.png'});check('Begin defense is visible without scrolling the briefing',await page.locator('#begin-defense').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}));check('Briefing states objective, loss conditions and unlock rewards',(await page.locator('#dialog').innerText()).includes('WIN')&&(await page.locator('#dialog').innerText()).includes('Dawn standard'));await page.locator('#begin-defense').click();await page.locator('#journey-action').click();await page.locator('[data-action="recruit"][data-id="bow"]').click();await page.locator('[data-action="order"][data-id="follow"]').click();await page.locator('#close-menu').click();
 check('First mission teaching leads to a real deployed squad and army order',await page.evaluate(()=>window.__oathfire.allies.filter(a=>a.unit==='bow').length===3&&['mission','recruit','order'].every(id=>window.__oathfire.store.data.guide.done.includes(id))));await page.evaluate(()=>window.__oathfire.checkpoint());await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').click();check('Training and active battle survive reload',await page.evaluate(()=>window.__oathfire.battle.id===0&&window.__oathfire.store.data.guide.done.includes('order')&&!window.__oathfire.ui.modal));
 // Isolated fully-unlocked campaign fixture exercises assets, collisions and tactical behavior.
 await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.store.commit(s=>{s.completed=Array.from({length:15},(_,i)=>i);s.supplies=100000;s.guide.active=false;});g.ui.open('defenses');});
 const modelAudit=await page.evaluate(async()=>{const {UNITS,DEFENSES}=await import('/src/data.js'),g=window.__oathfire,C=g.hero.character.constructor,results={troops:{},defenses:{}};for(const [id,u]of Object.entries(UNITS)){let fingerprints=[];for(let rank=1;rank<=10;rank++){const c=new C(u.model,{weapon:u.weapon,design:id,rank,color:u.color,mounted:id==='rider'});c.update(.1,{speed:2});let count=0;c.root.traverse(o=>{if(o.geometry)count+=o.geometry.attributes.position.count;});fingerprints.push(count);c.dispose();}results.troops[id]=fingerprints;}for(const id of Object.keys(DEFENSES)){results.defenses[id]=[];for(let rank=1;rank<=10;rank++){const m=g.world.defenseModel(id,rank);let count=0;m.traverse(o=>{if(o.geometry)count+=o.geometry.attributes.position.count;});results.defenses[id].push(count);}}return results;});report.models=modelAudit;
 check('All 150 troop ranks build animated 3D bodies',Object.keys(modelAudit.troops).length===15&&Object.values(modelAudit.troops).every(a=>a.length===10&&a.every(n=>n>1000)));
 check('Every new defense rank changes geometry',Object.entries(modelAudit.defenses).filter(([id])=>!['gate','tower','ballista'].includes(id)).every(([,a])=>new Set(a).size===10));
 check('All new regiments gain visible geometry on every rank',Object.entries(modelAudit.troops).filter(([id])=>['banner','engineer','assassin','pyre','marksman','frost','dawn'].includes(id)).every(([,a])=>new Set(a).size===10));
 await page.locator('[data-action="defense"][data-id="cannon"]').click();await page.locator('[data-action="refit"][data-id="0"]').click();check('Refitting updates the actual castle and keeps four colliders',await page.evaluate(()=>window.__oathfire.world.towerObjects.length===4&&window.__oathfire.world.towerObjects[0].id==='cannon'&&window.__oathfire.world.towerObjects.every(t=>!!t.collider)));
 await page.locator('[data-action="rank"][data-value="10"]').click();await page.locator('#animate-preview').click();await page.waitForTimeout(250);check('Defense action preview launches visible cannon geometry',await page.evaluate(()=>window.__oathfire.ui.defenseEffects.some(p=>p.id==='cannon'&&p.model.position.z<p.pos.z)));await page.screenshot({path:out+'/04-cannon-rank-x.png'});await page.locator('[data-action="defense"][data-id="storm"]').click();await page.locator('[data-action="rank"][data-value="10"]').click();await page.screenshot({path:out+'/05-storm-rank-x.png'});await page.locator('[data-tab="troops"]').click();await page.locator('[data-action="unit"][data-id="banner"]').click();await page.locator('[data-action="rank"][data-value="10"]').click();await page.screenshot({path:out+'/06-standard-rank-x.png'});
 await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(0);g.ui.open('pause');});
 const tactics=await page.evaluate(async()=>{const g=window.__oathfire,{supportRegiment}=await import('/src/regiments.js'),{tickFortification}=await import('/src/fortifications.js'),{DEFAULT_LAYOUT}=await import('/src/roster.js');g.combat.clear();for(const e of [...g.enemies,...g.allies]){e.character.dispose();if(e.phys)g.physics.removeActor(e.phys);}g.enemies=[];g.allies=[];g.battle.nextWave=999;const a=g.spawnAlly('engineer',{x:0,y:0,z:-26});g.battle.gate-=150;const hp=g.battle.gate;supportRegiment(g,a,1/60);const repair=g.battle.gate>hp;
 const banner=g.spawnAlly('banner',{x:0,y:0,z:-32});supportRegiment(g,banner,1/60);const buff=a.buff>0;const dawn=g.spawnAlly('dawn',{x:0,y:0,z:-32});a.hp-=30;const target=g.spawnEnemy('knight',{x:1,y:0,z:-34});const before=a.hp;for(let i=0;i<3;i++)g.combat.hit(target,1,dawn,{weapon:'sword'});const heal=a.hp>before;
 const n=g.spawnEnemy('knight',{x:0,y:0,z:-50},{training:true,hp:10000,stats:{hp:10000,armor:50}});const marks=g.spawnAlly('marksman',{x:0,y:0,z:-40});let prev=n.hp;g.combat.hit(n,40,marks,{projectile:true});const piercing=prev-n.hp;prev=n.hp;g.combat.hit(n,40,banner,{projectile:true});const normal=prev-n.hp;
 const outcomes={repair,buff,heal,piercing,normal};for(const id of ['cannon','frost','mortar','storm','sanctuary']){g.combat.clear();g.store.data.defenseLayout=[id,...DEFAULT_LAYOUT.slice(1)];g.ui.rebuildDefenses();const t=g.world.towerObjects[0];g.physics.teleport(n.phys,{x:t.x,y:0,z:t.z-14});g.physics.position(n.phys,n.pos);g.physics.step();a.hp=20;g.physics.teleport(a.phys,{x:t.x+3,y:0,z:t.z-4});g.physics.position(a.phys,a.pos);const old=n.hp,ahp=a.hp;tickFortification(g,t,.1,[n]);const types=g.combat.projectiles.map(p=>p.type);for(let i=0;i<250;i++)g.combat.update(1/60);outcomes[id]={damage:old-n.hp,slow:n.slow||0,healed:a.hp-ahp,types};}return outcomes;});report.tactics=tactics;console.log('TACTICS',JSON.stringify(tactics));check('Engineers repair, standards buff, Sun sworn heal on the third landed hit',tactics.repair&&tactics.buff&&tactics.heal);check('Marksmen pierce armor for more damage',tactics.piercing>tactics.normal);check('Cannon, ice, lobber and storm defenses deal real damage',['cannon','frost','mortar','storm'].every(id=>tactics[id].damage>0));check('Ice slows and Sanctuary heals',tactics.frost.slow>0&&tactics.sanctuary.healed>0);check('Physical cannonballs, ice shards and arcing stones are distinct',tactics.cannon.types.includes('shell')&&tactics.frost.types.includes('frost')&&tactics.mortar.types.includes('stone'));

 const legacy=await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(0);g.store.data.units.shield=4;g.store.data.supplies=713;g.checkpoint();const s=JSON.parse(g.store.export()).campaign;delete s.rosterVersion;delete s.guide;delete s.defenseLayout;for(const id of ['banner','engineer','assassin','pyre','marksman','frost','dawn'])delete s.units[id];for(const id of ['cannon','frost','mortar','sanctuary','storm'])delete s.defenses[id];localStorage.setItem('oathfire.campaign.v1',JSON.stringify(s));return JSON.stringify(s);});
 await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').click();check('An original-format suspended save migrates and resumes with its ranks and resources',await page.evaluate(()=>{const g=window.__oathfire,s=g.store.data;return s.supplies===713&&s.units.shield===4&&s.battle?.id===0&&Object.keys(s.units).length===15&&Object.keys(s.defenses).length===8&&!g.ui.modal;}));
 await page.locator('#pause-btn').click();await page.locator('[data-tab="settings"]').click();await page.locator('#import-save').setInputFiles({name:'legacy-save.json',mimeType:'application/json',buffer:Buffer.from(legacy)});await page.locator('#confirm-dialog').click();await page.waitForFunction(()=>window.__oathfire.menu===null);check('The real import UI accepts an original save and preserves the campaign',await page.evaluate(()=>window.__oathfire.store.data.supplies===713&&window.__oathfire.store.data.units.shield===4&&window.__oathfire.battle.id===0));
 const friendly=await page.evaluate(()=>{const g=window.__oathfire;g.ui.open('pause');g.combat.clear();const h=g.hero;g.physics.teleport(h.phys,{x:6,y:0,z:-31});g.physics.position(h.phys,h.pos);const a=g.spawnAlly('bow',{x:6,y:0,z:-27}),t=g.spawnEnemy('hollow',{x:6,y:0,z:-36},{training:true});g.physics.step();const hp=h.hp;g.combat.shoot(a,t,{type:'arrow',damage:50});for(let i=0;i<80;i++)g.combat.update(1/60);return h.hp===hp;});check('Allied projectiles cannot hurt the hero',friendly);
 check('No browser runtime errors',errors.length===0);
}catch(e){report.failure=e.message;console.error(e.stack);await page.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
