import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.argv.includes('--playwright-module')?process.argv[process.argv.indexOf('--playwright-module')+1]:'playwright'));
const base=process.env.GAME_URL||'http://127.0.0.1:4180',out=process.env.QA_OUT||'output/menus';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]}),page=await browser.newPage({viewport:{width:844,height:390},hasTouch:true}),errors=[],report={url:base,checks:[],errors};page.on('pageerror',e=>errors.push(e.message));const check=(name,ok=true)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS',name);};const click=async(action,id)=>page.locator('[data-action="'+action+'"]'+(id!=null?'[data-id="'+id+'"]':'')).first().click();const shot=async n=>{await page.evaluate(()=>document.querySelectorAll('.toast').forEach(e=>e.remove()));await page.screenshot({path:out+'/'+n+'.png'});};
try{
 await page.goto(base);await page.waitForFunction(()=>window.__oathfire?.ready);check('Expected release is running',await page.evaluate(()=>window.__oathfire.debug().build==='oathfire-1.4.0-command-and-keep'));await page.locator('#new-game').click();await page.locator('#begin-oath').click();await page.locator('#story-skip').click();await page.locator('#pause-btn').click();
 check('Castle opens with destinations instead of nine global tabs',await page.locator('.destination-tile').count()===4&&await page.locator('[data-tab]').count()===0);await shot('01-castle');
 await click('navigate','troops');check('Regiment list contains all 15 entries without stat overload',await page.locator('.roster-row').count()===15&&await page.locator('.combat-stat').count()===0);await click('inspect-object','shield');check('Inspection shows a 3D soldier and three primary stats',await page.locator('.combat-stat').count()===3&&await page.evaluate(()=>window.__oathfire.ui.preview.design==='shield'));await shot('02-unit');
 await click('detail-section','stats');check('Detailed stats remain accessible',await page.locator('.combat-stat').count()===9&&await page.locator('[data-stat="hp"] b').innerText()==='120');await click('detail-section','abilities');check('Ability unlocks remain accessible',(await page.locator('.unit-abilities').innerText()).includes('RANK V'));
 await click('detail-section','upgrade');await page.locator('[data-action="rank"][data-value="5"]').click();check('Future rank changes model and compares real stats',await page.evaluate(()=>window.__oathfire.ui.preview.rank===5)&&(await page.locator('.rank-comparison').innerText()).includes('120 → 188'));await shot('03-upgrade');await click('menu-back');check('Back returns to roster',await page.locator('.roster-row').count()===15);await click('menu-back');
 await click('navigate','equipment');check('Armory first asks for one of four slots',await page.locator('.equipment-slot').count()===4&&await page.locator('.item-info').count()===0);await click('equipment-slot','armor');await page.locator('[data-action="item"]').first().click();check('Armor benefits and appearance are shown together',await page.locator('.armor-benefits').count()===1&&await page.evaluate(()=>!!window.__oathfire.ui.preview.armor));await click('detail-section','forge');check('Forge controls have their own layer',await page.locator('[data-action="forge"]').count()===1&&await page.locator('.armor-benefits').count()===0);await click('menu-back');check('Equipment back returns to chosen inventory slot',await page.locator('.inventory').count()===1);await click('menu-back');await click('menu-back');
 await click('navigate','hero');await click('detail-section','skills');check('Character skills are separated from attributes and techniques',await page.locator('.skill-list').count()===1&&await page.locator('.stats').count()===0&&await page.locator('select[data-setting="slot"]').count()===0);await shot('04-skills');await click('menu-back');
 await click('navigate','campaign');await click('embark','0');check('War table still leads to story briefing',await page.locator('#begin-defense').isVisible());await page.locator('#begin-defense').click();await page.locator('#army-button').click();await page.waitForFunction(()=>window.__oathfire.menu==='army');check('Battle command contains only Troops, Defenses, Orders',await page.locator('.battle-categories .destination-tile').count()===3&&await page.locator('[data-action="navigate"]').count()===0&&await page.locator('#model-stage').isHidden());await shot('05-battle-command');
 await click('battle-category','troops');check('Battle roster lists all 15 squads with Command costs',await page.locator('.deploy-button').count()===15&&(await page.locator('.deploy-button').first().innerText()).includes('⚑'));const before=await page.evaluate(()=>({c:window.__oathfire.battle.command,n:window.__oathfire.allies.length}));await click('recruit','bow');check('One tap deploys a squad and deducts its real cost',await page.evaluate(b=>{const g=window.__oathfire;return g.allies.length>b.n&&g.battle.command<b.c&&g.allies.filter(a=>a.unit==='bow').every(a=>a.order==='assault');},before));await shot('06-battle-roster');
 await click('inspect-object','bow');check('Battle inspection previews the selected troop',await page.evaluate(()=>window.__oathfire.ui.preview.design==='bow')&&await page.locator('.battle-detail').count()===1);await click('menu-back');await click('menu-back');await click('battle-category','defenses');check('All eight battlefield defense costs are visible',await page.locator('.deploy-button').count()===8);await shot('07-battle-defenses');
 await page.evaluate(()=>{const g=window.__oathfire;g.battle.command=220;g.battle.gate=100;g.ui.draw();});const layout=await page.evaluate(()=>JSON.stringify(window.__oathfire.store.data.defenseLayout));await click('field-select','gate');check('Gate repair deducts Command and restores 250 actual health',await page.evaluate(()=>window.__oathfire.battle.gate===350&&window.__oathfire.battle.command===175));await click('field-select','tower');await click('field-build','2');check('Battle refit changes actual emplacement without changing permanent castle layout',await page.evaluate(layout=>{const g=window.__oathfire;return g.battle.layout[2]==='tower'&&g.world.towerObjects[2].id==='tower'&&JSON.stringify(g.store.data.defenseLayout)===layout&&g.battle.gate===350&&g.battle.command===120;},layout));
 await click('menu-back');await click('battle-category','orders');await click('order','hold');await click('menu-back');await click('battle-category','troops');await click('recruit','shield');check('New troops seek enemies even after older troops were told to hold',await page.evaluate(()=>{const g=window.__oathfire;return g.order==='mixed'&&g.allies.at(-1).order==='assault'&&g.allies[0].order==='hold';}));
 const save=await page.evaluate(()=>{const g=window.__oathfire;g.checkpoint();return JSON.stringify({i:g.store.data.inventory,d:g.store.data.defenses,l:g.battle.layout,c:g.battle.command,o:g.allies.map(a=>a.order)});});await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').click();await page.locator('#army-button').click();await page.waitForFunction(()=>window.__oathfire.menu==='army');check('Reload preserves inventory, ranks, temporary layout, resources and individual orders',await page.evaluate(before=>{const g=window.__oathfire;const saved=JSON.parse(before),now={i:g.store.data.inventory,d:g.store.data.defenses,l:g.battle.layout,c:saved.c,o:g.allies.map(a=>a.order)};return Math.abs(g.battle.command-saved.c)<1&&JSON.stringify(now)===before;},save));
 for(const size of [{width:667,height:375},{width:844,height:390},{width:1280,height:720}]){await page.setViewportSize(size);await page.evaluate(()=>{const g=window.__oathfire;g.ui.open('army');});await click('battle-category','troops');check('Battle roster fits '+size.width+' × '+size.height,await page.evaluate(()=>{const e=document.querySelector('#menu-content');return e.scrollWidth<=e.clientWidth+1&&[...document.querySelectorAll('.deploy-button,.roster-select,#close-menu')].every(e=>e.getBoundingClientRect().height>=44); }));await shot('08-roster-'+size.width);}

 await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.ui.open('troops');g.ui.screen='detail';});
 const renders=await page.evaluate(()=>{const g=window.__oathfire,ui=g.ui,result={units:0,defenses:0};for(const [tab,key,ids]of [['troops','unit',Object.keys(g.store.data.units)],['defenses','defense',Object.keys(g.store.data.defenses)]]){g.menu=tab;ui.screen='detail';ui.battleCommand=false;for(const id of ids){ui[key]=id;for(let rank=1;rank<=10;rank++){ui.previewRank=rank;for(const section of ['stats','abilities','upgrade']){ui.detailTab=section;ui.draw();const text=document.querySelector('#menu-content').textContent;if(/NaN|undefined|Infinity/.test(text))throw Error(tab+' '+id+' '+rank+' '+section);if(section==='stats'&&!document.querySelector('.combat-stat'))throw Error('Missing stats');}result[tab==='troops'?'units':'defenses']++;}ui.previewForTab();if(!g.view.previewScene.children.length)throw Error('Missing model');}}return result;});check('All 230 rank screens render stats, abilities and comparisons',renders.units===150&&renders.defenses===80);
 for(const size of [{width:667,height:375},{width:844,height:390}]){await page.setViewportSize(size);await page.evaluate(()=>window.__oathfire.ui.open('pause'));check('Castle destinations fit without horizontal overflow at '+size.width,await page.evaluate(()=>{const c=document.querySelector('#menu-content');return c.scrollWidth<=c.clientWidth+1;}));await shot('09-castle-'+size.width);await click('navigate','defenses');await click('inspect-object','tower');await click('detail-section','abilities');await shot('10-defense-'+size.width);check('Defense abilities remain readable at '+size.width,await page.locator('.combat-ability p').first().evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=16));}
 await page.evaluate(()=>window.__oathfire.ui.open('pause'));await click('navigate','more');for(const id of ['shop','journal','bestiary','settings']){await click('navigate',id);check(id+' remains reachable through the keep',await page.locator('#menu-content').innerText().then(t=>t.length>50));if(id==='bestiary'){await click('enemy','brute');check('Bestiary opens a separate enemy profile',await page.locator('.cards').count()===0&&await page.evaluate(()=>window.__oathfire.ui.preview.design==='brute'));await click('menu-back');}await click('menu-back');}
 check('No browser errors',errors.length===0);
}catch(e){report.failure=e.message;console.error(e.stack);await shot('failure').catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
