import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';import {newSave} from '../src/state.js';import {MOUNTS} from '../src/mount-rules.js';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'/Users/christopherdayley/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),url=process.env.GAME_URL||'http://127.0.0.1:4181',out=process.env.QA_OUT||'work/qa-mounts';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=metal']}),report={url,checks:[],errors:[]},check=(n,v)=>{assert.ok(v,n);report.checks.push(n);console.log('PASS',n);};
try{
 const p=await browser.newPage({viewport:{width:844,height:390},isMobile:true,hasTouch:true});p.on('pageerror',e=>report.errors.push(e.stack));await p.goto(url);await p.waitForFunction(()=>window.__oathfire?.ready,{},{timeout:90000});
 const make=n=>{const s=newSave('ashwright');s.completed=Array.from({length:n},(_,i)=>i);s.supplies=95000;s.guide.active=false;s.guide.seen=['prologue'];s.position={x:24,y:0,z:20};return s;};
 const load=async s=>{await p.evaluate(async s=>{const g=window.__oathfire;g.ui.close();g.battle=null;g.store.import(JSON.stringify(s));await g.start(null,true);g.ui.close();},s);await p.waitForTimeout(350);};
 await load(make(11));await p.evaluate(()=>window.__oathfire.ui.open('stable'));check('Stables teach the Defense XII unlock and cannot sell early',await p.locator('#menu-content').innerText().then(t=>t.includes('Defense XII'))&&await p.locator('[data-action=mount-hire]').isDisabled());
 await load(make(23));await p.evaluate(()=>window.__oathfire.ui.open('stable'));check('Horse preview replaces hero in stable',await p.evaluate(()=>window.__oathfire.ui.preview.root.name==='Horse_courser'));
 check('Hire button fully visible without scrolling at 844×390',await p.locator('[data-action=mount-hire]').evaluate(e=>{const r=e.getBoundingClientRect(),f=document.querySelector('#menu>footer').getBoundingClientRect();return r.height>=44&&r.bottom<=f.top&&r.left>=0&&r.right<=innerWidth;}));
 await p.locator('[data-action=mount-hire]').click();check('Purchase confirmation quotes name, exact cost and stats',await p.locator('#dialog').innerText().then(t=>t.includes('2,400')&&t.includes('320 health')));await p.locator('#confirm-dialog').click();check('Contract deducts supplies once and selects horse',await p.evaluate(()=>{const s=window.__oathfire.store.data;return s.supplies===92600&&s.mounts.selected==='courser'&&s.mounts.owned.length===1;}));
 await p.screenshot({path:out+'/stable-mobile.png'});
 // Actual touch mount control, real movement, jump and damage; isolated test save.
 await p.evaluate(()=>{const g=window.__oathfire;g.ui.close();g.hero.pos.set(0,0,-28);g.physics.teleport(g.hero.phys,g.hero.pos);});await p.waitForTimeout(400);await p.locator('#mount-control').tap();await p.waitForTimeout(300);check('Touch mounts a seated hero with collision probes',await p.evaluate(()=>{const h=window.__oathfire.hero;return h.mount?.id==='courser'&&h.phys.probes?.length===2&&h.character.visual.position.y>.5;}));
 const start=await p.evaluate(()=>window.__oathfire.hero.pos.z);await p.keyboard.down('w');await p.waitForTimeout(1400);await p.keyboard.up('w');check('Horse accelerates and travels faster than on foot',await p.evaluate(start=>start-window.__oathfire.hero.pos.z>7,start));await p.waitForTimeout(500);
 const ground=await p.evaluate(()=>window.__oathfire.hero.pos.y);await p.keyboard.press('Space');await p.waitForTimeout(200);check('Mounted jump rises above ground',await p.evaluate(y=>window.__oathfire.hero.pos.y>y+.65,ground));await p.waitForTimeout(1200);check('Mounted jump lands without sinking',await p.evaluate(()=>window.__oathfire.hero.phys.grounded));
 check('Mount, rider and attack shapes remain finite',await p.evaluate(()=>{const h=window.__oathfire.hero;return h.pos.toArray().every(Number.isFinite)&&h.character.sockets.footl.matrixWorld.elements.every(Number.isFinite);}));
 await p.evaluate(()=>{const g=window.__oathfire;g.hero.pos.set(0,0,-28);g.physics.teleport(g.hero.phys,g.hero.pos);g.hero.velocity.set(0,0,0);g.physics.addBox(0,2,-35,12,4,1,'mount-test-wall');g.view.yaw=0;});await p.waitForTimeout(300);await p.keyboard.down('w');await p.waitForTimeout(1600);await p.keyboard.up('w');check('Horse nose probe stops before a wall',await p.evaluate(()=>{const h=window.__oathfire.hero;return h.pos.z>-33.05;}));
 await p.evaluate(()=>{const g=window.__oathfire;for(const c of [...g.physics.fixed])if(g.physics.meta.get(c.handle)?.kind==='mount-test-wall')g.physics.remove(c);g.hero.pos.set(0,0,-28);g.physics.teleport(g.hero.phys,g.hero.pos);g.hero.velocity.set(0,0,0);});await p.waitForTimeout(350);
 await p.evaluate(()=>{const g=window.__oathfire;g.hero.invuln=0;g.hero.guarding=false;g.testHP=g.hero.hp;g.combat.hit(g.hero,50,{team:'enemy',weapon:'bow',pos:g.hero.pos.clone().add({x:0,y:0,z:-3})},{projectile:true,weapon:'bow'});});check('Arrows hurt both rider and horse',await p.evaluate(()=>{const g=window.__oathfire;return g.hero.hp<g.testHP&&g.hero.mountHP<320;}));
 await p.waitForTimeout(900);await p.keyboard.press('h');await p.waitForFunction(()=>!window.__oathfire.hero.mount);const injured=await p.evaluate(()=>window.__oathfire.store.data.mounts.hp.courser);await p.waitForTimeout(1100);await p.keyboard.press('h');await p.waitForFunction(()=>!!window.__oathfire.hero.mount);check('Dismounting and remounting does not heal the horse',await p.evaluate(hp=>window.__oathfire.hero.mountHP===hp,injured));
 await p.evaluate(()=>{const g=window.__oathfire;g.hero.cooldowns={};g.hero.focus=100;g.testProjectiles=g.combat.stats.projectiles;});await p.keyboard.press('q');await p.waitForFunction(()=>window.__oathfire.combat.projectiles.some(x=>x.owner===window.__oathfire.hero));check('Mounted spell creates a visible projectile above the saddle',await p.evaluate(()=>{const g=window.__oathfire;return g.combat.projectiles.some(x=>x.owner===g.hero&&x.pos.y>g.hero.pos.y+1.9);}));
 await p.evaluate(()=>{const g=window.__oathfire,s=g.store.data;s.heroes[s.hero].equipped.weapon=s.inventory.find(i=>i.type==='bow').id;g.refreshHero();g.hero.cooldown=0;g.hero.stamina=100;});await p.keyboard.down('j');await p.waitForTimeout(70);await p.keyboard.up('j');await p.waitForFunction(()=>window.__oathfire.combat.projectiles.some(x=>x.type==='arrow'));check('Mounted bow fires an actual traveling arrow',await p.evaluate(()=>window.__oathfire.combat.projectiles.some(x=>x.type==='arrow'&&x.pos.y>window.__oathfire.hero.pos.y+1.9)));
 await p.evaluate(()=>{const g=window.__oathfire,s=g.store.data;s.heroes[s.hero].equipped.weapon=s.inventory.find(i=>i.type==='sword').id;g.refreshHero();g.hero.cooldown=0;g.hero.stamina=100;});await p.keyboard.down('j');await p.waitForTimeout(700);await p.keyboard.up('j');await p.waitForTimeout(150);check('Charged mounted melee uses its own downward animation',await p.evaluate(()=>{const c=window.__oathfire.hero.character;return c.mountedAttack?.heavy&&c.mountedAttack.type==='sword';}));
 await p.evaluate(()=>{const g=window.__oathfire;g.view.yaw=1.5;g.view.update(g,.1);});await p.waitForTimeout(500);await p.screenshot({path:out+'/mounted-side.png'});
 await p.evaluate(()=>{const g=window.__oathfire;g.store.data.settings.firstPerson=true;g.view.yaw=0;g.view.pitch=.02;});await p.waitForTimeout(500);check('First-person camera is at rider eye height',await p.evaluate(()=>{const g=window.__oathfire;return g.view.camera.position.y-g.hero.pos.y>g.hero.character.mount.userData.seat+.9;}));await p.screenshot({path:out+'/mounted-first-person.png'});
 await p.evaluate(()=>{const g=window.__oathfire;g.store.data.settings.firstPerson=false;g.hero.cooldown=0;g.hero.invuln=0;g.hero.mountHP=1;g.combat.hit(g.hero,10,{team:'enemy',pos:g.hero.pos.clone().add({x:0,y:0,z:-3})},{projectile:true,weapon:'bow'});});check('Exhausted horse dismounts and cannot be summoned again',await p.evaluate(()=>{const g=window.__oathfire;return !g.hero.mount&&g.store.data.mounts.hp.courser===0&&!g.store.data.mounts.riding;}));await p.keyboard.press('h');check('Zero-health remount is blocked',await p.evaluate(()=>!window.__oathfire.hero.mount));
 await p.evaluate(()=>window.__oathfire.returnHome());check('Hearthwatch restores injured horses',await p.evaluate(()=>window.__oathfire.store.data.mounts.hp.courser===320));
 const all=make(23);all.mounts={owned:MOUNTS.map(m=>m.id),selected:'suncrest',riding:true,hp:Object.fromEntries(MOUNTS.map(m=>[m.id,m.hp]))};all.position={x:0,y:0,z:-28};await load(all);await p.evaluate(()=>{const g=window.__oathfire;g.beginMission(24);g.hero.mountHP=387;g.hero.hp=133;g.checkpoint();});await p.reload();await p.waitForFunction(()=>window.__oathfire?.ready,{},{timeout:90000});await p.evaluate(()=>window.__oathfire.start(null,true));check('Suspended siege restores mount, health and riding status',await p.evaluate(()=>{const g=window.__oathfire;return g.battle.id===24&&g.hero.mount?.id==='suncrest'&&g.hero.mountHP===387&&g.hero.hp===133;}));
 check('Objective starts collapsed away from the central aiming area',await p.evaluate(()=>{const e=document.querySelector('#objective-toggle'),r=e.getBoundingClientRect();return document.querySelector('#objective-panel').hidden&&r.left>innerWidth*.75;}));await p.locator('#objective-toggle').tap();check('Objective expands only on demand',await p.locator('#objective-panel').isVisible());await p.locator('#objective-hide').tap();check('Objective hides with the close button',await p.locator('#objective-panel').isHidden());await p.screenshot({path:out+'/siege-hud.png'});
 await p.evaluate(async()=>{const f=window.__oathfire.audio.foley;await f.ready;f.limits.clear();f.impact({weapon:'sword',target:{stats:{armor:20}},hero:true});f.limits.clear();f.impact({weapon:'sword',target:{stats:{armor:20}},heavy:true,hero:true});f.limits.clear();f.impact({weapon:'bow',target:{stats:{armor:20}},hero:true});});check('Quick sword, charged sword and armor arrows use distinct recorded cues',await p.evaluate(()=>{const f=window.__oathfire.audio.foley;return ['hit-sword-armor','hit-sword-armor-heavy','hit-bow-armor'].every(k=>f.history.some(h=>h.key===k))&&f.manifest.banks['combat-v221'].bytes>0;}));
 check('No browser exceptions',report.errors.length===0);
}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
