import {createRequire} from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.argv.includes('--playwright-module')?process.argv[process.argv.indexOf('--playwright-module')+1]:'playwright'));
const base=(process.env.GAME_URL||'http://127.0.0.1:4180').replace(/\/$/,''),out=process.env.QA_OUT||'output/music-qa';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]});
const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true}),page=await context.newPage(),errors=[],report={url:base,checks:[],errors};
page.on('pageerror',e=>errors.push(e.message));const check=(name,ok=true)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS',name);};
const wait=ms=>page.waitForTimeout(ms),debug=()=>page.evaluate(()=>window.__oathfire.audio.music.debug());
try{
 await page.goto(base);await page.waitForFunction(()=>window.__oathfire?.ready);
 check('Royal Orchestra release loaded',await page.evaluate(()=>window.__oathfire.debug().build==='oathfire-2.0.0-kingdom-and-melody'));
 await page.locator('#new-game').tap();await page.locator('#begin-oath').tap();await page.locator('#story-skip').tap();
 await page.waitForFunction(()=>window.__oathfire.audio.music?.state==='ready');await wait(1200);
 let d=await debug();report.bank=d;check('All 26 recorded instrument banks decode within 120 MB',d.loaded===26&&d.decodedMB<120);check('Castle score schedules real sample voices',d.id==='castle'&&d.notes>8&&d.voices>0);check('New campaigns use separate effects and music settings',await page.evaluate(()=>{const s=window.__oathfire.store.data.settings;return s.volume===.55&&s.music===.5;}));
 const rms=async(source)=>page.evaluate(async source=>{const a=window.__oathfire.audio,an=a.ctx.createAnalyser();an.fftSize=2048;a[source].connect(an);const values=[];for(let j=0;j<8;j++){await new Promise(r=>setTimeout(r,70));const b=new Float32Array(an.fftSize);an.getFloatTimeDomainData(b);values.push(Math.sqrt(b.reduce((s,v)=>s+v*v,0)/b.length));}a[source].disconnect(an);return Math.max(...values);},source);
 check('Live output contains music audio',await rms('compressor')>.003);
 await page.evaluate(()=>window.__oathfire.audio.settings({volume:0,music:.65}));await wait(800);check('Muting effects leaves music audible',await rms('compressor')>.003);
 await page.evaluate(()=>window.__oathfire.audio.settings({volume:.7,music:0}));await wait(1600);check('Music mute reaches silence without muting the effects channel',await rms('compressor')<.0002&&await page.evaluate(()=>window.__oathfire.audio.master.gain.value>.69));
 const sfx=await page.evaluate(async()=>{const a=window.__oathfire.audio,an=a.ctx.createAnalyser();an.fftSize=2048;a.compressor.connect(an);a.play('sword');await new Promise(r=>setTimeout(r,65));const b=new Float32Array(an.fftSize);an.getFloatTimeDomainData(b);a.compressor.disconnect(an);return Math.max(...b.map(Math.abs));});check('Sword effects remain audible with music muted',sfx>.005);
 await page.evaluate(()=>{const g=window.__oathfire;g.audio.settings(g.store.data.settings);g.ui.open('settings');});await wait(400);check('Castle menus keep the music running at a quieter level',await page.evaluate(()=>{const m=window.__oathfire.audio.music;return !m.paused&&m.ducked&&m.bus.gain.value<.32;}));check('Settings links to the standalone soundtrack',await page.locator('a[href="./soundtrack.html"]').count()===1);await page.screenshot({path:out+'/settings.png'});
 await page.evaluate(()=>{const g=window.__oathfire;g.ui.close();g.beginMission(0);g.battle.nextWave=9999;});await wait(800);d=await debug();check('First defense switches from castle to Act I march',d.id==='march1'&&d.wave===0);
 const before=await page.evaluate(()=>{const g=window.__oathfire,m=g.audio.music;const before={bar:m.currentBar,elapsed:m.checkpoint().elapsed};g.spawnWave();g.battle.nextWave=9999;return before;});await wait(2400);d=await debug();check('Next wave raises intensity without rewinding the score',d.wave===1&&d.bar>=before.bar&&d.elapsed>before.elapsed&&d.profile.bpm===132);
 await page.locator('#army-button').tap();await wait(250);const paused=await page.evaluate(()=>{const m=window.__oathfire.audio.music;return {c:m.checkpoint(),notes:m.orchestra.notesPlayed,pending:m.pending.length};});await wait(700);check('Battle menu freezes musical position and note scheduling',await page.evaluate(p=>{const m=window.__oathfire.audio.music,c=m.checkpoint();return m.paused&&c.bar===p.c.bar&&Math.abs(c.beat-p.c.beat)<.001&&m.orchestra.notesPlayed===p.notes&&m.pending.length===p.pending;},paused));
 await page.locator('#close-menu').tap();await wait(220);check('Closing the menu resumes within the same measure',await page.evaluate(p=>{const c=window.__oathfire.audio.music.checkpoint();return c.elapsed>=p.c.elapsed&&c.elapsed-p.c.elapsed<.6;},paused));
 await page.evaluate(()=>{const g=window.__oathfire;g.ui.open('pause');g.checkpoint();});await wait(150);const saved=await page.evaluate(()=>{const g=window.__oathfire;g.checkpoint();return {music:g.store.data.battle.music,gear:JSON.stringify(g.store.data.inventory),units:JSON.stringify(g.store.data.units),settings:g.store.data.settings};});
 await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').tap();await page.waitForFunction(()=>window.__oathfire.audio.music?.state==='ready');await wait(250);
 report.resume=await page.evaluate(s=>{const g=window.__oathfire,c=g.audio.music.checkpoint();return {before:s.music,after:c,gear:JSON.stringify(g.store.data.inventory)===s.gear,units:JSON.stringify(g.store.data.units)===s.units,settings:JSON.stringify(g.store.data.settings)===JSON.stringify(s.settings)};},saved);console.log('RESUME',JSON.stringify(report.resume));check('Reload restores musical position, equipment and preferences',report.resume.after.id===saved.music.id&&report.resume.after.bar>=saved.music.bar&&report.resume.after.bar<=saved.music.bar+1&&report.resume.after.elapsed>=saved.music.elapsed-.2&&report.resume.after.elapsed<saved.music.elapsed+1.5&&report.resume.gear&&report.resume.units&&report.resume.settings);
 const newSave=await page.evaluate(()=>{const g=window.__oathfire;g.ui.close();g.store.data.completed=Array.from({length:24},(_,i)=>i);return true;});check('Restored campaign remains playable',newSave);
 for(const [mission,theme,waves]of [[4,'bell',3],[9,'castellan',4],[14,'veyr',5],[19,'regent',6],[23,'hollow',6]]){
  await page.evaluate(({mission,waves})=>{const g=window.__oathfire;g.beginMission(mission);g.battle.nextWave=9999;g.battle.wave=waves-1;g.spawnWave();g.battle.nextWave=9999;}, {mission,waves});await wait(800);d=await debug();check('Boss '+mission+' selects its unique live theme',d.id===theme&&d.notes>0&&!d.paused);
  check('Boss music stays intense after the boss falls while enemies remain',await page.evaluate(()=>{const g=window.__oathfire;g.enemies.find(e=>e.type==='boss').dead=true;g.audio.updateMusic(g);return g.audio.music.scene.kind==='boss'&&g.battle.bossTheme;}));
 }
 await page.evaluate(()=>window.__oathfire.endBattle(true));await wait(500);check('Victory report has its own orchestral cue',(await debug()).id==='victory');
 await page.evaluate(()=>window.__oathfire.returnHome());await wait(500);check('Return to the keep restores the royal suite',(await debug()).id==='castle');
 await page.evaluate(()=>{const g=window.__oathfire;g.beginMission(0);g.endBattle(false);});await wait(300);check('Defeat uses its own quieter theme',(await debug()).id==='defeat');
 await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.beginMission(0);g.battle.nextWave=9999;g.audio.updateMusic(g);});await wait(500);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await wait(150);check('Backgrounding pauses the battle and AudioContext',await page.evaluate(()=>{const g=window.__oathfire;return g.menu==='army'&&g.ui.screen==='pause'&&g.audio.ctx.state==='suspended'&&g.audio.music.paused;}));await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await page.locator('#close-menu').tap();await wait(250);check('A return gesture resumes browser audio',await page.evaluate(()=>window.__oathfire.audio.ctx.state==='running'&&!window.__oathfire.audio.music.paused));
 report.realtime=await debug();check('Realtime orchestra remains below its 112-voice cap',report.realtime.maxVoices<112);
 // Explicitly exercise the only wrapping boundary; no 160-second test delay required.
 await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.audio.updateMusic(g);const m=g.audio.music;m.nextBar=95;m.nextTime=m.ctx.currentTime+.02;m.pending=[];m.pump();});check('Castle schedules its coda then wraps at measure 96',await page.evaluate(()=>{const m=window.__oathfire.audio.music;return m.currentBar===95&&m.nextBar===0;}));
 await page.evaluate(()=>window.__oathfire.checkpoint());
 const player=await context.newPage();player.on('pageerror',e=>errors.push(e.message));await player.goto(base+'/soundtrack.html');await player.locator('#play').tap();await player.waitForFunction(()=>window.__oathfireMusic?.sound.music?.state==='ready');
 for(const id of ['castle','march1','march2','march3','march4','march5','bell','castellan','veyr','regent','hollow']){await player.locator('[data-track="'+id+'"]').tap();await player.waitForTimeout(250);check('Soundtrack player plays '+id,await player.evaluate(id=>window.__oathfireMusic.sound.music.scene.id===id&&!window.__oathfireMusic.sound.music.paused&&(id==='castle'?document.getElementById('status').textContent.includes('3:35'):document.getElementById('status').textContent.includes('Continuous')),id));}
 await player.locator('[data-track="march3"]').tap();await player.locator('[data-wave="5"]').tap();await player.waitForTimeout(2000);check('Auditioning wave five applies the strongest act arrangement',await player.evaluate(()=>window.__oathfireMusic.sound.music.lastProfile.intensity===.88));await player.locator('#play').tap();const clock=await player.locator('#clock').innerText();await player.waitForTimeout(300);check('Pause freezes the displayed soundtrack clock',clock===await player.locator('#clock').innerText());
 for(const size of [{width:667,height:375},{width:844,height:390},{width:390,height:844}]){await player.setViewportSize(size);check('Soundtrack fits '+size.width+'x'+size.height+' with touch sized controls',await player.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&[...document.querySelectorAll('button')].every(b=>b.getBoundingClientRect().height>=44)));await player.screenshot({path:out+'/soundtrack-'+size.width+'.png',fullPage:true});}
 if(!base.includes('4179')){await page.bringToFront();await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await page.waitForFunction(()=>navigator.serviceWorker.controller);const cached=await page.evaluate(async()=>{const c=await caches.keys(),cache=await caches.open(c.find(k=>k.startsWith('oathfire-')));return (await cache.keys()).filter(r=>/music\/.*\.m4a$/.test(r.url)).length;});check('All new and retained orchestral banks are cached for offline play',cached===44);await context.setOffline(true);await player.bringToFront();await player.reload();await player.locator('#play').tap();await player.waitForFunction(()=>window.__oathfireMusic?.sound.music?.state==='ready');check('Soundtrack navigation and orchestra work offline',await player.evaluate(()=>window.__oathfireMusic.sound.music.orchestra.notesPlayed>0));await context.setOffline(false);}
 // An isolated uncached page verifies a failed audio download cannot break the game and can retry.
 const failureContext=await browser.newContext({serviceWorkers:'block'}),failure=await failureContext.newPage();await failure.route('**/music/chamber/violin.m4a',r=>r.abort());await failure.goto(base+'/soundtrack.html');await failure.locator('#play').click();await failure.waitForFunction(()=>window.__oathfireMusic?.sound.music?.state==='unavailable');check('Audio load failure offers a retry',/retry/.test(await failure.locator('#status').innerText()));await failure.unroute('**/music/chamber/violin.m4a');await failure.locator('#play').click();await failure.waitForFunction(()=>window.__oathfireMusic.sound.music.state==='ready');check('Retry successfully loads the orchestra',await failure.locator('#play').innerText()==='Pause score');await failureContext.close();
 check('No browser runtime errors',errors.length===0);
}catch(e){report.failure=e.stack;console.error(e.stack);process.exitCode=1;await page.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
