import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.argv.includes('--playwright-module')?process.argv[process.argv.indexOf('--playwright-module')+1]:'playwright'));
const base=process.env.GAME_URL||(process.argv.includes('--url')?process.argv[process.argv.indexOf('--url')+1]:'http://127.0.0.1:4178'),out='work/qa';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]});const page=await browser.newPage({viewport:{width:1280,height:720}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const report={url:base,checks:[],errors};const check=(name,value=true)=>{assert.ok(value,name);report.checks.push(name);console.log('PASS',name);};
try{
await page.goto(base);await page.waitForFunction(()=>window.__oathfire?.ready,{timeout:45000});await page.locator('#new-game').click();await page.locator('#begin-oath').click();await page.locator('#story-skip').click();await page.waitForFunction(()=>window.__oathfire?.hero?.phys.grounded);check('Game loads; character grounded on actual terrain');
await page.screenshot({path:out+'/01-courtyard.png'});
const before=await page.evaluate(()=>window.__oathfire.hero.pos.toArray());await page.keyboard.down('KeyD');await page.waitForTimeout(1200);const walking=await page.evaluate(()=>{let g=window.__oathfire,c=g.hero.character;return {pos:g.hero.pos.toArray(),anim:c.actionName,leg:c.sockets.upperlegl.quaternion.toArray()};});await page.waitForTimeout(220);const legs=await page.evaluate(()=>window.__oathfire.hero.character.sockets.upperlegl.quaternion.toArray());await page.keyboard.up('KeyD');console.log('MOVEMENT',JSON.stringify({before,walking,legs}));check('WASD moves the hero with an active running animation',walking.pos[0]>before[0]+2&&walking.anim.includes('Running'));check('Full-body skeleton changes while walking',walking.leg.some((v,i)=>Math.abs(v-legs[i])>.03));
await page.keyboard.press('KeyJ');await page.waitForTimeout(300);let light=await page.evaluate(()=>window.__oathfire.debug());check('Quick input triggers a light attack',light.combat.light===1);await page.waitForTimeout(700);await page.keyboard.down('KeyJ');await page.waitForTimeout(700);await page.keyboard.up('KeyJ');await page.waitForTimeout(120);check('Held input releases a distinct charged attack',(await page.evaluate(()=>window.__oathfire.debug())).combat.heavy===1);
await page.keyboard.press('Space');await page.waitForTimeout(200);check('Jump input leaves the ground',!(await page.evaluate(()=>window.__oathfire.hero.phys.grounded)));await page.waitForTimeout(700);
await page.keyboard.down('KeyJ');await page.waitForTimeout(550);check('Holding attack keeps an anticipation pose',await page.evaluate(()=>window.__oathfire.hero.charging&&window.__oathfire.hero.character.current.paused));const attackCount=await page.evaluate(()=>window.__oathfire.combat.stats.light+window.__oathfire.combat.stats.heavy);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(120);await page.keyboard.up('KeyJ');await page.waitForTimeout(180);check('Losing focus cancels charge without a ghost strike',await page.evaluate(n=>{const g=window.__oathfire;return !g.hero.charging&&!g.hero.character.current.paused&&g.combat.stats.light+g.combat.stats.heavy===n;},attackCount));
await page.locator('#portrait').click();await page.screenshot({path:out+'/02-character.png'});check('Character menu contains live 3D model and skill trees',await page.locator('.skill-list .card').count()===6);for(const name of ['equipment','troops','defenses','campaign','shop','journal','settings']){await page.locator('[data-tab="'+name+'"]').click();check(name+' menu renders content',(await page.locator('#menu-content').innerText()).length>150);}
await page.locator('[data-tab="troops"]').click();await page.locator('[data-action="rank"][data-value="10"]').click();await page.screenshot({path:out+'/03-troop-rank-x.png'});check('Rank X is visibly inspectable', (await page.locator('#preview-caption').innerText()).includes('X'));await page.locator('[data-tab="defenses"]').click();await page.locator('[data-action="rank"][data-value="10"]').click();await page.screenshot({path:out+'/04-tower-rank-x.png'});
const supplies=await page.evaluate(()=>window.__oathfire.store.data.supplies);await page.locator('[data-action="upgrade-defense"]').click();check('Defense upgrade charges resources and changes actual tower',(await page.evaluate(()=>({s:window.__oathfire.store.data.supplies,r:window.__oathfire.world.towerObjects[0].level}))).r===2);check('Upgrade cost deducted',(await page.evaluate(()=>window.__oathfire.store.data.supplies))<supplies);
await page.locator('[data-tab="equipment"]').click();const bowID=await page.evaluate(()=>window.__oathfire.store.data.inventory.find(i=>i.type==='bow').id);await page.locator('[data-action="item"][data-id="'+bowID+'"]').click();await page.locator('[data-action="equip"]').click();await page.locator('#close-menu').click();await page.keyboard.press('KeyJ');await page.waitForTimeout(450);const projectile=await page.evaluate(()=>window.__oathfire.combat.projectiles[0]?.pos.toArray());check('Equipped bow launches a visible arrow mesh',!!projectile);await page.waitForTimeout(180);const projectile2=await page.evaluate(()=>window.__oathfire.combat.projectiles[0]?.pos.toArray());check('Arrow travels through the world',projectile2&&Math.hypot(...projectile2.map((n,i)=>n-projectile[i]))>1);
// Deterministic physics fixtures use the real capsule controller and fixed simulation steps.
const collision=await page.evaluate(()=>{const g=window.__oathfire,h=g.hero;g.input.clear();const run=(n,move,jump=false)=>{let max=-99;for(let i=0;i<n;i++){g.physics.move(h.phys,move,1/60,jump&&i===0);g.physics.step();g.physics.position(h.phys,h.pos);max=Math.max(max,h.pos.y);}return {p:h.pos.toArray(),max};};g.physics.teleport(h.phys,{x:8,y:0,z:-28.5});run(20,{x:0,y:0,z:0});const grounded=h.phys.grounded,blocked=run(60,{x:0,y:0,z:-5});g.physics.teleport(h.phys,{x:8,y:0,z:-29.4});run(20,{x:0,y:0,z:0});const jumped=run(65,{x:0,y:0,z:-5},true);return {grounded,blocked,jumped};});console.log('PHYSICS',JSON.stringify(collision));check('Solid rock blocks walking',collision.blocked.p[2]>-32);check('Jump clears low rock with real collision',collision.jumped.max>1&&collision.jumped.p[2]<-32.8);
const stairs=await page.evaluate(()=>{const g=window.__oathfire,h=g.hero,original=h.pos.clone();g.physics.teleport(h.phys,{x:-30,y:0,z:-9.5});for(let i=0;i<480;i++){g.physics.move(h.phys,{x:0,z:i<20?0:5},1/60);g.physics.step();g.physics.position(h.phys,h.pos);}const result=h.pos.toArray();g.physics.teleport(h.phys,original);return result;});console.log('RAMPART',stairs);check('Castle stairs lead to the raised treasure walkway',stairs[1]>5&&stairs[2]>25);
await page.evaluate(()=>{const g=window.__oathfire;g.physics.teleport(g.hero.phys,{x:58,y:g.world.height(58,-38),z:-37});for(let i=0;i<5;i++){g.physics.move(g.hero.phys,{x:0,z:0},1/60);g.physics.step();g.physics.position(g.hero.phys,g.hero.pos);}});await page.keyboard.press('KeyF');await page.waitForTimeout(200);check('Exploration chest grants unique loot',(await page.evaluate(()=>window.__oathfire.store.data.treasures.length))===1);
await page.locator('#pause-btn').click();await page.locator('[data-tab="hero"]').click();await page.locator('[data-action="hero"][data-id="ashwright"]').click();await page.locator('#close-menu').click();await page.keyboard.press('KeyQ');await page.waitForFunction(()=>window.__oathfire.combat.stats.casts.fireball===1&&window.__oathfire.audio.history.some(a=>a.name==='fireball'),null,{timeout:10000});check('Ashwright casts visible fire with a unique sound',await page.evaluate(()=>window.__oathfire.combat.stats.casts.fireball===1&&window.__oathfire.audio.history.some(a=>a.name==='fireball')));await page.screenshot({path:out+'/05-fireball.png'});
await page.locator('#pause-btn').click();await page.locator('[data-tab="campaign"]').click();await page.locator('[data-action="embark"]').click();await page.locator('#begin-defense').click();await page.waitForTimeout(300);await page.locator('#army-button').click();await page.locator('[data-action="recruit"][data-id="bow"]').click();check('Army deployment creates one animated bow soldier',(await page.evaluate(()=>window.__oathfire.allies.filter(a=>a.unit==='bow').length))===1);await page.locator('[data-action="order"][data-id="follow"]').click();await page.locator('#close-menu').click();await page.screenshot({path:out+'/06-battlefield.png'});
await page.evaluate(()=>window.__oathfire.checkpoint());const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('oathfire.campaign.v1')));await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').click();check('Reload resumes battle and army',(await page.evaluate(()=>window.__oathfire.battle.id===0&&window.__oathfire.allies.length===6)));check('Save resources preserved',(await page.evaluate(()=>window.__oathfire.store.data.supplies))===saved.supplies);
await page.setViewportSize({width:844,height:390});await page.screenshot({path:out+'/07-mobile-combat.png'});const overflow=await page.evaluate(()=>[...document.querySelectorAll('#hud button')].filter(e=>!e.hidden&&e.getBoundingClientRect().width).filter(e=>{const r=e.getBoundingClientRect();return r.right>innerWidth+1||r.left<0||r.bottom>innerHeight+1||r.top<0;}).map(e=>e.id));check('All mobile combat buttons fit the viewport',overflow.length===0);await page.locator('#pause-btn').click();await page.locator('[data-tab="hero"]').click();await page.screenshot({path:out+'/08-mobile-character.png'});check('Mobile menus remain scrollable',(await page.evaluate(()=>document.getElementById('menu-content').scrollHeight>document.getElementById('menu-content').clientHeight)));
if(process.argv.includes('--pwa')){await page.evaluate(()=>navigator.serviceWorker.ready);await page.context().setOffline(true);await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready,{timeout:30000});await page.locator('#continue-game').click();check('Installed build starts and resumes with the network offline',await page.evaluate(()=>!!window.__oathfire.hero&&!!window.__oathfire.battle));await page.context().setOffline(false);}
check('No runtime or WebGL shader errors',errors.length===0);report.physics=collision;report.final=await page.evaluate(()=>window.__oathfire.debug());
}catch(e){report.failure=e.message;report.diagnostics=await page.evaluate(()=>{const g=window.__oathfire;return g?{state:g.debug(),sounds:g.audio.history.slice(-10),audio:g.audio.ctx?.state}:null;}).catch(()=>null);console.error(e.stack);await page.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
