import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({headless:true,args:['--use-angle=metal']}),page=await browser.newPage({viewport:{width:844,height:390},isMobile:true,hasTouch:true}),errors=[],checks=[];const url=process.env.GAME_URL||'http://127.0.0.1:4180';page.on('pageerror',e=>errors.push(e.message));const check=(name,pass)=>{assert.ok(pass,name);checks.push(name);console.log('PASS',name);};
try{
 await page.goto(url);await page.waitForFunction(()=>window.__oathfire?.ready);check('Production build is 2.4.0',await page.evaluate(()=>window.__oathfire.debug().build==='oathfire-2.4.0-active-oaths'));
 await page.locator('#new-game').tap();await page.locator('#begin-oath').tap();await page.locator('#story-skip').tap();
 await page.evaluate(()=>{const g=window.__oathfire;g.store.data.guide.active=false;g.beginMission(0);g.store.data.heroes.warden.level=2;g.defeat('Regroup and return.');});
 await page.locator('[data-result="home"]').tap();check('A level earned during defeat still gets its reveal',await page.locator('.level-numbers').innerText()==='1\n→\n2');await page.locator('[data-unlock="next"]').tap();check('New active ability gets a specific reveal',/Signal Volley/.test(await page.locator('.unlock-copy').innerText()));await page.locator('[data-unlock="next"]').tap();
 await page.locator('[data-unlock="go"][data-id="hero"]').tap();check('Next-step button opens the revealed ability',await page.locator('.technique-detail').getAttribute('data-technique')==='volley');await page.locator('[data-action="skill"][data-id="volley"]').tap();await page.locator('[data-action="ability-equip"][data-value="1"]').tap();await page.waitForTimeout(3900);await page.locator('.technique-detail').scrollIntoViewIfNeeded();
 fs.mkdirSync('output/progression',{recursive:true});await page.screenshot({path:'output/progression/'+(url.includes('github.io')?'live':'production')+'-abilities.png'});
 await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);check('Production saves preserve the learned and equipped active',await page.evaluate(()=>{const h=window.__oathfire.store.data.heroes.warden;return h.skills.volley===1&&h.slots[1]==='volley';}));await page.locator('#continue-game').tap();await page.evaluate(()=>{const g=window.__oathfire;g.ui.unlocks.hide();g.ui.close();g.beginMission(0);g.battle.nextWave=999;});await page.locator('#spell-1').tap();check('Production combat button fires the learned spell',await page.evaluate(()=>window.__oathfire.combat.stats.casts.volley===1));
 check('No runtime errors',errors.length===0);
}catch(e){console.error(e.stack);process.exitCode=1;}finally{fs.writeFileSync('output/progression/'+(url.includes('github.io')?'live':'production')+'-smoke.json',JSON.stringify({url,checks,errors,success:!process.exitCode},null,2));await browser.close();}
