import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,args:['--use-angle=metal']}),page=await browser.newPage({viewport:{width:844,height:390},isMobile:true,hasTouch:true}),out='output/progression',report={checks:[],errors:[]};fs.mkdirSync(out,{recursive:true});page.on('pageerror',e=>report.errors.push(e.message));const check=(name,ok)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS',name);};
try{
 await page.routeWebSocket('**',ws=>ws.close());await page.goto(process.env.GAME_URL||'http://127.0.0.1:4179');await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#new-game').tap();await page.locator('#begin-oath').tap();await page.locator('#story-skip').tap();
 await page.evaluate(()=>{const g=window.__oathfire;g.store.commit(s=>{s.guide.active=false;s.heroes.warden.level=2;});g.ui.open('hero');});
 await page.locator('[data-action="detail-section"][data-id="skills"]').first().tap();
 await page.locator('[data-action="ability-select"][data-id="volley"]').tap();
 check('Abilities are separate from passive training and show the level-two unlock',await page.locator('.technique-detail').getAttribute('data-technique')==='volley');
 await page.locator('[data-action="skill"][data-id="volley"]').tap();await page.locator('[data-action="ability-equip"][data-value="1"]').tap();
 check('Learning and equipping through mobile controls spends one point and changes button two',await page.evaluate(()=>{const h=window.__oathfire.store.data.heroes.warden;return h.skills.volley===1&&h.slots[1]==='volley';}));
 await page.waitForTimeout(3900);await page.screenshot({path:out+'/learn-equip-844.png'});
 await page.evaluate(()=>{const g=window.__oathfire;g.ui.close();g.beginMission(0);g.battle.nextWave=999;});await page.locator('#spell-1').tap();await page.waitForTimeout(450);
 check('The newly equipped combat button actually casts Signal Volley',await page.evaluate(()=>window.__oathfire.combat.stats.casts.volley===1));
 report.spells=await page.evaluate(async()=>{
  const {HEROES}=await import('/src/data.js'),{skillRank,trainSkill,equipTechnique}=await import('/src/state.js'),g=window.__oathfire,rows=[];
  for(const [hero,data]of Object.entries(HEROES))for(const node of data.skills.filter(n=>n.active)){
   g.battle=null;g.store.data.battle=null;g.store.data.hero=hero;const h=g.store.data.heroes[hero];h.level=30;h.questPoints=6;h.skills={};h.slots=[...data.starter];h.capstone=null;while(skillRank(g.store.data,node.id)<node.max)trainSkill(g.store.data,node.id);equipTechnique(g.store.data,node.id,0);
   g.beginMission(0);g.battle.nextWave=999;g.ui.open('army');g.hero.pos.set(0,0,-35);g.physics.teleport(g.hero.phys,g.hero.pos);g.hero.hp=100;g.hero.focus=200;g.hero.stamina=200;g.view.yaw=0;
   const enemy=g.spawnEnemy('brute',{x:0,y:0,z:-40},{hp:9999});const ally=g.spawnAlly('bow',{x:1,y:0,z:-36});ally.hp=1;g.physics.step();const before=g.combat.stats.projectiles;g.combat.cast(node.id);for(let i=0;i<20;i++)g.combat.update(1/60);
   rows.push({hero,id:node.id,cast:g.combat.stats.casts[node.id]||0,animation:g.hero.character.actionName,projectiles:g.combat.stats.projectiles-before,hp:g.hero.hp,focus:g.hero.focus,dash:g.hero.dash,protect:g.hero.protect,buff:g.hero.buff,marked:enemy.marked,rooted:enemy.rooted,zones:g.combat.zones.map(z=>({kind:z.kind,heal:z.heal})),overdrive:g.battle.overdrive,hurt:enemy.hp<9999});
  }return rows;
 });
 for(const r of report.spells){const ok=['step','windstep'].includes(r.id)?r.dash>0:r.id==='fireball'||r.id==='volley'||r.id==='guide'?r.projectiles>0:r.id==='quench'?r.hp>100:r.id==='rally'?r.buff>0:r.id==='thorns'?r.rooted>0:r.id==='mark'?r.marked===8:['bulwark','tether','sunwall'].includes(r.id)?r.protect>0:r.id==='overdrive'?r.overdrive===12:r.id==='mine'?r.zones.length===3:['seedward','march','sanctuary','grove'].includes(r.id)?r.zones.some(z=>z.heal>0):r.hurt||r.zones.length>0;check(r.hero+' / '+r.id+' casts and produces its combat effect',r.cast>0&&ok);}
 report.units=await page.evaluate(async()=>{
  const {UNITS}=await import('/src/data.js'),{unitInspection}=await import('/src/inspection.js'),g=window.__oathfire,result=[];g.store.data.completed=Array.from({length:24},(_,i)=>i);
  for(const id of Object.keys(UNITS))for(const rank of [1,10]){g.store.data.units[id]=rank;g.beginMission(0);g.battle.nextWave=999;g.ui.open('army');const pos={x:0,y:0,z:-35},a=g.spawnAlly(id,pos);const e=g.spawnEnemy('brute',{x:0,y:0,z:-37},{hp:10000});g.hero.pos.set(0,0,-34);g.physics.teleport(g.hero.phys,g.hero.pos);g.hero.hp=100;g.battle.gate=100;g.gatePos.set(0,0,-35);a.hp=a.stats.hp;g.physics.step();
   const stats=unitInspection(id,rank);if(id==='lantern')g.ai(a,.1);if(id==='engineer'||id==='banner'){g.ai(a,.1);g.battleTick(.1);}if(id==='rider')a.cavalryCharge=true;
   const hp=e.hp;g.combat.hit(e,100,a,{weapon:a.weapon});if(id==='dawn')for(let i=1;i<a.stats.healEvery;i++)g.combat.hit(e,1,a,{weapon:a.weapon});
   result.push({id,rank,stats:a.stats,preview:stats,damage:hp-e.hp,knock:e.knock?.length()||0,stun:e.stun||0,healed:g.hero.hp-100,gate:g.battle.gate,income:g.battle.standardIncome||0});
  }return result;
 });
 for(const id of ['pike','breaker','crew','rider','assassin','marksman']){const [a,b]=report.units.filter(r=>r.id===id);check(id+' training changes real hit damage against armor or siege targets',b.damage>a.damage);}
 for(const id of ['lantern','dawn']){const [a,b]=report.units.filter(r=>r.id===id);check(id+' training restores more health in combat',b.healed>a.healed);}
 for(const id of ['crew','giant']){const [a,b]=report.units.filter(r=>r.id===id);check(id+' training increases physical knockback',b.knock>a.knock);}
 const engineers=report.units.filter(r=>r.id==='engineer'),banners=report.units.filter(r=>r.id==='banner');check('Training improves actual gate repairs and limited standard income',engineers[1].gate>engineers[0].gate&&banners[1].income>banners[0].income);
 report.projectiles=await page.evaluate(async()=>{
  const g=window.__oathfire,out=[];for(const unit of ['frost','pyre'])for(const rank of [1,10]){g.store.data.units[unit]=rank;g.beginMission(0);g.battle.nextWave=999;g.ui.open('army');const a=g.spawnAlly(unit,{x:0,y:0,z:-40}),e=g.spawnEnemy('brute',{x:0,y:0,z:-44},{hp:10000}),edge=g.spawnEnemy('brute',{x:2.2,y:0,z:-44},{hp:10000});g.physics.step();g.ai(a,.01);for(let i=0;i<100;i++)g.combat.update(1/60);out.push({unit,rank,slow:e.rimeStrength,duration:e.rimeTime,edgeDamage:10000-edge.hp});}return out;
 });
 const ice=report.projectiles.filter(r=>r.unit==='frost'),fire=report.projectiles.filter(r=>r.unit==='pyre');check('Travelling ice projectiles apply stronger and longer slows',ice[1].slow>ice[0].slow&&ice[1].duration>ice[0].duration);check('Trained fireballs actually damage enemies beyond the original blast radius',fire[0].edgeDamage===0&&fire[1].edgeDamage>0);
 report.holdRange=await page.evaluate(()=>{const g=window.__oathfire,out=[];for(const rank of [1,10]){g.store.data.units.bow=rank;g.beginMission(0);g.ui.open('army');const a=g.spawnAlly('bow',{x:0,y:0,z:-45}),e=g.spawnEnemy('hollow',{x:0,y:0,z:-80});g.physics.step();a.order='hold';g.holdPoint.copy(a.pos);g.ai(a,.01);out.push({rank,cooldown:a.cooldown,speed:a.velocity.length()});}return out;});check('Veteran archers use their longer range while holding ground',report.holdRange[0].cooldown===0&&report.holdRange[1].cooldown>0);
 await page.evaluate(async()=>{const g=window.__oathfire,{trainSkill}=await import('/src/state.js');g.battle=null;g.store.data.battle=null;g.store.data.hero='warden';trainSkill(g.store.data,'volley');trainSkill(g.store.data,'sunwall');g.returnHome();g.ui.open('hero');g.ui.action('ability-select','sunwall');});
 await page.waitForTimeout(3900);report.layouts=[];for(const [width,height]of [[844,390],[667,375],[390,844]]){await page.setViewportSize({width,height});await page.evaluate(()=>document.body.classList.add('allow-portrait'));await page.waitForTimeout(350);await page.locator('.technique-detail').scrollIntoViewIfNeeded();report.layouts.push(await page.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,buttons:[...document.querySelectorAll('.technique-equip button')].map(b=>{const r=b.getBoundingClientRect();return r.width>=90&&r.height>=42&&r.right<=innerWidth;})})));await page.screenshot({path:out+'/abilities-'+width+'.png'});}check('Ability detail and equip controls fit landscape and portrait phones',report.layouts.every(l=>!l.overflow&&l.buttons.every(Boolean)));
 await page.evaluate(()=>{const g=window.__oathfire;g.store.data.hero='warden';g.ui.open('troops');g.ui.action('inspect-object','frost','troops');g.ui.action('rank',null,'1');g.ui.action('detail-section','upgrade');});await page.setViewportSize({width:844,height:390});await page.locator('.rank-comparison').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/frost-upgrade.png'});check('Upgrade comparisons include tactical percentages and durations',/Movement slowed/.test(await page.locator('.rank-comparison').innerText())&&/Slow duration/.test(await page.locator('.rank-comparison').innerText()));
 await page.evaluate(async()=>{const g=window.__oathfire,{createUnlockReview}=await import('/src/unlocks.js');g.ui.close();g.beginMission(0);g.victory();g.store.data.lastBattle.tutorial={version:1,cards:[{kind:'ability',id:'volley',hero:'warden'}],cursor:0,complete:false};g.ui.unlocks.show();});
 for(const [width,height]of [[844,390],[667,375],[390,844]]){await page.setViewportSize({width,height});await page.waitForTimeout(350);check('Ability reveal fits '+width+'×'+height+' without scrolling',await page.evaluate(()=>{const el=document.querySelector('.unlock-copy');return el.scrollHeight<=el.clientHeight+1&&el.scrollWidth<=el.clientWidth+1;}));await page.screenshot({path:out+'/unlock-'+width+'.png'});}
 await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);check('Trained abilities and pending unlock reveal survive reload',await page.evaluate(()=>{const s=window.__oathfire.store.data;return s.heroes.warden.skills.volley>0&&s.lastBattle.tutorial.cards[0].kind==='ability';}));check('No browser runtime errors',report.errors.length===0);
}catch(e){report.failure=e.stack;process.exitCode=1;console.error(e.stack);}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
