import{createRequire}from'node:module';import fs from'node:fs';import assert from'node:assert/strict';import{newSave,makeItem}from'../src/state.js';import{UNITS}from'../src/data.js';import{regimentStats,regimentUpgrade}from'../src/regiment-details.js';import{equipmentName}from'../src/equipment-name.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),base=process.env.GAME_URL||'http://127.0.0.1:4179',out=process.env.QA_OUT||'work/qa-regiments';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=metal']}),page=await browser.newPage({viewport:{width:844,height:390},hasTouch:true}),report={url:base,checks:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));const check=(n,v)=>{assert.ok(v,n);report.checks.push(n);console.log('PASS',n)},click=(a,id)=>page.locator('[data-action="'+a+'"]'+(id?'[data-id="'+id+'"]':'')+':visible').click();const shot=async name=>{await page.evaluate(()=>document.querySelectorAll('.toast').forEach(e=>e.remove()));await page.waitForFunction(()=>window.__oathfire.ui.preview?.phase>1.4);await page.screenshot({path:out+'/'+name+'.jpg',quality:86});};
const s=newSave();s.guide.active=false;s.completed=Array.from({length:15},(_,i)=>i);s.supplies=12000;const armor=makeItem('armor',4,20,()=>.4,'bastion'),weapon=makeItem('sword',5,20,()=>.4);armor.name='Vigorous Crownplate of the Last Dawn';weapon.name='Infernal Dawnfang of the Last Ember';s.inventory.push(armor,weapon);
try{
 await page.goto(base);await page.waitForFunction(()=>window.__oathfire?.ready);check('Release 2.9.0 is running',(await page.locator('#title-screen').innerText()).includes('2.9.0'));await page.evaluate(s=>{const g=window.__oathfire;g.store.import(JSON.stringify(s));g.start(null,true);},s);await page.waitForFunction(()=>window.__oathfire.hero);if(await page.locator('#story-skip').isVisible())await page.locator('#story-skip').click();await page.locator('#pause-btn').click();await click('navigate','troops');
 check('Regiments opens directly into the three-column roster, model and stats',await page.locator('.regiment-choice').count()===15&&await page.locator('.regiment-sheet').isVisible()&&await page.locator('#menu-nav').isHidden()&&await page.locator('.destination-tile').count()===0);
 check('No unrelated salvage or hero skill points on the army screen',! /SALVAGE|SKILL POINTS/.test(await page.locator('#resources').innerText()));
 const snapshot=await page.evaluate(()=>{const s=window.__oathfire.store.data;return JSON.stringify({u:s.units,i:s.inventory,s:s.supplies});});
 const expected=Object.entries(UNITS).flatMap(([id])=>Array.from({length:10},(_,i)=>({id,rank:i+1,rows:regimentStats(id,i+1).rows.map(r=>[r.key,r.text])})));
 const audit=await page.evaluate(expected=>{const g=window.__oathfire,fail=[];for(const x of expected){g.ui.unit=x.id;g.ui.previewRank=x.rank;g.ui.regimentMode='stats';g.ui.draw();for(const [key,text]of x.rows){const el=document.querySelector('[data-stat="'+key+'"] dd');if(el?.textContent!==text)fail.push(x.id+x.rank+key);}if(!document.querySelector('.regiment-purpose')?.textContent||/NaN|undefined|Infinity/.test(document.querySelector('.regiment-sheet').textContent))fail.push(x.id+x.rank+'copy');}return fail;},expected);
 check('All 150 unit-rank profiles match combat values with tactical descriptions',audit.length===0);
 check('Inspecting all ranks spends nothing and preserves equipment',snapshot===await page.evaluate(()=>{const s=window.__oathfire.store.data;return JSON.stringify({u:s.units,i:s.inventory,s:s.supplies});}));
 await click('regiment-select','bow');await page.selectOption('#regiment-rank','10');check('Future rank changes the animated model without training',await page.evaluate(()=>window.__oathfire.ui.preview.rank===10&&window.__oathfire.store.data.units.bow===1));
 await click('regiment-upgrade');const cost=regimentUpgrade('bow',1).cost;check('Upgrade previews next owned rank with cost and exact range gain',await page.locator('.training-price').innerText().then(t=>t.includes(cost+' Supplies'))&&(await page.locator('[data-upgrade-stat="reach"]').innerText()).includes('+1.5 m')&&await page.evaluate(()=>window.__oathfire.ui.preview.rank===2));await shot('longbow-upgrade');await click('regiment-cancel');check('Cancelling restores owned model and spends nothing',snapshot===await page.evaluate(()=>{const s=window.__oathfire.store.data;return JSON.stringify({u:s.units,i:s.inventory,s:s.supplies});})&&await page.evaluate(()=>window.__oathfire.ui.preview.rank===1));
 await click('regiment-upgrade');await click('regiment-confirm','bow');check('Confirm buys exactly one rank at the previewed price',await page.evaluate(cost=>window.__oathfire.store.data.units.bow===2&&window.__oathfire.store.data.supplies===12000-cost,cost));await page.evaluate(()=>window.__oathfire.ui.action('regiment-confirm','bow'));check('Duplicate confirmation cannot purchase another rank',await page.evaluate(()=>window.__oathfire.store.data.units.bow===2));
 await page.evaluate(()=>{const g=window.__oathfire;g.store.commit(s=>{s.units.shield=3;});g.ui.action('regiment-select','shield');});await click('regiment-upgrade');check('Squad upgrade discloses both extra soldiers and higher deployment cost',await page.locator('[data-upgrade-stat="count"]').innerText().then(t=>t.includes('+1'))&&await page.locator('[data-upgrade-stat="cost"]').innerText().then(t=>t.includes('Command')));await shot('shieldward-company-upgrade');await click('regiment-cancel');
 await page.evaluate(()=>{const g=window.__oathfire;g.store.commit(s=>{s.units.pyre=4;});g.ui.action('regiment-select','pyre');});await click('regiment-upgrade');check('New rank ability is described before confirming',await page.locator('.training-ability').innerText().then(t=>t.includes('Lingering embers')&&t.includes('3s')));await click('regiment-cancel');
 await page.evaluate(()=>{const g=window.__oathfire;g.store.commit(s=>{s.supplies=0;});g.ui.action('regiment-select','bow');});await click('regiment-upgrade');check('Unaffordable upgrades remain previewable but cannot be confirmed',await page.locator('[data-action="regiment-confirm"]').isDisabled()&&await page.locator('.regiment-warning').innerText().then(t=>t.includes('more Supplies')));await click('regiment-cancel');
 await page.evaluate(()=>{const g=window.__oathfire;g.store.commit(s=>{s.completed=[];s.units.shield=5;s.supplies=12000;});g.ui.action('regiment-select','shield');});check('Campaign rank cap cannot be bypassed',await page.locator('[data-action="regiment-upgrade"]').isDisabled());await click('regiment-select','giant');check('Locked units can be inspected but cannot be upgraded',await page.locator('[data-action="regiment-upgrade"]').isDisabled()&&await page.locator('.regiment-warning').isVisible());await click('regiment-abilities');check('Specific ability mechanics are accessible',await page.locator('.regiment-abilities').innerText().then(t=>t.includes('push')&&t.includes('Captains')));await click('regiment-overview');
 await page.evaluate(()=>{const g=window.__oathfire;g.store.commit(s=>{s.completed=Array.from({length:15},(_,i)=>i);s.units.shield=10;s.units.bow=10;});g.ui.action('regiment-select','shield');});check('Max-rank troops have no purchase action',await page.locator('[data-action="regiment-upgrade"]').isDisabled()&&(await page.locator('[data-action="regiment-upgrade"]').innerText())==='Fully trained');
 for(const [w,h]of [[1280,720],[844,390],[667,375],[390,844]]){
  await page.setViewportSize({width:w,height:h});if(w<h&&await page.locator('#portrait-continue').isVisible())await page.locator('#portrait-continue').click();
  for(const id of ['shield','bow','banner','rider']){
   await click('regiment-select',id);await shot('regiment-'+id+'-'+w);
   const layout=await page.evaluate(()=>{const rect=e=>e.getBoundingClientRect(),els=['#regiment-roster','#model-stage','#menu-content','.regiment-actions'];return {viewport:[innerWidth,innerHeight],overflow:els.filter(sel=>{const e=document.querySelector(sel),r=rect(e);return e.scrollWidth>e.clientWidth+1||r.left<-.5||r.right>innerWidth+.5||r.bottom>innerHeight+.5;}),buttons:[...document.querySelectorAll('.regiment-actions button,#close-menu')].every(e=>{const r=rect(e);return r.height>=40&&r.top>=0&&r.bottom<=innerHeight;})};});check(id+' layout and controls fit '+w+'×'+h,layout.overflow.length===0&&layout.buttons);
  }
 }
 await page.setViewportSize({width:844,height:390});await page.evaluate(()=>{const g=window.__oathfire;g.ui.close();g.beginMission(0);g.ui.open('army');});await click('battle-category','troops');check('Battle troop tab uses the same clean roster and live model',await page.locator('.regiment-menu').count()===1&&await page.locator('#model-stage').isVisible()&&await page.locator('.field-filters').count()===0&&await page.locator('[data-action="regiment-upgrade"]').count()===0);
 await page.evaluate(()=>{const g=window.__oathfire;g.battle.command=220;g.battle.research=[{id:'infantry',complete:true,remaining:0}];g.ui.action('regiment-select','shield');});const fieldExpected=regimentStats('shield',10,{research:[{id:'infantry',complete:true,remaining:0}]}).stats;check('Battle profile includes completed research',Number(await page.locator('[data-stat="damage"] dd').innerText())===fieldExpected.damage);const before=await page.evaluate(()=>({c:window.__oathfire.battle.command,n:window.__oathfire.allies.length}));await click('recruit','shield');check('Recruitment charges shown cost and creates shown squad size',await page.evaluate(({before,cost,count})=>{const g=window.__oathfire;return g.allies.length===before.n+count&&g.battle.command===before.c-cost;},{before,cost:fieldExpected.cost,count:fieldExpected.count}));await shot('battle-troops');await click('menu-back');await click('battle-category','defenses');check('Back restores battle categories and defense menu still works',await page.locator('.field-roster-tile').count()===8&&await page.locator('#regiment-roster').isHidden());
 await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.ui.open('equipment');});
 for(const [w,h]of [[844,390],[667,375],[390,844]]){
  await page.setViewportSize({width:w,height:h});if(w<h&&await page.locator('#portrait-continue').isVisible())await page.locator('#portrait-continue').click();
  for(const item of [weapon,armor]){
   await page.evaluate(item=>{const ui=window.__oathfire.ui;ui.open('equipment');ui.action('equipment-slot',item.type==='armor'?'armor':'weapon');ui.action('item',item.id);},item);
   for(const tab of ['overview','compare','forge']){await click('detail-section',tab);check(item.type+' name remains visible in '+tab+' at '+w,await page.locator('.equipment-name').innerText().then(t=>t.includes(item.name))&&await page.locator('.equipment-name').evaluate(e=>{const r=e.getBoundingClientRect(),c=document.querySelector('#menu-content').getBoundingClientRect();return r.top>=c.top-.5&&r.bottom<=c.bottom&&e.scrollWidth<=e.clientWidth+1;}));}
   await page.locator('#menu-content').evaluate(e=>e.scrollTop=e.scrollHeight);check(item.type+' name stays pinned when scrolling at '+w,await page.locator('.equipment-name').evaluate(e=>{const r=e.getBoundingClientRect(),c=document.querySelector('#menu-content').getBoundingClientRect();return r.top>=c.top-.5&&r.bottom<=c.bottom;}));await click('detail-section','overview');await shot('equipment-'+item.type+'-'+w);
  }
 }
 const saved=await page.evaluate(()=>{const g=window.__oathfire;g.checkpoint();return JSON.stringify({u:g.store.data.units,i:g.store.data.inventory,s:g.store.data.supplies});});await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);check('Reload preserves upgraded ranks, Supplies and all equipment',saved===await page.evaluate(()=>{const s=window.__oathfire.store.data;return JSON.stringify({u:s.units,i:s.inventory,s:s.supplies});}));
 check('No browser runtime errors',report.errors.length===0);
}catch(error){report.failure=error.message;console.error(error.stack);await page.screenshot({path:out+'/failure.jpg',quality:85}).catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}
