import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),browser=await chromium.launch({headless:true,args:['--use-angle=metal']}),page=await browser.newPage({viewport:{width:844,height:390},isMobile:true,hasTouch:true}),url=process.env.GAME_URL||'http://127.0.0.1:4179',out='output/world-26',report={url,checks:[],errors:[],views:[]};fs.mkdirSync(out,{recursive:true});
page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});const check=(name,pass)=>{assert.ok(pass,name);report.checks.push(name);console.log('PASS',name);};
try{await page.goto(url);await page.waitForFunction(()=>window.__oathfire?.ready,{timeout:120000});await page.locator('#new-game').tap();await page.locator('#begin-oath').tap();await page.locator('#story-skip').tap();await page.waitForFunction(()=>window.__oathfire.hero.phys.grounded);await page.evaluate(()=>{const g=window.__oathfire;g.store.data.guide.active=false;g.audio.music?.setPaused(true);});
report.alpha=await page.evaluate(async()=>{const img=await createImageBitmap(await(await fetch(new URL('./scenery/woodland-atlas.webp',location.href))).blob()),c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const d=ctx.getImageData(0,0,c.width,c.height).data;let opaque=0,red=0,clear=0;for(let i=0;i<d.length;i+=4){if(d[i+3]>128){opaque++;if(d[i]>180&&d[i+1]<80&&d[i+2]<70)red++;}if(d[i+3]===0)clear++;}return {width:c.width,height:c.height,opaque,red,clear};});check('Painted woodland has real alpha transparency without an opaque backdrop',report.alpha.clear>100000);console.log('ATLAS',report.alpha);
const motion=await page.evaluate(async()=>{const g=window.__oathfire,s=g.world.scenography,a=s.mills.map(o=>o.rotation.z);await new Promise(r=>setTimeout(r,400));return {moving:s.mills.every((o,i)=>Math.abs(o.rotation.z-a[i])>.01),parts:s.mills.map(o=>o.children.filter(c=>c.isMesh).length),birds:s.birds.count};});check('Three windmills animate as compact models and the flock is present',motion.moving&&motion.parts.every(n=>n<=4)&&motion.birds===12);
// Check world geometry is finite and every biome selects the proper painted world.
for(const [biome,expected]of [['plain','crownlands'],['forest','crownlands'],['river','crownlands'],['quarry','crownlands'],['snow','northern'],['desert','sunlands']]){const info=await page.evaluate(({biome,expected})=>{const g=window.__oathfire;g.loadWorld(biome,7919);g.spawnHero({x:0,y:0,z:-28});g.view.yaw=0;g.view.pitch=-.14;g.view.camera.position.copy(g.hero.pos);let finite=true;g.world.root.traverse(o=>{if(o.geometry){const p=o.geometry.attributes.position?.array;for(let i=0;i<(p?.length||0);i++)if(!Number.isFinite(p[i]))finite=false;}});return {biome,expected,panorama:g.view.scene.background.image.currentSrc||g.view.scene.background.image.src,finite,details:g.world.root.userData.scenography};},{biome,expected});check(biome+' scenery has finite geometry and its regional panorama',info.finite&&info.panorama.includes(expected)&&info.details.upperTown===16);await page.waitForTimeout(500);await page.screenshot({path:out+'/'+biome+'-mobile.png'});report.views.push(info);}
await page.evaluate(()=>{const g=window.__oathfire;g.returnHome();g.view.pitch=-.08;});await page.waitForTimeout(500);
report.physics=await page.evaluate(()=>{const g=window.__oathfire,h=g.hero;g.testTick=g.tick.bind(g);g.tick=()=>{};const run=(n,move,jump=false)=>{let max=-99;for(let i=0;i<n;i++){g.physics.move(h.phys,move,1/60,jump&&i===0);g.physics.step();g.physics.position(h.phys,h.pos);max=Math.max(max,h.pos.y);}return {p:h.pos.toArray(),max};};g.physics.teleport(h.phys,{x:8,y:0,z:-28.5});run(20,{x:0,z:0});const rock=run(60,{x:0,z:-5});g.physics.teleport(h.phys,{x:8,y:0,z:-29.4});run(20,{x:0,z:0});const jump=run(65,{x:0,z:-5},true);g.physics.teleport(h.phys,{x:-30,y:0,z:-9.5});run(20,{x:0,z:0});const stairs=run(460,{x:0,z:5});g.physics.teleport(h.phys,{x:0,y:0,z:-9});run(20,{x:0,z:0});const passage=run(190,{x:0,z:-5});g.physics.teleport(h.phys,{x:0,y:0,z:11.5});run(20,{x:0,z:0});const hall=run(130,{x:0,z:5});g.physics.teleport(h.phys,{x:48,y:0,z:10});run(20,{x:0,z:0});const town=run(140,{x:0,z:5});g.tick=g.testTick;return {rock,jump,stairs,passage,hall,town};});console.log('PHYSICS',report.physics);
check('Existing rock collision and jump still work',report.physics.rock.p[2]>-32&&report.physics.jump.max>1&&report.physics.jump.p[2]<-32.8);check('Castle stairs and gate passage remain accessible',report.physics.stairs.p[1]>5&&report.physics.passage.p[2]<-23);check('The ornate hall portal remains traversable',report.physics.hall.p[2]>21);check('New upper-town mass blocks the hero instead of being walk-through art',report.physics.town.p[2]<14.7);
for(const [width,height]of [[844,390],[667,375]]){await page.setViewportSize({width,height});await page.evaluate(()=>{const g=window.__oathfire;g.hero.pos.set(-3,0,1);g.physics.teleport(g.hero.phys,g.hero.pos);g.view.yaw=0;g.view.pitch=-.12;g.view.quality('auto');});await page.waitForTimeout(800);const perf=await page.evaluate(async()=>{const times=[];let previous=performance.now();for(let i=0;i<90;i++)await new Promise(r=>requestAnimationFrame(t=>{times.push(t-previous);previous=t;r();}));times.sort((a,b)=>a-b);const g=window.__oathfire;return {width:innerWidth,height:innerHeight,medianMs:times[45],p95Ms:times[85],render:{...g.view.renderer.info.render},ratio:g.view.renderer.getPixelRatio(),overflow:document.documentElement.scrollWidth>innerWidth};});report.views.push(perf);console.log('PERFORMANCE',perf);check(width+' mobile viewport renders without horizontal overflow',!perf.overflow&&perf.medianMs<40);await page.screenshot({path:out+'/courtyard-'+width+'.png'});}
await page.evaluate(()=>{const g=window.__oathfire;g.ui.open('pause');g.checkpoint();});const before=await page.evaluate(()=>{const s=structuredClone(window.__oathfire.store.data);delete s.updated;return JSON.stringify(s);});await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready,{timeout:120000});const after=await page.evaluate(()=>{const s=structuredClone(window.__oathfire.store.data);delete s.updated;return JSON.stringify(s);});check('Scenery reload preserves all progress and resources',before===after);await page.locator('#continue-game').tap();await page.waitForTimeout(500);check('No runtime or shader errors',report.errors.length===0);report.success=true;
}catch(e){report.failure=e.stack;process.exitCode=1;console.error(e.stack);await page.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{fs.writeFileSync(out+'/'+(url.includes('github.io')?'live-qa':'qa')+'.json',JSON.stringify(report,null,2));await browser.close();}
