import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.argv.includes('--playwright-module')?process.argv[process.argv.indexOf('--playwright-module')+1]:'playwright'));
const browser=await chromium.launch({headless:true,args:process.platform==='darwin'?['--use-angle=metal']:[]}),page=await browser.newPage({viewport:{width:844,height:390},hasTouch:true,isMobile:true});
const out=process.env.QA_OUT||'output/foley',errors=[],report={url:process.env.GAME_URL||'http://127.0.0.1:4179',checks:[],errors};fs.mkdirSync(out,{recursive:true});page.on('pageerror',e=>errors.push(e.message));const check=(name,ok=true)=>{assert.ok(ok,name);report.checks.push(name);console.log('PASS',name);};
await page.goto(process.env.GAME_URL||'http://127.0.0.1:4179');await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#new-game').click();await page.locator('#begin-oath').click();await page.locator('#story-skip').click();
try{if(process.argv.includes('--inspect')){const data=await page.evaluate(()=>{const g=window.__oathfire,c=g.hero.character;g.ui.open('settings');const data={};for(const name of ['Walking_A','Running_A']){c.mixer.stopAllAction();c.current=null;c.play(name,0);c.actionLock=999;c.current.timeScale=1;const duration=c.current.getClip().duration,frames=[];for(let i=0;i<160;i++){c.current.time=duration*i/160;c.update(0,{grounded:false});c.root.updateMatrixWorld(true);const l=c.sockets.footl.getWorldPosition(c.root.position.clone()),r=c.sockets.footr.getWorldPosition(c.root.position.clone());frames.push({phase:i/160,l:l.toArray(),r:r.toArray()});}data[name]={duration,frames};}return data;});fs.mkdirSync('work/foley',{recursive:true});fs.writeFileSync('work/foley/contacts.json',JSON.stringify(data));for(const [name,{duration,frames}]of Object.entries(data)){console.log(name,duration);for(const foot of ['l','r']){const min=Math.min(...frames.map(f=>f[foot][1]));console.log(foot,frames.filter(f=>f[foot][1]<min+.015).map(f=>+f.phase.toFixed(3)));}}}
else{
 await runChecks();
}}catch(e){report.failure=e.stack;console.error(e.stack);process.exitCode=1;await page.screenshot({path:out+'/failure.png'}).catch(()=>{});}
finally{if(!process.argv.includes('--inspect'))fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();}

async function runChecks(){
 const wait=ms=>page.waitForTimeout(ms),foley=()=>page.evaluate(()=>window.__oathfire.audio.foley.history);
 await page.waitForFunction(()=>window.__oathfire.audio.foley?.state==='ready');await page.evaluate(()=>{const g=window.__oathfire;g.store.data.settings.music=0;g.audio.settings(g.store.data.settings);g.store.data.guide.active=false;});
 check('Steel and Sorcery release loaded',await page.evaluate(()=>window.__oathfire.debug().build==='oathfire-2.0.0-kingdom-and-melody'));
 report.audio=await page.evaluate(()=>window.__oathfire.audio.foley.debug());check('All 87 effect cues decode into five local banks',report.audio.banks===5&&report.audio.cues===87);
 const place=async(x,z,biome='plain')=>{await page.evaluate(({x,z,biome})=>{const g=window.__oathfire;g.ui.close();g.input.clear();if(g.world.biome!==biome){g.loadWorld(biome,7919);g.spawnHero({x,y:g.world.height(x,z)+.1,z});}else g.physics.teleport(g.hero.phys,{x,y:g.world.height(x,z)+.1,z});g.hero.velocity.set(0,0,0);g.view.yaw=0;g.hero.character.footsteps.previous=null;},{x,z,biome});await wait(500);await page.evaluate(()=>window.__oathfire.audio.foley.history=[]);};
 const move=async(speed,ms=2500)=>{await page.evaluate(speed=>window.__oathfire.input.joy.y=speed,speed);await wait(ms);await page.evaluate(()=>window.__oathfire.input.clear());await wait(200);return (await foley()).filter(e=>e.event==='footfall');};
 await place(10,12);const run=await move(1,3000);report.run=run;check('Running emits alternating contacts at the animation cadence',run.length>=6&&run.length<=11&&run.every((e,i)=>!i||e.foot!==run[i-1].foot)&&run.every((e,i)=>!i||e.at-run[i-1].at>.24));check('Courtyard foot contacts select stone and plate armor',run.every(e=>e.surface==='stone'&&e.armor==='plate'));
 const notes=(await foley()).filter(e=>e.key==='step-stone');check('Steps rotate recorded variations instead of repeating one sample',new Set(notes.map(e=>e.index)).size===5);
 await page.evaluate(()=>window.__oathfire.audio.foley.history=[]);await wait(800);check('Standing still is silent',!(await foley()).some(e=>e.event==='footfall'));
 await place(10,12);const walk=await move(.4,3500);report.walk=walk;check('Walking uses a slower alternating cadence than running',walk.length>=3&&walk.length<=7&&walk.every(e=>e.clip==='Walking_A')&&walk.length/3.5<run.length/3);
 await place(23,-38);check('Field footsteps select grass',(await move(.5,1700)).some(e=>e.surface==='grass'));
 await place(-3.7,-38);check('The visible road selects dirt',(await move(.5,1700)).some(e=>e.surface==='dirt'));
 const water=await page.evaluate(()=>{const g=window.__oathfire;g.loadWorld('river',7919);g.spawnHero({x:0,y:1,z:-70});for(let z=-82;z>-120;z-=2){const x=12+Math.sin(z*.045)*15,y=g.world.height(x,z);if(y<-1.6&&Math.abs(z+126)>4&&Math.abs(z+63)>4)return {x,z,y};}return null;});check('A walkable submerged riverbed exists',!!water);await place(water.x,water.z,'river');check('Walking through the river uses water splashes',(await move(.35,2200)).some(e=>e.surface==='water'));
 await place(10,12);await page.evaluate(()=>{const g=window.__oathfire;g.physics.addBox(10,1.5,9,5,3,1,'rock');});await move(1,1400);await page.evaluate(()=>{window.__oathfire.audio.foley.history=[];window.__oathfire.input.joy.y=1;});await wait(700);check('Pushing into solid rock produces no running footsteps',!(await foley()).some(e=>e.event==='footfall')&&await page.evaluate(()=>window.__oathfire.hero.speed<.3));await page.evaluate(()=>window.__oathfire.input.clear());
 await place(20,5);await page.keyboard.press('Space');await wait(200);await page.evaluate(()=>window.__oathfire.audio.foley.history=[]);await wait(350);check('Airborne feet do not make surface sounds',!(await foley()).some(e=>e.event==='footfall'));await wait(800);const land=(await foley()).filter(e=>e.event==='footfall');check('Jumping ends with one grounded landing sound',land.length===1&&land[0].kind==='land');
 await place(20,5);await page.evaluate(()=>{const g=window.__oathfire;g.store.data.settings.firstPerson=true;g.audio.foley.history=[];});check('First person keeps animation-driven steps',(await move(.5,1800)).length>=2);
 await page.evaluate(()=>{const g=window.__oathfire;g.store.data.settings.firstPerson=false;g.ui.open('settings');});await wait(100);check('Settings exposes a separate footsteps and armor volume',await page.locator('[data-setting="footsteps"]').count()===1);
 for(const size of [{width:667,height:375},{width:844,height:390}]){await page.setViewportSize(size);check('Audio settings fit '+size.width+'px',await page.evaluate(()=>{const el=document.getElementById('menu-content');return el.scrollWidth<=el.clientWidth&&document.querySelector('[data-setting="footsteps"]').getBoundingClientRect().height>=20;}));await page.screenshot({path:out+'/settings-'+size.width+'.png'});}
 await page.evaluate(()=>{const g=window.__oathfire;g.audio.foley.history=[];});await wait(600);check('Menus do not create phantom foot contacts',!(await foley()).some(e=>e.event==='footfall'));
 // Confirm contact routing using real damage calls, then exercise both timed swing paths.
 await place(20,5);const impacts=await page.evaluate(()=>{const g=window.__oathfire,h=g.hero,out=[];g.audio.foley.history=[];const foe=g.spawnEnemy('knight',{x:20,z:3},{training:true,hp:9999});for(const weapon of ['sword','spear','hammer','bow','crossbow']){g.audio.foley.limits.clear();g.combat.hit(foe,10,h,{weapon,heavy:weapon==='hammer'});out.push(g.audio.foley.history.at(-1));}foe.stats.armor=0;foe.type='hollow';g.audio.foley.limits.clear();g.combat.hit(foe,10,h,{weapon:'sword'});out.push(g.audio.foley.history.at(-1));h.facing=Math.PI;h.guarding=true;h.guardTime=.1;h.invuln=0;g.audio.foley.limits.clear();g.combat.hit(h,5,foe,{weapon:'sword'});out.push(g.audio.foley.history.at(-1));h.guarding=false;return out;});report.impacts=impacts;
 check('Sword, spear, hammer, arrow and bolt hits choose distinct armor recordings',impacts.slice(0,5).every((e,i)=>e.key==='hit-'+['sword','spear','hammer','bow','crossbow'][i]+'-armor'));check('Unarmored targets get body impacts and blocks get a parry',impacts[5].key==='hit-sword-body'&&impacts[6].key==='parry');
 for(const heavy of [false,true]){const observed=await page.evaluate(async heavy=>{const g=window.__oathfire,h=g.hero;h.cooldown=0;h.stamina=300;g.audio.foley.history=[];g.audio.foley.limits.clear();g.combat.attack(h,heavy);const immediate=g.audio.foley.history.filter(e=>e.key?.startsWith('swing')).length;await new Promise(r=>setTimeout(r,heavy?650:350));return {immediate,events:g.audio.foley.history.filter(e=>e.key?.startsWith('swing'))};},heavy);check((heavy?'Charged':'Quick')+' attack sound follows the swing windup',observed.immediate===0&&observed.events.some(e=>e.key===('swing-sword'+(heavy?'-heavy':''))));}
 const ranged=await page.evaluate(()=>{const g=window.__oathfire,h=g.hero;g.audio.foley.history=[];g.combat.clear();const foe=g.enemies.find(e=>e.training);foe.hp=9999;foe.type='knight';foe.stats.armor=30;foe.invuln=0;foe.pos.set(h.pos.x,0,h.pos.z-5);g.physics.teleport(foe.phys,foe.pos);g.physics.step();g.audio.foley.limits.clear();g.combat.shoot(h,foe,{type:'arrow',damage:10,speed:28});for(let i=0;i<60;i++)g.combat.update(1/60);return {hp:foe.hp,events:g.audio.foley.history};});check('A moving arrow produces an impact on actual collision',ranged.hp<9999&&ranged.events.some(e=>e.key==='hit-bow-armor'));
 const ids=Object.keys(JSON.parse(fs.readFileSync('public/sfx/foley.json')).clips).filter(k=>k.startsWith('cast-')).map(k=>k.slice(5));
 const casted=await page.evaluate(async ids=>{const g=window.__oathfire,h=g.hero,data=g.store.data.heroes[g.store.data.hero],out=[];g.audio.foley.history=[];const before=structuredClone(data);for(const id of ids){g.audio.foley.limits.clear();g.combat.clear();h.cooldowns={};h.focus=1000;h.stamina=1000;data.capstone=id;data.skills[id]=3;const n=g.audio.foley.history.length;if(['frost','storm','grave','holy'].includes(id))g.audio.play(id,1,{position:h.pos,rank:3});else g.combat.cast(id);out.push({id,keys:g.audio.foley.history.slice(n).filter(e=>e.key).map(e=>e.key)});g.audio.foley.stop();await new Promise(r=>setTimeout(r,80));}Object.assign(data,before);g.refreshHero();return out;},ids);report.spells=casted;check('All 23 hero techniques and four elemental NPC casts have their own sound',casted.length===27&&casted.every(e=>e.keys.includes('cast-'+e.id)));check('Upgraded spells add their own elemental resonance layer',casted.every(e=>e.keys.some(k=>k.startsWith('rank-'))));
 await page.evaluate(()=>{const g=window.__oathfire;g.ui.close();g.audio.foley.stop();g.audio.settings({volume:.8,music:0,footsteps:0});});await wait(500);
 const silent=await page.evaluate(async()=>{const g=window.__oathfire,a=g.audio,an=a.ctx.createAnalyser();an.fftSize=2048;a.master.connect(an);a.footstep({surface:'stone',armor:'plate',foot:'left',strength:1});await new Promise(r=>setTimeout(r,90));const b=new Float32Array(2048);an.getFloatTimeDomainData(b);a.master.disconnect(an);return Math.max(...b.map(Math.abs));});check('Footstep mute silences both boots and armor',silent<.0002);
 const audio=await page.evaluate(async()=>{const a=window.__oathfire.audio,an=a.ctx.createAnalyser();an.fftSize=2048;a.master.connect(an);a.foley.limits.clear();a.play('fireball',1,{rank:3});await new Promise(r=>setTimeout(r,150));const b=new Float32Array(2048);an.getFloatTimeDomainData(b);a.master.disconnect(an);return Math.max(...b.map(Math.abs));});check('Muting footsteps leaves grand spell effects audible',audio>.02);
 report.finalAudio=await page.evaluate(()=>window.__oathfire.audio.foley.debug());check('Effects stay within the mobile voice budget',report.finalAudio.maxVoices<=40);
 await page.evaluate(()=>{const g=window.__oathfire;g.ui.open('settings');const el=document.querySelector('[data-setting="footsteps"]');el.value='.3';el.dispatchEvent(new Event('change',{bubbles:true}));});
 if(!report.url.includes(':4179')){await page.evaluate(()=>navigator.serviceWorker.ready);const cached=await page.evaluate(async()=>{const keys=await caches.keys();return(await Promise.all(keys.map(async k=>(await(await caches.open(k)).keys()).map(r=>r.url)))).flat().filter(u=>u.includes('/sfx/'));});check('All five sound banks and their manifest are available offline',cached.length===6);await page.context().setOffline(true);}
 await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').click();await page.waitForFunction(()=>window.__oathfire.audio.foley?.state==='ready');
 check('Footstep volume survives reload without changing the campaign',await page.evaluate(()=>window.__oathfire.store.data.settings.footsteps===.3&&window.__oathfire.store.data.hero==='warden'));
 if(!report.url.includes(':4179'))check('Recorded footsteps and combat sounds decode with the network disconnected',await page.evaluate(()=>window.__oathfire.audio.foley.debug().banks===5));
 check('No browser runtime errors',errors.length===0);
}
