import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),browser=await chromium.launch({headless:true,args:['--use-angle=metal']}),page=await browser.newPage({viewport:{width:844,height:390},isMobile:true,hasTouch:true}),url=process.env.GAME_URL||'http://127.0.0.1:4180',report={url,checks:[],errors:[]};
page.on('pageerror',e=>report.errors.push(e.message));const check=(name,pass)=>{assert.ok(pass,name);report.checks.push(name);console.log('PASS',name);};
try{await page.goto(url);await page.waitForFunction(()=>window.__oathfire?.ready);check('Published game identifies the Living Horizons release',await page.evaluate(()=>window.__oathfire.debug().build==='oathfire-2.6.0-living-horizons'));await page.locator('#new-game').tap();await page.locator('#begin-oath').tap();await page.locator('#story-skip').tap();
await page.evaluate(()=>{const g=window.__oathfire;g.store.commit(s=>{s.guide.active=false;s.completed=[0];});g.ui.open('campaign');g.ui.selectedMission=24;g.ui.draw();});await page.locator('[data-action="embark"][data-id="24"]').tap();await page.locator('#begin-defense').tap();await page.waitForTimeout(700);check('Production launches a real enemy fortress with four damageable parts',await page.evaluate(()=>{const g=window.__oathfire;return g.battle.siege&&g.siegeTargets.length===4&&g.world.root.userData.enemyFortress.name==='Willowmill';}));
await page.locator('#army-button').tap();await page.locator('[data-action="battle-category"][data-id="troops"]').tap();await page.locator('[data-action="field-inspect"][data-id="bow"]').tap();check('Siege troop menus omit home-only defenses',await page.locator('[data-action="battle-category"][data-id="defenses"]').count()===0);await page.locator('[data-action="recruit"][data-id="bow"]').tap();check('One archer recruit is one soldier and spawns at the assault rally point',await page.evaluate(()=>{const a=window.__oathfire.allies.filter(a=>a.unit==='bow');return a.length===1&&a[0].pos.z<-100;}));await page.locator('#close-menu').tap();
report.hit=await page.evaluate(()=>{const g=window.__oathfire;g.testTick=g.tick.bind(g);g.tick=()=>{};g.hero.pos.set(0,3,-140);g.physics.teleport(g.hero.phys,g.hero.pos);g.physics.step();g.view.yaw=0;g.hero.cooldown=0;g.hero.stamina=100;const gate=g.siegeTargets.find(t=>t.part==='gate'),hp=gate.hp;g.combat.attack(g.hero,true);for(let i=0;i<60;i++)g.combat.update(1/60);const damage=hp-gate.hp;g.combat.hit(gate,10000,g.hero,{heavy:true});g.checkpoint();return {damage,gate:g.store.data.battle.siege.hp.gate};});check('Real charged attacks damage the gate and the breach is saved',report.hit.damage>0&&report.hit.gate===0);
await page.reload();await page.waitForFunction(()=>window.__oathfire?.ready);await page.locator('#continue-game').tap();await page.waitForTimeout(500);check('Reload keeps the gate destroyed and the hero in the ongoing siege',await page.evaluate(()=>{const g=window.__oathfire,t=g.siegeTargets.find(t=>t.part==='gate');return g.battle?.id===24&&t.dead&&!t.phys&&!t.model.visible;}));
await page.evaluate(()=>{const g=window.__oathfire;g.tick=()=>{};g.battle.time=350;g.battleTick(.01);g.checkpoint();g.store.commit(s=>s.journal.push('QA checkpoint'));});check('Pressure-six checkpoint validates in the production bundle',await page.evaluate(()=>window.__oathfire.store.data.battle.siege.pressure===6));
await page.evaluate(()=>{const g=window.__oathfire,t=g.siegeTargets.find(t=>t.part==='keep');g.combat.hit(t,100000,g.hero,{heavy:true});g.battleTick(.01);});check('Destroying the keep settles the siege and rescues its settlement',await page.evaluate(()=>{const g=window.__oathfire;return g.mode==='result'&&g.store.data.settlements.includes(24)&&g.store.data.lastBattle.siege.destroyed===2&&g.store.data.lastBattle.stats.heroDamage>0;}));await page.waitForTimeout(4000);await page.screenshot({path:'output/siege/'+(url.includes('github.io')?'live':'production')+'-summary.png'});
check('Production flow has no runtime errors',report.errors.length===0);report.success=true;
}catch(e){report.failure=e.stack;process.exitCode=1;console.error(e.stack);}finally{fs.writeFileSync('output/siege/'+(url.includes('github.io')?'live':'production')+'-smoke.json',JSON.stringify(report,null,2));await browser.close();}
