import {HEROES,SPELLS} from './data.js';
import {heroData,skillRank,skillPoints,skillGate} from './state.js';
import {EVOLUTIONS,abilityStats,rankCost,evolutionFor} from './ability-progression.js';
import {techniqueResource} from './technique-cast.js';
import {sigil} from './menu-flow.js';
import {Effects} from './effects.js';
import * as T from 'three';
export function renderAbilities(ui){
 const s=ui.g.store.data,h=heroData(s),list=HEROES[s.hero].skills.filter(n=>n.active).sort((a,b)=>a.learnLevel-b.learnLevel),chosen=list.find(n=>n.id===ui.ability)||list.find(n=>!skillRank(s,n.id)&&h.level>=n.learnLevel)||list[0];ui.ability=chosen.id;
 const rank=skillRank(s,chosen.id),gate=skillGate(s,chosen.id),spell=SPELLS[chosen.id],evolved=evolutionFor(chosen.id,h.evolutions?.[chosen.id]),points=skillPoints(s);
 if(!ui.abilityFocus)return '<div class="section-head"><h2>Active abilities</h2><span class="tag">'+points+' points</span></div><div class="technique-picker">'+list.map(n=>'<button data-action="ability-select" data-id="'+n.id+'" class="'+(n.id===chosen.id?'selected ':'')+(h.level<n.learnLevel?'locked':'')+'">'+sigil(SPELLS[n.id].icon)+'<span><b>'+n.name+'</b><small>'+(skillRank(s,n.id)?'Rank '+skillRank(s,n.id)+' / 10'+(h.evolutions?.[n.id]?' · Evolved':''):h.level>=n.learnLevel?'Ready to learn':'Hero level '+n.learnLevel)+'</small></span></button>').join('')+'</div>';
 const mode=ui.abilityPanel||'train',override=techniqueResource(chosen.id,rank,evolved?.id),cost=(override?.cost||spell.cost)*(skillRank(s,'borrowed')?.75:1),cooldown=override?.cooldown||(chosen.id==='windstep'&&rank>=2?6:spell.cooldown);
 const header='<article class="technique-detail focused-ability" data-panel="'+mode+'" data-technique="'+chosen.id+'"><header>'+ui.button(mode==='evolve'?'ability-panel':'ability-list',mode==='evolve'?'train':null,'‹')+'<span><h3>'+chosen.name+'</h3><small>RANK '+rank+' / 10 · '+cost+' '+(spell.type||'focus')+' · '+cooldown+'s</small></span></header><div class="mastery-track" aria-label="Rank '+rank+' of 10">'+Array.from({length:10},(_,i)=>'<i class="'+(i<rank?'earned':'')+'">'+(i+1)+'</i>').join('')+'</div><div class="ability-tabs">'+ui.button('ability-panel','train','Training',false,mode==='train')+ui.button('ability-panel','evolve',rank===10?'Evolutions':'Rank 10 evolutions',false,mode==='evolve')+ui.button('ability-panel','equip','Equip',!rank,mode==='equip')+'</div>';

 if(mode==='equip')return header+'<p>'+spell.desc+'</p><div class="technique-equip">'+[0,1].map(i=>ui.button('ability-equip',chosen.id,h.slots[i]===chosen.id?'✓ Button '+(i+1):'Equip to button '+(i+1),h.slots[i]===chosen.id||!!ui.g.battle,false,i)).join('')+'</div><small>'+(chosen.capstone?'One signature ability can be equipped at a time.':'Two active abilities can be equipped at a time.')+'</small></article>';
 if(mode==='evolve'){
  const paths=EVOLUTIONS[chosen.id],selected=paths.find(p=>p.id===ui.evolutionPreview)||paths.find(p=>p.id===evolved?.id)||paths[0];ui.evolutionPreview=selected.id;
  return header+'<div class="evolution-choices">'+paths.map(p=>ui.button('evolution-preview',p.id,p.name,false,p.id===selected.id)).join('')+'</div><div class="evolution-detail"><small>'+(rank===10?'EVOLUTION · NO EXTRA POINT COST':'PREVIEW · UNLOCK AT RANK 10 / HERO LEVEL '+chosen.rankLevels[9])+'</small><p>'+selected.description+'</p></div><div class="evolution-actions">'+ui.button('ability-preview',null,'Preview animation')+ui.button('evolution',chosen.id,evolved?.id===selected.id?'✓ Equipped evolution':rank<10?'Requires rank 10':'Choose '+selected.name,rank<10||evolved?.id===selected.id||!!ui.g.battle,true,selected.id)+'</div><small>One evolution per ability. Switch freely at Hearthwatch.</small></article>';
 }
 const current=abilityStats(chosen.id,Math.max(1,rank)),next=rank<10?abilityStats(chosen.id,Math.max(1,rank+1)):null;
 return header+'<p class="ability-role '+(rank?'trained':'')+'">'+spell.desc+'</p><table class="ability-stats"><thead><tr><th>Effect</th><th>'+(rank?'Now':'Rank 1')+'</th>'+(next&&rank?'<th>Rank '+(rank+1)+'</th>':'')+'</tr></thead><tbody>'+current.map(([label,value],i)=>'<tr><th>'+label+'</th><td>'+value+'</td>'+(next&&rank?'<td class="'+(String(value)!==String(next[i]?.[1])?'improved':'')+'">'+next[i]?.[1]+'</td>':'')+'</tr>').join('')+'</tbody></table><div class="ability-purchase"><small>'+(rank<10?'Hero level '+chosen.rankLevels[rank]+' · '+rankCost(chosen,rank+1)+' skill point'+(rankCost(chosen,rank+1)>1?'s':''):'Rank 10 · Evolution available')+'</small>'+ui.button(rank===10?'ability-panel':'skill',rank===10?'evolve':chosen.id,rank===10?'Choose evolution':gate||(rank?'Improve to rank '+(rank+1):'Learn ability'),rank<10&&(!!gate||!!ui.g.battle),true)+'</div></article>';
}
export function previewAbility(ui){
 if(!ui.preview)return;const s=ui.g.store.data,id=ui.ability,path=ui.abilityPanel==='evolve'?ui.evolutionPreview:heroData(s).evolutions?.[id],rank=ui.abilityPanel==='evolve'?10:Math.max(1,skillRank(s,id));
 if(!ui.abilityFX){ui.abilityFXRoot=new T.Group();ui.g.view.previewScene.add(ui.abilityFXRoot);ui.abilityFX=new Effects(ui.abilityFXRoot);}ui.abilityFXRoot.scale.set(path==='corona'?.23:1,1,path==='corona'?.23:1);ui.abilityFX.clear();ui.preview.cast(id,rank,path);ui.abilityFX.technique(id,new T.Vector3(),new T.Vector3(0,0,1.8),rank,path);ui.g.audio.play(id,.6,{rank:Math.min(3,rank)});
}
