import {commandBenefits} from './battle-plan.js';
import {equipmentName} from './equipment-name.js';
import {sectionTabs} from './menu-flow.js';
import {WEAPONS,RARITIES,AFFIXES} from './data.js';
import {heroData,heroStats,equipped,itemValue,forgeCost} from './state.js';
import {armorDefinition,armorBenefits} from './armor.js';
import {weaponPattern,weaponPower} from './weapon-patterns.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slots={weapon:'Weapon',armor:'Armor',shield:'Shield',relic:'Relic'},slotOf=i=>WEAPONS[i.type]?'weapon':i.type,n=n=>Number(n.toFixed(2));
const formatPercent=v=>Number((v*100).toFixed(1))+'%';
function wearing(s,item){const h=heroData(s);return {...s,inventory:s.inventory.map(i=>i.id===item.id?item:i),heroes:{...s.heroes,[s.hero]:{...h,equipped:{...h.equipped,[slotOf(item)]:item.id}}}};}
const statRows=[['startingCommand','Starting Command',n],['commandRegen','Passive Command',v=>n(v)+'/s'],['commandKill','Command / hero kill',n],['eliteCommand','Extra / elite kill',n],['commandCapacity','Command capacity',n],['damage','Weapon damage',n],['armor','Armor',n],['hp','Health',n],['focus','Focus',n],['stamina','Stamina',n],['speed','Move speed',v=>n(v)+' m/s'],['attackSpeed','Attack speed',formatPercent],['guardCost','Block cost',formatPercent,-1],['staminaRegen','Stamina recovery',v=>n(v)+'/s'],['focusRegen','Focus recovery',v=>n(v)+'/s'],['fireResistance','Fire resistance',formatPercent],['heavyBonus','Charged bonus',formatPercent],['healFactor','Healing received',formatPercent],['supportRadius','Command radius',v=>n(v)+' m'],['allyBonus','Troop damage bonus',formatPercent]];
function comparison(a,b,always='armor'){return '<div class="armor-comparison">'+statRows.filter(([key])=>key===always||Math.abs(a[key]-b[key])>.00001).map(([key,label,fmt,direction=1])=>'<div class="compare-row"><span>'+label+'</span><b class="'+(a[key]===b[key]?'':(b[key]-a[key])*direction>0?'stat-gain':'stat-loss')+'">'+fmt(a[key])+' → '+fmt(b[key])+(a[key]===b[key]?'':' <small>('+(b[key]>a[key]?'+':'')+fmt(b[key]-a[key])+')</small>')+'</b></div>').join('')+'</div>';}
export function weaponThumb(item){const d=WEAPONS[item.type]?weaponPattern(item):null,shape=d?.shape||0,paths={sword:'M29 10 20 47 24 49 38 13 38 3ZM15 43 32 52M21 49 15 63',spear:'M35 4 26 15 30 24 41 10ZM30 22 13 64',hammer:'M16 13 43 20 40 33 13 25ZM26 29 17 63',bow:'M15 7Q59 34 15 64L35 35ZM8 35h39',staff:'M31 22 16 64M31 3 22 13 28 25 40 17 42 8Z',armor:'M11 19 18 10 26 16 33 10 43 19 36 31 38 56 16 56 18 31Z',shield:'M12 14 28 8 44 14 40 47 28 61 16 47Z',relic:'M28 8 45 34 28 60 11 34Z'};return '<svg class="weapon-thumb pattern-'+shape+'" viewBox="0 0 56 72" aria-hidden="true" style="--metal:#'+(d?.color||0xa3b9b6).toString(16).padStart(6,'0')+'"><path d="'+(paths[item.type]||paths.relic)+'"/>'+(shape===1?'<path class="ornament" d="m20 24 7 6-9 7m15-16 7 9-9 7"/>':shape===2?'<path class="ornament" d="m17 31-7-10 14 6m10-2 13-5-7 12"/>':'')+'<circle cx="28" cy="34" r="'+(shape?3:1.5)+'" fill="'+(d?.glow?'#'+d.glow.toString(16):'#e5c37c')+'"/></svg>';}
function powerCard(item){const p=weaponPower(item);return p?'<div class="signature-power '+(p.active?'active':'dormant')+'"><small>SIGNATURE · '+(p.active?'ACTIVE':'DORMANT')+'</small><h4>'+p.title+'</h4><p>'+p.description+'</p><small>'+p.cooldown+'s cooldown · '+(!p.active?p.requirement:'Scales with quality and forging.')+'</small></div>':'';}
export function renderArmory(ui){const s=ui.g.store.data,filter=ui.inventoryFilter||'weapon',all=s.inventory.filter(i=>filter==='all'||slotOf(i)===filter),items=all.filter(i=>ui.screen!=='inventory'||filter!=='weapon'||!ui.weaponFilter||ui.weaponFilter==='all'||i.type===ui.weaponFilter).sort((a,b)=>b.rarity-a.rarity||b.plus-a.plus||b.level-a.level),i=all.find(x=>x.id===ui.item)||all[0];if(i&&ui.screen!=='list')ui.item=i.id;
 if(ui.screen==='list')return '<p class="list-hint">Your shared armory · Choose a slot.</p><div class="equipment-slots">'+Object.entries(slots).map(([key,label])=>{const x=equipped(s,key);return '<button data-action="equipment-slot" data-id="'+key+'" class="equipment-slot" style="--item:'+RARITIES[x.rarity].color+'">'+weaponThumb(x)+'<span><small>'+label.toUpperCase()+' · '+RARITIES[x.rarity].name+'</small><b>'+esc(equipmentName(x))+' +'+x.plus+'</b><em>'+ (key==='armor'?armorDefinition(x).role:key==='weapon'?itemValue(x)+' damage':itemValue(x)+' power')+'</em></span></button>';}).join('')+'</div>';
 if(ui.screen==='inventory')return '<div class="section-head"><h2>'+slots[filter]+'</h2><span class="tag">'+all.length+' owned</span></div>'+(filter==='weapon'?'<div class="weapon-filters" aria-label="Weapon type">'+[['all','All'],...Object.entries(WEAPONS).map(([id,d])=>[id,d.name])].map(([id,label])=>'<button data-action="weapon-filter" data-id="'+id+'" class="'+((ui.weaponFilter||'all')===id?'active':'')+'">'+label+'</button>').join('')+'</div>':'')+'<div class="inventory equipment-inventory">'+items.map(x=>'<button data-action="item" data-id="'+esc(x.id)+'" class="item" style="--item:'+RARITIES[x.rarity].color+'">'+weaponThumb(x)+'<span class="item-copy"><b class="inventory-name">'+esc(equipmentName(x))+' +'+x.plus+'</b><small class="inventory-quality">'+RARITIES[x.rarity].name+' · Lv '+x.level+'</small><em>'+itemValue(x)+(filter==='weapon'?' damage':filter==='armor'?' armor':' power')+(equipped(s,slotOf(x)).id===x.id?' · EQUIPPED':'')+'</em></span></button>').join('')+(items.length?'':'<p>No equipment of this type yet.</p>')+'</div>';
 if(!i)return '<p>No equipment in this slot yet.</p>';
 const current=equipped(s,slotOf(i)),used=current?.id===i.id,armor=i.type==='armor',weapon=WEAPONS[i.type],cost=forgeCost(i),rarity=RARITIES[i.rarity],selected=heroStats(wearing(s,i)),section=ui.detailTab;
 const heading='<div class="item-status">'+(used?'EQUIPPED':'PREVIEW · NOT EQUIPPED')+'</div><h2 class="equipment-name" style="color:'+rarity.color+'">'+esc(equipmentName(i))+' <span>+'+i.plus+'</span></h2><p class="item-quality">'+rarity.name+' · Item level '+i.level+'</p>';
 let body='';
 if(section==='forge'){
  const next={...i,plus:Math.min(10,i.plus+1),awakened:i.awakened||i.plus===9&&s.completed.length>=10},p=weaponPower(i),q=weaponPower(next);
  body='<h4 class="forge-step">Forge +'+i.plus+' → +'+next.plus+'</h4>'+comparison(selected,heroStats(wearing(s,next)),weapon?'damage':'armor')+(weapon?'<div class="compare-row"><span>Charged damage</span><b class="stat-gain">'+Math.round(selected.damage*weapon.heavy*(1+selected.heavyBonus))+' → '+Math.round(heroStats(wearing(s,next)).damage*weapon.heavy*(1+selected.heavyBonus))+'</b></div>':'')+(p&&q&&!['root','ward'].includes(p.id)&&(p.damage!==q.damage||p.heal!==q.heal)?'<p class="forge-notes">Signature power: '+(['dawn','tide'].includes(p.id)?p.heal+' → '+q.heal+' healing':p.damage+' → '+q.damage+' effect damage')+'</p>':'')+(p&&!p.active&&q?.active?'<p class="stat-gain">Unlocks '+q.title+'</p>':'')+'<div class="forge-cost"><span>'+cost.supplies+' Supplies</span><span>'+cost.salvage+' Salvage</span></div><div class="item-actions">'+ui.button('forge',i.id,i.plus>=10?'Fully forged':'Improve to +'+(i.plus+1),i.plus>=10||!!ui.g.battle||s.supplies<cost.supplies||s.salvage<cost.salvage,true)+'</div><p class="forge-notes">+3 Rune · +6 Temper · +10 Awakening after 10 main victories</p>';
  if(i.plus>=3)body+='<details class="forge-choice"><summary>Rune · '+(i.rune||'Empty socket')+' · 8 Salvage</summary><div class="subtabs">'+['ember','frost','vital'].map(r=>ui.button('rune',i.id,r===i.rune?'✓ '+r:r,!!ui.g.battle||r===i.rune||s.salvage<8,false,r)).join('')+'</div><p>'+(armor?'Ember: 15% fire resistance · Frost: 12 stamina · Vital: 24 health.':'Ember: 3s burn · Frost: 2s slow · Vital: heal 1 on hit.')+'</p></details>';
  if(i.plus>=6)body+='<details class="forge-choice"><summary>Temper · '+(i.temper||'Unchosen')+' · 15 Salvage</summary><div class="subtabs">'+['swift','sunder','guard'].map(r=>ui.button('temper',i.id,r===i.temper?'✓ '+r:r,!!ui.g.battle||r===i.temper||s.salvage<15,false,r)).join('')+'</div><p>'+(armor?'Swift: 5% speed · Sunder: 10% charged damage · Guard: 15% lower block cost.':'Swift: 10% attack speed · Sunder: 20% armor strip on heavy hits · Guard: 20% lower block cost.')+'</p></details>';
  body+='<details class="forge-choice salvage-choice"><summary>Salvage this item</summary><p>Receive '+(4+i.rarity*5+i.plus*3)+' Salvage and '+(10+i.rarity*15)+' Supplies. Consumes the item.</p>'+ui.button('salvage',i.id,'Salvage equipment',Object.values(s.heroes).some(h=>Object.values(h.equipped).includes(i.id))||!!ui.g.battle)+'</details>';
 }else if(section==='compare')body='<p class="compare-heading">YOUR HERO · WORN → SELECTED</p>'+comparison(heroStats(s),selected,weapon?'damage':'armor')+(weapon?powerCard(i):'')+(current?.affix&&current.affix!==i.affix?'<p>Replaces: '+AFFIXES[current.affix].desc+'</p>':'')+'<div class="item-actions">'+ui.button('equip',i.id,used?'Equipped':'Equip selected',used||!!ui.g.battle,true)+'</div>';
 else body='<div class="weapon-key-stats"><div><b>'+itemValue(i)+'</b><small>'+ (weapon?'DAMAGE':armor?'ARMOR':'POWER')+'</small></div>'+(weapon?'<div><b>'+Math.round(selected.damage*weapon.heavy*(1+selected.heavyBonus))+'</b><small>CHARGED HIT</small></div><div><b>'+n(weapon.speed/selected.attackSpeed)+'s</b><small>QUICK RECOVERY</small></div><div><b>'+weapon.reach+'m</b><small>REACH</small></div>':'')+'</div>'+powerCard(i)+(commandBenefits(i).length?'<div class="gear-command-benefits"><h4>Command bonuses</h4>'+commandBenefits(i).map(line=>'<p>'+line+'</p>').join('')+'</div>':'')+(armor?'<div class="armor-benefits"><h4>'+armorDefinition(i).role+'</h4><ul>'+armorBenefits(i).map(b=>'<li>'+esc(b)+'</li>').join('')+'</ul></div>':'')+(i.affix?'<p class="rolled-affix"><b>'+AFFIXES[i.affix].name+'</b> · '+AFFIXES[i.affix].desc+'</p>':'')+'<div class="item-actions">'+ui.button('equip',i.id,used?'Equipped':'Equip '+slots[slotOf(i)].toLowerCase(),used||!!ui.g.battle,true)+ui.button('detail-section','forge','Improve ›')+'</div>';
 return '<div class="armory-item-header">'+heading+'</div>'+sectionTabs(ui,{overview:'Overview',compare:'Compare',forge:'Improve'})+'<article class="item-info">'+body+'</article>';
}
