import {WEAPONS,RARITIES,AFFIXES} from './data.js';
import {heroData,heroStats,equipped,itemValue,forgeCost} from './state.js';
import {armorDefinition,armorBenefits} from './armor.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slots={weapon:'Weapon',armor:'Armor',shield:'Shield',relic:'Relic'};
const slotOf=i=>WEAPONS[i.type]?'weapon':i.type;
const number=n=>Number(n.toFixed(2));
const percent=n=>Number((n*100).toFixed(1))+'%';
function compareArmor(s,item){
 const h=heroData(s),a=heroStats(s),b=heroStats({...s,heroes:{...s.heroes,[s.hero]:{...h,equipped:{...h.equipped,armor:item.id}}}});
 const rows=[['armor','Armor',number],['hp','Health',number],['focus','Focus',number],['stamina','Stamina',number],['speed','Move speed',n=>number(n)+' m/s'],['attackSpeed','Attack speed',percent],['guardCost','Block cost',percent,-1],['staminaRegen','Resting stamina recovery',n=>number(n)+'/s'],['focusRegen','Focus recovery',n=>number(n)+'/s'],['fireResistance','Fire resistance',percent],['heavyBonus','Charged attack bonus',percent],['healFactor','Draught / Quench healing',percent],['supportRadius','Command radius',n=>number(n)+' m'],['allyBonus','Nearby troop bonus',percent]];
 return '<div class="armor-comparison"><div class="compare-heading"><span>HERO TOTALS</span><span>WORN → SELECTED</span></div>'+rows.filter(([key])=>key==='armor'||Math.abs(a[key]-b[key])>.00001).map(([key,label,fmt,direction=1])=>'<div class="compare-row"><span>'+label+'</span><b class="'+(b[key]===a[key]?'':(b[key]-a[key])*direction>0?'stat-gain':'stat-loss')+'">'+fmt(a[key])+' → '+fmt(b[key])+'</b></div>').join('')+'</div>';
}
export function renderArmory(ui){
 const s=ui.g.store.data,filter=ui.inventoryFilter||'all',items=s.inventory.filter(i=>filter==='all'||slotOf(i)===filter);
 if(!items.some(i=>i.id===ui.item))ui.item=(items.find(i=>i.id===heroData(s).equipped[filter])||items.find(i=>i.id===heroData(s).equipped.weapon)||items[0])?.id;
 const i=items.find(x=>x.id===ui.item),current=i&&equipped(s,slotOf(i)),used=current?.id===i?.id;
 const equipmentSlots='<div class="equipment-slots">'+Object.entries(slots).map(([key,label])=>{const x=equipped(s,key);return '<button data-action="equipment-slot" data-id="'+key+'" class="equipment-slot '+(filter===key?'active':'')+'" style="--item:'+RARITIES[x.rarity].color+'"><small>'+label.toUpperCase()+' SLOT</small><b>'+esc(x.name)+(x.plus?' +'+x.plus:'')+'</b><span>'+ (key==='armor'?armorDefinition(x).role:key==='weapon'?itemValue(x)+' damage':itemValue(x)+' power')+'</span></button>';}).join('')+'</div>';
 const filters='<div class="subtabs inventory-filters">'+Object.entries({all:'All equipment',...slots}).map(([key,label])=>'<button data-action="inventory-filter" data-id="'+key+'" class="'+(filter===key?'active':'')+'">'+label+'</button>').join('')+'</div>';
 const inventory='<div class="inventory">'+items.map(x=>'<button data-action="item" data-id="'+esc(x.id)+'" class="item '+(i?.id===x.id?'active':'')+'" style="--item:'+RARITIES[x.rarity].color+'"><b>'+esc(x.name)+(x.plus?' +'+x.plus:'')+'</b><small>'+RARITIES[x.rarity].name+' · '+(Object.values(heroData(s).equipped).includes(x.id)?'EQUIPPED':x.type.toUpperCase())+'</small></button>').join('')+'</div>';
 let detail='';if(i){const armor=i.type==='armor',cost=forgeCost(i),rarity=RARITIES[i.rarity],benefits=armor?armorBenefits(i):[];
 detail='<article class="item-info"><div class="item-status">'+(used?'CURRENTLY WORN':'PREVIEW · NOT EQUIPPED')+'</div><h3 style="color:'+rarity.color+'">'+esc(i.name)+(i.plus?' +'+i.plus:'')+'</h3><p>'+rarity.name+' · Item level '+i.level+' · '+(WEAPONS[i.type]?'Damage':armor?'Armor':'Equipment power')+' '+itemValue(i)+(current&&!used?' <span class="muted">(equipped '+itemValue(current)+')</span>':'')+'</p>'+
 (armor?'<p class="armor-lore">'+armorDefinition(i).lore+'</p><div class="armor-benefits"><h4>'+armorDefinition(i).role+'</h4>'+(benefits.length?'<ul>'+benefits.map(b=>'<li>'+esc(b)+'</li>').join('')+'</ul>':'<p>Balanced protection. Find a specialized pattern in treasure or battle rewards.</p>')+'</div>':'')+
 (i.affix?'<p class="rolled-affix"><b>Rolled bonus:</b> '+AFFIXES[i.affix].desc+'</p>':'')+
 (armor&&!used&&current?.affix&&current.affix!==i.affix?'<p class="replaced-affix">Replacing '+esc(current.name)+' also removes its rolled bonus: '+AFFIXES[current.affix].desc+'</p>':'')+(armor?compareArmor(s,i):'')+'<div class="item-actions">'+ui.button('equip',i.id,used?'Equipped':armor?'Equip armor':'Equip',used||!!ui.g.battle,true)+ui.button('forge',i.id,i.plus>=10?'Fully forged':'Forge to +'+(i.plus+1)+' · '+cost.supplies+' Supplies + '+cost.salvage+' Salvage',i.plus>=10||!!ui.g.battle)+ui.button('salvage',i.id,'Salvage',Object.values(s.heroes).some(h=>Object.values(h.equipped).includes(i.id))||!!ui.g.battle)+'</div>'+
 '<p class="forge-notes">'+(armor?'Forging strengthens protection and this pattern’s innate benefits. Only worn armor grants its buffs. ':'')+'+3 unlocks a rune · +6 unlocks a temper · +10 awakens after reclaiming Act II.</p><p>Rune: '+(i.rune||'none')+' · Temper: '+(i.temper||'none')+(i.awakened?' · Awakened +12%':'')+'</p>'+
 (i.plus>=3?'<h3>Rune socket · 8 Salvage</h3><div class="subtabs">'+['ember','frost','vital'].map(r=>ui.button('rune',i.id,r===i.rune?'✓ '+r:r,!!ui.g.battle||r===i.rune,false,r)).join('')+'</div><p class="muted">'+(armor?'Armor runes: Ember adds 15% fire resistance · Frost adds 12 stamina · Vital adds 24 health.':'Ember burns · Frost slows · Vital restores 1 health on hit.')+'</p>':'')+
 (i.plus>=6?'<h3>Temper · 15 Salvage</h3><div class="subtabs">'+['swift','sunder','guard'].map(r=>ui.button('temper',i.id,r===i.temper?'✓ '+r:r,!!ui.g.battle||r===i.temper,false,r)).join('')+'</div><p>'+(armor?'Armor tempers: Swift adds 5% movement speed · Sunder adds 10% charged attack damage · Guard reduces block cost by another 15%.':'Swift speeds attacks · Sunder strips armor on a heavy hit · Guard lowers block cost.')+'</p>':'')+'</article>';
 }
 return '<div class="section-head"><h2>Your equipment</h2><span class="tag">'+s.inventory.length+' / 160 ITEMS</span></div>'+equipmentSlots+'<p class="intro armory-intro">Armor has its own slot. Find six specialized patterns in treasure and victory rewards; your first defense guarantees one. Select a piece to try it on and compare its benefits before equipping.</p>'+filters+inventory+detail;
}
