import {sectionTabs} from './menu-flow.js';
import {WEAPONS,RARITIES,AFFIXES} from './data.js';
import {heroData,heroStats,equipped,itemValue,forgeCost} from './state.js';
import {armorDefinition,armorBenefits} from './armor.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slots={weapon:'Weapon',armor:'Armor',shield:'Shield',relic:'Relic'};
const slotOf=i=>WEAPONS[i.type]?'weapon':i.type;
const number=n=>Number(n.toFixed(2));
const percent=n=>Number((n*100).toFixed(1))+'%';
function compareArmor(s,item){
 const h=heroData(s),a=heroStats(s),b=heroStats({...s,heroes:{...s.heroes,[s.hero]:{...h,equipped:{...h.equipped,armor:item.id}}}});
 const rows=[['armor','Armor',number],['hp','Health',number],['focus','Focus',number],['stamina','Stamina',number],['speed','Move speed',n=>number(n)+' m/s'],['attackSpeed','Attack speed',percent],['guardCost','Block cost',percent,-1],['staminaRegen','Resting stamina recovery',n=>number(n)+'/s'],['focusRegen','Focus recovery',n=>number(n)+'/s'],['fireResistance','Fire resistance',percent],['heavyBonus','Charged attack bonus',percent],['healFactor','Draught / Quench healing',percent],['supportRadius','Command radius',n=>number(n)+' m'],['allyBonus','Nearby troop bonus',percent]];
 return '<div class="armor-comparison"><div class="compare-heading"><span>HERO TOTALS</span><span>WORN → SELECTED</span></div>'+rows.filter(([key])=>key==='armor'||Math.abs(a[key]-b[key])>.00001).map(([key,label,fmt,direction=1])=>'<div class="compare-row"><span>'+label+'</span><b class="'+(b[key]===a[key]?'':(b[key]-a[key])*direction>0?'stat-gain':'stat-loss')+'">'+fmt(a[key])+' → '+fmt(b[key])+'</b></div>').join('')+'</div>';
}
export function renderArmory(ui){
 const s=ui.g.store.data,filter=ui.inventoryFilter||'weapon',items=s.inventory.filter(i=>filter==='all'||slotOf(i)===filter);
 const i=items.find(x=>x.id===ui.item)||items[0];if(i&&ui.screen!=='list')ui.item=i.id;
 if(ui.screen==='list')return '<p class="list-hint">Choose an equipment slot.</p><div class="equipment-slots">'+Object.entries(slots).map(([key,label])=>{const x=equipped(s,key);return '<button data-action="equipment-slot" data-id="'+key+'" class="equipment-slot" style="--item:'+RARITIES[x.rarity].color+'"><small>'+label.toUpperCase()+'</small><b>'+esc(x.name)+(x.plus?' +'+x.plus:'')+'</b><span>'+ (key==='armor'?armorDefinition(x).role:key==='weapon'?itemValue(x)+' damage':itemValue(x)+' power')+'</span></button>';}).join('')+'</div>';
 if(ui.screen==='inventory')return '<div class="section-head"><h2>'+slots[filter]+'</h2><span class="tag">'+items.length+' items</span></div><p class="list-hint">Choose a piece to try it on and compare.</p><div class="inventory">'+items.map(x=>'<button data-action="item" data-id="'+esc(x.id)+'" class="item" style="--item:'+RARITIES[x.rarity].color+'"><b>'+esc(x.name)+(x.plus?' +'+x.plus:'')+'</b><small>'+RARITIES[x.rarity].name+' · '+(Object.values(heroData(s).equipped).includes(x.id)?'EQUIPPED':'Level '+x.level)+'</small></button>').join('')+'</div>';
 if(!i)return '<p>No equipment in this slot yet.</p>';
 const current=equipped(s,slotOf(i)),used=current?.id===i.id,armor=i.type==='armor',cost=forgeCost(i),rarity=RARITIES[i.rarity],benefits=armor?armorBenefits(i):[],section=ui.detailTab;
 const heading='<div class="item-status">'+(used?'CURRENTLY WORN':'TRYING ON · NOT EQUIPPED')+'</div><h3 style="color:'+rarity.color+'">'+esc(i.name)+(i.plus?' +'+i.plus:'')+'</h3><p>'+rarity.name+' · Level '+i.level+' · '+(WEAPONS[i.type]?'Damage':armor?'Armor':'Power')+' '+itemValue(i)+'</p>';
 let body='';
 if(section==='forge')body='<div class="item-actions">'+ui.button('forge',i.id,i.plus>=10?'Fully forged':'Forge +'+(i.plus+1)+' · '+cost.supplies+' Supplies + '+cost.salvage+' Salvage',i.plus>=10||!!ui.g.battle||s.supplies<cost.supplies||s.salvage<cost.salvage,true)+'</div><p class="forge-notes">+3 unlocks a rune · +6 unlocks a temper · +10 awakens after Act II.</p><p>Rune: '+(i.rune||'none')+' · Temper: '+(i.temper||'none')+(i.awakened?' · Awakened +12%':'')+'</p>'+ (i.plus>=3?'<h3>Rune · 8 Salvage</h3><div class="subtabs">'+['ember','frost','vital'].map(r=>ui.button('rune',i.id,r===i.rune?'✓ '+r:r,!!ui.g.battle||r===i.rune||s.salvage<8,false,r)).join('')+'</div><p>'+(armor?'Ember: 15% fire resistance · Frost: 12 stamina · Vital: 24 health.':'Ember burns · Frost slows · Vital heals 1 on hit.')+'</p>':'')+(i.plus>=6?'<h3>Temper · 15 Salvage</h3><div class="subtabs">'+['swift','sunder','guard'].map(r=>ui.button('temper',i.id,r===i.temper?'✓ '+r:r,!!ui.g.battle||r===i.temper||s.salvage<15,false,r)).join('')+'</div><p>'+(armor?'Swift: 5% speed · Sunder: 10% charged damage · Guard: 15% lower block cost.':'Swift speeds attacks · Sunder strips armor on heavy hits · Guard lowers block cost.')+'</p>':'')+'<div class="salvage-action">'+ui.button('salvage',i.id,'Salvage equipment',Object.values(s.heroes).some(h=>Object.values(h.equipped).includes(i.id))||!!ui.g.battle)+'</div>';
 else if(section==='compare')body=(armor?compareArmor(s,i):'<div class="compare-row"><span>Equipped → selected power</span><b>'+itemValue(current)+' → '+itemValue(i)+'</b></div>')+(current?.affix&&current.affix!==i.affix?'<p>Replaces bonus: '+AFFIXES[current.affix].desc+'</p>':'');
 else body='<div class="item-actions">'+ui.button('equip',i.id,used?'Equipped':'Equip '+slots[slotOf(i)].toLowerCase(),used||!!ui.g.battle,true)+'</div>'+(armor?'<div class="armor-benefits"><h4>'+armorDefinition(i).role+'</h4>'+(benefits.length?'<ul>'+benefits.map(b=>'<li>'+esc(b)+'</li>').join('')+'</ul>':'<p>Balanced protection. Find specialized patterns in treasure and battle rewards.</p>')+'</div>':'')+(i.affix?'<p class="rolled-affix"><b>Rolled bonus:</b> '+AFFIXES[i.affix].desc+'</p>':'')+(armor?'<p class="armor-lore">'+armorDefinition(i).lore+'</p>':'');
 return sectionTabs(ui,{overview:'Benefits',compare:'Compare',forge:'Forge'})+'<article class="item-info">'+heading+body+'</article>';
}
