import {validateSiegeState} from './siege-rules.js';
import {WEAPON_PATTERNS} from './weapon-patterns.js';
import {MISSIONS,WEAPONS,AFFIXES,UNITS,DEFENSES,HEROES} from './data.js';
import {ARMORS} from './armor.js';
import {RESEARCH} from './research.js';
export const LEDGER_KEYS=['kills','heroKills','troopKills','defenseKills','heroDamage','troopDamage','defenseDamage','damageTaken','recruited','reinforcements','lost','commandSpent','defenseRefits','light','heavy','casts','guards','projectiles','xp','supplies','salvage'];
export function newBattleLedger(level=1){return {version:1,startLevel:level,...Object.fromEntries(LEDGER_KEYS.map(k=>[k,0])),chests:[],foundItems:[]};}
export function tally(battle,key,amount=1){if(!battle?.ledger||!LEDGER_KEYS.includes(key)||!Number.isFinite(amount))return;battle.ledger[key]+=Math.max(0,amount);}
export function recordDamage(battle,target,source,hero,damage){if(!battle?.ledger||target.training)return;const actual=Math.max(0,Math.min(damage,target.hp));if(target.team==='enemy'){const key=source===hero?'heroDamage':source?.defense?'defenseDamage':source?.team==='ally'?'troopDamage':null;if(key)tally(battle,key,actual);}else if(target===hero)tally(battle,'damageTaken',actual);}
export function recordKill(battle,target,source,hero){if(!battle?.ledger||target.training)return;if(target.team==='enemy'){tally(battle,'kills');tally(battle,source===hero?'heroKills':source?.defense?'defenseKills':'troopKills');}else if(target.team==='ally')tally(battle,'lost');}
const finite=(x,max=1e9)=>Number.isFinite(x)&&x>=0&&x<=max;
const validItem=i=>i&&typeof i.id==='string'&&i.id.length<100&&typeof i.name==='string'&&i.name.length<200&&Object.hasOwn({...WEAPONS,armor:1,shield:1,relic:1},i.type)&&Number.isInteger(i.rarity)&&i.rarity>=0&&i.rarity<=4&&Number.isInteger(i.level)&&i.level>=1&&i.level<=30&&Number.isInteger(i.plus)&&i.plus>=0&&i.plus<=10&&finite(i.base,10000)&&(!i.affix||Object.hasOwn(AFFIXES,i.affix))&&(!i.rune||['ember','frost','vital'].includes(i.rune))&&(!i.temper||['swift','sunder','guard'].includes(i.temper))&&(i.weaponPattern===undefined||WEAPON_PATTERNS[i.weaponPattern]?.type===i.type)&&(i.armorKind===undefined||i.type==='armor'&&Object.hasOwn(ARMORS,i.armorKind));
export function validateBattleLedger(ledger){if(ledger===undefined)return;if(!ledger||ledger.version!==1||!Number.isInteger(ledger.startLevel)||ledger.startLevel<1||ledger.startLevel>30||LEDGER_KEYS.some(k=>!finite(ledger[k])))throw Error('Invalid battle statistics.');if(!Array.isArray(ledger.chests)||ledger.chests.length>5||new Set(ledger.chests.map(c=>c?.id)).size!==ledger.chests.length)throw Error('Invalid battle chests.');for(const c of ledger.chests){if(typeof c.id!=='string'||c.id.length>100||!Number.isInteger(c.rarity)||c.rarity<0||c.rarity>4||typeof c.secured!=='boolean'||!c.pos||['x','y','z'].some(k=>!Number.isFinite(c.pos[k])||Math.abs(c.pos[k])>(k==='z'?2400:1000))||!c.rewards||!finite(c.rewards.supplies,10000)||!finite(c.rewards.salvage,10000)||!Array.isArray(c.rewards.items)||c.rewards.items.length<1||c.rewards.items.length>2||c.rewards.items.some(i=>!validItem(i)))throw Error('Invalid battle chest contents.');}if(!Array.isArray(ledger.foundItems)||ledger.foundItems.length>20||ledger.foundItems.some(i=>!validItem(i)))throw Error('Invalid field loot.');}
export function validateBattleReport(report){if(report==null)return;validateSiegeState(report.siege,MISSIONS[report.mission]);validateUnlockReview(report.tutorial);if(report.income!==undefined&&!finite(report.income,10000))throw Error('Invalid settlement income.');if(report.version!==1||typeof report.id!=='string'||report.id.length>100||!MISSIONS[report.mission]||typeof report.win!=='boolean'||typeof report.acknowledged!=='boolean'||typeof report.reason!=='string'||report.reason.length>500||!finite(report.time,1e7)||!Array.isArray(report.chests)||report.chests.length>5||!Array.isArray(report.items)||report.items.length>30||report.items.some(i=>!validItem(i))||!Array.isArray(report.revealed)||report.revealed.some(id=>!report.chests.some(c=>c.id===id)))throw Error('Invalid battle report.');if(!Number.isInteger(report.mission)||typeof report.first!=='boolean'||typeof report.camp!=='boolean'||!finite(report.lostChests,5)||!Array.isArray(report.research)||report.research.length>4||report.research.some(id=>!Object.hasOwn(RESEARCH,id))||report.chests.some(c=>typeof c.recovered!=='boolean'||!finite(c.converted,100)||!Array.isArray(c.grantedItemIds)||c.grantedItemIds.some(id=>!c.rewards?.items?.some(i=>i.id===id))))throw Error('Invalid reward settlement.');validateBattleLedger(report.stats);validateBattleLedger({...report.stats,chests:report.chests,foundItems:[]});for(const k of ['supplies','salvage','xp','gate','maxGate','beacon','survivors','waves','endLevel'])if(!finite(report[k]))throw Error('Invalid battle report values.');}

export function validateUnlockReview(q){if(q===undefined)return;const bad=()=>{throw Error('Invalid unlock review.');};if(!q||q.version!==1||!Array.isArray(q.cards)||q.cards.length>24||!Number.isInteger(q.cursor)||q.cursor<0||q.cursor>q.cards.length||typeof q.complete!=='boolean'||q.started!==undefined&&typeof q.started!=='boolean')bad();for(const c of q.cards){if(!c||typeof c.id!=='string')bad();if(c.kind==='unit'){if(!Object.hasOwn(UNITS,c.id))bad();}else if(c.kind==='defense'){if(!Object.hasOwn(DEFENSES,c.id))bad();}else if(c.kind==='research'){if(!Object.hasOwn(RESEARCH,c.id))bad();}else if(c.kind==='territory'){if(!/^\d+$/.test(c.id)||!MISSIONS[Number(c.id)])bad();}else if(c.kind==='item'){if(!c.id||c.id.length>100)bad();}else if(c.kind==='ability'){if(!Object.hasOwn(HEROES,c.hero)||!HEROES[c.hero].skills.some(n=>n.id===c.id&&n.active))bad();}else if(c.kind==='hero'){if(!Object.hasOwn(HEROES,c.id)||!Number.isInteger(c.from)||!Number.isInteger(c.to)||c.from<1||c.to<=c.from||c.to>30)bad();}else if(c.kind==='lesson'){if(!['equipment','exploration','ranks','tribute'].includes(c.id))bad();if(c.id==='ranks'&&![7,10].includes(c.rank))bad();if(c.id==='tribute'&&MISSIONS[c.mission]?.kind!=='settlement')bad();}else bad();}}
