import {UNITS,DEFENSES,ROMAN} from './data.js';
import {battleUnitStats,battleDefenseStats} from './research.js';
import {unitUnlocked,defenseUnlocked} from './state.js';
import {fieldDefenseCost} from './field-command.js';
import {UNIT_ICONS,DEFENSE_ICONS} from './battle-icons.js';
import {sigil} from './menu-flow.js';
export function fieldRoster(ui,kind){const g=ui.g,s=g.store.data,b=g.battle,units=kind==='troops',list=units?UNITS:DEFENSES,id=units?ui.unit:ui.defense,d=list[id],rank=(units?s.units:s.defenses)[id],available=units?unitUnlocked:defenseUnlocked,icons=units?UNIT_ICONS:DEFENSE_ICONS,unlocked=available(s,id),st=units?battleUnitStats(id,rank,b):battleDefenseStats(id,rank,s.doctrines[id],b),cost=units?st.cost:fieldDefenseCost(id),count=g.allies.filter(a=>!a.dead).length,full=units&&count+st.count>24;
 const blocked=!unlocked||b.command<cost||full||(!units&&id==='gate'&&(b.gate<=0||b.gate>=b.maxGate));
 return '<div class="field-library roster-library"><div class="field-selection"><div class="field-filters">'+['troops','defenses','orders','research'].filter(key=>!b.siege||key!=='defenses').map(key=>'<button data-action="battle-category" data-id="'+key+'" class="'+(kind===key?'active':'')+'">'+({troops:'Troops',defenses:'Defenses',orders:'Orders',research:'Research'}[key])+'</button>').join('')+'</div><div class="field-roster-grid" aria-label="'+kind+'">'+Object.entries(list).map(([key,u])=>{const lock=!available(s,key),r=(units?s.units:s.defenses)[key],price=units?battleUnitStats(key,r,b).cost:fieldDefenseCost(key);return '<button class="field-roster-tile '+(id===key?'selected ':'')+(lock?'locked':'')+'" data-action="field-inspect" data-id="'+key+'" data-value="'+kind+'" aria-pressed="'+(id===key)+'">'+sigil(icons[key])+'<span><b>'+u.name+'</b><small>'+(lock?'Unlock · '+u.unlock+' victories':'Rank '+ROMAN[r-1]+' · '+(units?battleUnitStats(key,r,b).count+' soldiers':key==='gate'?'Repair':'Emplacement'))+'</small></span><em>⚑ '+price+'</em></button>';}).join('')+'</div><small class="field-list-note">'+(units?count+' / 24 soldiers · Each repeat purchase of this troop costs +20% of its initial price.':'Four emplacements · Refits last this battle.')+'</small></div><aside class="field-detail roster-detail"><div class="field-detail-scroll"><h2>'+d.name+'</h2><div id="battle-mini-stage" aria-label="Animated '+d.name+' preview"></div><div class="field-primary-stats"><span><b>'+(units?st.hp:id==='gate'?Math.ceil(b.gate):'—')+'</b><small>'+(units?'Health':id==='gate'?'Gate HP':'Protected')+'</small></span><span><b>'+(id==='gate'?st.hp:st.damage)+'</b><small>'+(id==='gate'?'Max HP':id==='sanctuary'?'Healing':'Damage')+'</small></span><span><b>'+(units?st.reach:id==='gate'?'650':st.range)+'</b><small>'+(id==='gate'?'Beacon HP':'Range · m')+'</small></span></div></div><div class="field-detail-actions">'+ui.button(units?'recruit':'field-select',id,!unlocked?'Unlock · '+d.unlock+' victories':full?'Army capacity reached':b.command<cost?'Need '+cost+' Command':(units?'Recruit':id==='gate'?'Repair':'Refit')+' · ⚑ '+cost,blocked,true)+ui.button('inspect-object',id,'Stats & abilities',false,false,kind)+'</div></aside></div>';
}
