import {commandBreakdown} from './command-economy.js';
import {SIEGE_NAMES,siegeConfig,SIEGE_OUTPOSTS,SIEGE_GATE_Z} from './siege-rules.js';
import {UNITS,MISSIONS} from './data.js';
import {battleUnitStats,commandIncome} from './research.js';
import {sigil} from './menu-flow.js';
const $=id=>document.getElementById(id);
const icons={hp:'hero',stamina:'spear',focus:'fire'};
const unitIcon=id=>UNITS[id].weapon==='bow'?'bow':UNITS[id].weapon==='staff'?'fire':UNITS[id].weapon==='spear'?'spear':id==='shield'?'hero':'troops';
export function mountBattleHUD(ui){const el=document.createElement('section');el.id='combat-summary';el.hidden=true;el.setAttribute('aria-label','Battle status');el.innerHTML='<div class="combat-summary-left"><div class="combat-vitals">'+[['hp','Health'],['stamina','Stamina'],['focus','Magic']].map(([id,name])=>'<div class="combat-vital '+id+'" id="combat-'+id+'">'+sigil(icons[id])+'<span><b id="combat-'+id+'-value"></b><small>'+name+'</small></span><i id="combat-'+id+'-fill"></i></div>').join('')+'</div><button class="combat-command" id="command-income-detail" aria-label="Command income details"><b id="combat-command-value"></b><span id="combat-command-rate"></span></button><div id="quick-recruits" aria-label="Recruit recent squads again"></div></div><div class="combat-summary-right"><div class="combat-counts"><button id="combat-army-count" aria-label="Army capacity: open troops"><span>'+sigil('troops')+'<b id="combat-army-value"></b></span><small id="combat-army-free"></small></button><button id="combat-defense-count" aria-label="Installed defenses: open defenses"><span>'+sigil('defenses')+'<b id="combat-defense-value"></b></span><small>Defenses</small></button></div><div class="combat-gate"><span id="combat-gate-label"></span><b id="combat-gate-value"></b><i id="combat-gate-fill"></i></div><small id="combat-wave"></small></div>';$('hud').append(el);
 $('command-income-detail').onclick=()=>{const g=ui.g,d=commandBreakdown(g.battle);ui.dialog('<small>PASSIVE COMMAND</small><h2>+'+d.total.toFixed(2)+' per second</h2><div class="row"><span>Base income</span><b>+0.60/s</b></div><div class="row"><span>Castle command lodge</span><b>+'+d.castle.toFixed(2)+'/s</b></div><div class="row"><span>Dawn standards · strongest 3</span><b>+'+d.standards.toFixed(2)+'/s</b></div><div class="row"><span>Ridge camp</span><b>+'+d.camp.toFixed(2)+'/s</b></div><div class="row"><span>Field logistics research</span><b>'+(d.multiplier>1?'+20%':'Not active')+'</b></div><p>Hire Dawn standards after your first victory. Upgrade the command lodge at Castle → Command lodge. Income pauses at 220 Command.</p><div class="dialog-actions"><button id="income-close" class="primary">Return to battle</button></div>');$('income-close').onclick=()=>{$('dialog').hidden=true;};};
 $('combat-army-count').onclick=()=>{ui.open('army');ui.action('battle-category','troops');};$('combat-defense-count').onclick=()=>ui.open('battle-defenses');
 $('quick-recruits').onclick=e=>{const button=e.target.closest('[data-quick-recruit]');if(button&&!button.disabled&&ui.g.input.enabled&&!ui.g.menu&&!ui.modal&&ui.g.battle){ui.g.recruit(button.dataset.quickRecruit);updateBattleHUD(ui);}};
 const research=document.createElement('button');research.id='research-button';research.className='army-button glass';research.hidden=true;research.innerHTML=sigil('more')+'<span>RESEARCH</span><small id="research-hud-status">0/4 chosen</small>';research.onclick=()=>{if(ui.g.battle&&ui.g.mode==='play')ui.open('research');};$('hud').append(research);
}
export function updateBattleHUD(ui){const g=ui.g,b=g.battle,s=g.store.data,active=!!b&&g.mode==='play';$('hud').classList.toggle('in-battle',active);$('combat-summary').hidden=!active;$('research-button').hidden=!active;if(!active)return;const h=g.hero,st=h.stats;for(const [id,max]of [['hp',st.hp],['stamina',st.stamina],['focus',st.focus]]){const value=Math.max(0,Math.ceil(h[id]));$('combat-'+id+'-value').textContent=value;$('combat-'+id+'-fill').style.width=Math.max(0,Math.min(100,h[id]/max*100))+'%';$('combat-'+id).setAttribute('aria-label',({hp:'Health',stamina:'Stamina',focus:'Magic'}[id])+': '+value+' of '+Math.ceil(max));}
 const count=g.allies.filter(a=>!a.dead).length;$('combat-command-value').textContent='⚑ '+Math.floor(b.command);$('combat-command-rate').textContent='+'+commandIncome(b).toFixed(2)+'/s'+(b.command>=220?' · FULL':' · Command');$('combat-army-value').textContent=count+'/24';$('combat-army-free').textContent=(24-count)+' free';$('combat-defense-value').textContent=g.world.towerObjects.length+'/4';if(b.siege){const st=b.siege,near=(g.siegeTargets||[]).filter(t=>!t.dead&&['west','east'].includes(t.part)&&t.pos.distanceTo(g.hero.pos)<18).sort((a,c)=>a.pos.distanceTo(g.hero.pos)-c.pos.distanceTo(g.hero.pos))[0],part=near?.part||(st.hp.gate>0?'gate':'keep'),c=siegeConfig(MISSIONS[b.id]),pct=Math.ceil(st.hp[part]/c.hp[part]*100);$('combat-gate-label').textContent=SIEGE_NAMES[part];$('combat-gate-value').textContent=pct+'%';$('combat-gate-fill').style.width=pct+'%';const next=SIEGE_OUTPOSTS.find((p,i)=>!st.outposts[i]&&p.z<g.hero.pos.z+60),meters=Math.round(Math.hypot(g.hero.pos.x-(next?.x||0),g.hero.pos.z-(next?.z??SIEGE_GATE_Z)));$('combat-wave').textContent='Pressure '+st.pressure+'/6 · '+(st.capture>0?'Capturing '+Math.ceil(st.capture)+'/6s':(next?'Camp':'Fortress')+' '+(meters>=1000?(meters/1000).toFixed(1)+'km':meters+'m'));$('combat-defense-value').textContent=(Number(st.hp.west>0)+Number(st.hp.east>0))+'/2';$('combat-defense-count').querySelector('small').textContent='Bastions';$('combat-defense-count').disabled=true;$('combat-defense-count').setAttribute('aria-label','Enemy bastions still firing: '+(Number(st.hp.west>0)+Number(st.hp.east>0)));}else{const gate=b.gate>0;$('combat-gate-label').textContent=gate?'Gate':'Beacon';$('combat-gate-value').textContent=Math.ceil((gate?b.gate/b.maxGate:b.core/650)*100)+'%';$('combat-gate-fill').style.width=Math.max(0,(gate?b.gate/b.maxGate:b.core/650)*100)+'%';$('combat-wave').textContent='Wave '+b.wave+'/'+MISSIONS[b.id].waves;$('combat-defense-count').querySelector('small').textContent='Defenses';$('combat-defense-count').disabled=false;$('combat-defense-count').setAttribute('aria-label','Installed defenses: open defenses');}
 const recent=b.recentRecruits||[],signature=recent.join(',');if(ui.quickSignature!==signature){ui.quickSignature=signature;$('quick-recruits').innerHTML=recent.map(id=>'<button data-quick-recruit="'+id+'" class="quick-recruit" aria-label="Recruit '+UNITS[id].name+' again">'+sigil(unitIcon(id))+'<b></b><small>'+({shield:'Shields',bow:'Bows',pike:'Pikes',lantern:'Lanterns',breaker:'Breakers',crew:'Siege',rider:'Riders',giant:'Giant',banner:'Banner',engineer:'Engineers',assassin:'Blades',pyre:'Cinders',marksman:'Marksmen',frost:'Rime',dawn:'Sun sworn'}[id])+'</small></button>').join('');}
 for(const button of $('quick-recruits').children){const id=button.dataset.quickRecruit,st=battleUnitStats(id,s.units[id],b),cost=st.cost;button.querySelector('b').textContent=cost;button.disabled=b.command<cost||count+st.count>24;button.setAttribute('aria-label','Recruit '+UNITS[id].name+' again, '+cost+' Command for '+st.count+' soldiers');button.title=button.disabled?(count+st.count>24?'Not enough army capacity':'Not enough Command'):'Recruit '+UNITS[id].name;}
 const list=b.research||[],pending=list.filter(r=>!r.complete),status=pending.length?pending.length+' learning · '+Math.ceil(Math.min(...pending.map(r=>r.remaining)))+'s':list.length?list.length+'/4 active':'0/4 chosen';$('research-hud-status').textContent=status;$('research-button').classList.toggle('research-learning',pending.length>0);
}
