import {UNITS,MISSIONS} from './data.js';
import {battleUnitStats} from './research.js';
import {sigil} from './menu-flow.js';
const $=id=>document.getElementById(id);
const icons={hp:'hero',stamina:'spear',focus:'fire'};
const unitIcon=id=>UNITS[id].weapon==='bow'?'bow':UNITS[id].weapon==='staff'?'fire':UNITS[id].weapon==='spear'?'spear':id==='shield'?'hero':'troops';
export function mountBattleHUD(ui){const el=document.createElement('section');el.id='combat-summary';el.hidden=true;el.setAttribute('aria-label','Battle status');el.innerHTML='<div class="combat-summary-left"><div class="combat-vitals">'+[['hp','Health'],['stamina','Stamina'],['focus','Magic']].map(([id,name])=>'<div class="combat-vital '+id+'" id="combat-'+id+'">'+sigil(icons[id])+'<span><b id="combat-'+id+'-value"></b><small>'+name+'</small></span><i id="combat-'+id+'-fill"></i></div>').join('')+'</div><div class="combat-command"><b id="combat-command-value"></b><span id="combat-command-rate"></span></div><div id="quick-recruits" aria-label="Recruit recent squads again"></div></div><div class="combat-summary-right"><div class="combat-counts"><button id="combat-army-count" aria-label="Army capacity: open troops"><span>'+sigil('troops')+'<b id="combat-army-value"></b></span><small id="combat-army-free"></small></button><button id="combat-defense-count" aria-label="Installed defenses: open defenses"><span>'+sigil('defenses')+'<b id="combat-defense-value"></b></span><small>Defenses</small></button></div><div class="combat-gate"><span id="combat-gate-label"></span><b id="combat-gate-value"></b><i id="combat-gate-fill"></i></div><small id="combat-wave"></small></div>';$('hud').append(el);
 $('combat-army-count').onclick=()=>{ui.open('army');ui.action('battle-category','troops');};$('combat-defense-count').onclick=()=>ui.open('battle-defenses');
 $('quick-recruits').onclick=e=>{const button=e.target.closest('[data-quick-recruit]');if(button&&!button.disabled&&ui.g.input.enabled&&!ui.g.menu&&!ui.modal&&ui.g.battle){ui.g.recruit(button.dataset.quickRecruit);updateBattleHUD(ui);}};
 const research=document.createElement('button');research.id='research-button';research.className='army-button glass';research.hidden=true;research.innerHTML=sigil('more')+'<span>RESEARCH</span><small id="research-hud-status">0/4 chosen</small>';research.onclick=()=>{if(ui.g.battle&&ui.g.mode==='play')ui.open('research');};$('hud').append(research);
}
export function updateBattleHUD(ui){const g=ui.g,b=g.battle,s=g.store.data,active=!!b&&g.mode==='play';$('hud').classList.toggle('in-battle',active);$('combat-summary').hidden=!active;$('research-button').hidden=!active;if(!active)return;const h=g.hero,st=h.stats;for(const [id,max]of [['hp',st.hp],['stamina',st.stamina],['focus',st.focus]]){const value=Math.max(0,Math.ceil(h[id]));$('combat-'+id+'-value').textContent=value;$('combat-'+id+'-fill').style.width=Math.max(0,Math.min(100,h[id]/max*100))+'%';$('combat-'+id).setAttribute('aria-label',({hp:'Health',stamina:'Stamina',focus:'Magic'}[id])+': '+value+' of '+Math.ceil(max));}
 const count=g.allies.filter(a=>!a.dead).length;$('combat-command-value').textContent='⚑ '+Math.floor(b.command);$('combat-command-rate').textContent=b.command>=220?'Command · Full':'Command · +'+(b.camp?'2.1':'1.6')+'/s';$('combat-army-value').textContent=count+'/24';$('combat-army-free').textContent=(24-count)+' free · Troops';$('combat-defense-value').textContent=g.world.towerObjects.length+'/4';const gate=b.gate>0;$('combat-gate-label').textContent=gate?'Gate':'Beacon';$('combat-gate-value').textContent=Math.ceil((gate?b.gate/b.maxGate:b.core/650)*100)+'%';$('combat-gate-fill').style.width=Math.max(0,(gate?b.gate/b.maxGate:b.core/650)*100)+'%';$('combat-wave').textContent='Wave '+b.wave+'/'+MISSIONS[b.id].waves;
 const recent=b.recentRecruits||[],signature=recent.join(',');if(ui.quickSignature!==signature){ui.quickSignature=signature;$('quick-recruits').innerHTML=recent.map(id=>'<button data-quick-recruit="'+id+'" class="quick-recruit" aria-label="Recruit '+UNITS[id].name+' again">'+sigil(unitIcon(id))+'<b></b><small>'+({shield:'Shields',bow:'Bows',pike:'Pikes',lantern:'Lanterns',breaker:'Breakers',crew:'Siege',rider:'Riders',giant:'Giant',banner:'Banner',engineer:'Engineers',assassin:'Blades',pyre:'Cinders',marksman:'Marksmen',frost:'Rime',dawn:'Sun sworn'}[id])+'</small></button>').join('');}
 for(const button of $('quick-recruits').children){const id=button.dataset.quickRecruit,cost=battleUnitStats(id,s.units[id],b).cost;button.querySelector('b').textContent=cost;button.disabled=b.command<cost||count+UNITS[id].count>24;button.setAttribute('aria-label','Recruit '+UNITS[id].name+' again, '+cost+' Command for '+UNITS[id].count+' soldiers');button.title=button.disabled?(count+UNITS[id].count>24?'Not enough army capacity':'Not enough Command'):'Recruit '+UNITS[id].name;}
 const list=b.research||[],pending=list.filter(r=>!r.complete),status=pending.length?pending.length+' learning · '+Math.ceil(Math.min(...pending.map(r=>r.remaining)))+'s':list.length?list.length+'/4 active':'0/4 chosen';$('research-hud-status').textContent=status;$('research-button').classList.toggle('research-learning',pending.length>0);
}
