import {MISSIONS,WEAPONS,AFFIXES} from './data.js';
import {ARMORS} from './armor.js';
import {RESEARCH} from './research.js';
export const LEDGER_KEYS=['kills','heroKills','troopKills','defenseKills','heroDamage','troopDamage','defenseDamage','damageTaken','recruited','reinforcements','lost','commandSpent','defenseRefits','light','heavy','casts','guards','projectiles','xp','supplies','salvage'];
export function newBattleLedger(level=1){return {version:1,startLevel:level,...Object.fromEntries(LEDGER_KEYS.map(k=>[k,0])),chests:[],foundItems:[]};}
export function tally(battle,key,amount=1){if(!battle?.ledger||!LEDGER_KEYS.includes(key)||!Number.isFinite(amount))return;battle.ledger[key]+=Math.max(0,amount);}
export function recordDamage(battle,target,source,hero,damage){if(!battle?.ledger||target.training)return;const actual=Math.max(0,Math.min(damage,target.hp));if(target.team==='enemy'){const key=source===hero?'heroDamage':source?.defense?'defenseDamage':source?.team==='ally'?'troopDamage':null;if(key)tally(battle,key,actual);}else if(target===hero)tally(battle,'damageTaken',actual);}
export function recordKill(battle,target,source,hero){if(!battle?.ledger||target.training)return;if(target.team==='enemy'){tally(battle,'kills');tally(battle,source===hero?'heroKills':source?.defense?'defenseKills':'troopKills');}else if(target.team==='ally')tally(battle,'lost');}
const finite=(x,max=1e9)=>Number.isFinite(x)&&x>=0&&x<=max;
const validItem=i=>i&&typeof i.id==='string'&&i.id.length<100&&typeof i.name==='string'&&i.name.length<200&&Object.hasOwn({...WEAPONS,armor:1,shield:1,relic:1},i.type)&&Number.isInteger(i.rarity)&&i.rarity>=0&&i.rarity<=4&&Number.isInteger(i.level)&&i.level>=1&&i.level<=30&&Number.isInteger(i.plus)&&i.plus>=0&&i.plus<=10&&finite(i.base,10000)&&(!i.affix||Object.hasOwn(AFFIXES,i.affix))&&(!i.rune||['ember','frost','vital'].includes(i.rune))&&(!i.temper||['swift','sunder','guard'].includes(i.temper))&&(i.armorKind===undefined||i.type==='armor'&&Object.hasOwn(ARMORS,i.armorKind));
export function validateBattleLedger(ledger){if(ledger===undefined)return;if(!ledger||ledger.version!==1||!Number.isInteger(ledger.startLevel)||ledger.startLevel<1||ledger.startLevel>30||LEDGER_KEYS.some(k=>!finite(ledger[k])))throw Error('Invalid battle statistics.');if(!Array.isArray(ledger.chests)||ledger.chests.length>5||new Set(ledger.chests.map(c=>c?.id)).size!==ledger.chests.length)throw Error('Invalid battle chests.');for(const c of ledger.chests){if(typeof c.id!=='string'||c.id.length>100||!Number.isInteger(c.rarity)||c.rarity<0||c.rarity>4||typeof c.secured!=='boolean'||!c.pos||['x','y','z'].some(k=>!Number.isFinite(c.pos[k])||Math.abs(c.pos[k])>1000)||!c.rewards||!finite(c.rewards.supplies,10000)||!finite(c.rewards.salvage,10000)||!Array.isArray(c.rewards.items)||c.rewards.items.length<1||c.rewards.items.length>2||c.rewards.items.some(i=>!validItem(i)))throw Error('Invalid battle chest contents.');}if(!Array.isArray(ledger.foundItems)||ledger.foundItems.length>20||ledger.foundItems.some(i=>!validItem(i)))throw Error('Invalid field loot.');}
export function validateBattleReport(report){if(report==null)return;if(report.version!==1||typeof report.id!=='string'||report.id.length>100||!MISSIONS[report.mission]||typeof report.win!=='boolean'||typeof report.acknowledged!=='boolean'||typeof report.reason!=='string'||report.reason.length>500||!finite(report.time,1e7)||!Array.isArray(report.chests)||report.chests.length>5||!Array.isArray(report.items)||report.items.length>30||report.items.some(i=>!validItem(i))||!Array.isArray(report.revealed)||report.revealed.some(id=>!report.chests.some(c=>c.id===id)))throw Error('Invalid battle report.');if(!Number.isInteger(report.mission)||typeof report.first!=='boolean'||typeof report.camp!=='boolean'||!finite(report.lostChests,5)||!Array.isArray(report.research)||report.research.length>4||report.research.some(id=>!Object.hasOwn(RESEARCH,id))||report.chests.some(c=>typeof c.recovered!=='boolean'||!finite(c.converted,100)||!Array.isArray(c.grantedItemIds)||c.grantedItemIds.some(id=>!c.rewards?.items?.some(i=>i.id===id))))throw Error('Invalid reward settlement.');validateBattleLedger(report.stats);validateBattleLedger({...report.stats,chests:report.chests,foundItems:[]});for(const k of ['supplies','salvage','xp','gate','maxGate','beacon','survivors','waves','endLevel'])if(!finite(report[k]))throw Error('Invalid battle report values.');}
