import {strategySnapshot,removeUnavailablePerks} from './strategy-progression.js';
import {ensureWar,warSnapshot,advanceWar} from './war-campaign.js';
import {exaltedRarity} from './equipment-style.js';
import {createUnlockReview} from './unlocks.js';
import {makeItem,heroData,completeMission} from './state.js';
import {newBattleLedger,tally} from './battle-record.js';
import {MISSIONS} from './data.js';
import {territoryIncomeSources} from './campaign.js';
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
export const dropChance=type=>type==='boss'?1:['brute','knight','mage'].includes(type)?.18:.08;
export function rollBattleChest(save,battle,enemy,rand=Math.random){if(!battle?.ledger||enemy.training||battle.ledger.chests.length>=5||rand()>=dropChance(enemy.type))return null;const n=rand(),rarity=Math.max(enemy.type==='boss'?2:0,n<.55?0:n<.85?1:n<.97?2:n<.995?3:4),types=['sword','spear','hammer','bow','staff','armor','armor','armor','shield','relic'];const c={id:uid(),rarity,pos:{x:enemy.pos.x,y:enemy.pos.y,z:enemy.pos.z},secured:false,rewards:{supplies:35+rarity*25+(MISSIONS[battle.id].kind==='relief'?MISSIONS[battle.id].unlockMain:battle.id)*2,salvage:5+rarity*3,items:Array.from({length:rarity>=3?2:1},()=>makeItem(types[Math.min(types.length-1,Math.floor(rand()*types.length))],save.completed.length>=12?exaltedRarity(save,rand(),rarity):rarity,heroData(save).level,rand))}};battle.ledger.chests.push(c);return c;}
export function grantChest(save,chest){save.supplies+=chest.rewards.supplies;save.salvage+=chest.rewards.salvage;let converted=0;const items=[];for(const item of chest.rewards.items){if(save.inventory.some(i=>i.id===item.id))continue;if(save.inventory.length>=160){const amount=6+item.rarity*5;save.salvage+=amount;converted+=amount;}else{save.inventory.push(structuredClone(item));items.push(item);}}return {items,converted};}
export function settleBattle(save,battle,win,{reason='',survivors=0}={}){battle.reportID||=uid();if(save.lastBattle?.id===battle.reportID)return save.lastBattle;ensureWar(save);const warBefore=warSnapshot(save),openBefore=MISSIONS.filter(m=>['settlement','fortress'].includes(m.kind)&&(m.kind==='settlement'?save.completed.includes(m.unlockMain):save.completed.length===24&&save.war.captured.length===8)).map(m=>m.id);const ledger=battle.ledger||newBattleLedger(heroData(save).level),before={supplies:save.supplies,salvage:save.salvage,completed:save.completed.length,strategy:strategySnapshot(save)},mission=win?completeMission(save,battle.id,{inProgress:true}):null,chests=ledger.chests.filter(c=>win||c.secured).map(c=>({...structuredClone(c),recovered:!c.secured,secured:true}));for(const c of chests){const granted=grantChest(save,c);c.converted=granted.converted;c.grantedItemIds=granted.items.map(i=>i.id);}
 // Resolve conquests, failed reliefs and invasion deadlines before paying the new day.
 const war=advanceWar(save,MISSIONS[battle.id],win,warBefore),incomeSources=territoryIncomeSources(save),income=incomeSources.reduce((sum,row)=>sum+row.amount,0);
 save.supplies+=income;removeUnavailablePerks(save);
 const report={version:1,id:battle.reportID||uid(),mission:battle.id,win,reason,first:!!mission?.first,income,incomeSources,war,rescued:!!mission?.rescued,acknowledged:false,celebrated:!win,time:battle.time,stats:structuredClone(ledger),gate:battle.gate,maxGate:battle.maxGate,beacon:battle.core,waves:win?MISSIONS[battle.id].waves:Math.max(0,battle.wave-(battle.enemiesRemaining>0?1:0)),survivors,endLevel:heroData(save).level,xp:ledger.xp+(win?MISSIONS[battle.id].xp:0),supplies:ledger.supplies+save.supplies-before.supplies,salvage:ledger.salvage+save.salvage-before.salvage,items:[...ledger.foundItems,...(mission?.item?[mission.item]:[])],chests,revealed:[],lostChests:ledger.chests.length-chests.length,research:(battle.research||[]).filter(r=>r.complete).map(r=>r.id),camp:!!battle.camp,...(battle.siege?{siege:structuredClone(battle.siege)}:{})};report.war.opened=MISSIONS.filter(m=>['settlement','fortress'].includes(m.kind)&&(m.kind==='settlement'?save.completed.includes(m.unlockMain):save.completed.length===24&&save.war.captured.length===8)&&!openBefore.includes(m.id)).map(m=>m.id);report.tutorial=createUnlockReview(save,before,report);save.lastBattle=report;save.battle=null;return report;}
export function revealChest(save,id){const report=save.lastBattle;if(!report?.chests.some(c=>c.id===id))throw Error('Chest is not in this battle report.');if(!report.revealed.includes(id)){report.revealed.push(id);const q=report.tutorial;if(q&&!q.complete)for(const i of report.chests.find(c=>c.id===id).rewards.items)if(q.cards.length<24&&!q.cards.some(c=>c.kind==='item'&&c.id===i.id))q.cards.push({kind:'item',id:i.id});}return report.chests.find(c=>c.id===id);}
export function acknowledgeReport(save){if(save.lastBattle){save.lastBattle.revealed=save.lastBattle.chests.map(c=>c.id);save.lastBattle.acknowledged=true;}}
