import {MISSIONS} from './data.js';
import {missionUnlocked,missionWon,missionLockReason,nextCampaignMission,territoryIncome} from './campaign.js';
import {nextDefense,daysToAttack,raidFor,daysToRaid,campaignComplete,TOWN_IDS} from './war-campaign.js';
const base=()=>import.meta.env?.BASE_URL||'/';
const glyph=kind=>'<svg viewBox="0 0 40 40" aria-hidden="true">'+(kind==='mill'?'<path d="M17 18h8l3 19H13ZM21 18 8 4 5 9 21 22 35 8 30 4ZM21 18 7 32 12 36 25 20 35 32 38 27Z"/>':kind==='port'?'<path d="M5 29h30l-6 8H12ZM21 3v26M19 7 5 24h14ZM24 10v14h12Z"/>':kind==='fortress'?'<path d="M3 37V16L9 3l6 13v6h5V8l4-7 4 7v14h5v-9l5 6v18ZM17 37V27h10v10Z"/>':'<path d="M7 36V15H4V6h5v5h5V6h5v9h-3v7h9v-7h-3V6h5v5h5V6h5v9h-3v21ZM16 36V25h10v11Z"/>')+'</svg>';
const dayText=n=>n+' day'+(n===1?'':'s');
const townName=id=>MISSIONS[id]?.name||'Hearthwatch';
export function warUrgency(s){const days=daysToAttack(s),raid=[...(s.war?.raids||[])].sort((a,b)=>a.deadline-b.deadline)[0];if(campaignComplete(s))return 'The Hollow March is over';if(days===0)return 'Hearthwatch is under attack';if(raid)return townName(raid.town)+' invaded in '+dayText(daysToRaid(s,raid));return days===null?'Take the war to the Obsidian Crown':'Hearthwatch attacked in '+dayText(days);}
function homePanel(s,reveal=false){const next=nextDefense(s),days=daysToAttack(s),pips=Array.from({length:24},(_,i)=>'<i class="'+(s.completed.includes(i)?'held':i===next?'next':'')+(reveal&&s.lastBattle?.war&&i>=s.lastBattle.war.defensesBefore&&i<s.lastBattle.war.defensesAfter?' recent':'')+'" title="Assault '+(i+1)+(s.completed.includes(i)?' repelled':'')+'"></i>').join('');return '<section class="war-home '+(days!==null&&days<=1?'urgent':'')+'"><div class="home-crest">'+glyph('city')+'</div><div class="home-description"><small>HEARTHWATCH · YOUR CASTLE</small><b>'+(days===null?'All 24 assaults repelled':days===0?'The enemy has reached our walls':dayText(days)+' until the next attack')+'</b><div class="defense-pips" aria-label="'+s.completed.length+' of 24 defenses completed">'+pips+'</div></div><span class="home-score">'+s.completed.length+'<small>/ 24 defended</small></span>'+(!reveal&&next!==undefined?'<button data-action="map-next" data-id="'+next+'">'+(days===0?'Defend now':'Prepare defense')+' ›</button>':'')+'</section>';}
const regions=[[[15,64],[27,59],[35,69],[33,86],[16,89]],[[34,70],[45,66],[54,77],[47,91],[33,86]],[[48,47],[63,45],[69,61],[56,72],[47,64]],[[29,19],[43,12],[51,24],[48,36],[35,38],[27,30]],[[68,52],[82,48],[93,58],[91,77],[75,79],[67,65]],[[24,38],[36,33],[49,39],[46,55],[32,62],[23,51]],[[68,30],[81,26],[91,37],[83,49],[69,46]],[[55,11],[68,7],[79,16],[73,29],[59,29]]];
export function campaignMap(s,{selected=24,reveal=false,events=null}={}){
 const raids=s.war?.raids||[],nodes=MISSIONS.filter(m=>['settlement','fortress'].includes(m.kind));
 const regionsSVG=regions.map((r,i)=>{const id=24+i,held=s.settlements.includes(id),raid=raidFor(s,id),changed=events&&(events.captured===id||events.relieved===id);return '<polygon class="war-region '+(held?'held':'hostile')+(raid?' threatened':'')+(changed?' reclaimed':'')+'" points="'+r.map(([x,y])=>x*10+','+y*6.67).join(' ')+'"/>';}).join('');
 const roads=TOWN_IDS.map((id,i)=>{const a=i===0?[10,73]:MISSIONS[TOWN_IDS[i-1]].map,b=MISSIONS[id].map;return '<path class="war-road '+(s.war?.captured.includes(id)?'travelled':'')+'" d="M'+a[0]*10+' '+a[1]*6.67+' Q'+a[0]*10+' '+b[1]*6.67+' '+b[0]*10+' '+b[1]*6.67+'"/>';}).join('');
 const armies=raids.map(r=>{const p=MISSIONS[r.town].map;return '<path class="invasion-route" d="M910 180 Q'+((p[0]*10+910)/2)+' '+(p[1]*6.67-60)+' '+p[0]*10+' '+p[1]*6.67+'"/>';}).join('');
 return '<div class="atlas-scroll war-map-frame"><div class="campaign-atlas war-atlas" style="background-image:url('+base()+'maps/hollow-march.webp)"><svg class="war-cartography" viewBox="0 0 1000 667" preserveAspectRatio="none" aria-hidden="true">'+regionsSVG+roads+armies+'</svg><div class="war-map-home" style="left:10%;top:73%">'+glyph('city')+'<span>Hearthwatch</span></div>'+nodes.map(m=>{const held=missionWon(s,m),raid=raidFor(s,m.id),known=m.kind==='fortress'||s.completed.includes(m.unlockMain)||held,changed=events&&(events.captured===m.id||events.relieved===m.id),opened=events?.opened.includes(m.id);return '<button class="atlas-node '+(m.id===32?'enemy-fortress ':'')+(held?'rescued ':'')+(!known?'locked ':'')+(raid?'besieged ':'')+(changed?'newly-held ':'')+(opened?'new-route ':'')+(selected===m.id?'selected ':'')+'" '+(reveal?'data-war-select':'data-action="map-select" data-id')+'="'+m.id+'" style="left:'+m.map[0]+'%;top:'+m.map[1]+'%" aria-label="'+m.name+', '+(raid?'invasion in '+dayText(daysToRaid(s,raid)):held?'held':known?'enemy held':'unexplored')+'" aria-pressed="'+(selected===m.id)+'">'+glyph(m.icon)+(raid?'<em>'+daysToRaid(s,raid)+'d</em>':held?'<i>✓</i>':!known?'<em>◇</em>':'')+'<span>'+m.name+'</span></button>';}).join('')+'<div class="war-map-compass">N<br>✧</div></div><div class="war-map-legend"><span>● Held</span><span>● Enemy</span><span>◌ Unexplored</span>'+(raids.length?'<strong>⚑ Invasion route</strong>':'')+'</div></div>';
}
function selectedDetail(s,id,reveal=false){
 const m=MISSIONS[id]||nextCampaignMission(s,MISSIONS),home=m.kind==='main',town=m.kind==='relief'?m.town:m.id,raid=raidFor(s,town),target=raid?MISSIONS[town+9]:m,held=missionWon(s,m),available=missionUnlocked(s,target),complete=campaignComplete(s);
 const heading=home?'Hearthwatch':townName(town),status=home?'HOME DEFENSE · ASSAULT '+(m.id+1):raid?'INVADING ARMY · '+dayText(daysToRaid(s,raid)).toUpperCase():m.id===32?'FINAL SIEGE · THE HOLLOW KING':held?'LIBERATED TOWN':'ENEMY OCCUPATION';
 return '<aside class="war-detail '+(raid?'urgent':'')+'"><small>'+status+'</small><h2>'+heading+'</h2>'+(home?'<p>Repel the army from '+m.name+'. All defenses take place at your castle.</p><div class="war-detail-facts"><b>'+m.waves+' waves</b><span>'+(m.boss?m.bossName:'Protect the gate & beacon')+'</span></div>':raid?'<p>Defeat '+target.waves+' invading waves to protect this town and its tribute.</p><div class="war-detail-facts"><b>'+daysToRaid(s,raid)+' mission'+(daysToRaid(s,raid)===1?'':'s')+' left</b><span>Lose the town if the army reaches it.</span></div>':m.id===32?'<p>'+(complete?'The Hollow King and his fortress are gone. Every town stands free, and Hearthwatch is safe.':'Breach the fortress gate to draw out the Hollow King. Destroy him and his keep to end the war.')+'</p><div class="war-checklist"><span class="'+(s.completed.length===24?'done':'')+'">'+s.completed.length+'/24 Hearthwatch defenses</span><span class="'+(s.settlements.length===8?'done':'')+'">'+s.settlements.length+'/8 towns held</span><span class="'+(!s.war?.raids.length?'done':'')+'">'+(s.war?.raids.length||0)+' invading armies</span></div>':'<p>'+m.story+'</p><div class="war-detail-facts"><b>+'+m.income+' Supplies</b><span>Each home-defense victory while held.</span></div>')+(complete?'<div class="war-complete">THE KINGDOM IS FREE</div>':!available?'<p class="war-lock">'+missionLockReason(s,target)+'</p>':reveal?'':'<button class="primary" data-action="embark" data-id="'+target.id+'">'+(home?'Prepare defense':raid?'Intercept army':held?'Replay siege':'Plan siege')+' ›</button>')+'<small class="war-day-rule">Every battle advances 1 day.<br>Exploring town and menus does not.</small></aside>';
}
export function campaignPage(ui){const s=ui.g.store.data,next=nextCampaignMission(s,MISSIONS),selected=ui.selectedMission,m=MISSIONS[selected],node=m?.kind==='relief'?m.town:selected;return '<div class="war-heading"><div><small>THE HOLLOW MARCH</small><b>Day '+(s.war?.day||1)+'</b></div><p>'+warUrgency(s)+'</p><span>'+s.settlements.length+'/8 towns · +'+territoryIncome(s)+' Supplies</span></div>'+homePanel(s)+'<div class="war-layout">'+campaignMap(s,{selected:node})+selectedDetail(s,selected)+'</div>'+(next.id!==selected?'<button class="war-recommend" data-action="map-next" data-id="'+next.id+'">Recommended: '+(next.kind==='main'?'Defend Hearthwatch':next.name)+' ›</button>':'');}
export function campaignReveal(s,selected){const r=s.lastBattle,e=r.war,next=nextCampaignMission(s,MISSIONS),focus=selected??e?.captured??e?.relieved??e?.raidsAdded[0]??e?.opened[0]??(next.kind==='relief'?next.town:next.id),completed=campaignComplete(s);const headline=completed?'The kingdom is free':e?.lost.length?'The frontier has changed':e?.captured!==null&&e?.captured!==undefined?townName(e.captured)+' is free':e?.relieved!==null&&e?.relieved!==undefined?townName(e.relieved)+' is safe':r.win?'Your kingdom endures':'The war continues';
 const changes=[e?.defensesAfter>e?.defensesBefore?'Assault '+e.defensesAfter+' repelled':null,e?.captured?townName(e.captured)+' liberated':null,e?.relieved?townName(e.relieved)+' invasion defeated':null,...(e?.lost||[]).map(id=>townName(id)+' lost · retake its castle'),...(e?.raidsAdded||[]).map(id=>townName(id)+' threatened · 3 days'),...(e?.opened||[]).map(id=>'New route: '+townName(id))].filter(Boolean);
 return '<header class="war-reveal-header"><div><small>THE HOLLOW MARCH · CAMPAIGN REPORT</small><h1>'+headline+'</h1></div><div class="war-day-turn">'+(e?'<span>Day '+e.fromDay+'</span><em>→</em>':'')+'<b>Day '+(e?.toDay||s.war?.day||1)+'</b></div><button data-unlock="skip-map" aria-label="Skip map animation">Skip animation</button></header>'+homePanel(s,true)+'<main class="war-reveal-main">'+campaignMap(s,{selected:focus,reveal:true,events:e})+selectedDetail(s,focus,true)+'</main><div class="war-changes" role="status">'+(changes.length?changes.map(t=>'<span>'+t+'</span>').join(''):'<span>'+warUrgency(s)+'</span>')+'</div><footer><span>'+s.completed.length+'/24 defenses · '+s.settlements.length+'/8 towns · '+(s.fortresses.includes(32)?'King defeated':'King undefeated')+'</span><div><button data-unlock="back">‹ Rewards</button><button class="primary" data-unlock="go" data-id="campaign">'+(completed?'Return to Hearthwatch':'Return home · Find Sera')+'</button></div></footer>';
}
export function centerMap(){} // The entire strategic map now fits its panel; no pan needed.
