import {MISSIONS,ENEMIES} from './data.js';
import {MAIN_COUNT,missionUnlocked,territoryIncome,rosterIntel,REGIONAL_LOOT} from './campaign.js';
import {WEAPON_PATTERNS} from './weapon-patterns.js';
const base=()=>import.meta.env?.BASE_URL||'/';
const glyph=kind=>'<svg viewBox="0 0 40 40" aria-hidden="true">'+(kind==='mill'?'<path d="M17 18h8l3 19H13ZM21 18 8 4 5 9 21 22 35 8 30 4ZM21 18 7 32 12 36 25 20 35 32 38 27Z"/>':kind==='port'?'<path d="M5 29h30l-6 8H12ZM21 3v26M19 7 5 24h14ZM24 10v14h12Z"/>':'<path d="M7 36V15H4V6h5v5h5V6h5v9h-3v7h9v-7h-3V6h5v5h5V6h5v9h-3v21ZM16 36V25h10v11Z"/>')+'</svg>';
export function campaignPage(ui){const s=ui.g.store.data,m=MISSIONS[ui.selectedMission]||MISSIONS[0],main=m.kind==='main',done=main?s.completed.includes(m.id):(s.settlements||[]).includes(m.id),available=missionUnlocked(s,m),next=MISSIONS.find(x=>x.kind==='main'&&!s.completed.includes(x.id))||MISSIONS[23];
 return '<div class="atlas-heading"><div><small>THE HOLLOW MARCH</small><b>'+s.completed.length+' / '+MAIN_COUNT+' main missions</b></div><div><small>RESCUED SETTLEMENTS</small><b>'+(s.settlements||[]).length+' / 8 · +'+territoryIncome(s)+' Supplies / victory</b></div><button data-action="map-next" data-id="'+next.id+'">Next mission ›</button></div><div class="atlas-layout"><div class="atlas-scroll" aria-label="Illustrated campaign map. Scroll to explore the continent."><div class="campaign-atlas" style="background-image:url('+base()+'maps/hollow-march.webp)"><svg class="atlas-routes" viewBox="0 0 1000 667" aria-hidden="true">'+MISSIONS.slice(1,MAIN_COUNT).map((m,i)=>'<path class="'+(s.completed.includes(i)?'open':'')+'" d="M'+MISSIONS[i].map[0]*10+' '+MISSIONS[i].map[1]*6.67+' L'+m.map[0]*10+' '+m.map[1]*6.67+'"/>').join('')+'</svg>'+MISSIONS.map(n=>{const side=n.kind==='settlement',won=side?(s.settlements||[]).includes(n.id):s.completed.includes(n.id),open=missionUnlocked(s,n);return '<button class="atlas-node '+(side?'settlement ':'')+(won?'rescued ':'')+(!open?'locked ':'')+(m.id===n.id?'selected ':'')+'" data-action="map-select" data-id="'+n.id+'" style="left:'+n.map[0]+'%;top:'+n.map[1]+'%" aria-label="'+n.name+(side?' optional settlement':' mission '+(n.id+1))+(won?', reclaimed':!open?', locked':'')+'" aria-pressed="'+(m.id===n.id)+'">'+glyph(n.icon)+(side?'':'<em>'+(n.id+1)+'</em>')+(won?'<i>✓</i>':'')+'<span>'+n.name+'</span></button>';}).join('')+'<div class="atlas-legend">◆ Campaign road &nbsp; ⚑ Optional settlements<br>Gold seals mark rescued territory</div></div></div><aside class="atlas-detail"><small>'+ (main?'ACT '+m.act+' · MISSION '+(m.id+1):'OPTIONAL SETTLEMENT')+'</small><h2>'+m.name+'</h2><button class="primary" data-action="embark" data-id="'+m.id+'" '+(!available?'disabled':'')+'>'+(available?done?'Replay mission':'Read briefing':main?'Complete mission '+m.id:'Complete mission '+(m.unlockMain+1))+'</button><p>'+m.story+'</p><div class="atlas-facts"><span>'+m.waves+' waves</span><span>Troop rank '+m.recommended+'</span><span>'+m.reward+' Supplies</span>'+(m.boss?'<span class="atlas-boss">'+m.bossName+'</span>':'')+'</div>'+(!main?'<div class="settlement-income"><b>+'+m.income+' Supplies</b><span>After every main-mission victory once rescued. Replays also pay tribute.</span></div>':'')+(m.introduced?'<h3>New enemy</h3><b>'+ENEMIES[m.introduced].name+'</b>':'')+'<details class="enemy-intel"><summary>Regional equipment</summary><p>'+ (REGIONAL_LOOT[m.biome]||REGIONAL_LOOT.plain).map(id=>WEAPON_PATTERNS[id].name).join(' · ')+'</p><p>First boss or settlement victory guarantees one Rare-or-better regional weapon. Replays: 35% regional reward chance. Other equipment can still drop in battle.</p></details>'+'<details class="enemy-intel"><summary>Enemy counters</summary>'+rosterIntel(m).map(t=>'<p>'+t+'</p>').join('')+'</details></aside></div>';
}
export function centerMap(ui){const el=document.querySelector('.atlas-scroll'),node=document.querySelector('.atlas-node.selected');if(el&&node){el.scrollLeft=node.offsetLeft-el.clientWidth*.5;el.scrollTop=node.offsetTop-el.clientHeight*.5;}}
