// Campaign IDs 0–14 are stable so existing journeys continue without losing progress.
export const MAIN_COUNT=24;
export const EXTRA_LOCATIONS=[
 ['The Pale Orchard','forest','What the crown concealed','Beyond Veyr’s throne, the trees flower with stolen memories. Hold the orchard beacon while Sera follows their roots.'],
 ['Starfall Observatory','quarry','A signal from the dark','The astronomers have found a second voice beneath the broken oath. Defend their instruments and recover its coordinates.'],
 ['Saltwind Bastion','desert','The fleet comes home','A refugee fleet needs the harbor beacon. Hold the coast against the Regent’s siege batteries.'],
 ['Winterglass Pass','snow','A mountain of mirrors','The Glass Regent turns our own beacons against us. Establish a light on the pass that his mirrors cannot command.'],
 ['The Mirror Citadel','snow','The Regent of Glass','Defeat the Glass Regent and free the winter cities from his reflections.'],
 ['The Unwritten Coast','river','An army without names','The original oath was sealed beneath the sea. Hold the newly revealed coast while the tide gives us a road.'],
 ['The Cinder Stair','quarry','Every fire has a beginning','The first beacon waits above the siege terraces. Protect the climbing parties from the Host’s oldest war machines.'],
 ['The Door of Names','forest','A door that opens both ways','All the rescued voices gather here. Keep their road open against the final counterattack.'],
 ['The First Ember','desert','Until every voice is free','Face the Hollow King, the will that taught Veyr to bind the dead. Hold the first beacon, defeat its keeper, and give every soul a choice.']
];
export const SETTLEMENTS=[
 {name:'Willowmill',biome:'plain',title:'Bread for the road',story:'Rescue the millers and reopen the valley’s grain road.',unlockMain:0,income:28,map:[26,72],icon:'mill'},
 {name:'Reedhaven',biome:'river',title:'The lantern harbor',story:'Free the river harbor so its traders can provision Hearthwatch.',unlockMain:2,income:42,map:[43,79],icon:'port'},
 {name:'Coppergate',biome:'quarry',title:'Hammers after midnight',story:'Reclaim the miners’ market and restore the copper caravans.',unlockMain:5,income:62,map:[57,59],icon:'city'},
 {name:'Whitepine',biome:'snow',title:'A hearth beneath the snow',story:'Break the winter blockade and bring the mountain families home.',unlockMain:8,income:80,map:[41,29],icon:'city'},
 {name:'Sunspire',biome:'desert',title:'The caravans return',story:'Rescue the oasis city and its golden road through the dunes.',unlockMain:11,income:102,map:[79,61],icon:'city'},
 {name:'Briarhaven',biome:'forest',title:'A garden worth defending',story:'Free the woodland refuge. Its herbalists will support each expedition.',unlockMain:14,income:126,map:[37,44],icon:'mill'},
 {name:'Greywake',biome:'river',title:'Sails on the horizon',story:'Reopen the coastal shipyards under the Regent’s siege.',unlockMain:17,income:152,map:[78,37],icon:'port'},
 {name:'Dawnmere',biome:'snow',title:'The city that remembers',story:'Rescue the last northern city and unite its people behind the first ember.',unlockMain:20,income:180,map:[69,20],icon:'city'}
];
const POS=[[19,76],[33,70],[48,60],[32,55],[22,48],[62,69],[53,74],[45,20],[22,33],[76,71],[26,58],[52,50],[65,60],[59,23],[60,39],[39,50],[52,36],[82,54],[66,30],[77,26],[82,41],[72,47],[79,18],[89,11]];
const INTRO={0:'hollow',1:'archer',2:'runner',3:'knight',5:'bomber',6:'herald',7:'longbow',8:'brute',10:'bulwark',12:'mender',14:'mage',16:'reaver',18:'mortar',20:'wraith',22:'warpriest'};
export const ENEMY_INTEL={
 hollow:'Infantry · modest health, vulnerable to flanking.',archer:'Bone archers · block their arrows and close the distance.',runner:'Raven runners · rush past the front. Pikeguard and slows stop them.',knight:'Iron revenants · armored melee. Charged strikes strip their guard.',bomber:'Cinder bombers · lob timed bombs at a marked location. Leave the orange circle before detonation.',herald:'War heralds · nearby enemies gain damage and speed. Hunt the banner bearer first.',longbow:'Blackfeather hunters · long range, slow powerful arrows. Use cover and rush between shots.',brute:'Siege brutes · heavy armor and large health pools. Focus ballistae and armor piercing troops.',bulwark:'Grave bulwarks · front shields absorb most direct hits. Flank them or break the guard with a charged attack.',mender:'Bone menders · heal injured enemies every six seconds. Separate them from their escort.',mage:'Grave callers · cold bolts slow your movement. Keep your distance from the front line.',reaver:'Blood reavers · become faster and strike harder below half health. Finish one before wounding the next.',mortar:'Ash mortars · bombard large areas from long range. Dodge the red warning rings and attack the crew.',wraith:'Mirror wraiths · briefly phase toward nearby targets. Their violet arrival ring reveals the landing.',warpriest:'Hollow warpriests · protect and heal an escort. Kill the priest to collapse its formation.'};
export function decorateMissions(locations){return [...locations,...EXTRA_LOCATIONS].map(([name,biome,title,story],id)=>{const act=1+Math.floor(id/5),boss=[4,9,14,19,23].includes(id),bossIndex=[4,9,14,19,23].indexOf(id);return {id,name,biome,title,story,kind:'main',act:Math.min(5,act),boss,bossName:['The Bell Knight','The Ash Castellan','Marshal Veyr','The Glass Regent','The Hollow King'][bossIndex],bossMusic:['bell','castellan','veyr','regent','hollow'][bossIndex],waves:id<5?3:id<10?4:id<18?5:6,reward:180+id*55,xp:115+id*32,scale:id<6?.85+id*.07:id<10?1.25+(id-6)*.105:1.7+(id-10)*.105,seed:7919+id*3511,map:POS[id],introduced:INTRO[id]||null,recommended:Math.min(10,1+Math.floor(id/2.5))};}).concat(SETTLEMENTS.map((m,i)=>({...m,id:MAIN_COUNT+i,kind:'settlement',act:Math.min(5,1+Math.floor(m.unlockMain/5)),boss:false,waves:3+Math.floor(i/3),reward:220+i*70,xp:130+i*60,scale:1+m.unlockMain*.085,seed:90217+i*3511,recommended:Math.min(10,2+i)})));}
export function missionUnlocked(s,m){return m.kind==='settlement'?s.completed.includes(m.unlockMain):m.id===0||s.completed.includes(m.id-1);}
export function territoryIncome(s){return (s.settlements||[]).reduce((n,id)=>n+(SETTLEMENTS[id-MAIN_COUNT]?.income||0),0);}
export function missionRoster(m,wave=1){const stage=m.kind==='settlement'?m.unlockMain+1:m.id,unlocked=Object.entries(INTRO).filter(([id])=>Number(id)<=stage).map(([,type])=>type);let count=stage<6?6+wave+Math.floor(stage*.65):stage<10?10+wave+Math.floor((stage-6)*.8):15+wave*2+Math.floor((stage-10)*1.25);const roster=[];for(let i=0;i<count;i++){let type=i%3===0?'hollow':unlocked[(i+Math.floor(i/3)+wave*3)%unlocked.length];if(type==='brute'&&roster.filter(t=>t==='brute').length>2)type='knight';if(['herald','mender','warpriest','mortar'].includes(type)&&roster.includes(type))type=i%2?'knight':'archer';roster.push(type);}if(m.introduced&&wave===1)roster[Math.min(3,roster.length-1)]=m.introduced;return roster;}
export function rosterIntel(m){return [...new Set(missionRoster(m,1))].filter(t=>t!=='hollow').map(t=>ENEMY_INTEL[t]);}

export const REGIONAL_LOOT={plain:['dawnfang','oathbell'],river:['tidecaller','stormlance'],forest:['briarthorn','pyrecrown'],quarry:['faultbreaker','emberbrand'],snow:['rimespire','starsong'],desert:['emberbrand','stormlance']};
