import * as T from 'three';
import {makeMount} from './mount.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {mesh,box,cyl,beam,mat,weapon,shield,sunBadge,compactRigid} from './art.js';
const CACHE=new Map();let CLIPS=[];
export async function loadCharacters(progress=()=>{}){const loader=new GLTFLoader();const names=['Knight','Mage','Rogue_Hooded','Barbarian','Skeleton_Warrior','Skeleton_Mage','Skeleton_Rogue','Skeleton_Minion'];let done=0;await Promise.all(names.map(async name=>{const asset=await loader.loadAsync(import.meta.env.BASE_URL+'models/'+name+'.glb');asset.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;}});const skins=[];asset.scene.traverse(o=>{if(o.isSkinnedMesh)skins.push(o);});if(skins.length>1&&skins.every(s=>s.material===skins[0].material)){const g=mergeGeometries(skins.map(s=>s.geometry),false);if(g){const m=new T.SkinnedMesh(g,skins[0].material);m.name=name+'_UnifiedBody';m.bind(skins[0].skeleton,skins[0].bindMatrix);m.castShadow=true;m.receiveShadow=true;m.frustumCulled=false;skins[0].parent.add(m);skins.forEach(s=>s.removeFromParent());}}
 if(name==='Knight'){CLIPS=asset.animations.map(c=>{const clip=c.clone();clip.tracks=clip.tracks.filter(t=>!t.name.includes('IK')&&!t.name.includes('control-')&&!t.name.includes('heelIK'));for(const tr of clip.tracks)if(tr.name==='root.position'){for(let i=0;i<tr.values.length;i+=3){tr.values[i]=0;tr.values[i+2]=0;}}return clip;});}CACHE.set(name,asset.scene);progress(++done/names.length);}));}
export class Character{
 constructor(model='Knight',options={}){this.root=new T.Group();this.visual=clone(CACHE.get(model));this.root.add(this.visual);this.model=model;this.color=options.color||0x527f79;this.rank=options.rank||1;this.enemy=!!options.enemy;this.weaponType=options.weapon||'sword';this.height=options.height||2.0;this.sockets={};this.gear=[];this.phase=0;this.actionLock=0;this.actionName='';this.materials=[];
 this.visual.traverse(o=>{if(o.isBone)this.sockets[o.name]=o;if(o.isMesh){o.castShadow=true;o.receiveShadow=true;const materials=Array.isArray(o.material)?o.material:[o.material];const copies=materials.map(m=>{const c=m.clone();c.roughness=.68;c.metalness=.12;if(this.enemy&&c.emissive)c.emissive.setHex(0x55341c);this.materials.push(c);return c;});o.material=Array.isArray(o.material)?copies:copies[0];if(!o.isSkinnedMesh)o.visible=false;}});
 this.visual.updateMatrixWorld(true);const b=new T.Box3();this.visual.traverse(o=>{if(o.isSkinnedMesh)b.union(new T.Box3().setFromObject(o));});const size=b.getSize(new T.Vector3());this.factor=this.height/Math.max(size.y,1);this.visual.scale.set(this.factor*.84,this.factor*1.15,this.factor*.84);this.visual.position.y=-b.min.y*this.factor;
 this.mixer=new T.AnimationMixer(this.visual);this.actions=Object.fromEntries(CLIPS.map(c=>[c.name,this.mixer.clipAction(c)]));this.current=null;this.play('Idle',.0);this.updateGear(this.weaponType,this.rank,this.color,options.temper);this.root.userData.character=this;this.mounted=!!options.mounted;if(this.mounted){this.mount=makeMount(this.rank,this.color);this.root.add(this.mount);this.visual.position.y+=.90;}
 }
 attach(bone,obj){const parent=this.sockets[bone]||this.sockets[bone.replaceAll('.','')]||this.sockets[bone.replaceAll('.','_')]||this.visual;parent.add(obj);this.gear.push(obj);return obj;}
 updateGear(type=this.weaponType,rank=this.rank,color=this.color,temper=null){for(const obj of this.gear)obj.removeFromParent();this.gear=[];this.weaponType=type;this.rank=rank;this.color=color;const steel=mat(rank>=8?0xa6bab3:0x869b9c,.32,.72),gold=mat(0xcaa85e,.28,.7),cloth=mat(color,.87,0,{side:T.DoubleSide});
 this.held=compactRigid(weapon(type,rank,color,temper));this.held.rotation.y=Math.PI;this.attach('handslot.r',this.held);
 if(type==='sword'||type==='spear'){this.heldShield=compactRigid(shield(rank,color));this.heldShield.rotation.y=Math.PI;this.heldShield.rotation.z=-Math.PI/2;this.heldShield.position.set(0,-.02,.05);this.attach('handslot.l',this.heldShield);}else this.heldShield=null;
 const helmet=this.visual.getObjectByName(this.model==='Knight'?'Knight_Helmet':this.model.startsWith('Skeleton')?'Skeleton_Warrior_Helmet':'');if(helmet)helmet.visible=true;
 // Each level adds a distinct equipment silhouette, independent of tint.
 if(rank>=2){const belt=new T.Group();box(belt,[.48,.065,.28],[0,.07,0],mat(0x725334));box(belt,[.095,.09,.045],[0,.07,.155],gold);this.attach('hips',belt);}
 if(rank>=3){for(const side of ['l','r']){const p=new T.Group();const plate=mesh(new T.SphereGeometry(.16,10,5,0,Math.PI*2,0,Math.PI*.6),steel,p,0,-.08,0);plate.scale.set(1.18,.7,1);this.attach('upperarm.'+side,p);}}
 if(rank>=4){for(const side of ['l','r']){const p=new T.Group();cyl(p,.085,.065,.23,[0,-.1,0],steel,8);this.attach('lowerarm.'+side,p);}}
 if(rank>=5){const emblem=new T.Group();const b=sunBadge(emblem,.18,gold);b.position.set(0,.10,.18);this.attach('chest',emblem);}
 if(rank>=6){for(const side of ['l','r']){const p=new T.Group();box(p,[.13,.24,.065],[0,-.12,.10],steel);this.attach('lowerleg.'+side,p);}}
 if(rank>=7||!this.enemy){const cape=new T.Group();const geometry=new T.PlaneGeometry(rank>=7?.68:.54,rank>=7?1.05:.74,6,8);const cp=mesh(geometry,cloth,cape,0,-.25,-.22);cp.rotation.x=.17;cape.userData.cape=cp;this.cape=cp;this.capeBase=new Float32Array(geometry.attributes.position.array);if(rank>=7){const crest=sunBadge(cape,.20,gold);crest.position.set(0,-.12,-.25);crest.rotation.y=Math.PI;}this.attach('chest',cape);}
 if(rank>=8){const back=new T.Group();beam(back,[-.23,-.3,-.20],[-.23,.92,-.20],.014,gold);const f=mesh(new T.PlaneGeometry(.42,.25,3,2),cloth,back,-.02,.78,-.20);this.attach('chest',back);}
 if(rank>=9){const wings=new T.Group();for(const s of [-1,1]){const w=mesh(new T.ConeGeometry(.065,.27,4),gold,wings,s*.20,.10,0);w.rotation.z=-s*.48;}this.attach('head',wings);}
 if(rank>=10){const crest=new T.Group();for(let i=0;i<6;i++){const p=mesh(new T.ConeGeometry(.045,.24,6),cloth,crest,0,.20+Math.sin(i/5*Math.PI)*.04,-.12+i*.043);p.rotation.x=-.35;}this.attach('head',crest);}
 if(this.enemy){const horn=new T.Group();for(const s of [-1,1]){const h=mesh(new T.ConeGeometry(.08,.34,5),mat(0x5b5146,.5),horn,s*.2,.08,0);h.rotation.z=-s*.7;}if(this.height>2.5)this.attach('head',horn);}
 }
 play(name,fade=.14,once=false,duration=null){const action=this.actions[name]||this.actions.Idle;if(!action)return;if(this.current===action&&!once)return;action.reset();action.paused=false;action.enabled=true;action.setEffectiveWeight(1);action.setEffectiveTimeScale(duration?action.getClip().duration/duration:1);action.setLoop(once?T.LoopOnce:T.LoopRepeat,once?1:Infinity);action.clampWhenFinished=once;if(this.current)this.current.fadeOut(fade);action.fadeIn(fade).play();this.current=action;this.actionName=name;this.actionLock=once?(duration||action.getClip().duration):0;}
 attack(type,heavy=false,combo=0,duration=.65){let clip;if(type==='bow'||type==='crossbow')clip='2H_Ranged_Shoot';else if(type==='staff')clip='Spellcast_Shoot';else if(type==='spear')clip=heavy?'2H_Melee_Attack_Stab':'1H_Melee_Attack_Stab';else if(type==='hammer')clip=heavy?'2H_Melee_Attack_Chop':'2H_Melee_Attack_Slice';else clip=heavy?'1H_Melee_Attack_Chop':['1H_Melee_Attack_Slice_Diagonal','1H_Melee_Attack_Slice_Horizontal','1H_Melee_Attack_Stab'][combo%3];this.play(clip,.07,true,duration);}
 cast(id,rank=1){this.casting={id,rank,t:0,duration:.45+rank*.08,seed:[...id].reduce((s,c)=>s+c.charCodeAt(0),0)};const clip=['rally','sunwall','bulwark','tether','seedward','grove','sanctuary'].includes(id)?'Spellcast_Raise':id==='forgefall'?'2H_Melee_Attack_Chop':rank>=3?'Spellcasting':rank===2?'Spellcast_Long':'Spellcast_Shoot';this.play(clip,.08,true,.45+rank*.08);}
 update(dt,{speed=0,grounded=true,guarding=false,charging=false,dead=false,strafe=0}={}){this.phase+=dt;if(this.mount)this.mount.userData.animate(this.phase,speed);this.actionLock=Math.max(0,this.actionLock-dt);if(!this.actionLock&&!dead){let name=this.mounted?'2H_Ranged_Aiming':charging?(this.weaponType==='bow'?'2H_Ranged_Aiming':'2H_Melee_Attack_Chop'):guarding?'Blocking':!grounded?'Jump_Idle':speed>.2?(speed>3.2?'Running_A':'Walking_A'):'Idle';this.play(name,.18);if(charging&&this.current){this.current.time=this.current.getClip().duration*.18;this.current.paused=true;}if(this.current&&speed>.2&&grounded&&!charging)this.current.timeScale=clampSpeed(speed/(speed>3.2?4.5:2.2));}if(this.poseAdjusted&&this.sockets.hips)this.sockets.hips.position.y-=.23;this.mixer.update(dt);this.poseAdjusted=true;if(this.casting){const c=this.casting;c.t+=dt;const f=Math.sin(Math.min(1,c.t/c.duration)*Math.PI);if(this.sockets.upperarmr)this.sockets.upperarmr.rotation.z+=Math.sin(c.seed)*.12*f*c.rank;if(this.sockets.upperarml)this.sockets.upperarml.rotation.x+=Math.cos(c.seed)*.15*f*c.rank;if(c.t>=c.duration)this.casting=null;}if(this.sockets.head)this.sockets.head.scale.setScalar(.62);for(const id of ['upperlegl','upperlegr'])if(this.sockets[id])this.sockets[id].scale.set(1,1.80,1);if(this.sockets.hips)this.sockets.hips.position.y+=.23;if(this.mounted){for(const id of ['upperlegl','upperlegr']){const b=this.sockets[id];if(b){b.rotation.x+=.20;b.rotation.z=id==='upperlegl'?.35:-.35;}}}if(this.cape){const p=this.cape.geometry.attributes.position;for(let i=0;i<p.count;i++){let y=this.capeBase[i*3+1],w=(.525-y)/1.05;p.array[i*3+2]=this.capeBase[i*3+2]-Math.sin(this.phase*4+y*5)*.04*w-speed*.018*w;p.array[i*3]=this.capeBase[i*3]+Math.sin(this.phase*2.6+y*7)*.025*w;}p.needsUpdate=true;this.cape.geometry.computeVertexNormals();}}
 muzzle(target=new T.Vector3()){this.root.updateMatrixWorld(true);(this.sockets['handslot.r']||this.sockets['handslotr']||this.visual).getWorldPosition(target);return target;}
 dispose(){this.mixer.stopAllAction();this.root.removeFromParent();this.materials.forEach(m=>m.dispose());}
}
const clampSpeed=x=>Math.max(.6,Math.min(x,1.7));
