import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {warChest,disposeChest,CHEST_COLORS} from './chest-model.js';
export class ChestReveal{
 constructor(canvas,game,chest,opened=false){this.canvas=canvas;this.g=game;this.chest=chest;this.opened=opened;this.alive=true;this.start=null;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.scene=new T.Scene();const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(this.renderer);this.environment=pmrem.fromScene(room,.04);this.scene.environment=this.environment.texture;pmrem.dispose();room.dispose();this.scene.add(new T.HemisphereLight(0xb8d4f2,0x3d2113,2));const key=new T.DirectionalLight(0xffd4a0,5);key.position.set(-3,6,4);this.scene.add(key);const fill=new T.DirectionalLight(0xadd8ff,2.5);fill.position.set(4,2,5);this.scene.add(fill);const rim=new T.DirectionalLight(CHEST_COLORS[chest.rarity],3);rim.position.set(3,3,-4);this.scene.add(rim);this.model=warChest(chest.rarity);this.scene.add(this.model);this.camera=new T.PerspectiveCamera(37,1,.1,40);this.camera.position.set(4.3,3.4,6.6);this.camera.lookAt(0,.9,0);this.model.rotation.y=-.22;
 this.floor=new T.Mesh(new T.CircleGeometry(2.8,48),new T.MeshBasicMaterial({color:0x06070b,transparent:true,opacity:.45}));this.floor.rotation.x=-Math.PI/2;this.floor.position.y=.05;this.scene.add(this.floor);
 const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=64;const ctx=glowCanvas.getContext('2d'),gradient=ctx.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'#fff7da');gradient.addColorStop(.15,'#ffe0a9');gradient.addColorStop(1,'#ffe0a900');ctx.fillStyle=gradient;ctx.fillRect(0,0,64,64);this.texture=new T.CanvasTexture(glowCanvas);
 this.light=new T.PointLight(CHEST_COLORS[chest.rarity],0,8);this.light.position.set(0,1.5,0);this.scene.add(this.light);this.particles=[];for(let i=0;i<40;i++){const p=new T.Sprite(new T.SpriteMaterial({map:this.texture,color:CHEST_COLORS[chest.rarity],transparent:true,opacity:0,blending:T.AdditiveBlending,depthWrite:false}));p.scale.setScalar(.07+(i%4)*.025);this.scene.add(p);this.particles.push(p);}
 this.glow=new T.Sprite(new T.SpriteMaterial({map:this.texture,color:CHEST_COLORS[chest.rarity],transparent:true,opacity:0,blending:T.AdditiveBlending,depthWrite:false}));this.glow.position.set(0,1.65,.1);this.glow.scale.set(4,4,1);this.scene.add(this.glow);
 if(opened){this.model.userData.lid.rotation.x=-1.7;this.model.userData.lock.visible=false;}this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.resize();this.loop(performance.now());}
 resize(){if(!this.alive)return;const r=this.canvas.getBoundingClientRect();if(!r.width||!r.height)return;this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.position.set(4.3,r.width/r.height>1.4?3.8:3.4,r.width/r.height<.8?8.8:6.6);this.camera.lookAt(0,1.0,0);this.camera.updateProjectionMatrix();}
 open(onDone){if(this.opened||this.start!==null)return;this.callback=onDone;this.start=performance.now();this.g.audio.play('chest-unlock');if(matchMedia('(prefers-reduced-motion: reduce)').matches)this.finish();}
 finish(){if(!this.alive)return;this.opened=true;this.start=null;this.model.userData.lid.rotation.x=-1.7;this.model.userData.lock.visible=false;this.light.intensity=2;this.glow.material.opacity=.28;const cb=this.callback;this.callback=null;cb?.();}
 loop(now){if(!this.alive)return;this.frame=requestAnimationFrame(t=>this.loop(t));const t=now/1000;this.model.rotation.y=-.22+(this.opened||this.reduced?0:Math.sin(t*.6)*.04);if(this.start!==null){const p=Math.min(1,(now-this.start)/1700),ease=1-Math.pow(1-Math.max(0,(p-.18)/.72),3);this.model.rotation.z=p<.24?Math.sin(p*100)*.015*(1-p/.24):0;this.model.userData.lock.position.y=1.18+Math.min(1,p*4)*.3;this.model.userData.lock.visible=p<.3;this.model.userData.lid.rotation.x=-1.7*Math.min(1,ease);this.light.intensity=Math.min(4,ease*4);this.glow.material.opacity=Math.min(.45,ease*.45);for(let i=0;i<this.particles.length;i++){const q=this.particles[i],a=i*2.4,u=Math.max(0,p-.23);q.position.set(Math.sin(a)*u*(1+(i%3)),1.3+u*(2+i%4)-u*u*2,Math.cos(a)*u*1.8);q.material.opacity=Math.min(.8,u*3)*(1-p*.6);}if(p>=1){this.g.audio.play('chest-reveal-'+this.chest.rarity);this.finish();}}
 else if(this.opened&&!this.reduced){this.glow.material.opacity=.2+Math.sin(t*1.2)*.025;for(let i=0;i<this.particles.length;i++){const p=this.particles[i],phase=(t*.25+i*.13)%1;p.position.set(Math.sin(i*2.4)*(.4+phase),1.3+phase*2,Math.cos(i*2.4)*(.3+phase));p.material.opacity=(1-phase)*.35;}}
 this.renderer.render(this.scene,this.camera);}
 dispose(){this.alive=false;cancelAnimationFrame(this.frame);this.observer.disconnect();disposeChest(this.model);for(const p of this.particles)p.material.dispose();this.glow.material.dispose();this.texture.dispose();this.floor.geometry.dispose();this.floor.material.dispose();this.environment.dispose();this.renderer.dispose();this.renderer.forceContextLoss();}
}
