import {triggerWeaponPower} from './weapon-powers.js';
import {weaponPower} from './weapon-patterns.js';
import {researchHit,researchOnHit} from './research-combat.js';
import {tally,recordDamage,recordKill} from './battle-record.js';
import {regimentHit} from './regiments.js';
import * as T from 'three';
import {Character} from './characters.js';
import {arrowMesh,mesh,mat} from './art.js';
import {WEAPONS,SPELLS,ENEMIES,UNITS,unitStats,defenseStats,HEROES} from './data.js';
import {heroStats,heroData,skillRank,equipped,grantXP} from './state.js';
const UP=new T.Vector3(0,1,0),forward=y=>new T.Vector3(Math.sin(y),0,Math.cos(y));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export class Combat{
 constructor(game){this.g=game;this.projectiles=[];this.zones=[];this.events=[];this.serial=0;this.stats={light:0,heavy:0,projectiles:0,hits:0,casts:{},guards:0};}
 clear(){for(const p of this.projectiles)p.model.removeFromParent();this.projectiles=[];this.zones=[];this.events=[];}
 later(delay,fn){this.events.push({t:delay,fn});}
 target(entity,max=40){const list=entity.team==='enemy'?[this.g.hero,...this.g.allies]:this.g.enemies;let best=null,d=max;for(const e of list){if(e.dead)continue;const n=dist(entity.pos,e.pos);if(n<d){d=n;best=e;}}return best;}
 aim(entity,range=35){if(entity===this.g.hero){const facing=new T.Vector3(-Math.sin(this.g.view.yaw),0,-Math.cos(this.g.view.yaw));let target=null,score=range;for(const e of this.g.enemies){if(e.dead)continue;const v=e.pos.clone().sub(entity.pos),d=v.length();if(d<range&&v.normalize().dot(facing)>.68&&d<score&&this.g.physics.lineClear(entity.pos.clone().addScaledVector(UP,1.2),e.pos.clone().addScaledVector(UP,1.2))){target=e;score=d;}}return target;}return this.target(entity,range);}
 attack(e,heavy=false){if(e.dead||e.cooldown>0)return false;const isHero=e===this.g.hero,s=isHero?this.g.heroStats():e.stats,type=isHero?s.weapon:e.weapon,w=WEAPONS[type]||WEAPONS.bow,stamina=heavy?22:3;if(isHero&&e.stamina<stamina){this.g.toast('Catch your breath — not enough stamina.');return false;}if(isHero)e.stamina-=stamina;const duration=w.speed*(heavy?1.45:1)/(s.attackSpeed||1)/(e.haste>0?1.18:1);e.cooldown=duration;e.attacking=true;e.actionTime=0;e.combo=(e.combo||0)+1;e.character.attack(type,heavy,e.combo,duration);const reach=isHero?w.reach:(s.reach||s.range||w.reach),target=this.aim(e,reach+2);if(target&&isHero){const d=target.pos.clone().sub(e.pos);e.facing=Math.atan2(d.x,d.z);}else if(isHero)e.facing=this.g.view.yaw+Math.PI;e.character.root.rotation.y=e.facing;
 if(isHero){this.stats[heavy?'heavy':'light']++;tally(this.g.battle,heavy?'heavy':'light');this.g.journey?.mark(heavy?'heavy':'light');}this.later(duration*(['bow','crossbow'].includes(type)?(heavy?.43:.30):heavy?.32:.18),()=>{if(!e.dead)this.g.audio.play(type==='staff'?'fireball':type,(isHero?1:.22)*(heavy?1.2:.78),{position:e.pos,heavy,rank:type==='staff'?Math.max(1,skillRankSafe(this.g,'fireball')):1});});
 this.later(duration*(heavy?.43:.30),()=>{if(e.dead)return;const damage=(s.damage||18)*(heavy?w.heavy*(1+(s.heavyBonus||0)):1)*(e.buff>0?1.15:1)*(e.empowered>0?1.3:1);e.empowered=0;if(['bow','crossbow','staff'].includes(type)){this.shoot(e,target,{damage,type:type==='staff'?'fire':type==='crossbow'?'bolt':'arrow',speed:heavy?35:27,heavy,rank:Math.max(1,skillRankSafe(this.g,'fireball'))});}else{let hits=0;const candidates=e.team==='enemy'?[this.g.hero,...this.g.allies]:this.g.enemies;const f=forward(e.facing);for(const t of candidates){if(t.dead)continue;const v=t.pos.clone().sub(e.pos),d=v.length();if(d<reach+(t.stats.scale||1)*.4&&Math.abs(v.y)<2.5&&v.normalize().dot(f)>(heavy&&type==='hammer'?-.1:type==='spear'?.73:.28)&&this.g.physics.lineClear(e.pos.clone().addScaledVector(UP,1.1),t.pos.clone().addScaledVector(UP,1.1))){this.hit(t,damage,e,{heavy,weapon:type});hits++;if(type==='spear'&&!heavy)break;}}if(e.team==='enemy'&&e.gateTarget&&!hits&&dist(e.pos,this.g.gatePos)<reach+1)this.g.damageGate(damage);const start=e.pos.clone().addScaledVector(UP,1.15),end=start.clone().addScaledVector(f,reach);this.g.fx.slash(start,end,heavy?0xf3c578:e.character.rank>=7?0xd7d6a7:0xc3d0c5);if(e.character.rank>=3)this.g.fx.emit('spark',end,Math.floor(e.character.rank/2),{speed:.6,size:.05,life:.2});if(heavy){this.g.fx.emit('dust',end,8+e.character.rank,{speed:3});if(isHero&&skillRankSafe(this.g,'volatile')&&e.stored>0){this.burst(end,3,e.stored,e,'fire');e.stored=0;}}} });return true;
 }
 shoot(owner,target,{secondary=false,ignorePhys=null,passThrough=1,damage=20,type='arrow',speed=28,heavy=false,rank=1,origin=null,direction=null,gravity=0,blast=null,slow=0,pierce=0}={}){const pos=origin?.clone()||owner.pos.clone().add(new T.Vector3(0,1.3,0));let dir;if(direction)dir=direction.clone();else if(target){const dst=target.pos.clone().addScaledVector(UP,1.05);if(target.velocity)dst.addScaledVector(target.velocity,Math.min(.5,dist(pos,dst)/speed));dir=dst.sub(pos).normalize();}else dir=new T.Vector3(-Math.sin(this.g.view.yaw)*Math.cos(this.g.view.pitch),-Math.sin(this.g.view.pitch)*.38,-Math.cos(this.g.view.yaw)*Math.cos(this.g.view.pitch)).normalize();let model;if(type==='arrow'||type==='bolt'){model=arrowMesh(type==='bolt'||heavy);model.scale.setScalar(type==='bolt'?1.4+rank*.01:1+rank*.007);}else if(['frost','stone','shell','holy'].includes(type)){model=new T.Group();const color={frost:0x9edce7,stone:0x807b6c,shell:0x454846,holy:0xe6d39b}[type],geo=type==='frost'?new T.OctahedronGeometry(.18,0):type==='stone'?new T.IcosahedronGeometry(.32,1):new T.SphereGeometry(type==='shell'?.19:.13,12,8);const core=mesh(geo,mat(color,type==='shell'?.45:.75,type==='shell'?.7:0,{emissive:type==='frost'?0x357c94:type==='holy'?0xb09c53:0,emissiveIntensity:1.1}),model);if(type==='frost')core.scale.set(.6,.6,2.4);}else{model=new T.Group();const core=mesh(new T.IcosahedronGeometry(type==='grave'?.15:.17,1),mat(type==='grave'?0xab98cd:0xffad39,.3,0,{emissive:type==='grave'?0x9674b1:0xff6820,emissiveIntensity:2}),model);core.scale.y=.85;}
 pos.addScaledVector(dir,.55);const velocity=dir.clone().multiplyScalar(speed);if(gravity&&target){const dst=target.pos.clone().addScaledVector(UP,.8),flight=Math.max(.3,dist(pos,dst)/speed);velocity.set((dst.x-pos.x)/flight,(dst.y-pos.y+.5*gravity*flight*flight)/flight,(dst.z-pos.z)/flight);}model.position.copy(pos);model.quaternion.setFromUnitVectors(new T.Vector3(0,0,-1),dir);this.g.view.scene.add(model);this.projectiles.push({id:++this.serial,owner,target,secondary,ignorePhys,passThrough,damage,type,rank,heavy,pos,velocity,gravity,blast,slow,pierce,model,life:gravity?6:3.7,trail:0});this.stats.projectiles++;if(owner===this.g.hero)tally(this.g.battle,'projectiles');return model;
 }
 hit(t,amount,source,opt={}){if(this.g.mode==='result'||t.dead||t.invuln>0||!Number.isFinite(amount))return;const g=this.g,isHero=t===g.hero,s=g.store.data;let blocked=false;let armor=t===g.hero?g.heroStats().armor:t.stats.armor||0;if(t.sunder>0)armor*=.8;const pierce=(source===g.hero&&opt.heavy&&weaponPower(equipped(s))?.active&&weaponPower(equipped(s))?.id==='pierce'?1:opt.pierce)||({assassin:.5,marksman:.7,breaker:.55,crew:.5}[source?.unit]||0);armor*=1-pierce;if(source?.unit==='pike'&&['brute','boss'].includes(t.type))amount*=1.5;if(source?.unit==='crew'&&['brute','boss'].includes(t.type))amount*=1.35;if(source?.unit==='rider'&&source.cavalryCharge&&!opt.secondary)amount*=1.6;({amount,armor}=researchHit(g,t,source,opt,amount,armor));let damage=amount*100/(100+armor*2);if(isHero&&opt.fire)damage*=1-g.heroStats().fireResistance;if(t.protect>0)damage*=.7;if(t.type==='bulwark'&&source?.pos&&!opt.secondary&&!opt.heavy&&forward(t.facing).dot(source.pos.clone().sub(t.pos).setY(0).normalize())>.15){damage*=.3;g.fx.emit('spark',t.pos.clone().addScaledVector(UP,1.2),7,{speed:1.5});}if(t.type==='bulwark'&&opt.heavy)t.sunder=5;if(t.team==='ally'&&t.unit==='shield'&&s.units.shield>=5&&(t.order||g.order)==='hold'&&opt.projectile&&g.allies.some(a=>a!==t&&!a.dead&&a.unit==='shield'&&dist(a.pos,t.pos)<2))damage*=.85;if(t.team==='ally'&&g.hero.guarding&&skillRank(s,'bastion')&&dist(t.pos,g.hero.pos)<6)damage*=.8;if(t.marked>0)damage*=source===g.hero?1.2:1.15;
 if(isHero&&t.guarding&&t.stamina>4&&(!source||forward(t.facing).dot(source.pos.clone().sub(t.pos).normalize())>-.05)){const perfect=t.guardTime<.28;const cost=(perfect?3:damage*.45)*g.heroStats().guardCost;t.stamina=Math.max(0,t.stamina-cost);damage*=perfect?.06:.24;blocked=true;g.audio.parry(t.pos,perfect);g.fx.emit('spark',t.pos.clone().addScaledVector(UP,1.4),18,{speed:3});this.stats.guards++;tally(g.battle,'guards');if(perfect){if(skillRank(s,'riposte'))t.riposte=2;t.stamina=Math.min(g.heroStats().stamina,t.stamina+(skillRank(s,'riposte')>=2?8:0));if(skillRank(s,'body')>=5)t.stamina=Math.min(g.heroStats().stamina,t.stamina+4);if(skillRank(s,'rally')>=3)for(const a of g.allies)if(dist(a.pos,t.pos)<g.heroStats().supportRadius)a.protect=2;}if(skillRank(s,'volatile'))t.stored=Math.min([0,20,30,40][skillRank(s,'volatile')],(t.stored||0)+(amount-damage)*[0,.1,.15,.2][skillRank(s,'volatile')]);}
 if(source===g.hero){const hs=g.heroStats(),item=equipped(s);if(source.riposte>0&&opt.weapon&&!opt.secondary){damage*=1.4;source.riposte=0;if(skillRank(s,'edge'))t.burn=4;if(skillRank(s,'riposte')>=3){let count=0;for(const e of g.enemies)if(e!==t&&!e.dead&&dist(e.pos,t.pos)<3&&count++<2)this.hit(e,amount*.6,source,{secondary:true});}}
 if(hs.affixes.includes('vampiric')&&opt.weapon&&!['bow','staff'].includes(opt.weapon))source.hp=Math.min(hs.hp,source.hp+2);if(hs.affixes.includes('ember')||item?.rune==='ember')t.burn=Math.max(3,t.burn||0);if(item?.rune==='frost')t.slow=2;if(item?.rune==='vital')source.hp=Math.min(hs.hp,source.hp+1);if(opt.heavy&&(hs.affixes.includes('sunder')||item?.temper==='sunder'))t.sunder=4;}
 if(source?.team==='ally'&&g.hero&&!g.hero.dead&&dist(source.pos,g.hero.pos)<g.heroStats().supportRadius){if(source.unit)damage*=1+g.heroStats().allyBonus;if(g.heroStats().affixes.includes('command'))damage*=1.08;if(skillRank(s,'burden'))damage*=1.2;}
 damage=Math.max(1,Math.round(damage));recordDamage(g.battle,t,source,g.hero,damage);t.hp-=damage;regimentHit(g,t,source,opt);this.stats.hits++;if(dist(t.pos,g.hero.pos)<35){g.fx.damageText(t.pos.clone().addScaledVector(UP,1.9),damage,isHero?'#ed9f88':opt.heavy?'#ffda87':'#f0e7ce');g.fx.emit(opt.fire?'fire':t.team==='enemy'?'spark':'blood',t.pos.clone().addScaledVector(UP,1.1),opt.heavy?20:8,{speed:2});if(!blocked&&!opt.secondary&&!opt.silent)g.audio.impact({weapon:opt.weapon||source?.weapon||'sword',element:opt.element||(opt.fire?'fire':null),target:t,position:t.pos,heavy:!!opt.heavy,hero:source===g.hero||isHero});}if(isHero){g.view.shake=.45;t.invuln=.12;}else if(opt.heavy){t.stun=.48*(1+[0,.2,.35,.45][source===g.hero?skillRank(s,'breaker'):0]);if(source===g.hero&&skillRank(s,'breaker')>=3)t.sunder=4;const away=t.pos.clone().sub(source.pos).setY(0).normalize();t.knock=away.multiplyScalar(5);t.character.play('Hit_A',.08,true,.28);}researchOnHit(g,t,source,opt);if(source===g.hero)triggerWeaponPower(g,t,opt);if(t.hp<=0){t.hp=0;this.kill(t,source);} }
 kill(t,source){if(this.g.mode==='result'||t.dead)return;const g=this.g;recordKill(g.battle,t,source,g.hero);t.dead=true;t.deathTime=0;t.character.play('Death_A',.1,true,1.1);g.audio.play('death',.4);if(t.phys){g.physics.removeActor(t.phys);t.phys=null;}if(t===g.hero){g.defeat('The last ember still burns. Regroup at Hearthwatch.');return;}if(t.team==='enemy'){if(!t.training){g.store.data.kills++;const old=heroData(g.store.data).level;const xp=Math.round((t.stats.xp||12)*.6);grantXP(g.store.data,xp);tally(g.battle,'xp',xp);if(heroData(g.store.data).level>old){g.audio.play('level');g.toast('Level '+heroData(g.store.data).level+' · A new skill point awaits.');g.hero.hp=Math.min(g.heroStats().hp,g.hero.hp+40);}if(g.battle){if(g.battle.command<220)g.battle.command=Math.min(220,g.battle.command+4);g.droppedChest(t);}g.fx.emit('holy',t.pos,9,{speed:1.3});}else this.later(4,()=>g.spawnTraining());if(skillRankSafe(g,'edge')>=2&&t.burn>0){const next=g.enemies.find(e=>!e.dead&&dist(e.pos,t.pos)<3);if(next)next.burn=4;if(skillRankSafe(g,'edge')>=3)this.zone(t.pos,2,3,3,g.hero,'fire');}} }
 burst(pos,r,damage,owner,kind='fire',audible=true){if(audible)this.g.audio.impact({element:kind==='leaf'?'nature':kind==='dust'?'stone':kind,position:pos,hero:owner===this.g.hero,heavy:r>=5});this.g.fx.emit(kind,pos,45,{speed:r,life:.8,size:kind==='fire'?.7:.18});this.g.fx.ring(pos,r,kind==='leaf'?0x9dbc69:kind==='water'?0x85d3db:0xf2b857,.6);const list=owner.team==='enemy'?[this.g.hero,...this.g.allies]:this.g.enemies;for(const e of list)if(!e.dead&&dist(e.pos,pos)<r&&Math.abs(e.pos.y-pos.y)<4)this.hit(e,damage,owner,{fire:kind==='fire',secondary:true});}
 zone(pos,r,time,damage,owner,kind='fire',heal=0){this.zones.push({pos:pos.clone(),r,time,damage,owner,kind,heal,tick:0});if(kind==='leaf')this.g.fx.roots(pos,r,time,8);else this.g.fx.ring(pos,r,kind==='water'?0x79bfce:0xe8bc77,time);}
 cast(id){const g=this.g,h=g.hero,s=g.store.data,spell=SPELLS[id],r=Math.max(1,skillRank(s,id));if(!spell||h.dead)return;const technique=HEROES[s.hero].skills.find(n=>n.id===id);if(technique?.capstone&&heroData(s).capstone!==id){g.toast('Activate this capstone at the oath shrine.');return;}if(h.cooldowns[id]>0){g.toast('That technique is recovering.');return;}const resource=spell.type||'focus',cost=spell.cost*(skillRank(s,'borrowed')?.75:1);if(h[resource]<cost){g.toast('Not enough '+resource+'.');return;}h[resource]-=cost;h.cooldowns[id]=id==='windstep'&&r>=2?6:spell.cooldown;h.character.cast(id,r);h.facing=g.view.yaw+Math.PI;h.character.root.rotation.y=h.facing;h.cooldown=Math.max(h.cooldown,.45);g.audio.play(id,1,{position:h.pos,rank:r});this.stats.casts[id]=(this.stats.casts[id]||0)+1;tally(g.battle,'casts');g.journey?.mark('cast');const target=this.aim(h,40),dir=forward(h.facing),point=target?target.pos.clone():h.pos.clone().addScaledVector(dir,6);point.y=g.world.height(point.x,point.z);triggerWeaponPower(g,{pos:point},{},true);if(['quench','windstep'].includes(id)&&skillRank(s,'medic')){const allies=g.allies.filter(a=>!a.dead&&dist(a.pos,h.pos)<g.heroStats().supportRadius).sort((a,b)=>a.hp/a.stats.hp-b.hp/b.stats.hp);for(const a of allies.slice(0,3))a.hp=Math.min(a.stats.hp,a.hp+[0,12,20,26][skillRank(s,'medic')]);}const heal=(amount)=>{h.hp=Math.min(g.heroStats().hp,h.hp+amount*g.heroStats().healFactor);};
 if(id==='step'||id==='windstep'){h.dash=.24;h.dashVelocity=dir.multiplyScalar(id==='windstep'?(r>=3?29:21):(r>=3?21:13));h.invuln=.24;h.protect=r>=2?2:1;g.fx.ward(h.pos,1.2,.6,id==='windstep'?'leaf':'holy');g.fx.emit(id==='windstep'?'leaf':'holy',h.pos,20,{speed:3});if(id==='windstep'&&r>=3)h.empowered=4;}
 else if(id==='fireball'){this.later(.24,()=>this.shoot(h,target,{damage:[0,34,44,56][r]||56,type:'fire',speed:22,rank:r}));}
 else if(id==='quench'){heal([0,18,28,36][r]);h.burn=0;this.burst(h.pos,4+r*.6,0,h,'water');for(const e of g.enemies)if(dist(h.pos,e.pos)<4+r*.6)e.slow=3;g.fx.emit('water',h.pos.clone().addScaledVector(UP,1),40+r*12,{speed:3+r});for(const a of g.allies)if(dist(h.pos,a.pos)<5)a.hp=Math.min(a.stats.hp,a.hp+20+r*8);}
 else if(id==='rally'){const radius=g.heroStats().supportRadius;g.fx.ward(h.pos,radius,2);h.buff=5;h.protect=2;const allies=g.allies.filter(a=>!a.dead&&dist(h.pos,a.pos)<radius).sort((a,b)=>a.hp/a.stats.hp-b.hp/b.stats.hp);for(const a of allies){a.buff=5;if(r>=2)a.haste=4;if(r>=3)a.protect=3;}const medic=skillRank(s,'medic');if(medic)for(const a of allies.slice(0,3))a.hp=Math.min(a.stats.hp,a.hp+[0,12,20,26][medic]);}
 else if(id==='thorns'){const count=r>=3?4:r>=2?2:1;let chosen=g.enemies.filter(e=>!e.dead&&dist(e.pos,point)<(r>=3?4:3)).sort((a,b)=>dist(a.pos,point)-dist(b.pos,point)).slice(0,count);if(!chosen.length)g.fx.roots(point,2,2);for(const e of chosen){e.rooted=r>=2?2.5:2;g.fx.roots(e.pos,1.5,2.5,5+r);this.hit(e,18+r*3,h,{secondary:true});}}
 else if(id==='mark'){if(target){target.marked=r>=3?8:5;g.fx.ring(target.pos,1.4,0xe5ba70,5);g.fx.emit('holy',target.pos.clone().addScaledVector(UP,2),18);}}
 else if(id==='volley'||id==='guide'){if(r>=2&&target)target.marked=4;const archers=g.allies.filter(a=>!a.dead&&['bow','crossbow'].includes(a.weapon));if(!archers.length){this.shoot(h,target,{damage:g.heroStats().damage*1.2,type:'arrow',speed:30});}for(const a of archers){a.character.attack('bow',false,0,.6);this.shoot(a,target,{damage:a.stats.damage*(r>=3?.8:1.2),type:'arrow',speed:30});if(r>=3)this.later(.25,()=>!a.dead&&this.shoot(a,target,{damage:a.stats.damage*.8,type:'arrow',speed:30}));}g.fx.emit('holy',h.pos.clone().addScaledVector(UP,1.5),15);}
 else if(id==='bulwark'||id==='tether'){h.protect=r>=3?6:4;g.fx.ward(h.pos,2+r*.4,h.protect);if(r>=2)for(const a of g.allies)if(dist(a.pos,h.pos)<6)a.protect=h.protect;}
 else if(id==='overdrive'){if(g.battle)g.battle.overdrive=6+r*2;g.fx.ward(h.pos,3,3);for(const a of g.allies)if(dist(a.pos,h.pos)<12)a.haste=8;}
 else if(id==='mine'){const n=r>=3?3:1;for(let i=0;i<n;i++){const p=h.pos.clone().addScaledVector(forward(h.facing+(i-(n-1)/2)*.7),3);p.y=g.world.height(p.x,p.z);g.fx.ring(p,.75,0xea8d42,14);this.zones.push({pos:p,r:2,time:14,damage:38+r*6,owner:h,kind:'mine',tick:0});}}
 else if(id==='seedward'){this.zone(h.pos,4,r>=3?5:4,0,h,'leaf',3+r);g.fx.ward(h.pos,4,4,'leaf');}
 else if(id==='sunwall'){h.protect=8;g.fx.ward(h.pos,5,8);for(const a of g.allies)if(dist(a.pos,h.pos)<9)a.protect=8;this.burst(h.pos,5,50,h,'holy');}
 else if(id==='march'||id==='sanctuary'||id==='grove'){const kind=id==='grove'?'leaf':'holy';this.zone(h.pos,7,8,0,h,kind,12);g.fx.ward(h.pos,7,8,kind);h.buff=8;h.protect=8;}
 else{const kind=['briarstorm','verdant'].includes(id)?'leaf':'fire';this.burst(id==='briarstorm'?point:h.pos,8,140,h,kind);if(kind==='leaf')g.fx.roots(point,7,4,15);else this.zone(h.pos,6,4,12,h,'fire');h.invuln=1;}
 }
 update(dt){const g=this.g;for(let i=this.events.length-1;i>=0;i--){const e=this.events[i];e.t-=dt;if(e.t<=0){this.events.splice(i,1);e.fn();if(g.mode==='result')return;}}
 for(let i=this.projectiles.length-1;i>=0;i--){if(g.mode==='result')return;const p=this.projectiles[i];p.life-=dt;const delta=p.velocity.clone().multiplyScalar(dt),len=delta.length(),hit=g.physics.ray(p.pos,delta.clone().normalize(),len,p.ignorePhys||p.owner.phys);let impact=!!hit;if(hit?.meta?.entity)impact=(hit.meta.entity.team==='enemy')!==(p.owner.team==='enemy');if(hit?.meta?.kind==='actor'&&hit.meta.entity===p.owner)impact=false; // Allies never absorb friendly arrows.
 if(impact){p.pos.addScaledVector(delta.clone().normalize(),hit.distance);const t=hit.meta?.entity;g.audio.impact({weapon:p.type==='arrow'?'bow':p.type==='bolt'?'crossbow':'sword',element:p.type,target:t,position:p.pos,heavy:p.heavy,hero:p.owner===g.hero,kind:hit.meta?.kind});if(t&&!t.dead){if(p.damage>0)this.hit(t,p.damage,p.owner,{secondary:p.secondary,pierce:p.pierce,fire:p.type==='fire',projectile:true,weapon:p.type==='arrow'?'bow':p.type==='bolt'?'crossbow':null,element:p.type,silent:true,heavy:p.heavy});if(p.slow&&!t.dead)t.slow=Math.max(t.slow||0,p.slow);if(p.owner.defense==='tower'&&p.owner.rank>=8){if(p.owner.doctrine==='longwatch')t.marked=p.owner.rank>=9?3:2;else t.slow=p.owner.rank>=9?1:.7;}if(p.owner.defense==='ballista'&&p.owner.rank>=5){if(p.owner.doctrine==='pinning')t.slow=2;else if(!p.owner.secondary){const d=p.velocity.clone().normalize(),second=g.enemies.filter(e=>e!==t&&!e.dead&&dist(e.pos,t.pos)<12&&e.pos.clone().sub(t.pos).normalize().dot(d)>.94).sort((a,b)=>dist(a.pos,t.pos)-dist(b.pos,t.pos))[0];if(second)this.shoot({...p.owner,phys:t.phys,secondary:true},second,{damage:p.damage*.5,type:'bolt',speed:34,origin:p.pos.clone(),rank:p.rank});}}} if(p.blast){this.burst(p.pos,p.blast.radius,p.blast.damage,p.owner,p.type==='shell'?'fire':'dust',false);} if(p.type==='fire'){this.burst(p.pos,1.6,p.damage*.35,p.owner,'fire',false);if(p.rank>=2)this.zone(p.pos,2.1,3,3,p.owner,'fire');if(p.rank>=3){for(let n=0;n<3;n++){const v=p.velocity.clone().normalize().applyAxisAngle(UP,(n-1)*.5);v.y=.15;this.shoot(p.owner,null,{damage:16,type:'fire',speed:13,rank:1,origin:p.pos.clone().addScaledVector(v,.3),direction:v.normalize()});}}}else g.fx.emit(p.type==='frost'?'water':p.type==='holy'?'holy':p.type==='grave'?'arcane':'spark',p.pos,8,{speed:1.5});if(t&&p.passThrough>1){p.passThrough--;p.ignorePhys=t.phys;p.pos.addScaledVector(p.velocity.clone().normalize(),.12);}else p.life=0;}else p.pos.add(delta);
 p.velocity.y-=dt*(p.gravity||((p.type==='arrow'||p.type==='bolt')?.95:0));p.model.position.copy(p.pos);p.model.quaternion.setFromUnitVectors(new T.Vector3(0,0,-1),p.velocity.clone().normalize());p.trail+=dt;if(p.trail>.04&&(['fire','grave','frost','holy'].includes(p.type)||(p.type==='bolt'&&p.heavy))){p.trail=0;g.fx.emit(p.type==='frost'?'water':p.type==='holy'?'holy':p.type==='grave'?'arcane':'fire',p.pos,3,{speed:.6,life:.28,size:.40});if(p.type==='fire')g.fx.emit('smoke',p.pos,1,{speed:.3,life:.35});}if(p.life<=0){p.model.removeFromParent();this.projectiles.splice(i,1);}}
 for(let i=this.zones.length-1;i>=0;i--){if(g.mode==='result')return;const z=this.zones[i];z.time-=dt;z.tick-=dt;if(z.kind==='mine'){if(g.enemies.some(e=>!e.dead&&dist(e.pos,z.pos)<z.r)){this.burst(z.pos,3,z.damage,z.owner,'fire');z.time=0;}}else if(z.tick<=0){z.tick=.5;if(z.damage)this.burst(z.pos,z.r,z.damage*.5,z.owner,z.kind,false);else if(z.heal){for(const a of [g.hero,...g.allies])if(!a.dead&&dist(a.pos,z.pos)<z.r)a.hp=Math.min(a===g.hero?g.heroStats().hp:a.stats.hp,a.hp+z.heal*.5);g.fx.emit(z.kind,z.pos,6,{speed:2});}}if(z.time<=0)this.zones.splice(i,1);}
 }
}
function skillRankSafe(g,id){return g.store.data?skillRank(g.store.data,id):0;}
