import {techniqueArt,flameCircle} from './technique-art.js';
import * as T from 'three';
import {mesh,mat,beam} from './art.js';
const PALETTES={fire:[0xffbd42,0xfa7129,0xe74315],ember:[0xffab32,0xe6581b],spark:[0xffefb0,0xe7b967,0xb5d4d4],water:[0xb8efeb,0x72c4d6,0x549eaf],leaf:[0xa8c87a,0x5b9d6b,0xd0b47c],holy:[0xffe4a5,0xbddfca,0xe8ba63],dust:[0xab9e80,0xc0b492],smoke:[0x625f56,0x807a68],arcane:[0xb5d7ff,0x809ddd,0xe4b8fb],blood:[0x696c60,0x939378]};
export class Effects{
 constructor(scene){this.scene=scene;this.particles=[];this.objects=[];this.max=1500;this.g=new T.BufferGeometry();for(const [name,n]of [['position',3],['color',3],['aSize',1],['aLife',1],['aType',1]])this.g.setAttribute(name,new T.BufferAttribute(new Float32Array(this.max*n),n).setUsage(T.DynamicDrawUsage));this.g.setDrawRange(0,0);this.material=new T.ShaderMaterial({transparent:true,depthWrite:false,vertexColors:true,blending:T.NormalBlending,uniforms:{time:{value:0}},vertexShader:`attribute float aSize;attribute float aLife;attribute float aType;varying vec3 vColor;varying float vLife;varying float vType;void main(){vColor=color;vLife=aLife;vType=aType;vec4 p=modelViewMatrix*vec4(position,1.);gl_PointSize=clamp(aSize*340./max(1.,-p.z),1.,90.);gl_Position=projectionMatrix*p;}`,fragmentShader:`uniform float time;varying vec3 vColor;varying float vLife;varying float vType;void main(){vec2 uv=gl_PointCoord-.5;float d=length(uv);float a=smoothstep(.5,.12,d);if(vType>0.5&&vType<1.5){float w=.22+sin(uv.y*14.+time*16.)*.045;float body=abs(uv.x+sin(uv.y*11.+time*8.)*.035);a=smoothstep(w*(.7+uv.y),.01,body)*smoothstep(-.5,-.2,uv.y)*smoothstep(.5,.25,uv.y);}if(vType>1.5&&vType<2.5)a=smoothstep(.5,0.,d)*.3;if(vType>2.5)a=smoothstep(.45,.18,abs(uv.x)+abs(uv.y));if(a<.01)discard;gl_FragColor=vec4(vColor,a*vLife);}`});this.points=new T.Points(this.g,this.material);this.points.frustumCulled=false;scene.add(this.points);}
 flameCircle(pos,r,time){return flameCircle(this,pos,r,time);}
 technique(id,pos,target,rank,path){return techniqueArt(this,id,pos,target,rank,path);}
 emit(kind,pos,count=12,options={}){const colors=PALETTES[kind]||PALETTES.holy;for(let i=0;i<count&&this.particles.length<this.max;i++){const angle=Math.random()*Math.PI*2,speed=(options.speed||2)*(Math.random()*.7+.3),up=kind==='fire'||kind==='smoke';const life=(options.life||.55)*(Math.random()*.65+.65);this.particles.push({pos:pos.clone().add(new T.Vector3((Math.random()-.5)*.1,0,(Math.random()-.5)*.1)),vel:new T.Vector3(Math.sin(angle)*speed*(up?.3:1),(up?1.2:Math.random()*1.4)*speed,Math.cos(angle)*speed*(up?.3:1)),life,max:life,size:(options.size||(kind==='smoke'?.85:kind==='fire'?.45:kind==='leaf'?.22:.11))*(.7+Math.random()*.6),color:new T.Color(colors[i%colors.length]),type:kind==='fire'?1:kind==='smoke'?2:kind==='leaf'?3:0,gravity:up?-1.5:7});}}
 ring(pos,r=3,color=0xf5cd79,duration=.5){const material=new T.MeshBasicMaterial({color,transparent:true,opacity:.38,side:T.DoubleSide,depthWrite:false}),m=new T.Mesh(new T.RingGeometry(Math.max(.01,r-Math.min(.075,r*.04)),r,72),material);m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y+=.10;this.scene.add(m);this.objects.push({m,t:duration,max:duration,update:(o,f)=>{o.scale.setScalar(.6+f*.5);o.material.opacity=(1-f)*.35;}});return m;}
 roots(pos,radius=2,duration=2,count=7){const g=new T.Group(),material=mat(0x526d3c,.9);g.position.copy(pos);for(let i=0;i<count;i++){const a=i/count*Math.PI*2,curve=new T.CatmullRomCurve3([new T.Vector3(),new T.Vector3(Math.sin(a)*radius*.4,.1,Math.cos(a)*radius*.4),new T.Vector3(Math.sin(a)*radius*.7,.4,Math.cos(a)*radius*.7),new T.Vector3(Math.sin(a)*radius,.14,Math.cos(a)*radius)]);mesh(new T.TubeGeometry(curve,12,.045,5,false),material,g);for(let j=1;j<4;j++){const p=curve.getPoint(j/4),thorn=mesh(new T.ConeGeometry(.055,.24,4),material,g,p.x,p.y+.12,p.z);thorn.rotation.z=.35*Math.sin(a);}}this.scene.add(g);this.objects.push({m:g,t:duration,max:duration,update:(o,f)=>{o.scale.setScalar(Math.min(1,f*7)*(f>.88?(1-f)/.12:1));}});this.emit('leaf',pos,20,{speed:3,life:1});}
 ward(pos,radius=3,duration=4,kind='holy'){this.ring(pos,radius,kind==='leaf'?0xa0c17b:0xecc777,duration);this.emit(kind,pos,35,{speed:2,life:1.4});const g=new T.Group();g.position.copy(pos);const material=new T.MeshStandardMaterial({color:kind==='leaf'?0xaac888:0xe7cf89,emissive:kind==='leaf'?0x5c8c46:0xc88c39,emissiveIntensity:.4,transparent:true,opacity:.28,metalness:.4,roughness:.3,side:T.DoubleSide,depthWrite:false});for(let i=0;i<5;i++){const a=i/5*Math.PI*2,m=mesh(new T.PlaneGeometry(.8,1.8),material,g,Math.sin(a)*radius,.9,Math.cos(a)*radius);m.rotation.y=a;}this.scene.add(g);this.objects.push({m:g,t:duration,max:duration,update:(o,f)=>{o.rotation.y=f*.3;o.scale.y=Math.min(1,f*8,Math.max(0,(1-f)*6));}});}
 slash(from,to,color=0xdce3bd){const d=to.clone().sub(from),len=d.length();if(len<.05)return;const m=new T.Mesh(new T.CylinderGeometry(.015,.05,len,5),new T.MeshBasicMaterial({color,transparent:true,opacity:.8,depthWrite:false}));m.position.copy(from).add(to).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());this.scene.add(m);this.objects.push({m,t:.14,max:.14,update:(o,f)=>o.material.opacity=.8*(1-f)});}
 damageText(pos,text,color='#f0debb'){const p=document.createElement('span');p.className='floating-number';p.textContent=text;p.style.color=color;document.getElementById('floating-layer').appendChild(p);this.objects.push({dom:p,pos:pos.clone(),t:.85,max:.85,update:()=>{}});}
 update(dt,time,camera){this.material.uniforms.time.value=time;let write=0;for(let i=0;i<this.particles.length;i++){const p=this.particles[i];p.life-=dt;if(p.life<=0)continue;p.vel.y-=p.gravity*dt;p.pos.addScaledVector(p.vel,dt);p.vel.multiplyScalar(Math.max(0,1-dt*1.5));this.particles[write++]=p;}this.particles.length=write;const a=this.g.attributes;for(let i=0;i<write;i++){const p=this.particles[i];a.position.setXYZ(i,p.pos.x,p.pos.y,p.pos.z);a.color.setXYZ(i,p.color.r,p.color.g,p.color.b);a.aSize.setX(i,p.size*(p.type===2?1+(1-p.life/p.max):1));a.aLife.setX(i,Math.min(1,p.life/p.max*1.5));a.aType.setX(i,p.type);}for(const x of Object.values(a))x.needsUpdate=true;this.g.setDrawRange(0,write);
 for(let i=this.objects.length-1;i>=0;i--){const o=this.objects[i];o.t-=dt;const f=1-o.t/o.max;if(o.t<=0){if(o.dom)o.dom.remove();if(o.m){o.m.removeFromParent();o.m.traverse(n=>{if(n.isMesh){n.geometry.dispose();n.material.dispose();}});}this.objects.splice(i,1);continue;}if(o.dom){const p=o.pos.clone();p.y+=f*.8;p.project(camera);o.dom.hidden=p.z>1;o.dom.style.left=(p.x*.5+.5)*innerWidth+'px';o.dom.style.top=(-p.y*.5+.5)*innerHeight+'px';o.dom.style.opacity=String(Math.min(1,o.t*3));}else o.update(o.m,f);}
 }
 clear(){this.particles=[];for(const o of this.objects){o.dom?.remove();if(o.m){o.m.removeFromParent();o.m.traverse(n=>{if(n.isMesh){n.geometry.dispose();n.material.dispose();}});}}this.objects=[];this.g.setDrawRange(0,0);}
}
