import * as T from 'three';
import {View} from './render.js';
import {Physics,initPhysics} from './physics.js';
import {Landscape} from './world.js';
import {Character,loadCharacters} from './characters.js';
import {Input} from './input.js';
import {Effects} from './effects.js';
import {Soundscape} from './audio.js';
import {Combat} from './combat.js';
import {UI} from './ui.js';
import {SaveStore,heroData,heroStats,skillRank,equipped,claimTreasure,completeMission,unitUnlocked} from './state.js';
import {HEROES,UNITS,DEFENSES,ENEMIES,MISSIONS,SERVICES,SPELLS,unitStats,defenseStats,BUILD} from './data.js';
const UP=new T.Vector3(0,1,0),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export class Game{
 constructor(){this.store=new SaveStore();this.audio=new Soundscape();this.time=0;this.accum=0;this.last=0;this.mode='title';this.menu=null;this.hero=null;this.enemies=[];this.allies=[];this.npcs=[];this.battle=null;this.gatePos=new T.Vector3(0,0,-20);this.order='hold';this.holdPoint=new T.Vector3(0,0,-32);this.saveTimer=0;this.frames=[];this.ready=false;this.keys=new Set();this.metrics={frames:0,physicsSteps:0,jumps:0,interactions:0};}
 async init(){const bar=document.getElementById('load-bar'),label=document.getElementById('load-text');this.view=new View(document.getElementById('game'));this.view.quality('auto');await Promise.all([initPhysics(),loadCharacters(p=>{bar.style.width=(10+p*75)+'%';label.textContent='Preparing the warband · '+Math.round(p*100)+'%';}),this.store.open()]);this.physics=new Physics();this.world=new Landscape(this.view.scene,this.physics);this.world.build('plain',7919,this.store.data?.defenses);this.fx=new Effects(this.view.scene);this.combat=new Combat(this);this.input=new Input(this.view.canvas);this.ui=new UI(this);this.spawnNPCs();this.physics.step();this.ready=true;bar.style.width='100%';document.getElementById('loading').hidden=true;this.ui.title();this.last=performance.now();requestAnimationFrame(t=>this.frame(t));document.addEventListener('visibilitychange',()=>{if(document.hidden){this.checkpoint();this.audio.suspend();if(this.mode==='play'&&!this.menu)this.ui.open('pause');}});window.addEventListener('pagehide',()=>this.checkpoint());if(this.store.error)this.toast(this.store.error);window.__oathfire=this;}
 async start(hero='warden',resume=false){await this.audio.unlock();if(!resume)this.store.start(hero);const s=this.store.data;this.audio.settings(s.settings);this.view.quality(s.settings.quality);this.menu=null;this.mode='play';document.getElementById('title-screen').hidden=true;document.getElementById('menu').hidden=true;document.getElementById('hud').hidden=false;document.getElementById('dialog').hidden=true;this.input.clear();this.input.enabled=true;const saved=s.battle;if(resume&&saved){this.beginMission(saved.id,saved);}else{this.loadWorld('plain',7919);this.spawnHero(s.position||{x:0,y:0,z:9});this.spawnTraining();this.view.yaw=0;this.view.pitch=.23;this.view.camera.position.copy(this.hero.pos).add(new T.Vector3(0,4,7));this.toast('Welcome to Hearthwatch. Find Sera at the war table, or explore the open gate.');}this.checkpoint();}
 clearActors(){for(const e of [this.hero,...this.enemies,...this.allies,...this.npcs])if(e){e.character.dispose();if(e.phys)this.physics.removeActor(e.phys);}this.hero=null;this.enemies=[];this.allies=[];this.npcs=[];this.combat.clear();this.fx.clear();}
 loadWorld(biome,seed){this.clearActors();this.navGrid=null;this.world.build(biome,seed,this.store.data.defenses);this.physics.step();this.spawnNPCs();this.syncTreasures();}
 spawnNPCs(){for(let i=0;i<SERVICES.length;i++){const s=SERVICES[i];if(s.id==='hero')continue;const c=new Character(['Barbarian','Mage','Knight','Rogue_Hooded','Rogue_Hooded'][i%5],{weapon:i===0?'hammer':'staff',rank:3,color:i%2?0xb09661:0x5d857b,height:1.85});c.root.position.set(s.x,s.y||0,s.z-1.1);c.root.rotation.y=s.x<0?Math.PI/3:-Math.PI/3;this.view.scene.add(c.root);this.npcs.push({character:c,pos:c.root.position});}for(const t of this.world.towerObjects){const c=new Character(t.id==='tower'?'Rogue_Hooded':'Knight',{weapon:t.id==='tower'?'bow':'crossbow',rank:t.level,color:0x6e9386,height:1.55});c.root.position.set(t.x+(t.id==='ballista'?1.0:0),t.id==='tower'?4+t.level*.15+.16:0,t.z+(t.id==='ballista'?1.1:0));c.root.rotation.y=Math.PI;this.view.scene.add(c.root);t.crew=c;this.npcs.push({character:c,pos:c.root.position});}}
 spawnHero(pos){const s=this.store.data,h=HEROES[s.hero],stats=heroStats(s),gear=equipped(s),rank=Math.min(10,1+Math.floor((heroData(s).level-1)/4)+(gear?.plus||0)/2|0);const c=new Character(h.model,{weapon:stats.weapon,rank,color:h.color,temper:gear?.temper});this.hero={id:'hero',team:'hero',character:c,pos:new T.Vector3(pos.x,pos.y||0,pos.z),velocity:new T.Vector3(),facing:Math.PI,hp:stats.hp,focus:stats.focus,stamina:stats.stamina,stats,cooldown:0,cooldowns:{},speed:0,charge:0,charging:false,guardTime:0,combo:0,burnTick:0};this.hero.phys=this.physics.actor(this.hero,this.hero.pos);this.view.scene.add(c.root);c.root.position.copy(this.hero.pos);this.view.firstPersonWeapon(stats.weapon,rank,h.color);this.input.enabled=true;}
 refreshHero(){if(!this.hero)return;const s=this.store.data,stats=heroStats(s),rank=Math.min(10,1+Math.floor((heroData(s).level-1)/4)+Math.floor((equipped(s)?.plus||0)/2));this.hero.stats=stats;this.hero.hp=Math.min(this.hero.hp,stats.hp);this.hero.focus=Math.min(this.hero.focus,stats.focus);this.hero.character.updateGear(stats.weapon,rank,HEROES[s.hero].color,equipped(s)?.temper);this.view.firstPersonWeapon(stats.weapon,rank,HEROES[s.hero].color);this.ui.previewForTab();}
 spawnEnemy(type,pos,opts={}){pos={...pos};if(!opts.training){for(let n=0;n<12;n++){const obstacle=this.world.nav.find(o=>Math.abs(pos.x-o.x)<o.hx+.4&&Math.abs(pos.z-o.z)<o.hz+.4);if(!obstacle)break;pos.x=obstacle.x+obstacle.hx+1.2;pos.y=this.world.height(pos.x,pos.z);}}const base=ENEMIES[type],scale=this.battle?MISSIONS[this.battle.id].scale:1,stats={...base,hp:Math.round(base.hp*scale),damage:base.damage*(.8+scale*.2),armor:base.armor||0},c=new Character(base.model,{weapon:base.weapon,rank:type==='boss'?8:type==='knight'||type==='brute'?4:1,color:0x8b7358,enemy:true,height:2*(base.scale||1)}),e={id:'enemy-'+Date.now()+'-'+Math.random(),type,team:'enemy',character:c,pos:new T.Vector3(pos.x,pos.y??this.world.height(pos.x,pos.z),pos.z),velocity:new T.Vector3(),facing:0,stats,weapon:base.weapon,hp:stats.hp,cooldown:Math.random()*.7,think:0,path:[],pathIndex:0,speed:0,burnTick:0,...opts};e.phys=this.physics.actor(e,e.pos,2*(base.scale||1),.36*(base.scale||1));c.root.position.copy(e.pos);this.view.scene.add(c.root);this.enemies.push(e);return e;}
 spawnTraining(){if(this.battle||this.mode!=='play')return;this.spawnEnemy('knight',{x:-10,y:0,z:-8},{training:true,hp:350,stats:{...ENEMIES.knight,hp:350,damage:0}});}
 spawnAlly(id,pos,opts={}){const u=UNITS[id],rank=this.store.data.units[id],stats={...unitStats(id,rank),armor:id==='shield'?10+rank*2:4},c=new Character(u.model,{weapon:u.weapon,rank,color:u.color,height:2*(u.scale||1),mounted:id==='rider'}),e={id:'ally-'+Date.now()+'-'+Math.random(),unit:id,team:'ally',character:c,pos:new T.Vector3(pos.x,pos.y??this.world.height(pos.x,pos.z),pos.z),velocity:new T.Vector3(),facing:Math.PI,stats,weapon:u.weapon,hp:stats.hp,cooldown:0,think:0,path:[],pathIndex:0,speed:0,burnTick:0,...opts};e.phys=this.physics.actor(e,e.pos,id==='rider'?3:2*(u.scale||1),id==='rider'?.6:.37*(u.scale||1));c.root.position.copy(e.pos);this.view.scene.add(c.root);this.allies.push(e);return e;}
 recruit(id){const u=UNITS[id];if(!this.battle){this.toast('Reinforcements are deployed during a battle.');return;}if(!unitUnlocked(this.store.data,id)){this.toast('Reclaim more castles to recruit this regiment.');return;}const cost=unitStats(id,this.store.data.units[id]).cost;if(this.battle.command<cost){this.toast('You need '+cost+' Command. Command recovers during the battle.');return;}if(this.allies.filter(a=>!a.dead).length+u.count>24){this.toast('Your field army is at its 24-soldier limit.');return;}this.battle.command-=cost;for(let i=0;i<u.count;i++)this.spawnAlly(id,{x:(i-(u.count-1)/2)*1.2+(Math.random()-.5)*2,y:0,z:-23});this.audio.play('rally',.4);this.toast(u.name+' are on the field.');this.ui.updateResources();}
 beginMission(id,saved=null){const m=MISSIONS[id];if(!m)return;if(!saved&&id>0&&!this.store.data.completed.includes(id-1)){this.toast('Reclaim the previous territory first.');return;}this.ui.close();this.mode='play';this.loadWorld(m.biome,m.seed);this.battle={id,wave:0,nextWave:9,command:100,gate: defenseStats('gate',this.store.data.defenses.gate).hp,maxGate:defenseStats('gate',this.store.data.defenses.gate).hp,core:650,time:0,camp:false,order:'hold',kills:0,overdrive:0,...saved};this.battle.enemies=undefined;this.battle.allies=undefined;this.order=saved?.order||'hold';this.holdPoint.set(0,0,-32);this.spawnHero(saved?.hero?.pos||{x:0,y:0,z:-27});if(saved?.hero){for(const k of ['hp','focus','stamina','cooldowns'])if(saved.hero[k]!=null)this.hero[k]=saved.hero[k];}this.world.setGate(this.battle.gate>0);this.gatePos.set(0,0,this.battle.gate>0?-20:5);this.view.yaw=0;this.view.pitch=.23;this.view.camera.position.copy(this.hero.pos).add(new T.Vector3(0,4,7));if(saved){for(const e of saved.enemies||[])this.spawnEnemy(e.type,e.pos,{hp:e.hp});for(const a of saved.allies||[])this.spawnAlly(a.unit,a.pos,{hp:a.hp});}else{for(let i=0;i<3;i++)this.spawnAlly('shield',{x:-1.2+i*1.2,y:0,z:-32});this.toast(m.title+' · Deploy archers and choose where to hold.');}this.syncTreasures();this.checkpoint();}
 spawnWave(){const b=this.battle,m=MISSIONS[b.id];b.wave++;const n=5+b.wave*2+Math.floor(b.id*.4)-(b.camp?2:0);for(let i=0;i<n;i++){const flank=(i%3-1)*(24+Math.min(20,b.id*2)),x=flank+(Math.random()-.5)*15,z=-76-Math.random()*25-(b.id>4?12:0);let type=i%5===4?'archer':'hollow';if(b.id>=2&&i%6===3)type='knight';if(b.id>=3&&i%7===5)type='mage';if(b.id>=5&&i%9===7)type='brute';this.spawnEnemy(type,{x,z});}if(m.boss&&b.wave===m.waves)this.spawnEnemy('boss',{x:0,z:-105},{name:b.id===14?'Marshal Veyr':b.id===9?'The Ash Castellan':'The Bell Knight'});b.nextWave=42+b.id*1.3;this.toast('Wave '+b.wave+' / '+m.waves+' · '+(b.wave%2?'The Hollow Host approaches':'Watch your flanks'));this.audio.play('rally',.65);}
 damageGate(damage){if(!this.battle)return;const b=this.battle;if(b.gate>0){b.gate=Math.max(0,b.gate-damage);if(b.gate===0){this.world.setGate(false);this.gatePos.set(0,0,5);this.toast('The gate has fallen! Defend the beacon.');this.fx.burst?.(this.gatePos);}}else{b.core=Math.max(0,b.core-damage);if(b.core===0)this.defeat('The beacon was overwhelmed. Rebuild, retrain and return.');}}
 victory(){if(!this.battle||this.mode==='result')return;const id=this.battle.id;this.mode='result';this.battle=null;this.world.setGate(false);this.gatePos.set(0,0,-20);const result=this.store.commit(s=>completeMission(s,id));this.audio.play('victory');this.input.clear();this.input.enabled=false;this.ui.result(true,MISSIONS[id],result);}
 defeat(reason){if(this.mode==='result')return;this.mode='result';this.input.clear();this.input.enabled=false;this.store.commit(s=>{s.battle=null;});this.ui.result(false,this.battle?MISSIONS[this.battle.id]:null,{reason});}
 returnHome(){this.ui.close();this.battle=null;this.mode='play';this.gatePos.set(0,0,-20);this.loadWorld('plain',7919);this.spawnHero({x:0,y:0,z:9});this.spawnTraining();this.store.data.battle=null;this.view.yaw=0;this.view.pitch=.23;this.checkpoint();}
 syncTreasures(){if(!this.store.data)return;for(const t of this.world.treasures){const id=this.treasureID(t);t.open=this.store.data.treasures.includes(id);t.lid.rotation.x=t.open?-1.15:0;}}
 treasureID(t){return (t.hub?'hearthwatch':'map-'+(this.battle?.id??'outskirts'))+'-'+t.id;}
 interact(){this.metrics.interactions++;const t=this.nearby();if(!t)return;if(t.kind==='vendor'){if(!this.store.data.visits.includes(t.id))this.store.commit(s=>s.visits.push(t.id));this.ui.open(t.tab);}
 else if(t.kind==='treasure'&&!t.open){const item=this.store.commit(s=>claimTreasure(s,this.treasureID(t),t.id==='ruin-cache'?2:1));this.syncTreasures();this.audio.play('loot');this.fx.emit('holy',t.model.position.clone().addScaledVector(UP,.8),45,{speed:2});this.toast('Treasure found · '+(item?.name||'Salvage')+' · Supplies & crafting materials');}
 else if(t.kind==='camp'){if(this.battle&&!this.battle.camp){this.battle.camp=true;this.battle.command=Math.min(220,this.battle.command+45);this.audio.play('rally');this.toast('Ridge secured · +45 Command · Later waves lose two reinforcements.');}else this.toast('From this ridge, you can see both approaches to the keep.');}
 else if(t.kind==='crypt'){this.ui.crypt();}}
 nearby(){if(!this.hero)return null;let best=null,d=3.5;for(const t of this.world.interactables){if(t.open)continue;if(this.battle&&t.kind==='vendor')continue;const n=Math.hypot(t.x-this.hero.pos.x,t.z-this.hero.pos.z,(t.y||0)-this.hero.pos.y);if(n<d){d=n;best=t;}}return best;}
 potion(){const h=this.hero,s=this.store.data;if(!s.potions){this.toast('Visit Iona for more healing draughts.');return;}if(h.hp>=heroStats(s).hp){this.toast('Your health is already full.');return;}this.store.commit(n=>n.potions--);h.hp=Math.min(heroStats(s).hp,h.hp+100*heroStats(s).healFactor);this.fx.emit('holy',h.pos.clone().addScaledVector(UP,1),24);this.audio.play('quench');}
 handleEvents(){for(const e of this.input.consume()){if(e==='pause'){this.menu?this.ui.close():this.ui.open('pause');continue;}if(this.menu||this.mode!=='play')continue;if(e==='army'){this.ui.open('army');continue;}if(e==='character'){this.ui.open('hero');continue;}if(e==='campaign'){this.ui.open('campaign');continue;}if(e==='camera'){this.store.data.settings.firstPerson=!this.store.data.settings.firstPerson;this.store.persist();}if(e==='jump'&&this.hero.phys.grounded){this.hero.jump=true;this.metrics.jumps++;this.hero.character.play('Jump_Start',.08,true,.24);this.audio.play('jump');}if(e==='release'){this.combat.attack(this.hero,this.hero.charge>.32);this.hero.charge=0;this.hero.charging=false;}if(e==='cancelAttack'){this.hero.charge=0;this.hero.charging=false;}if(e==='spell0'||e==='spell1')this.combat.cast(heroData(this.store.data).slots[Number(e.slice(-1))]);if(e==='potion')this.potion();if(e==='interact')this.interact();if(e.startsWith('recruit')){const id=Object.keys(UNITS)[Number(e.slice(-1))-1];if(id)this.recruit(id);}}}
 tick(dt){this.metrics.physicsSteps++;this.time+=dt;const h=this.hero,s=this.store.data,stats=heroStats(s);h.stats=stats;this.handleEvents();if(this.menu||this.mode!=='play')return;const axes=this.input.axes(),yaw=this.view.yaw;let desired=new T.Vector3(axes.x*Math.cos(yaw)-axes.y*Math.sin(yaw),0,-axes.x*Math.sin(yaw)-axes.y*Math.cos(yaw));h.guarding=this.input.guard&&!h.charging;h.guardTime=h.guarding?h.guardTime+dt:0;if(this.input.attack&&h.cooldown<=0&&!h.guarding){if(!h.charging){h.charging=true;h.charge=0;}h.charge=Math.min(1.2,h.charge+dt);if(h.charge>=.32&&!h.chargeSound){this.audio.play('charge');h.chargeSound=true;}if(h.charge>.32&&this.metrics.physicsSteps%6===0)this.fx.emit(s.hero==='ashwright'?'ember':'spark',h.character.muzzle(),2,{speed:.35,life:.25,size:.06});}else if(!this.input.attack){h.chargeSound=false;h.charging=false;h.charge=0;}
 const slow=h.guarding?(skillRank(s,'bastion')?.36:.48):h.charging?.58:h.attacking?.6:1;desired.multiplyScalar(stats.speed*slow*(h.buff>0?1.15:1));if(h.dash>0){desired.copy(h.dashVelocity);h.dash-=dt;this.fx.emit(s.hero==='ranger'?'leaf':'holy',h.pos,2,{speed:1});}h.velocity.lerp(desired,1-Math.exp(-dt*12));if(h.knock){h.velocity.add(h.knock);h.knock.multiplyScalar(.82);if(h.knock.length()<.1)h.knock=null;}this.physics.move(h.phys,h.velocity,dt,h.jump);h.jump=false;h.speed=h.velocity.length();if(h.speed>.2&&!h.attacking&&!h.charging&&!h.guarding){const a=Math.atan2(h.velocity.x,h.velocity.z);h.facing+=Math.atan2(Math.sin(a-h.facing),Math.cos(a-h.facing))*Math.min(1,dt*15);}if(h.guarding)h.facing=this.view.yaw+Math.PI;h.character.root.rotation.y=h.facing;h.stamina=Math.min(stats.stamina,h.stamina+dt*(h.charging||h.guarding?2:h.attacking?3:18));h.focus=Math.min(stats.focus,h.focus+dt*3.5);if(!this.battle)h.hp=Math.min(stats.hp,h.hp+dt*6);for(const key of Object.keys(h.cooldowns))h.cooldowns[key]=Math.max(0,h.cooldowns[key]-dt);if(h.speed>1&&h.phys.grounded)this.audio.play('foot',.55);
 for(const e of [h,...this.enemies,...this.allies]){if(e.dead){e.deathTime+=dt;if(e.deathTime>1.8)e.character.root.position.y-=dt*.6;continue;}e.cooldown=Math.max(0,e.cooldown-dt);e.actionTime=(e.actionTime||0)+dt;e.attacking=e.cooldown>.06;for(const k of ['invuln','protect','buff','haste','sunder','marked','riposte','rooted','slow','empowered','stun'])if(e[k]>0)e[k]-=dt;if(e.burn>0){e.burn-=dt;e.burnTick-=dt;if(e.burnTick<=0){e.burnTick=1;this.combat.hit(e,3,h,{secondary:true,fire:true});this.fx.emit('fire',e.pos.clone().addScaledVector(UP,.7),6);}}if(e!==h)this.ai(e,dt);}
 this.physics.step();for(const e of [h,...this.enemies,...this.allies])if(!e.dead&&e.phys){this.physics.position(e.phys,e.pos);e.character.root.position.copy(e.pos);if(e.pos.y<-12){if(e===h)this.physics.teleport(e.phys,{x:0,y:1,z:this.battle?-27:9});else this.combat.kill(e,h);}}this.combat.update(dt);this.battleTick(dt);for(const list of [this.enemies,this.allies])for(let i=list.length-1;i>=0;i--)if(list[i].dead&&list[i].deathTime>3.5){list[i].character.dispose();list.splice(i,1);}this.saveTimer+=dt;s.timePlayed+=dt;if(this.saveTimer>6){this.saveTimer=0;this.checkpoint();}}
 ai(e,dt){if(e.training){e.velocity.set(0,0,0);this.physics.move(e.phys,e.velocity,dt);e.speed=0;return;}e.think-=dt;const g=this,h=g.hero,isEnemy=e.team==='enemy';let target=this.combat.target(e,isEnemy?22:36);let goal;if(isEnemy){goal=target?.pos||this.gatePos;e.gateTarget=!target;}else{if(this.order==='follow'&&dist(e.pos,h.pos)>10)target=null;if(this.order==='hold'&&target&&dist(target.pos,this.holdPoint)>23)target=null;goal=target?.pos||(this.order==='follow'?h.pos:this.order==='assault'?new T.Vector3(0,0,-90):this.holdPoint);if(e.unit==='lantern'){e.healTimer=(e.healTimer||0)-dt;if(e.healTimer<=0){e.healTimer=3;const a=[h,...g.allies].filter(a=>!a.dead&&a.hp<(a===h?heroStats(g.store.data).hp:a.stats.hp)&&dist(a.pos,e.pos)<10).sort((a,b)=>a.hp/a.stats.hp-b.hp/b.stats.hp)[0];if(a){a.hp=Math.min(a.stats.hp,a.hp+12+g.store.data.units.lantern*2);e.character.cast('tether',1);g.fx.ward(a.pos,1,.6);}}}}
 const distance=dist(e.pos,goal),range=target?(e.stats.range||e.stats.reach||2.4):isEnemy?(e.stats.range>10?18:2.8):this.order==='follow'?3.8:2.5;const los=target?this.physics.lineClear(e.pos.clone().addScaledVector(UP,1.3),target.pos.clone().addScaledVector(UP,1.1)):true;let velocity=new T.Vector3();if(distance>range||!los){let waypoint=goal;if(e.think<=0){e.think=.7+Math.random()*.3;e.path=this.findPath(e.pos,goal);e.pathIndex=0;}if(e.path?.length){while(e.pathIndex<e.path.length-1&&dist(e.pos,e.path[e.pathIndex])<2)e.pathIndex++;waypoint=e.path[e.pathIndex];}velocity.subVectors(waypoint,e.pos).setY(0).normalize().multiplyScalar(e.stats.speed*(e.slow>0?.65:1)*(e.buff>0?1.15:1));}else if(e.cooldown<=0&&!(e.rooted>0)&&!(e.stun>0)){e.facing=Math.atan2(goal.x-e.pos.x,goal.z-e.pos.z);e.character.root.rotation.y=e.facing;if(target){if(['bow','staff','crossbow'].includes(e.weapon)){e.cooldown=e.team==='enemy'?2.3:1.5;e.character.attack(e.weapon,false,0,.75);this.combat.later(.3,()=>{if(!e.dead)this.combat.shoot(e,target,{damage:e.stats.damage,type:e.weapon==='staff'?(isEnemy?'grave':'fire'):e.weapon==='crossbow'?'bolt':'arrow',speed:24,rank:1});});}else this.combat.attack(e,false);}else if(isEnemy){e.cooldown=1.8;e.character.attack(e.weapon,false,0,.8);this.combat.later(.4,()=>!e.dead&&this.damageGate(e.stats.damage));}}
 // Separation is applied before the capsule sweep; it cannot push anyone through scenery.
 for(const other of [h,...this.allies,...this.enemies])if(other!==e&&!other.dead){const dx=e.pos.x-other.pos.x,dz=e.pos.z-other.pos.z,d=Math.hypot(dx,dz),min=.74*((e.stats.scale||1)+(other.stats.scale||1))/2;if(d>0&&d<min)velocity.add(new T.Vector3(dx/d,0,dz/d).multiplyScalar((min-d)*5));}if(e.rooted>0||e.stun>0)velocity.multiplyScalar(0);if(e.knock){velocity.add(e.knock);e.knock.multiplyScalar(.84);if(e.knock.length()<.1)e.knock=null;}e.velocity.lerp(velocity,.25);this.physics.move(e.phys,e.velocity,dt);e.speed=e.velocity.length();if(e.speed>.3&&e.cooldown<.2){const a=Math.atan2(e.velocity.x,e.velocity.z);e.facing+=Math.atan2(Math.sin(a-e.facing),Math.cos(a-e.facing))*Math.min(1,dt*8);}e.character.root.rotation.y=e.facing;}
 findPath(start,end){const cell=3,key=(x,z)=>x+','+z,sx=Math.round(start.x/cell),sz=Math.round(start.z/cell),ex=Math.round(end.x/cell),ez=Math.round(end.z/cell);if(Math.hypot(ex-sx,ez-sz)<2)return [end.clone()];if(!this.navGrid){this.navGrid=new Set();for(let x=-40;x<=40;x++)for(let z=-73;z<=17;z++)if(this.world.nav.some(o=>Math.abs(x*cell-o.x)<o.hx&&Math.abs(z*cell-o.z)<o.hz&&o.top>this.world.height(x*cell,z*cell)+.6))this.navGrid.add(key(x,z));}const blocked=(x,z)=>Math.abs(x)>40||z<-73||z>17||this.navGrid.has(key(x,z));const open=[{x:sx,z:sz,g:0,f:0,p:null}],seen=new Map();seen.set(key(sx,sz),0);let found=null,best=open[0],bestDist=1e9;for(let n=0;n<450&&open.length;n++){open.sort((a,b)=>b.f-a.f);const cur=open.pop(),d=Math.hypot(cur.x-ex,cur.z-ez);if(d<bestDist){best=cur;bestDist=d;}if(d<1.5){found=cur;break;}for(const [dx,dz]of [[0,1],[0,-1],[1,0],[-1,0],[1,1],[1,-1],[-1,1],[-1,-1]]){const x=cur.x+dx,z=cur.z+dz;if(blocked(x,z)||(dx&&dz&&(blocked(x,cur.z)||blocked(cur.x,z))))continue;const ng=cur.g+Math.hypot(dx,dz),k=key(x,z);if(seen.has(k)&&seen.get(k)<=ng)continue;seen.set(k,ng);open.push({x,z,g:ng,f:ng+Math.hypot(ex-x,ez-z)*1.05,p:cur});}}const path=[];for(let c=found||best;c?.p;c=c.p)path.push(new T.Vector3(c.x*cell,0,c.z*cell));return path.reverse();}
 battleTick(dt){const b=this.battle;if(!b)return;const m=MISSIONS[b.id];b.time+=dt;b.command=Math.min(220,b.command+dt*(1.6+(b.camp?.5:0)));b.overdrive=Math.max(0,b.overdrive-dt);const alive=this.enemies.filter(e=>!e.dead);b.nextWave-=dt;if(b.wave<m.waves&&(b.nextWave<=0||(b.wave>0&&alive.length===0&&b.nextWave>4)))b.nextWave=Math.min(b.nextWave,4);if(b.wave<m.waves&&b.nextWave<=0)this.spawnWave();if(b.wave>=m.waves&&this.enemies.every(e=>e.dead)){this.victory();return;}for(const t of this.world.towerObjects){t.cooldown=(t.cooldown||0)-dt;t.special=Math.max(0,(t.special||0)-dt);if(t.cooldown>0)continue;const st=defenseStats(t.id,t.level),doctrine=this.store.data.doctrines[t.id],range=st.range*(t.level>=5?(t.id==='tower'?(doctrine==='longwatch'?1.2:.85):1):1),origin=t.model.userData.muzzle.clone().add(t.model.position),target=alive.filter(e=>dist(e.pos,t.model.position)<range).sort((a,b)=>t.id==='ballista'?(b.stats.hp-a.stats.hp):(dist(a.pos,t.model.position)-dist(b.pos,t.model.position)))[0];if(target){t.recoil=.35;t.cooldown=(t.id==='tower'?1.4:4)*(t.level>=5&&t.id==='tower'?(doctrine==='longwatch'?1.2:.8):1)/(b.overdrive>0?1.3:1);const owner={team:'ally',pos:t.model.position,stats:{},phys:null,defense:t.id,rank:t.level,doctrine};let damage=st.damage*(t.id==='ballista'&&t.level>=5&&doctrine==='pinning'?.85:1),special=t.level===10&&t.special===0;if(special)t.special=t.id==='tower'?18:22;t.crew?.attack(t.id==='tower'?'bow':'crossbow',special,0,t.id==='tower'?.85:1.4);if(t.crew)t.crew.root.rotation.y=Math.atan2(target.pos.x-t.x,target.pos.z-t.z);if(t.id==='ballista'){t.model.userData.aim.rotation.y=Math.atan2(target.pos.x-t.x,target.pos.z-t.z)+Math.PI;this.audio.play('bolt',.3);if(special){this.fx.emit('fire',origin,22,{speed:1});damage*=target.type==='brute'||target.type==='boss'?1.8:1.2;}}const fire=()=>this.combat.shoot(owner,target,{damage:special&&t.id==='tower'?damage*.5:damage,type:t.id==='tower'?'arrow':'bolt',speed:t.id==='tower'?31:38,origin,rank:t.level,heavy:special});if(t.id==='ballista'&&special)this.combat.later(.65,fire);else fire();if(special&&t.id==='tower'){this.combat.later(.12,fire);this.combat.later(.24,fire);}}}}

 checkpoint(){if(!this.store.data||!this.hero||this.mode==='title')return;const s=this.store.data;s.position={x:this.hero.pos.x,y:this.hero.pos.y,z:this.hero.pos.z};if(this.battle&&this.mode!=='result'){const pack=e=>({type:e.type,unit:e.unit,pos:{x:e.pos.x,y:e.pos.y,z:e.pos.z},hp:e.hp});s.battle={...this.battle,order:this.order,hero:{pos:{...s.position},hp:this.hero.hp,focus:this.hero.focus,stamina:this.hero.stamina,cooldowns:{...this.hero.cooldowns}},enemies:this.enemies.filter(e=>!e.dead&&!e.training).map(pack),allies:this.allies.filter(e=>!e.dead).map(pack)};}else s.battle=null;s.updated=Date.now();this.store.persist();}
 toast(text){this.ui?.toast(text);}
 frame(now){const dt=Math.min(.10,(now-this.last)/1000);this.last=now;this.metrics.frames++;this.frames.push(dt*1000);if(this.frames.length>600)this.frames.shift();if(this.store.data?.settings.quality==='auto'&&!this.adaptiveLow&&!this.menu&&this.frames.length>=180&&this.metrics.frames%180===0&&this.frames.slice(-180).reduce((a,b)=>a+b,0)/180>34){this.view.quality('low');this.adaptiveLow=true;}if(this.mode==='title'){this.time+=dt;this.view.title(this.time);}else if(this.hero){if(!this.menu&&this.mode==='play'){this.accum+=dt;let steps=0;while(this.accum>=1/60&&steps++<6){this.tick(1/60);this.accum-=1/60;}this.view.update(this,dt);}else{this.accum=0;this.handleEvents();}for(const e of [this.hero,...this.enemies,...this.allies])if(e){const animdt=this.menu?0:dt;e.character.root.visible=e===this.hero||e.pos.distanceTo(this.hero.pos)<100;e.character.update(animdt,{speed:e.speed,grounded:e.phys?.grounded??true,guarding:e.guarding,charging:e.charging,dead:e.dead});}this.ui.hud(dt);}
 for(const n of this.npcs)n.character.update(dt,{speed:0});this.world.update(this.menu?0:dt,this.time);if(!this.menu)this.fx.update(dt,this.time,this.view.camera);if(this.ui.preview){this.ui.preview.update(dt,{speed:this.ui.previewWalking?2:0});if(this.ui.previewSpin)this.view.previewSpin+=dt*.35;}this.view.render(!!this.menu);requestAnimationFrame(t=>this.frame(t));}
 debug(){return {build:BUILD,ready:this.ready,mode:this.mode,menu:this.menu,hero:this.hero?{pos:this.hero.pos.toArray(),hp:this.hero.hp,grounded:this.hero.phys?.grounded,animation:this.hero.character.actionName,weapon:this.hero.stats.weapon}:null,battle:this.battle?{id:this.battle.id,wave:this.battle.wave,time:this.battle.time,gate:this.battle.gate,command:this.battle.command}:null,enemies:this.enemies.filter(e=>!e.dead).length,allies:this.allies.filter(e=>!e.dead).length,projectiles:this.combat?.projectiles.length,particles:this.fx?.particles.length,combat:this.combat?.stats,metrics:this.metrics,render:this.view?.renderer.info.render};}
}
