import {renderAbilities} from './ability-ui.js';
import {HEROES,SPELLS} from './data.js';
import {heroData,heroStats,skillRank,skillPoints,skillSpent,skillGate,xpToNext} from './state.js';
import {sectionTabs,sigil} from './menu-flow.js';
export function renderHero(ui){const s=ui.g.store.data,h=heroData(s),b=HEROES[s.hero],st=heroStats(s),points=skillPoints(s);if(!b.trees[ui.tree])ui.tree=Object.keys(b.trees)[0];
 const tabs=sectionTabs(ui,{overview:'Hero',skills:'Abilities',passives:'Passives',loadout:'Loadout'});
 if(ui.detailTab==='skills')return (ui.abilityFocus?'':tabs)+renderAbilities(ui);
 if(ui.detailTab==='passives')return tabs+'<div class="section-head"><h2>Passive training</h2><span class="tag">'+points+' points</span></div><div class="subtabs skill-trees">'+Object.entries(b.trees).map(([k,n])=>'<button class="'+(ui.tree===k?'active':'')+'" data-action="tree" data-id="'+k+'">'+n+' · '+skillSpent(s,k)+'</button>').join('')+'</div><div class="skill-list">'+b.skills.filter(n=>!n.active&&n.tree===ui.tree).map(n=>{const rank=skillRank(s,n.id),gate=skillGate(s,n.id);return '<article class="card '+(rank?'active':'')+'"><span class="skill-ranks">'+rank+' / '+n.max+'</span><h4>'+n.name+'</h4><small>PASSIVE'+(rank&&rank<n.max?' · NEXT RANK':'')+'</small><p>'+n.effects[Math.min(rank,n.effects.length-1)]+'</p>'+ui.button('skill',n.id,rank>=n.max?'Mastered':gate||'Train · '+(n.cost||1)+' point'+((n.cost||1)>1?'s':''),!!gate||!!ui.g.battle,!gate&&!ui.g.battle)+'</article>';}).join('')+'</div>';
 if(ui.detailTab==='loadout')return tabs+'<h2>Combat abilities</h2><div class="equipped-techniques">'+h.slots.map((id,i)=>'<button data-action="ability-select" data-id="'+id+'">'+sigil(SPELLS[id].icon)+'<span><small>BUTTON '+(i+1)+' · '+(i?'E':'Q')+'</small><b>'+SPELLS[id].name+'</b><small>Rank '+skillRank(s,id)+' · Tap to change</small></span></button>').join('')+'</div>'+ui.button('detail-section','skills','Learn & equip abilities',false,true)+'<h3>Your order</h3><div class="subtabs">'+Object.entries(HEROES).map(([id,v])=>ui.button('hero',id,v.name.replace('The ',''),s.hero===id||!!ui.g.battle)).join('')+'</div>'+ui.button('respec',null,'Refund all skill points',!!ui.g.battle);
 const next=b.skills.filter(n=>n.active&&!skillRank(s,n.id)).sort((a,b)=>a.learnLevel-b.learnLevel)[0];
 return tabs+'<div class="section-head"><h2>Level '+h.level+'</h2><span class="tag">'+points+' skill points</span></div><p class="list-hint">'+Math.floor(h.xp)+' / '+xpToNext(h.level)+' XP to next level</p><div class="xpbar"><i style="width:'+Math.min(100,h.xp/xpToNext(h.level)*100)+'%"></i></div><div class="stats">'+ui.stat('HEALTH',st.hp)+ui.stat('WEAPON DAMAGE',st.damage)+ui.stat('ARMOR',st.armor)+ui.stat('FOCUS',st.focus)+ui.stat('STAMINA',st.stamina)+ui.stat('COMMAND RADIUS',st.supportRadius+' m')+'</div>'+(next?'<p class="ability-unlock-hint"><b>'+next.name+'</b> · '+(h.level>=next.learnLevel?'Ready to learn':'Unlocks at level '+next.learnLevel)+'</p>':'')+ui.button('detail-section','skills','Learn active abilities',false,true);
}
