import {HEROES,SPELLS} from './data.js';
import {heroData,heroStats,skillRank,skillPoints,skillSpent,skillGate,xpToNext} from './state.js';
import {sectionTabs} from './menu-flow.js';
export function renderHero(ui){const s=ui.g.store.data,h=heroData(s),b=HEROES[s.hero],st=heroStats(s),points=skillPoints(s);if(!b.trees[ui.tree])ui.tree=Object.keys(b.trees)[0];
 const tabs=sectionTabs(ui,{overview:'Attributes',skills:'Skills',loadout:'Techniques'});
 if(ui.detailTab==='skills')return tabs+'<div class="section-head"><h2>Shape your oath</h2><span class="tag">'+points+' points</span></div><div class="subtabs skill-trees">'+Object.entries(b.trees).map(([k,n])=>'<button class="'+(ui.tree===k?'active':'')+'" data-action="tree" data-id="'+k+'">'+n+' · '+skillSpent(s,k)+'</button>').join('')+'</div><div class="skill-list">'+b.skills.filter(n=>n.tree===ui.tree).map(n=>{const rank=skillRank(s,n.id),gate=skillGate(s,n.id);return '<article class="card '+(rank?'active':'')+'"><span class="skill-ranks">'+rank+' / '+n.max+'</span><h4>'+n.name+'</h4><small>'+(n.capstone?'CAPSTONE':n.parent?'ADVANCED':'FOUNDATION')+'</small><p>'+n.effects[Math.min(rank,n.effects.length-1)]+'</p>'+ui.button('skill',n.id,rank>=n.max?'Mastered':gate||'Train · '+(n.cost||1)+' point'+((n.cost||1)>1?'s':''),!!gate||!!ui.g.battle,!gate&&!ui.g.battle)+(n.capstone&&rank>0?ui.button('capstone',n.id,h.capstone===n.id?'Active capstone':'Make active',h.capstone===n.id):'')+'</article>';}).join('')+'</div>';
 if(ui.detailTab==='loadout')return tabs+'<h2>Equipped techniques</h2><p class="intro">Choose two learned techniques for combat.</p><div class="slot-row">'+[0,1].map(i=>'<select aria-label="Technique '+(i+1)+'" data-setting="slot" data-slot="'+i+'">'+Object.entries(SPELLS).filter(([id])=>b.starter.includes(id)||skillRank(s,id)>0).map(([id,v])=>'<option value="'+id+'" '+(h.slots[i]===id?'selected':'')+'>'+v.name+'</option>').join('')+'</select>').join('')+'</div><h3>Your order</h3><div class="subtabs">'+Object.entries(HEROES).map(([id,v])=>ui.button('hero',id,v.name.replace('The ',''),s.hero===id||!!ui.g.battle)).join('')+'</div>'+ui.button('respec',null,'Reforge oath · Refund skill points',!!ui.g.battle);
 return tabs+'<div class="section-head"><h2>Level '+h.level+'</h2><span class="tag">'+points+' skill points</span></div><p class="list-hint">'+Math.floor(h.xp)+' / '+xpToNext(h.level)+' XP to next level</p><div class="xpbar"><i style="width:'+Math.min(100,h.xp/xpToNext(h.level)*100)+'%"></i></div><div class="stats">'+ui.stat('HEALTH',st.hp)+ui.stat('WEAPON DAMAGE',st.damage)+ui.stat('ARMOR',st.armor)+ui.stat('FOCUS',st.focus)+ui.stat('STAMINA',st.stamina)+ui.stat('COMMAND RADIUS',st.supportRadius+' m')+'</div>'+ui.button('detail-section','skills','Spend skill points',false,true);
}
