export class Input{
 constructor(canvas){this.keys=new Set();this.joy={x:0,y:0};this.look={x:0,y:0};this.events=[];this.attack=false;this.guard=false;this.enabled=false;this.lookPointer=null;this.joyPointer=null;this.last={x:0,y:0};this.attackPointer=null;
  // iOS long-press selection/callouts must not steal a held combat pointer.
  const hud=document.getElementById('hud');
  for(const type of ['selectstart','contextmenu'])hud.addEventListener(type,e=>e.preventDefault());
  hud.addEventListener('touchstart',e=>{if(e.target.closest('[data-control], #joystick'))e.preventDefault();},{passive:false});
  window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;this.keys.add(e.code);if(e.code==='Space')this.events.push('jump');if(e.code==='KeyF')this.events.push('interact');if(e.code==='KeyQ')this.events.push('spell0');if(e.code==='KeyE')this.events.push('spell1');if(e.code==='KeyR')this.events.push('potion');if(e.code==='KeyV')this.events.push('camera');if(e.code==='Escape')this.events.push('pause');if(e.code==='Tab')this.events.push('army');if(e.code==='KeyC')this.events.push('character');if(e.code==='KeyH')this.events.push('mount');if(e.code==='KeyM')this.events.push('campaign');if(e.code.startsWith('Digit'))this.events.push('recruit'+e.code.slice(-1));if(e.code==='KeyJ')this.attack=true;if(e.code==='KeyK')this.guard=true;});
  window.addEventListener('keyup',e=>{const pressed=this.keys.has(e.code);this.keys.delete(e.code);if(e.code==='KeyJ'){if(pressed&&this.attack)this.events.push('release');this.attack=false;}if(e.code==='KeyK')this.guard=false;});
  canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(!this.enabled)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);if(e.pointerType==='touch'||e.button===2){this.lookPointer=e.pointerId;this.last={x:e.clientX,y:e.clientY};}else if(e.button===0){this.attack=true;this.attackPointer=e.pointerId;}});
  canvas.addEventListener('pointermove',e=>{if(e.pointerId===this.lookPointer){this.look.x+=e.clientX-this.last.x;this.look.y+=e.clientY-this.last.y;this.last={x:e.clientX,y:e.clientY};}});
  const up=e=>{if(e.pointerId===this.lookPointer)this.lookPointer=null;if(e.pointerId===this.attackPointer){this.attack=false;this.attackPointer=null;if(e.type==='pointerup')this.events.push('release');else this.events.push('cancelAttack');}};canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('lostpointercapture',up);
  const joy=document.getElementById('joystick'),knob=document.getElementById('joy-knob');const joyMove=e=>{const rect=joy.getBoundingClientRect(),x=e.clientX-rect.left-rect.width/2,y=e.clientY-rect.top-rect.height/2,len=Math.hypot(x,y),max=rect.width*.32,f=Math.min(1,max/Math.max(len,.001));this.joy={x:x*f/max,y:-y*f/max};knob.style.transform=`translate(${x*f}px,${y*f}px)`;};joy.addEventListener('pointerdown',e=>{if(!this.enabled)return;e.preventDefault();joy.setPointerCapture(e.pointerId);this.joyPointer=e.pointerId;joyMove(e);});joy.addEventListener('pointermove',e=>{if(e.pointerId===this.joyPointer)joyMove(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(event,e=>{if(e.pointerId!==this.joyPointer)return;this.joyPointer=null;this.joy={x:0,y:0};knob.style.transform='';});
  document.querySelectorAll('[data-control]').forEach(b=>{const id=b.dataset.control;b.addEventListener('pointerdown',e=>{if(!this.enabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);b.classList.add('held');if(id==='attack'){this.attack=true;this.attackPointer=e.pointerId;}else if(id==='guard')this.guard=true;else this.events.push(id);});const release=e=>{b.classList.remove('held');if(id==='attack'&&e.pointerId===this.attackPointer){this.attack=false;this.attackPointer=null;this.events.push(e.type==='pointerup'?'release':'cancelAttack');}else if(id==='guard')this.guard=false;};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,release);});
  window.addEventListener('blur',()=>this.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.clear();});
 }
 axes(){let x=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0)+this.joy.x,y=(this.keys.has('KeyW')?1:0)-(this.keys.has('KeyS')?1:0)+this.joy.y;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l;}return {x,y,magnitude:Math.min(1,l)};}
 consume(){return this.events.splice(0);}
 clear(){this.keys.clear();this.joy={x:0,y:0};this.attack=false;this.guard=false;this.attackPointer=null;this.joyPointer=null;this.lookPointer=null;this.events=[];this.look={x:0,y:0};const knob=document.getElementById('joy-knob');if(knob)knob.style.transform='';document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));}
}
