import {rosterList,sectionTabs} from './menu-flow.js';
import {fieldDefenseCost} from './field-command.js';
import {UNITS,DEFENSES,MISSIONS,ROMAN,unitCost} from './data.js';
import {unitUnlocked,defenseUnlocked,campaignCap} from './state.js';
import {EMPLACEMENTS} from './roster.js';
import {unitInspection,defenseInspection,statNumber as n} from './inspection.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metric=(key,label,value,detail='')=>'<div class="combat-stat" data-stat="'+key+'"><small>'+label+'</small><b>'+esc(value)+'</b>'+(detail?'<span>'+detail+'</span>':'')+'</div>';
const track=(rank,view)=>'<div class="rank-track" aria-label="Inspect upgrade rank">'+ROMAN.map((r,i)=>'<button class="'+(i<rank?'owned ':'')+(view===i+1?'active':'')+'" data-action="rank" data-value="'+(i+1)+'">'+r+'</button>').join('')+'</div>';
function abilities(list,rank){return '<div class="unit-abilities"><h3>Abilities & special effects</h3>'+list.map(a=>'<article class="combat-ability '+(rank<a.unlock?'ability-locked':'')+'" data-unlock="'+a.unlock+'"><h4>'+a.name+' <small>'+(rank<a.unlock?'UNLOCKS AT RANK '+ROMAN[a.unlock-1]:'ACTIVE AT THIS RANK')+'</small></h4><p>'+a.text+'</p></article>').join('')+'</div>';}
function comparison(a,b,from,to,kind){const rows=kind==='unit'?[['hp','Health'],['damage','Damage / hit'],['armor','Armor'],['reach','Range',' m'],['attackInterval','Attack cycle',' s',-1],['speed','Movement',' m/s'],['cost','Deployment',' Command',-1]]:[['hp','Gate health'],['damage',kind==='sanctuary'?'Healing / target':'Damage / hit'],['range','Range',' m'],['interval','Attack cycle',' s',-1]];
 const shown=rows.filter(([key])=>!(key==='hp'&&a.protected)&&Number.isFinite(a[key])&&n(a[key])!==n(b[key]));
 return '<div class="rank-comparison"><h3>'+esc(from)+' → '+esc(to)+'</h3>'+(shown.length?shown.map(([key,label,suffix='',direction=1])=>'<div class="compare-row"><span>'+label+'</span><b>'+n(a[key])+suffix+' → '+n(b[key])+suffix+' <em class="'+((b[key]-a[key])*direction>0?'stat-gain':'stat-loss')+'">('+(b[key]>a[key]?'+':'')+n(b[key]-a[key])+')</em></b></div>').join(''):'<p class="intro">Core values match this rank. Check the abilities below for new effects.</p>')+'</div>';
}
export function renderTroops(ui){
 if(ui.screen!=='detail')return rosterList(ui,'troops');
 const s=ui.g.store.data,id=ui.unit,u=UNITS[id],rank=s.units[id],view=ui.previewRank||rank,unlocked=unitUnlocked(s,id),st=unitInspection(id,view,ui.battleCommand?ui.g.battle:null),section=ui.detailTab;
 const tabs=sectionTabs(ui,{overview:'Overview',stats:'Stats',abilities:'Abilities',...(!ui.battleCommand?{upgrade:'Upgrade'}:{})}),field=ui.g.allies.filter(a=>!a.dead&&a.unit===id);
 let content='';
 if(section==='stats')content=metric('hp','HEALTH',st.hp,'per soldier')+metric('damage','DAMAGE',st.damage,'per hit')+metric('armor','ARMOR',st.armor,n(st.mitigation)+'% hit reduction')+metric('attackInterval','ATTACK CYCLE',n(st.attackInterval)+' s')+metric('reach','ATTACK RANGE',n(st.reach)+' m')+metric('dps','DIRECT DPS',n(st.dps),'before armor; excludes abilities')+metric('speed','MOVEMENT',n(st.speed)+' m/s')+metric('count','SQUAD SIZE',u.count)+metric('cost','DEPLOYMENT',st.cost,'Command per squad');
 else if(section==='abilities')content=abilities(st.abilities,view);
 else if(section==='upgrade')content=track(rank,view)+(view!==rank?comparison(unitInspection(id,rank),st,'Owned '+ROMAN[rank-1],'Preview '+ROMAN[view-1],'unit'):rank<10?comparison(st,unitInspection(id,rank+1),'Current '+ROMAN[rank-1],'Next '+ROMAN[rank],'unit'):'')+'<div class="upgrade-panel"><h3>'+(u.spec?.names?.[view-1]||u.name+' '+ROMAN[view-1])+'</h3><p>'+esc(u.spec?.appearance?.[view-1]||ui.rankDescription(view))+'</p>'+ui.button('upgrade-unit',id,!unlocked?'Unlock · '+u.unlock+' victories':rank>=10?'Fully trained':rank>=campaignCap(s)?'Reclaim the next act':'Train to '+ROMAN[rank]+' · '+unitCost(id,rank)+' Supplies',!unlocked||rank>=10||rank>=campaignCap(s)||!!ui.g.battle||s.supplies<unitCost(id,rank),true)+'</div><p class="inspection-note">Select a rank to preview its appearance and stats. Ranks VI–VII unlock after 5 victories; VIII–X after 10.</p>';
 else content='<p class="object-role">'+u.role+'</p><div class="combat-stats overview-stats">'+metric('hp','HEALTH',st.hp)+metric('damage','DAMAGE',st.damage)+metric('armor','ARMOR',st.armor)+'</div><p class="list-hint">'+u.count+' soldier'+(u.count>1?'s':'')+' · '+st.cost+' Command per squad</p>'+(!unlocked?'<p class="unlock-note">Unlock after '+u.unlock+' victories.</p>':'')+(ui.battleCommand?ui.button('recruit',id,'Deploy · ⚑ '+st.cost,!unlocked||ui.g.battle.command<st.cost||ui.g.allies.filter(a=>!a.dead).length+u.count>24,true):ui.button('detail-section','upgrade','Train & preview upgrades',false,true));
 return tabs+'<section class="inspection-detail" data-inspection="unit" data-type="'+id+'" data-rank="'+view+'">'+(section==='stats'?'<p class="inspection-note">Per soldier. Completed battle research is included; enemy armor and short-lived buffs are not.</p><div class="combat-stats">'+content+'</div>'+(ui.battleCommand?'<p class="field-status">On the field: '+field.length+' soldiers · '+Math.ceil(field.reduce((n,a)=>n+a.hp,0))+' / '+field.reduce((n,a)=>n+a.stats.hp,0)+' combined health.</p>':''):content)+'</section>';
}
export function renderDefenses(ui){
 if(ui.screen!=='detail')return rosterList(ui,'defenses');
 const g=ui.g,s=g.store.data,id=ui.defense,d=DEFENSES[id],rank=s.defenses[id],view=ui.previewRank||rank,doctrine=s.doctrines[id],st=defenseInspection(id,view,doctrine,ui.battleCommand?g.battle:null),owned=defenseInspection(id,rank,doctrine),available=defenseUnlocked(s,id),healing=id==='sanctuary',section=ui.detailTab;
 const tabs=sectionTabs(ui,{overview:'Overview',stats:'Stats',abilities:'Abilities',...(!ui.battleCommand?{upgrade:'Upgrade',...(id!=='gate'?{emplacements:'Fit'}:{})}:{})});
 const core=id==='gate'?metric('hp','GATE HEALTH',st.hp)+(g.battle?metric('currentHp','CURRENT HEALTH',Math.ceil(g.battle.gate)):'')+metric('beacon','BEACON HEALTH',g.battle?Math.ceil(g.battle.core)+' / 650':650):metric('health','HEALTH','Protected')+metric('damage',healing?'HEALING':'DAMAGE',n(st.damage))+metric('range','RANGE',n(st.range)+' m',st.minRange?'Minimum '+st.minRange+' m':'');
 let content='';
 if(section==='stats')content='<div class="combat-stats">'+core+(id==='gate'?'':metric('interval',healing?'HEALING CYCLE':'ATTACK CYCLE',n(st.interval)+' s')+metric('dps',healing?'HEALING / SECOND':'DIRECT DPS',n(st.dps))+metric('targets','TARGETS',healing?'Up to 4':id==='storm'?'Up to 3':['mortar','cannon'].includes(id)?'Area':'Single'))+'</div><p class="inspection-note">'+(st.protected?'Emplacements cannot take damage. Enemies attack the gate, then the beacon. ':'')+'Values are before armor and temporary buffs.'+(view>=5&&['tower','ballista'].includes(id)?' Includes '+doctrine+' doctrine.':'')+'</p>';
 else if(section==='abilities')content=abilities(st.abilities,view)+(['tower','ballista'].includes(id)?'<h3>Firing doctrine · Rank V</h3><div class="subtabs">'+(id==='tower'?['longwatch','suppression']:['piercing','pinning']).map(value=>ui.button('doctrine',id,(doctrine===value?'✓ ':'')+value,rank<5||!!g.battle,false,value)).join('')+'</div>':'');
 else if(section==='upgrade')content=track(rank,view)+(view!==rank?comparison(owned,st,'Owned '+ROMAN[rank-1],'Preview '+ROMAN[view-1],id):rank<10?comparison(st,defenseInspection(id,rank+1,doctrine),'Current '+ROMAN[rank-1],'Next '+ROMAN[rank],id):'')+'<div class="upgrade-panel"><h3>'+d.name+' '+ROMAN[view-1]+(view!==rank?' · Preview':'')+'</h3><p>'+esc(d.appearance?.[view-1]||'A heavier gate, stronger bracing and new fittings at every rank.')+'</p>'+ui.button('upgrade-defense',id,!available?'Plans locked · '+d.unlock+' victories':rank>=10?'Fully constructed':rank>=campaignCap(s)?'Reclaim the next act':'Construct '+ROMAN[rank]+' · '+(d.costs[rank-1]||0)+' Supplies',!available||rank>=10||rank>=campaignCap(s)||!!g.battle||s.supplies<(d.costs[rank-1]||0),true)+'</div>';
 else if(section==='emplacements')content='<p class="list-hint">Fit owned defenses freely at the castle.</p><div class="placement-list">'+EMPLACEMENTS.map((slot,i)=>'<div><b>'+slot.name+'</b><span>'+DEFENSES[s.defenseLayout[i]].name+'</span>'+ui.button('refit',i,s.defenseLayout[i]===id?'Installed':'Fit '+d.name,!available||!!g.battle||s.defenseLayout[i]===id)+'</div>').join('')+'</div>';
 else content='<p class="object-role">'+d.desc+'</p><div class="combat-stats overview-stats">'+core+'</div>'+(!available?'<p class="unlock-note">Plans unlock after '+d.unlock+' victories.</p>':'')+(ui.battleCommand?ui.button('field-select',id,(id==='gate'?'Repair +250 health':'Choose emplacement')+' · ⚑ '+fieldDefenseCost(id),!available||g.battle.command<fieldDefenseCost(id)||(id==='gate'&&(g.battle.gate>=g.battle.maxGate||g.battle.gate<=0)),true):ui.button('detail-section','upgrade','Construct & preview upgrades',false,true));
 return tabs+'<section class="inspection-detail" data-inspection="defense" data-type="'+id+'" data-rank="'+view+'">'+content+'</section>';
}
export function renderArmy(ui){return rosterList(ui,'troops',true);}
