import {UNITS,DEFENSES,MISSIONS,ROMAN,unitCost} from './data.js';
import {unitUnlocked,defenseUnlocked,campaignCap} from './state.js';
import {EMPLACEMENTS} from './roster.js';
import {unitInspection,defenseInspection,statNumber as n} from './inspection.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metric=(key,label,value,detail='')=>'<div class="combat-stat" data-stat="'+key+'"><small>'+label+'</small><b>'+esc(value)+'</b>'+(detail?'<span>'+detail+'</span>':'')+'</div>';
const track=(rank,view)=>'<div class="rank-track" aria-label="Inspect upgrade rank">'+ROMAN.map((r,i)=>'<button class="'+(i<rank?'owned ':'')+(view===i+1?'active':'')+'" data-action="rank" data-value="'+(i+1)+'">'+r+'</button>').join('')+'</div>';
function picker(s,kind,selected){const items=kind==='unit'?UNITS:DEFENSES,unlocked=kind==='unit'?unitUnlocked:defenseUnlocked;return '<div class="subtabs inspection-picker" aria-label="Choose '+(kind==='unit'?'regiment':'defense')+'">'+Object.entries(items).map(([id,u])=>'<button class="'+(selected===id?'active':'')+'" data-action="'+kind+'" data-id="'+id+'">'+u.name+(unlocked(s,id)?'':' ◇')+'</button>').join('')+'</div>';}
function abilities(list,rank){return '<div class="unit-abilities"><h3>Abilities & special effects</h3>'+list.map(a=>'<article class="combat-ability '+(rank<a.unlock?'ability-locked':'')+'" data-unlock="'+a.unlock+'"><h4>'+a.name+' <small>'+(rank<a.unlock?'UNLOCKS AT RANK '+ROMAN[a.unlock-1]:'ACTIVE AT THIS RANK')+'</small></h4><p>'+a.text+'</p></article>').join('')+'</div>';}
function comparison(a,b,from,to,kind){const rows=kind==='unit'?[['hp','Health'],['damage','Damage / hit'],['armor','Armor'],['reach','Range',' m'],['attackInterval','Attack cycle',' s',-1],['speed','Movement',' m/s'],['cost','Deployment',' Command',-1]]:[['hp','Gate health'],['damage',kind==='sanctuary'?'Healing / target':'Damage / hit'],['range','Range',' m'],['interval','Attack cycle',' s',-1]];
 const shown=rows.filter(([key])=>!(key==='hp'&&a.protected)&&Number.isFinite(a[key])&&n(a[key])!==n(b[key]));
 return '<div class="rank-comparison"><h3>'+esc(from)+' → '+esc(to)+'</h3>'+(shown.length?shown.map(([key,label,suffix='',direction=1])=>'<div class="compare-row"><span>'+label+'</span><b>'+n(a[key])+suffix+' → '+n(b[key])+suffix+' <em class="'+((b[key]-a[key])*direction>0?'stat-gain':'stat-loss')+'">('+(b[key]>a[key]?'+':'')+n(b[key]-a[key])+')</em></b></div>').join(''):'<p class="intro">Core values match this rank. Check the abilities below for new effects.</p>')+'</div>';
}
export function unitPanel(ui,id,view,{army=false}={}){
 const g=ui.g,s=g.store.data,u=UNITS[id],owned=s.units[id],st=unitInspection(id,view),current=unitInspection(id,owned);
 const field=g.allies.filter(a=>!a.dead&&a.unit===id),tag=view===owned?'CURRENT':'PREVIEW · OWNED '+ROMAN[owned-1];
 return '<section class="inspection-detail" data-inspection="unit" data-type="'+id+'" data-rank="'+view+'"><div class="section-head inspection-title"><h2>'+u.name+'</h2><span class="tag">RANK '+ROMAN[view-1]+' · '+tag+'</span></div><p class="inspection-note">Per soldier, before enemy armor and temporary battlefield buffs. Deployment cost buys the whole squad.</p><div class="combat-stats">'+
 metric('hp','HEALTH',st.hp,'per soldier')+metric('damage','DAMAGE',st.damage,'per hit')+metric('armor','ARMOR',st.armor,n(st.mitigation)+'% hit reduction')+
 metric('attackInterval','ATTACK CYCLE',n(st.attackInterval)+' s','between attacks')+metric('reach','ATTACK RANGE',n(st.reach)+' m',u.reach>10?'ranged fire':'melee reach')+metric('dps','DIRECT DPS',n(st.dps),'one target; excludes abilities')+
 metric('speed','MOVEMENT',n(st.speed)+' m/s')+metric('count','SQUAD SIZE',u.count,'soldier'+(u.count===1?'':'s')+' per deployment')+metric('cost','DEPLOYMENT',st.cost,'Command per squad')+'</div>'+
 (army&&g.battle?'<p class="field-status">On the field: <b>'+field.length+' '+u.name+'</b> · '+Math.ceil(field.reduce((v,a)=>v+a.hp,0))+' / '+field.reduce((v,a)=>v+a.stats.hp,0)+' combined health.</p>':'')+
 (!army?(view!==owned?comparison(current,st,'Owned '+ROMAN[owned-1],'Preview '+ROMAN[view-1],'unit'):owned<10?comparison(st,unitInspection(id,owned+1),'Current '+ROMAN[owned-1],'Next '+ROMAN[owned],'unit'):''):'')+abilities(st.abilities,view)+'</section>';
}
export function renderTroops(ui){const s=ui.g.store.data,id=ui.unit,u=UNITS[id],rank=s.units[id],view=ui.previewRank||rank,unlocked=unitUnlocked(s,id);
 return '<p class="intro inspection-intro">Choose a regiment and rank to inspect its stats, abilities and animated equipment.</p>'+picker(s,'unit',id)+track(rank,view)+unitPanel(ui,id,view)+'<div class="upgrade-panel"><h3>'+(u.spec?.names?.[view-1]||u.name+' '+ROMAN[view-1])+'</h3><p>'+esc(u.spec?.appearance?.[view-1]||ui.rankDescription(view))+'</p>'+(!unlocked?'<p>Unlock after '+u.unlock+' campaign victories.</p>':'')+ui.button('upgrade-unit',id,!unlocked?'Locked · '+u.unlock+' victories':rank>=10?'Fully trained':rank>=campaignCap(s)?'Reclaim the next act to train further':'Train to '+ROMAN[rank]+' · '+unitCost(id,rank)+' Supplies',!unlocked||rank>=10||rank>=campaignCap(s)||!!ui.g.battle,true)+'</div><p class="inspection-note">Ranks I–V: Act I · VI–VII: reclaim five castles · VIII–X: reclaim ten castles. Selecting a future rank only previews it.</p>';
}
export function renderDefenses(ui){const g=ui.g,s=g.store.data,id=ui.defense,d=DEFENSES[id],rank=s.defenses[id],view=ui.previewRank||rank,doctrine=s.doctrines[id],st=defenseInspection(id,view,doctrine),owned=defenseInspection(id,rank,doctrine),available=defenseUnlocked(s,id),healing=id==='sanctuary';
 const stats=id==='gate'?metric('hp','GATE HEALTH',st.hp,'maximum at this rank')+(g.battle&&view===rank?metric('currentHp','CURRENT HEALTH',Math.ceil(g.battle.gate),'in this battle'):'')+metric('beacon','BEACON HEALTH',g.battle?Math.ceil(g.battle.core)+' / 650':650,'vulnerable after gate falls')+metric('damage','DAMAGE',0,'defensive barrier'):
 metric('health','HEALTH','Protected','cannot be damaged')+metric('damage',healing?'HEALING':id==='mortar'?'AREA DAMAGE':'DAMAGE',n(st.damage),healing?'per target, per pulse':id==='mortar'?'per impact':'per hit')+metric('range','RANGE',n(st.range)+' m',st.minRange?'minimum: '+st.minRange+' m':'from emplacement')+metric('interval',healing?'HEALING CYCLE':'ATTACK CYCLE',n(st.interval)+' s',healing?'between pulses':'between attacks')+metric('dps',healing?'HEALING / SECOND':id==='mortar'?'AREA DPS':'DIRECT DPS',n(st.dps),healing?'per target, while wounded':'before armor; excludes bonuses')+metric('targets',healing?'HEAL TARGETS':'TARGETS',healing?'Up to 4':id==='storm'?'Up to 3':['mortar','cannon'].includes(id)?'Area':'Single',healing?'lowest health percentage first':id==='storm'?'chain jumps':'see abilities below');
 return '<p class="intro inspection-intro">Inspect every defense and upgrade rank. Weapon and support defenses fit into four castle emplacements.</p>'+picker(s,'defense',id)+track(rank,view)+'<section class="inspection-detail" data-inspection="defense" data-type="'+id+'" data-rank="'+view+'"><div class="section-head inspection-title"><h2>'+d.name+'</h2><span class="tag">RANK '+ROMAN[view-1]+' · '+(view===rank?'CURRENT':'PREVIEW · OWNED '+ROMAN[rank-1])+'</span></div><div class="combat-stats">'+stats+'</div><p class="inspection-note">'+(st.protected?'Emplacements cannot take damage. Enemies attack the gate, then the beacon. ':'')+(view>=5&&['tower','ballista'].includes(id)?'Stats include '+esc(doctrine)+' doctrine. ':'')+'Damage is shown before enemy armor and battlefield buffs.</p>'+(view!==rank?comparison(owned,st,'Owned '+ROMAN[rank-1],'Preview '+ROMAN[view-1],id):rank<10?comparison(st,defenseInspection(id,rank+1,doctrine),'Current '+ROMAN[rank-1],'Next '+ROMAN[rank],id):'')+abilities(st.abilities,view)+'</section>'+
 (['tower','ballista'].includes(id)?'<h3>Firing doctrine · Rank V</h3><div class="subtabs">'+(id==='tower'?['longwatch','suppression']:['piercing','pinning']).map(value=>ui.button('doctrine',id,(doctrine===value?'✓ ':'')+value,rank<5||!!g.battle,false,value)).join('')+'</div><p class="inspection-note">'+(rank<5?'Train to rank V to choose a doctrine.':'Changing doctrine immediately updates the stats above.')+'</p>':'')+
 (id!=='gate'?'<h3>Castle emplacements</h3><div class="emplacement-grid">'+EMPLACEMENTS.map((slot,i)=>'<div><small>'+slot.name.toUpperCase()+'</small><b>'+DEFENSES[s.defenseLayout[i]].name+'</b>'+ui.button('refit',i,s.defenseLayout[i]===id?'Installed':'Fit '+d.name,!available||!!g.battle||s.defenseLayout[i]===id)+'</div>').join('')+'</div>':'')+
 '<div class="upgrade-panel"><h3>'+d.name+' '+ROMAN[view-1]+(view!==rank?' · Preview':'')+'</h3><p>'+esc(d.appearance?.[view-1]||'A heavier gate, stronger bracing and new fittings at every rank.')+'</p>'+(!available?'<p>Recover these plans by reclaiming '+d.unlock+' castles: '+MISSIONS[d.unlock-1].name+'.</p>':'')+ui.button('upgrade-defense',id,!available?'Plans locked · '+d.unlock+' victories':rank>=10?'Fully constructed':rank>=campaignCap(s)?'Reclaim the next act to construct further':'Construct '+ROMAN[rank]+' · '+(d.costs[rank-1]||0)+' Supplies',!available||rank>=10||rank>=campaignCap(s)||!!g.battle,true)+'</div>';
}
export function renderArmy(ui){const g=ui.g,b=g.battle,s=g.store.data;
 return '<div class="section-head"><h2>Army & orders</h2><span class="tag">'+(b?Math.floor(b.command)+' COMMAND':'AT HEARTHWATCH')+'</span></div><div class="troop-orders">'+['hold','follow','assault'].map(id=>ui.button('order',id,(g.order===id?'✓ ':'')+{hold:'Hold here',follow:'Follow me',assault:'Assault'}[id],!b)).join('')+'</div>'+picker(s,'unit',ui.unit)+unitPanel(ui,ui.unit,s.units[ui.unit],{army:true})+'<h3>Deploy reinforcements</h3><p class="inspection-note">Command regenerates in battle. Orders apply to every surviving soldier. You can field up to 24 soldiers.</p><div class="cards">'+Object.entries(UNITS).map(([id,u])=>{const available=unitUnlocked(s,id),st=unitInspection(id,s.units[id]);return '<article class="card '+(id===ui.unit?'active ':'')+(!available?'locked':'')+'"><h4>'+u.name+' '+ROMAN[s.units[id]-1]+'</h4><p>'+u.role+'</p><div class="recruit-stats">'+st.hp+' health · '+st.damage+' damage per soldier</div><div class="meta">'+u.count+' soldier'+(u.count>1?'s':'')+' · '+st.cost+' Command</div>'+ui.button('inspect-army',id,'Inspect stats')+ui.button('recruit',id,available?'Deploy · '+st.cost:'Unlock · '+u.unlock+' victories',!available||!b||b.command<st.cost,true)+'</article>';}).join('')+'</div><div class="row"><span>Field army</span><b>'+g.allies.filter(a=>!a.dead).length+' / 24 soldiers</b></div>';
}
