import {EXTRA_LOCATIONS,SETTLEMENTS,MAIN_COUNT} from './campaign.js';
import * as T from 'three';
import {MISSIONS,UNITS,DEFENSES} from './data.js';
const $=id=>document.getElementById(id);
export const PROLOGUE=[
 {speaker:'SERA · KEEPER OF THE WAR TABLE',title:'The lights went out one by one.',text:'The beacons once carried our dead home. Then Marshal Veyr tried to break the oath that bound their voices. Every light he touched turned cold. Now the fallen march under his command—even the people we buried ourselves.'},
 {speaker:'IONA · QUARTERMASTER',title:'There are people on the road.',text:'My brother is bringing the last families in from Reedwater. They have children, carts, and no soldiers. If Hearthwatch falls tonight, there is nowhere left for them to go. That is why this ember matters.'},
 {speaker:'CAPTAIN ROWAN · YOUR FIRST ORDERS',title:'Learn here. Then stand with us.',text:'Practice your movement, quick strike, charged attack and magic in the courtyard. I will show you our regiments; Nell will explain the defenses. When you are ready, speak to Sera at the war table—or tap “Start first defense.” Training is optional and can be restarted from the Journal.'}
];
// Briefings describe the playable hold-the-beacon mission, not imaginary escort or siege mechanics.
export const CHAPTERS=[
 ['Sera','Keep a road home open.','The families from Reedwater are still out there. Hold Hearthwatch’s outer approaches against three waves while the road behind the keep is evacuated. Keep the beacon burning so they have a light to follow home.','Start with Shieldward and Longbows. Tap RESEARCH to begin up to four temporary upgrades; timers run while you fight. Recruit more squads using their icons at upper left. Use COMMAND → Orders to regroup on either flank.','Iona finds a strip of her brother’s green scarf among the arrivals. He went back for the bridge watch. We have bought time, not safety. Sera marks Reedwater Ford on the map.'],
 ['Nell','We need the bridge watch.','The Hollow Host is using the ford to reach our supply road. Establish a beacon foothold here and hold both approaches. Recovering this position lets my engineers bring their workshop plans to Hearthwatch.','Keep ranged soldiers on firm ground. Shift your line between the crossings instead of chasing every scout.','The watch is alive. Iona’s brother stayed to carry a wounded engineer across the ford. Among their supplies are cannon drawings and the names of prisoners taken to the quarry.'],
 ['Rowan','People are trapped beneath the stone.','The quarry once built our walls. Now swift dead patrol its terraces. Hold the field beacon so the survivors have a safe route out of the excavation.','Raven runners rush the flanks. Pikeguard and slow effects stop them before they reach the gate.','The quarry survivors speak of voices in the forest. The Lanternkeepers and Veil blades offer their service. One rescued mason recognizes the voice of his dead daughter.'],
 ['Iona','A voice is not a promise.','The lantern order refuses to abandon Thorn Abbey. Grave callers mimic the voices of loved ones to draw the living into the trees. Defend the new beacon until the abbey’s road is secure.','Iron revenants join the front line. Charged strikes, flanking and Pikeguard answer their armor.','The abbey’s records reveal that Veyr cannot command a soul whose name is remembered freely. Sera takes the book of names. Cinder adepts recover their lost art among its pages.'],
 ['Sera','Our first answer to Veyr.','The Bell Knight blocks the road north. His bell drowns out every voice that refuses the marshal. Survive the attack and defeat him in the final wave to open the next act.','Train before departing. Rime obelisks slow the rush; keep a reserve of Command for fallen squads.','The bell breaks. For one moment the dead remember their own names. Rowan hears his former captain thank him. The foundry road opens, and veteran training becomes available.'],
 ['Torren','Take back the fire.','I built the foundry gates. I never imagined they would keep the living out. Establish a foothold outside the works and defeat the waves protecting Veyr’s furnaces.','Cinder bombers join the attack. Move out of orange warning circles and hunt the throwers before their bombs reach the gate.','The foundry is ours again. Its ledgers describe a crown designed to bind every beacon at once. The Siege crew and Ironwatch marksmen bring their recovered weapons to your ranks.'],
 ['Nell','One army. Two banks.','Our supply columns must cross the split river before Veyr seals the northern road. Hold this foothold against attacks arriving across both banks.','War heralds carry banners that strengthen nearby enemies. Hunt them first, then personally reinforce the weak bank. Field engineers can repair a damaged gate.','The bridge crews arrive. A frostbound scholar carries a warning from Frostmere: Veyr has begun taking voices from the living as well.'],
 ['Sera','The lake has stopped singing.','Frostmere’s beacon is silent, but its watch still holds the ice road. Keep our foothold alive while the last defenders withdraw into your protection.','Blackfeather hunters fire slow, powerful arrows over long distances. Use cover between shots. Slow enemies with Rime scholars and protect your line with a Sanctuary brazier.','The watch joins you. Their commander remembers the riders who vanished in the western downs. A sanctuary ember survives beneath the ice.'],
 ['Rowan','Leave room for the riders.','The old cavalry has been fighting alone beyond the downs. Hold the open approaches and give them somewhere to regroup. The field is wide; use it.','Siege brutes enter the field. Focus ballistae and armor piercing troops on their heavy armor. Lead a flank while your shields hold the central approach.','The riders bring news of the Buried Crown: Veyr’s second captain keeps the stolen names there. Nell rebuilds a storm spire from their recovered copperwork.'],
 ['Sera','Names beneath the sand.','The Ash Castellan guards a city full of captive memories. Defend your beacon through the siege and defeat him in the final wave. The names must survive.','Bring armor piercing troops and a plan for large targets. A healing emplacement trades damage for endurance.','The Castellan falls. The rescued names reveal Veyr’s fear: without the beacon oath, he thinks every soul will simply vanish. The Sun sworn join you, and the final training ranks open.'],
 ['Iona','The roots remember.','The oldest beacon stood in Blackroot Reach. Its roots hold the first oath, written before any marshal claimed it. Hold the field while Sera searches its meaning.','Grave bulwarks shield their front. Flank their formation or break their guard with charged strikes.','The first oath was a promise of shelter, never ownership. The dead are bound because the living forgot the difference. An old giant has guarded the original stone for centuries.'],
 ['Rowan','A promise older than the crown.','The Giant’s Stair leads to that stone. Prove that you can shelter the living by holding this approach against Veyr’s army.','High ground separates the fronts. Your Oathbound giant can hold a broad melee line, but still needs ranged support.','The giant gives Sera the first oath: “A fire for every traveler. A door that opens both ways.” We can free the voices without extinguishing the beacons.'],
 ['Nell','The last road to the crown.','Glasswater is the final supply crossing. Veyr knows what Sera carries. Defend the beacon here so our army can reach the frozen watch together.','Bone menders heal nearby enemies. Kill them first. Five waves test your reserves; keep Command for reinforcements.','The crossing holds. Across the water, the Frozen Beacon flares once in answer. Someone inside Veyr’s kingdom is still listening.'],
 ['Sera','Let the living answer.','Before we face Veyr, one more beacon must burn freely. Hold the frozen approaches while its wardens replace the marshal’s oath with the original promise.','Use the width of the field. Your final defense layout should balance large-target damage, crowd control and survival.','The beacon answers in a thousand voices. None are commanded to stay. Some depart; others choose to guide us. Veyr’s crown cracks, and the road opens.'],
 ['Sera','No more borrowed souls.','At the Crown of Ash, Veyr brings his last army. Hold our beacon through five waves and defeat the marshal. We came to open the door, not to claim his throne.','Grave callers now cast slowing frost bolts. Commit your strongest regiments and protect the beacon while Veyr is on the field.','Veyr hears the voices leave of their own accord. The crown falls from his hands. Hearthwatch’s ember burns on—not as a prison, but as a light a traveler may choose to follow.']
].map(([speaker,title,brief,tactics,aftermath])=>({speaker,title,brief,tactics,aftermath}));
for(const [name,biome,title,story] of EXTRA_LOCATIONS)CHAPTERS.push({speaker:'Sera',title,brief:story,tactics:'Study the enemy counters at the war table. Veteran support troops, armor piercing weapons and trained defenses matter on these fronts.',aftermath:name==='The First Ember'?'The Hollow King falls. Each rescued city lights a fire of its own. The voices choose their journeys, and Hearthwatch opens its gates.':'The beacon at '+name+' burns freely. The rescued voices reveal the road ahead.'});
for(const city of SETTLEMENTS)CHAPTERS.push({speaker:'Iona',title:city.title,brief:city.story+' This optional rescue strengthens the kingdom without advancing the main story.',tactics:'Hold the local beacon through every wave. Once rescued, this settlement sends '+city.income+' Supplies after each main-mission victory, including replays.',aftermath:city.name+' is free. Its people pledge supplies to each successful campaign expedition.'});
export const TRAINING=[
 {id:'move',title:'Find your feet',text:'Walk 8m with the left stick or WASD. Drag the open screen (right mouse on desktop) to turn the camera.',target:[-10,-8],action:'Practice in the yard'},
 {id:'look',title:'Look around',text:'Drag an empty part of the screen to turn the camera. On desktop, hold the right mouse button while dragging.',action:'Camera practice'},
 {id:'light',title:'A quick strike',text:'Tap and release ATTACK, or press J. The armored training sentinel by Rowan cannot hurt you.',target:[-10,-8],action:'Find the training sentinel'},
 {id:'heavy',title:'Put weight behind it',text:'Hold ATTACK until the golden charge appears, then release. On desktop, hold J for half a second. A charge uses more stamina.',target:[-10,-8],action:'Practice a charged attack'},
 {id:'cast',title:'Remember your oath',text:'Tap either named ability beside ATTACK, or press Q / E. Abilities spend focus or stamina and need time to recover.',action:'Practice an ability'},
 {id:'jump',title:'Get above the ground',text:'Tap JUMP or press Space. You can climb low rocks, use the rampart stairs, and explore between battles.',action:'Practice jumping'},
 {id:'troops',title:'Meet your warband',text:'Visit Rowan at the barracks or open Regiments below. Supplies buy permanent ranks; Command buys squads during a battle. Inspect a troop to continue.',target:[-18,-4],tab:'troops',action:'Open Regiments'},
 {id:'defenses',title:'Prepare the keep',text:'Visit Nell or open Defenses. The gate stays built; four emplacements hold your chosen weapons. Choose a defense, then Upgrade to preview its ten ranks.',target:[19,-5],tab:'defenses',action:'Open Defenses'},
 {id:'mission',title:'Your first defense',text:'Sera is at the war table beside the beacon. Read her briefing and select Begin defense. You can start directly with the button below.',target:[0,17],action:'Read the first briefing'},
 {id:'recruit',title:'You lead an army',text:'Open COMMAND → Troops, then deploy Longbows. Menus pause the battle. Your soldiers seek enemies automatically; give them ranged support.',tab:'army',action:'Deploy your first squad'},
 {id:'order',title:'Give an order',text:'Open COMMAND → Orders. Follow me regroups your current troops; Hold here defends your position; Seek & attack hunts across the field. New recruits always advance.',tab:'army',action:'Open army orders'},
 {id:'victory',title:'Keep the ember alive',text:'Survive all three waves. If the gate breaks, defend the beacon behind it. Watch both flanks, replenish fallen squads, and use your abilities.',action:'Review battle tactics'}
];
export function unlocksAt(count){return [...Object.entries(UNITS).filter(([,u])=>u.unlock===count).map(([,u])=>u.name),...Object.entries(DEFENSES).filter(([,d])=>d.unlock===count).map(([,d])=>d.name)];}
export function nextMission(s){return MISSIONS.find(m=>m.kind==='main'&&!s.completed.includes(m.id))||MISSIONS[MAIN_COUNT-1];}
export class Journey{
 constructor(g){this.g=g;this.lastPos=null;this.lastYaw=null;this.lastCard='';$('journey-action').onclick=()=>this.act();$('journey-skip').onclick=()=>{g.store.commit(s=>{s.guide.active=false;s.guide.homeTask=null;});g.toast('Training hidden. Restart it anytime in the Journal.');};$('mission-shortcut').onclick=()=>g.ui.briefing(nextMission(g.store.data).id);}
 mark(id){const s=this.g.store.data;if(!s||s.guide.done.includes(id))return;s.guide.done.push(id);this.g.store.persist();this.lastCard='';}
 step(){const s=this.g.store.data;if(!s)return null;const tasks={troops:{id:'troops',title:'Give your army an edge',text:'Rowan trains permanent ranks with Supplies. Inspect a regiment, then open Upgrade to compare its next appearance, cost and stats.',target:[-18,-4],tab:'troops',action:'Visit the regiments',waypoint:'Rowan · Barracks'},defenses:{id:'defenses',title:'Build for the next assault',text:'Nell manages four weapon emplacements. Inspect a defense, upgrade its rank, or refit one of the four positions.',target:[19,-5],tab:'defenses',action:'Prepare castle defenses',waypoint:'Nell · Engineer'},equipment:{id:'equipment',title:'Make your spoils count',text:'At Torren’s forge, compare your new armor and weapons. Equip an item, or inspect exactly what its next improvement will cost and add.',target:[-19,8],tab:'equipment',action:'Inspect your armory',waypoint:'Torren · Forge'},hero:{id:'hero',title:'Give your oath a direction',text:'Open a skill tree and inspect its nodes. Skill points buy abilities and passives; you can respecialize for free at any time.',target:[-10,23],tab:'hero',action:'Shape your hero',waypoint:'Oath shrine'},explore:{id:'explore',title:'There is more beyond the road',text:'The western stairs lead to a forgotten cache. Visit the vendors, practice in the yard, or explore outside the gate before your next mission.',target:[-30,-8],tab:'more',action:'See town services',waypoint:'Western rampart'}};if(!this.g.battle&&tasks[s.guide.homeTask])return {...tasks[s.guide.homeTask],post:true};if(!s.guide.active)return null;return TRAINING.find(t=>!s.guide.done.includes(t.id)&&(!this.g.battle?!['recruit','order','victory'].includes(t.id):['recruit','order','victory'].includes(t.id)));}
 reset(){this.g.store.commit(s=>{s.guide.active=true;s.guide.done=[];s.guide.distance=0;});this.lastPos=null;this.lastYaw=null;this.g.ui.close();this.g.toast('Guided training restarted. Follow the gold objective card.');}
 observe(dt){const g=this.g,s=g.store.data;if(!s||!g.hero)return;const p=g.hero.pos;if(!g.battle&&this.lastPos){const d=p.distanceTo(this.lastPos);if(d<1&&g.hero.speed>.5)s.guide.distance+=d;if(s.guide.distance>=8)this.mark('move');}this.lastPos=p.clone();if(this.lastYaw===null)this.lastYaw=g.view.yaw;if(Math.abs(g.view.yaw-this.lastYaw)>.25)this.mark('look');}
 act(){const t=this.step(),g=this.g;if(!t)return;if(t.tab)g.ui.open(t.tab);else if(t.id==='mission')g.ui.briefing(0);else if(t.id==='victory')g.ui.help();else g.toast(t.text);}
 render(){const g=this.g,s=g.store.data;if(!s)return;const t=this.step(),card=$('journey-card'),visible=g.mode==='play'&&!g.menu&&!g.ui.modal;
 card.hidden=!visible||!t;$('mission-shortcut').hidden=!visible||!!g.battle;$('mission-shortcut').textContent=s.completed.length?'Next: '+nextMission(s).name:'Start first defense';
 if(t){const key=t.id+g.battle?.id;if(this.lastCard!==key){this.lastCard=key;$('journey-title').textContent=t.title;$('journey-text').textContent=t.text;$('journey-count').textContent=t.post?'BETWEEN BATTLES · PREPARE YOUR NEXT OATH':'FIELD TRAINING · '+(TRAINING.indexOf(t)+1)+' / '+TRAINING.length;$('journey-action').textContent=t.action;}}
 const target=t?.target||(!g.battle?[0,17]:null),way=$('journey-waypoint');way.hidden=!visible||!target;if(target){const v=new T.Vector3(target[0],2.8,target[1]),d=Math.round(Math.hypot(target[0]-g.hero.pos.x,target[1]-g.hero.pos.z));const camera=g.view.camera,local=v.clone().applyMatrix4(camera.matrixWorldInverse);v.project(camera);const off=local.z>0||Math.abs(v.x)>.88||Math.abs(v.y)>.8;let x=(v.x+1)*innerWidth/2,y=(1-v.y)*innerHeight/2;if(local.z>0){x=innerWidth-x;y=innerHeight*.42;}x=Math.max(20,Math.min(innerWidth-190,x));y=Math.max(90,Math.min(innerHeight-155,y));way.style.left=x+'px';way.style.top=y+'px';way.textContent=(off?(local.z>0||Math.abs(v.x)>.88?(local.x<0?'← ':'→ '):v.y>0?'↑ ':'↓ '):'◇ ')+(t?.waypoint|| (t?.target?t.id==='mission'?'Sera · War table':t.id==='troops'?'Rowan · Barracks':t.id==='defenses'?'Nell · Engineer':'Training yard':'Sera · War table'))+' · '+d+'m';}
 }
}
