import * as T from 'three';
import {groundSurfaceAt} from './footsteps.js';
import {mountDefinition,ensureMounts,mountWounds} from './mount-rules.js';
export function attachRidingHorse(g){const s=g.store.data,state=ensureMounts(s),h=g.hero,def=state.riding&&state.hp[state.selected]>0?mountDefinition(state.selected):null;if(!def)return;h.mount=def;h.mountHP=state.hp[def.id];h.character.setMount(def);g.physics.removeActor(h.phys);h.phys=g.physics.actor(h,h.pos,2.95+def.scale*.4,.70*def.scale);g.physics.horseBody(h.phys,h,def.scale);h.character.horseHeading=h.facing;}
export function toggleMount(g,forced=false){const h=g.hero,state=ensureMounts(g.store.data);if(!h||h.dead||g.mode!=='play'||g.menu||g.ui.modal)return false;if(!forced&&(h.speed>1||!h.phys.grounded||h.attacking||h.charging||h.guarding||(h.mountChangeAt||0)>g.time)){g.toast('Stop on clear ground to mount or dismount.');return false;}if(h.mount){state.hp[h.mount.id]=Math.max(0,h.mountHP);state.riding=false;h.mount=null;h.mountHP=0;h.character.setMount(null);g.physics.removeActor(h.phys);h.phys=g.physics.actor(h,h.pos);h.velocity.set(0,0,0);h.mountChangeAt=g.time+1;g.checkpoint();return true;}
 const def=mountDefinition(state.selected);if(!def){g.toast('Visit Orrin at the stables to hire a horse after Defense XII.');return false;}if(state.hp[def.id]<=0){g.toast('Your horse is injured. Return to Hearthwatch to recover.');return false;}
 const free=()=>[1.15,-.75].every(z=>g.physics.canOccupy({x:h.pos.x+Math.sin(h.facing)*z*def.scale,y:h.pos.y+.9*def.scale,z:h.pos.z+Math.cos(h.facing)*z*def.scale},1.4*def.scale,.36*def.scale,h.phys));if(!g.physics.canOccupy(h.pos,2.95+def.scale*.4,.70*def.scale,h.phys)||!free()){g.toast('Move into an open space before mounting.');return false;}state.riding=true;attachRidingHorse(g);h.velocity.set(0,0,0);h.mountChangeAt=g.time+1;g.audio.play('rally',.22);g.checkpoint();return true;
}
export function woundMount(g,damage,amount,opt){const h=g.hero;if(!h.mount)return damage;const hurt=mountWounds(h.mount,damage,amount,opt);h.mountHP=Math.max(0,h.mountHP-hurt.horse);ensureMounts(g.store.data).hp[h.mount.id]=h.mountHP;if(h.mountHP<=0){toggleMount(g,true);g.toast('Your horse is injured. Fight on foot; it will recover at Hearthwatch.');}return hurt.rider;}
export function updateHorseProbes(h){if(!h.mount)return;const yaw=h.character.horseHeading??h.facing;for(const p of h.phys.probes||[])p.collider.setTranslationWrtParent({x:Math.sin(yaw)*p.z,y:p.y,z:Math.cos(yaw)*p.z});}
export function tickMount(g,dt){const h=g.hero;if(!h.mount)return;const c=h.character;if(h.speed>.1){const wanted=Math.atan2(h.velocity.x,h.velocity.z),old=c.horseHeading??h.facing;c.horseHeading=old+Math.atan2(Math.sin(wanted-old),Math.cos(wanted-old))*Math.min(1,dt*5.5);}if(h.mount.stamina&&!h.charging&&!h.guarding)h.stamina=Math.min(h.stats.stamina,h.stamina+dt*h.stats.staminaRegen*h.mount.stamina);}
export function hoofSounds(g){const h=g.hero,m=h?.character.mount;if(!h?.mount||!h.phys.grounded||!m)return;for(const contact of m.userData.contacts||[]){const kind=groundSurfaceAt(g.world.biome,h.pos.x,h.pos.y,h.pos.z,'ground',g.world.minZ-1),surface=kind==='water'?'water':['stone','wood'].includes(kind)?'stone':'dirt';g.audio.foley?.cue('hoof-'+surface,{gain:.32*(g.store.data.settings.footsteps??.65),pan:contact.foot==='left'?-.09:.09,pitch:h.mount.rarity>=4?.88:1,priority:2,tag:'hoof-contact'});}m.userData.contacts=[];}
export function mountHUD(ui){let b=document.getElementById('mount-control');if(!b){b=document.createElement('button');b.id='mount-control';b.setAttribute('aria-label','Mount horse');b.onclick=()=>{if(ui.g.input.enabled)toggleMount(ui.g);};document.getElementById('hud').append(b);}const g=ui.g,h=g.hero,s=g.store.data,m=s&&mountDefinition(s.mounts?.selected);b.hidden=!m||g.mode!=='play'||!!g.menu||ui.modal;if(b.hidden)return;const hp=h.mount?h.mountHP:s.mounts.hp[m.id];b.innerHTML='<span>♞ '+(h.mount?'Dismount':'Mount')+'</span><small>'+Math.ceil(hp)+' / '+m.hp+'</small><i style="width:'+Math.max(0,hp/m.hp)*100+'%"></i>';b.disabled=hp<=0;b.setAttribute('aria-label',(h.mount?'Dismount from ':'Mount ')+m.name+', '+Math.ceil(hp)+' health');}
