import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {ART,material,worldMaterial} from './materials.js';
import {mat,mesh,box,cyl,beam,weapon} from './art.js';
export class View{
 constructor(canvas){this.canvas=canvas;this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.92;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.scene=new T.Scene();this.scene.background=new T.Color(0xb6c3b7);this.camera=new T.PerspectiveCamera(58,1,.09,600);this.camera.position.set(0,4,16);this.yaw=0;this.pitch=.26;this.distance=5.8;this.currentDistance=this.distance;this.firstPerson=false;this.shake=0;this.target=new T.Vector3();this.desired=new T.Vector3();this.lookAt=new T.Vector3();
 const env=new RoomEnvironment();this.env=new T.PMREMGenerator(this.renderer).fromScene(env,.025).texture;this.scene.environment=this.env;this.scene.environmentIntensity=.28;this.scene.add(new T.HemisphereLight(0xb9c6d4,0x353b2d,1.25));this.sun=new T.DirectionalLight(0xffce86,3.0);this.sun.position.set(-35,60,20);this.sun.castShadow=true;const c=this.sun.shadow.camera;c.left=-48;c.right=48;c.top=48;c.bottom=-48;c.near=1;c.far=150;this.sun.shadow.mapSize.set(1536,1536);this.sun.shadow.bias=-.00015;this.sun.shadow.normalBias=.045;this.scene.add(this.sun,this.sun.target);
 this.previewScene=new T.Scene();this.previewScene.background=new T.Color(0x101c20);this.previewScene.environment=this.env;this.previewScene.environmentIntensity=.85;this.previewScene.add(new T.HemisphereLight(0xc7e3dd,0x282521,2.0));const key=new T.DirectionalLight(0xffd5a2,4);key.position.set(-3,6,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=5;key.shadow.camera.bottom=-1;key.shadow.camera.near=.1;key.shadow.camera.far=18;key.shadow.normalBias=.015;key.target.position.y=1;this.previewScene.add(key,key.target);this.previewKey=key;const rim=new T.DirectionalLight(0x79bbd3,2.6);rim.position.set(3,3,-4);this.previewScene.add(rim);const ground=mesh(new T.CylinderGeometry(2.8,3.0,.25,48),mat(0x29373b,.62,.15),this.previewScene,0,-.13,0);const line=mesh(new T.TorusGeometry(2.45,.018,6,64),mat(0xb89c5c,.25,.7),this.previewScene,0,.01,0);line.rotation.x=-Math.PI/2;this.previewCamera=new T.PerspectiveCamera(38,1,.1,100);this.previewRoot=new T.Group();this.previewScene.add(this.previewRoot);this.previewObject=null;this.previewSpin=0;this.previewKind='hero';this.fp=new T.Group();this.camera.add(this.fp);this.scene.add(this.camera);this.resize();window.addEventListener('resize',()=>this.resize());}
 applyArt(){const pmrem=new T.PMREMGenerator(this.renderer);this.env.dispose();this.env=pmrem.fromEquirectangular(ART.sky).texture;pmrem.dispose();this.scene.environment=this.env;this.scene.environmentIntensity=.55;this.previewScene.environment=this.env;this.previewScene.environmentIntensity=.75;this.renderer.toneMappingExposure=.95;for(const c of this.scene.children)if(c.isHemisphereLight)c.intensity=.6;for(const c of this.previewScene.children)if(c.isHemisphereLight)c.intensity=.6;this.sun.color.setHex(0xffd4a2);this.sun.intensity=3.3;this.sun.shadow.camera.left=-32;this.sun.shadow.camera.right=32;this.sun.shadow.camera.top=32;this.sun.shadow.camera.bottom=-32;this.sun.shadow.normalBias=.025;this.distance=4.9;this.previewKey.intensity=2.4;this.buildArmory();}
 buildArmory(){const stone=worldMaterial('stone',0x747568,2.4),dark=worldMaterial('stone',0x383f3a,2.4),wood=worldMaterial('timber',0x4e4b3e,1.3),iron=material('steel',0x4b5857,{roughness:.7});const floor=mesh(new T.CircleGeometry(8,64),worldMaterial('cobble',0x888778,3.1),this.previewScene,0,-.012,0);floor.rotation.x=-Math.PI/2;floor.castShadow=false;this.previewScene.children.filter(o=>o.isMesh&&o!==floor).forEach(o=>{o.visible=false;});this.previewBackdrop=new T.Group();this.previewScene.add(this.previewBackdrop);const g=this.previewBackdrop;for(const x of [-2.2,2.2]){box(g,[1.7,5,.5],[x,2.5,-2.1],stone);cyl(g,.18,.24,4.1,[x-Math.sign(x)*.76,2.05,-1.76],dark,16);cyl(g,.28,.31,.16,[x-Math.sign(x)*.76,.1,-1.76],stone,16);cyl(g,.29,.24,.16,[x-Math.sign(x)*.76,4.1,-1.76],stone,16);}box(g,[5.9,1.3,.5],[0,4.8,-2.1],stone);box(g,[2.5,4.2,.08],[0,2.1,-2.35],new T.MeshStandardMaterial({color:0x0e1616,roughness:1}));for(let i=0;i<13;i++){const a=i*Math.PI/12;const block=box(g,[.4,.4,.43],[Math.cos(a)*1.45,2.7+Math.sin(a)*1.35,-1.85],dark);block.rotation.z=a-Math.PI/2;}for(const x of [-2.2,2.2]){box(g,[.8,.08,.38],[x,.68,-1.67],wood);box(g,[.8,.08,.38],[x,2.0,-1.67],wood);for(let i=0;i<3;i++){const w=weapon(i===1?'spear':'sword',2);w.position.set(x+(i-1)*.20,1.35,-1.48);w.rotation.z=-.12;g.add(w);}}}
 quality(value='auto'){const mobile=Math.min(innerWidth,innerHeight)<700;const ratio=value==='low'?1:value==='high'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,mobile?1.25:1.6);this.renderer.setPixelRatio(ratio);const size=value==='high'?2048:value==='low'?768:mobile?1024:1536;this.sun.shadow.mapSize.set(size,size);if(this.sun.shadow.map){this.sun.shadow.map.dispose();this.sun.shadow.map=null;}this.renderer.shadowMap.enabled=true;this.resize();}
 resize(){this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=innerWidth/innerHeight;this.camera.fov=innerWidth<innerHeight?66:58;this.camera.updateProjectionMatrix();}
 firstPersonWeapon(type,rank=1,color,item=null){this.fp.clear();const m=material('steel',0x8b9791,{roughness:.54,metalness:.85}),leather=material('leather',0x605340);const right=new T.Group();right.position.set(.28,-.32,-.43);right.rotation.set(-.35,0,-.22);cyl(right,.06,.085,.42,[0,-.07,.16],m,9).rotation.x=-.8;box(right,[.10,.13,.1],[0,.15,.01],leather);const w=weapon(type,rank,color,item?.temper,null,item);w.rotation.set(.40,0,-.22);w.scale.setScalar(.7);right.add(w);this.fp.add(right);this.fpWeapon=right;if(type==='bow'||type==='spear'){const left=right.clone();left.position.x=-.28;left.rotation.z=.25;this.fp.add(left);left.children[left.children.length-1].visible=false;}this.fp.visible=this.firstPerson;}
 update(game,dt){const hero=game.hero;if(!hero)return;const {input,physics}=game;this.yaw-=input.look.x*.004*(game.store.data?.settings.sensitivity||1);this.pitch=T.MathUtils.clamp(this.pitch+input.look.y*.003,-.3,1.0);input.look.x=input.look.y=0;const p=hero.pos;this.target.set(p.x,p.y+1.55,p.z);this.firstPerson=!!game.store.data?.settings.firstPerson;hero.character.visual.visible=!this.firstPerson;this.fp.visible=this.firstPerson;if(this.firstPerson){this.camera.position.lerp(this.target,1-Math.exp(-dt*25));this.lookAt.set(p.x-Math.sin(this.yaw)*8,p.y+1.55-Math.sin(this.pitch)*5,p.z-Math.cos(this.yaw)*8);this.camera.lookAt(this.lookAt);if(this.fpWeapon){const t=hero.actionTime||0,bob=hero.speed>.5?Math.sin(game.time*9)*.012:0;this.fpWeapon.position.y=-.32+bob+Math.sin(t*9)*.025;this.fpWeapon.rotation.x=-.35+(hero.attacking?Math.sin(t*12)*1.2:hero.charging?-.55:0);}}else{const horiz=this.distance*Math.cos(this.pitch),shoulder=.60;this.target.x+=Math.cos(this.yaw)*shoulder;this.target.z-=Math.sin(this.yaw)*shoulder;this.desired.set(p.x+Math.sin(this.yaw)*horiz+Math.cos(this.yaw)*shoulder,p.y+1.5+Math.sin(this.pitch)*this.distance+.35,p.z+Math.cos(this.yaw)*horiz-Math.sin(this.yaw)*shoulder);const dir=this.desired.clone().sub(this.target),dist=dir.length();dir.normalize();const hit=physics.ray(this.target,dir,dist,null,true);let allowed=hit?Math.max(.45,hit.distance-.30):dist;this.currentDistance=T.MathUtils.lerp(this.currentDistance,allowed,1-Math.exp(-dt*(allowed<this.currentDistance?25:6)));this.desired.copy(this.target).addScaledVector(dir,Math.min(allowed,this.currentDistance));this.camera.position.lerp(this.desired,1-Math.exp(-dt*14));this.camera.lookAt(this.target);if(this.currentDistance<1.05)hero.character.visual.visible=false;}
 this.shake=Math.max(0,this.shake-dt*2);if(this.shake>0){const amount=this.shake*(game.store.data?.settings.shake||0)*.06;this.camera.position.x+=(Math.random()-.5)*amount;this.camera.position.y+=(Math.random()-.5)*amount;}
 this.sun.position.set(p.x-35,p.y+32,p.z-25);this.sun.target.position.set(p.x,p.y,p.z-10);}
 title(time){this.camera.position.set(Math.sin(time*.035)*33,14+Math.sin(time*.07)*2,-49);this.camera.lookAt(0,6,0);this.sun.position.set(-35,60,-10);this.sun.target.position.set(0,0,-30);}
 setPreview(object,kind='hero'){this.previewRoot.clear();if(object)this.previewRoot.add(object);this.previewObject=object;this.previewKind=kind;this.previewSpin=kind==='hero'?.38:.3;}
 render(menu=false){const mini=document.getElementById('battle-mini-stage');if(menu||mini){const rect=(mini||document.getElementById('model-stage'))?.getBoundingClientRect();this.renderer.setScissorTest(false);if(menu){this.renderer.setClearColor(0x101c20);this.renderer.clear();}else{this.renderer.setViewport(0,0,innerWidth,innerHeight);this.renderer.render(this.scene,this.camera);}if(rect&&rect.width>0){this.previewCamera.aspect=rect.width/rect.height;if(this.previewBackdrop)this.previewBackdrop.rotation.y=this.previewSpin;const large=this.previewKind==='tower'||this.previewKind==='gate';const h=this.previewKind==='tower'?10:this.previewKind==='gate'?8:this.previewKind==='fortification'?5.4:this.previewKind==='ballista'?3.3:this.previewKind==='rider'?3.3:this.previewKind==='tallHero'?2.7:2;const dist=this.previewKind==='tower'?20:this.previewKind==='gate'?16:this.previewKind==='fortification'?11:this.previewKind==='ballista'?7:this.previewKind==='rider'?7.3:this.previewKind==='tallHero'?6.3:4.8;this.previewCamera.position.set(Math.sin(this.previewSpin)*dist,h*.56,Math.cos(this.previewSpin)*dist);this.previewCamera.lookAt(0,h*(['hero','tallHero','rider'].includes(this.previewKind)?.57:large?.53:.44),0);this.previewCamera.updateProjectionMatrix();this.renderer.setViewport(rect.left,innerHeight-rect.bottom,rect.width,rect.height);this.renderer.setScissor(rect.left,innerHeight-rect.bottom,rect.width,rect.height);this.renderer.setScissorTest(true);this.renderer.render(this.previewScene,this.previewCamera);this.renderer.setScissorTest(false);this.renderer.setViewport(0,0,innerWidth,innerHeight);}}else{this.renderer.setViewport(0,0,innerWidth,innerHeight);this.renderer.render(this.scene,this.camera);}}
}
