import {unitStats,defenseFiringStats,UNITS} from './data.js';
export const RESEARCH_LIMIT=4;
export const WAR_BANDS={hearth:['shield','pike','banner','dawn'],wild:['bow','rider','assassin','frost'],forge:['breaker','crew','engineer','marksman','giant']};
const project=(name,short,group,icon,seconds,unlock,summary,description,origin='Oathfire')=>({name,short,group,icon,seconds,unlock,summary,description,origin});
// Original mechanics are adapted to Oathfire's metres, army cap and defense missions.
export const RESEARCH={
 longbow:project('Longbows','Longbows','troops','bow',25,0,'+25% range · +5 Command','Longbows gain 25% range. Each new squad costs 5 more Command. Existing archers receive the range immediately.','H&C2'),
 gate:project('Reinforced walls I','Walls I','defenses','wall',40,0,'+20% gate health · Repair','Increase maximum gate health by 20% and fully repair it once, if it still stands. The stronger Walls II bonus replaces this health bonus.','H&C2'),
 demolition:project('TNT','TNT','defenses','bomb',20,1,'Explosive last defense','When the gate falls, its charges explode once: 200 damage and a 15-second stun to enemies within 9 m. Does not harm allies.','H&C2'),
 anchor:project('Lead foot','Lead foot','hero','boot',30,1,'Stand firm · +15 armor','Ignore knockback and stuns. While moving slower than 0.3 m/s, gain 15 armor. Move again and that armor bonus ends.','H&C2'),
 reinforcements:project('Bolstered defense','Reserve','defenses','reinforce',45,0,'Two reserve Longbows','Two individual Longbow soldiers join for no Command. If your army is full, they wait in reserve and arrive as spaces open. They count toward the 24-soldier cap.','H&C2'),
 imbue:project('Magic imbuement','Imbue','hero','rune',40,3,'Weapon hits ignore armor','Your direct weapon attacks and projectiles ignore enemy armor. Spell areas and secondary effects keep their normal armor rules.','H&C2'),
 impact:project('Heavy blows','Heavy blows','hero','hammer',40,2,'Weapon strikes can stun','Each direct hero weapon hit has a 5% chance to stun its target for 5 seconds. Bosses are stunned for 1 second.','H&C2'),
 heroHealth:project('Hero health I','Health I','hero','heart',40,0,'+50 maximum health','Gain 50 maximum health for this battle. Your current health percentage is preserved. Stacks with Hero health II.','H&C2'),
 heroDamage:project('Hero damage I','Damage I','hero','sword',40,0,'+5 weapon damage','Add 5 to your hero weapon damage before armor and charged-attack multipliers. Stacks with Hero damage II.','H&C2'),
 fastShot:project('Fast shot','Fast shot','troops','arrows',40,3,'25% chance of a fast reload','Longbows and Ironwatch marksmen have a 25% chance after firing to reload in 0.35 seconds. Each new shot rolls independently.','H&C2'),
 veterans:project('Forge veterancy','Veterans','troops','veteran',40,4,'25% chance of a veteran','New Forge-band soldiers have a 25% chance to arrive as a visibly decorated veteran, with +50% health, +100% damage and +100% armor. Applies to Ashbreakers, Siege crew, engineers, marksmen and giants.','H&C2'),
 regeneration:project('Regeneration','Regrowth','hero','regen',50,2,'Recover 1 health each second','Restore 1 hero health per second during active combat, up to your current maximum. Stops while menus are paused.','H&C2'),
 infantry:project('Footman training','Footmen','troops','shield',50,2,'Double damage · Shield blocks','Shieldward deal twice their usual damage and have a 20% chance to block 90% of an incoming hit. Future squads cost 10 extra Command.','H&C2'),
 spears:project('Infinity spears','Spears','troops','spear',50,3,'Double Pikeguard damage','Double Pikeguard damage, including their siege-target attack. Existing soldiers and future recruits benefit.','H&C2'),
 elite:project('The elite','Elite','troops','crown',50,7,'Champions: double health & damage','Dawn standards, Sun sworn and veteran Forge soldiers gain twice their normal health and damage. Veterans keep their veteran bonuses too. Current health percentage is preserved.','H&C2'),
 siegeHero:project('Siege hero','Siege hero','hero','siege',60,5,'Break siege troops · Survive hits','Your weapon hits deal 10 extra base damage against siege brutes and captains. Take 50% less damage from those enemies. Adapted for our defense battles.','H&C2'),
 mageFortune:project('Mage’s fortune','Mage fortune','troops','comet',60,4,'Stronger mages · Elemental rain','Cinder adepts and Rime scholars gain 50% health and damage. Their shots have a 25% chance to call five falling fireballs or ice shards over the target. Rain can occur once every 8 seconds per caster.','H&C2'),
 heroDamage2:project('Hero damage II','Damage II','hero','swords',70,8,'+10 weapon damage','Add 10 to hero weapon damage before armor and charged-attack multipliers. Stacks with Hero damage I.','H&C2'),
 gate2:project('Reinforced walls II','Walls II','defenses','wall2',75,6,'+35% gate health · Repair','Increase maximum gate health by 35% and fully repair a standing gate once. Replaces the 20% Walls I health bonus; does not resurrect a fallen gate.','H&C2'),
 rally:project('General’s rally','Rally','defenses','banner',80,6,'Gain 70 Command','Receive 70 Command when research finishes. Any amount above the normal 220 cap remains as reserve until spent. Normal regeneration resumes below 220.','H&C2'),
 heroHealth2:project('Hero health II','Health II','hero','heart2',80,8,'+125 maximum health','Gain 125 maximum health, preserving your current health percentage. Stacks with Hero health I.','H&C2'),
 wildPath:project('Warrior path','Wild path','troops','leaf',100,7,'Wild band: +50% health & damage','Longbows, Ember riders, Veil blades and Rime scholars gain 50% health and damage. Riders and Veil blades also move 25% faster.','H&C2'),
 resolve:project('Mankind’s resolve','Resolve','troops','troops',100,8,'Hearth band: +50% health & damage','Shieldward, Pikeguard, Dawn standards and Sun sworn gain 50% health and damage. Living soldiers keep their current health percentage.','H&C2'),
 forgeRunes:project('Dwarven runes','Forge runes','troops','anvil',100,9,'Forge band: +50% health & damage','Ashbreakers, Siege crew, engineers, Ironwatch marksmen and Oathbound giants gain 50% health and damage. These are Oathfire’s Forge band.','H&C2'),
 shield:project('Shield discipline','Discipline','troops','hero',35,0,'+25% health · +20% damage','Shieldward gain 25% maximum health and 20% damage. Future squads cost 5 extra Command. Health percentage is preserved.'),
 pike:project('Pike formations','Formations','troops','spear',40,1,'+35% Pikeguard damage','Pikeguard deal 35% more damage. Their bonus against siege brutes and captains still applies.'),
 runic:project('Runic focus','Runic','troops','fire',50,4,'+25% power · +15% health','Lanternkeepers, Cinder adepts, Rime scholars and Sun sworn gain 25% direct attack damage and healing, plus 15% maximum health. Health percentage is preserved.'),
 windlass:project('Windlass drills','Windlass','defenses','orders',35,0,'+20% mechanical fire rate','Archer towers, ballistas, Ember cannons and Stone lobbers fire 20% faster. Applies to existing emplacements and later refits.'),
 payload:project('Siege payloads','Payloads','defenses','siege',45,2,'+25% siege weapon damage','Ballistas, Ember cannons and Stone lobbers gain 25% damage, including their blasts. Applies to later refits too.'),
 wards:project('Ward harmonics','Wards','defenses','rune',50,4,'+20% range · +25% power','Rime obelisks, Storm spires and Sanctuary braziers gain 20% range and 25% damage or healing.'),
 crossfire:project('Crossfire doctrine','Crossfire','defenses','crossfire',45,3,'Exploit slowed or marked enemies','Allied ranged soldiers and defenses deal 20% more damage to enemies currently slowed or marked. Pair Rime obelisks with archers and siege weapons.'),
 logistics:project('Field logistics','Logistics','troops','supply',50,5,'+20% Command income · Cheaper troops','Command regeneration is 20% faster. Future squads cost 10% less Command, rounded up, after other research surcharges.'),
 lastOath:project('The last oath','Last oath','hero','phoenix',60,7,'Survive one fatal blow','Once this battle, a fatal hero hit instead restores 30% health and grants 3 seconds of invulnerability. Does not prevent a loss from a destroyed beacon.')
};
export const researchComplete=(battle,id)=>!!battle?.research?.some(r=>r.id===id&&r.complete);
export function startResearch(battle,save,id){const d=RESEARCH[id];if(!battle||!Object.hasOwn(RESEARCH,id))throw Error('Research is available during a battle.');if(save.completed.length<d.unlock)throw Error('Reclaim '+d.unlock+' castles to unlock this research.');const list=battle.research||(battle.research=[]);if(list.some(r=>r.id===id))throw Error('This research is already selected.');if(list.length>=RESEARCH_LIMIT)throw Error('All four research slots are committed. Cancel unfinished research to change a choice.');list.push({id,remaining:d.seconds,complete:false});}
export function cancelResearch(battle,id){const r=battle?.research?.find(r=>r.id===id);if(!r)throw Error('Research is not selected.');if(r.complete)throw Error('Completed research stays active until this battle ends.');battle.research=battle.research.filter(r=>r.id!==id);}
export function advanceResearch(battle,dt){if(!battle||!Number.isFinite(dt)||dt<=0)return [];const finished=[];for(const r of battle.research||[]){if(r.complete)continue;r.remaining=Math.max(0,r.remaining-dt);if(r.remaining<1e-8){r.remaining=0;r.complete=true;finished.push(r.id);}}return finished;}
export function validateBattleResearch(battle){if(battle.research!==undefined){const list=battle.research;if(!Array.isArray(list)||list.length>RESEARCH_LIMIT||new Set(list.map(r=>r?.id)).size!==list.length)throw Error('Invalid battle research slots.');for(const r of list)if(!Object.hasOwn(RESEARCH,r?.id)||typeof r.complete!=='boolean'||!Number.isFinite(r.remaining)||r.remaining<0||r.remaining>RESEARCH[r.id].seconds||r.complete!==(r.remaining===0))throw Error('Invalid battle research progress.');}if(battle.recentRecruits!==undefined&&(!Array.isArray(battle.recentRecruits)||battle.recentRecruits.length>4||new Set(battle.recentRecruits).size!==battle.recentRecruits.length||battle.recentRecruits.some(id=>!Object.hasOwn(UNITS,id))))throw Error('Invalid recruitment shortcuts.');if(battle.reserveArchers!==undefined&&(!Number.isInteger(battle.reserveArchers)||battle.reserveArchers<0||battle.reserveArchers>5))throw Error('Invalid reserve.');for(const key of ['lastOathUsed','demolitionUsed'])if(battle[key]!==undefined&&typeof battle[key]!=='boolean')throw Error('Invalid battle perk.');if(battle.allies?.some(a=>a.veteran!==undefined&&typeof a.veteran!=='boolean'))throw Error('Invalid veteran.');}
const rounded=n=>Math.round(n*100)/100;
export function battleUnitStats(id,rank,battle,{veteran=false}={}){const st={...unitStats(id,rank),healFactor:1};const has=x=>researchComplete(battle,x);let health=1,damage=1;
 if(id==='bow'&&has('longbow')){st.reach=rounded(st.reach*1.25);st.cost+=5;}if(id==='shield'&&has('shield')){health*=1.25;damage*=1.2;st.cost+=5;}if(id==='shield'&&has('infantry')){damage*=2;st.cost+=10;}if(id==='pike'&&has('pike'))damage*=1.35;if(id==='pike'&&has('spears'))damage*=2;
 if(['lantern','pyre','frost','dawn'].includes(id)&&has('runic')){health*=1.15;damage*=1.25;st.healFactor=1.25;}if(['pyre','frost'].includes(id)&&has('mageFortune')){health*=1.5;damage*=1.5;}
 if(veteran){health*=1.5;damage*=2;st.armor*=2;}if(has('elite')&&(['banner','dawn'].includes(id)||veteran)){health*=2;damage*=2;}
 for(const [key,band]of [['resolve','hearth'],['wildPath','wild'],['forgeRunes','forge']])if(has(key)&&WAR_BANDS[band].includes(id)){health*=1.5;damage*=1.5;}
 if(has('wildPath')&&['rider','assassin'].includes(id))st.speed*=1.25;if(has('logistics'))st.cost=Math.ceil(st.cost*.9);st.hp=Math.round(st.hp*health);st.damage=rounded(st.damage*damage);return st;}
export function battleDefenseStats(id,rank,doctrine,battle){const st=defenseFiringStats(id,rank,doctrine);if(id==='gate'){if(researchComplete(battle,'gate2'))st.hp=Math.round(st.hp*1.35);else if(researchComplete(battle,'gate'))st.hp=Math.round(st.hp*1.2);}if(['tower','ballista','cannon','mortar'].includes(id)&&researchComplete(battle,'windlass'))st.interval/=1.2;if(['ballista','cannon','mortar'].includes(id)&&researchComplete(battle,'payload'))st.damage=rounded(st.damage*1.25);if(['frost','storm','sanctuary'].includes(id)&&researchComplete(battle,'wards')){st.damage=rounded(st.damage*1.25);st.range=rounded(st.range*1.2);}return st;}
export function battleHeroStats(base,battle,hero=null){const st={...base};if(researchComplete(battle,'heroHealth'))st.hp+=50;if(researchComplete(battle,'heroHealth2'))st.hp+=125;if(researchComplete(battle,'heroDamage'))st.damage+=5;if(researchComplete(battle,'heroDamage2'))st.damage+=10;if(researchComplete(battle,'anchor')&&(hero?.speed||0)<.3)st.armor+=15;return st;}
export const commandIncome=b=> (.6+(b?.camp?.15:0))*(researchComplete(b,'logistics')?1.2:1);
