import {unitStats,defenseFiringStats,UNITS} from './data.js';
export const RESEARCH_LIMIT=4;
// Time and four committed choices are the cost. These never change permanent ranks.
export const RESEARCH={
 longbow:{name:'Longbow drill',short:'Longbows',group:'troops',icon:'bow',seconds:25,unlock:0,summary:'+25% range · +5 Command',description:'Longbows gain 25% attack range. Each new Longbow squad costs 5 extra Command. Existing archers gain the range when research finishes.'},
 shield:{name:'Shield discipline',short:'Shields',group:'troops',icon:'hero',seconds:35,unlock:0,summary:'+25% health · +20% damage',description:'Shieldward gain 25% maximum health and 20% damage. New Shieldward squads cost 5 extra Command. Living soldiers keep their current health percentage.'},
 pike:{name:'Pike formations',short:'Pikes',group:'troops',icon:'spear',seconds:40,unlock:1,summary:'+35% Pikeguard damage',description:'Pikeguard deal 35% more damage. Their existing bonus against siege brutes and captains still applies.'},
 runic:{name:'Runic focus',short:'Runic',group:'troops',icon:'fire',seconds:50,unlock:4,summary:'+25% power · +15% health',description:'Lanternkeepers, Cinder adepts, Rime scholars and Sun sworn gain 25% direct attack damage and healing, plus 15% maximum health. Living soldiers keep their current health percentage.'},
 gate:{name:'Reinforced gate',short:'Gate',group:'defenses',icon:'defenses',seconds:40,unlock:0,summary:'+20% gate health · Full repair',description:'The gate gains 20% maximum health. When research finishes, repair the standing gate to full health. A fallen gate stays fallen.'},
 windlass:{name:'Windlass drills',short:'Windlass',group:'defenses',icon:'orders',seconds:35,unlock:0,summary:'+20% mechanical fire rate',description:'Archer towers, ballistas, Ember cannons and Stone lobbers fire 20% faster. Applies to existing emplacements and later refits.'},
 payload:{name:'Siege payloads',short:'Payloads',group:'defenses',icon:'spear',seconds:45,unlock:2,summary:'+25% siege weapon damage',description:'Ballistas, Ember cannons and Stone lobbers gain 25% damage, including their blast damage. Applies to existing emplacements and later refits.'},
 wards:{name:'Ward harmonics',short:'Wards',group:'defenses',icon:'fire',seconds:50,unlock:4,summary:'+20% range · +25% power',description:'Rime obelisks, Storm spires and Sanctuary braziers gain 20% range and 25% damage or healing. Applies to existing emplacements and later refits.'}
};
export const researchComplete=(battle,id)=>!!battle?.research?.some(r=>r.id===id&&r.complete);
export function startResearch(battle,save,id){const d=RESEARCH[id];if(!battle||!Object.hasOwn(RESEARCH,id))throw Error('Research is available during a battle.');if(save.completed.length<d.unlock)throw Error('Reclaim '+d.unlock+' castles to unlock this research.');const list=battle.research||(battle.research=[]);if(list.some(r=>r.id===id))throw Error('This research is already selected.');if(list.length>=RESEARCH_LIMIT)throw Error('All four research slots are committed. Cancel unfinished research to change a choice.');list.push({id,remaining:d.seconds,complete:false});}
export function cancelResearch(battle,id){const r=battle?.research?.find(r=>r.id===id);if(!r)throw Error('Research is not selected.');if(r.complete)throw Error('Completed research stays active until this battle ends.');battle.research=battle.research.filter(r=>r.id!==id);}
export function advanceResearch(battle,dt){if(!battle||!Number.isFinite(dt)||dt<=0)return [];const finished=[];for(const r of battle.research||[]){if(r.complete)continue;r.remaining=Math.max(0,r.remaining-dt);if(r.remaining<1e-8){r.remaining=0;r.complete=true;finished.push(r.id);}}return finished;}
export function validateBattleResearch(battle){if(battle.research!==undefined){const list=battle.research;if(!Array.isArray(list)||list.length>RESEARCH_LIMIT||new Set(list.map(r=>r?.id)).size!==list.length)throw Error('Invalid battle research slots.');for(const r of list)if(!Object.hasOwn(RESEARCH,r?.id)||typeof r.complete!=='boolean'||!Number.isFinite(r.remaining)||r.remaining<0||r.remaining>RESEARCH[r.id].seconds||r.complete!==(r.remaining===0))throw Error('Invalid battle research progress.');}if(battle.recentRecruits!==undefined&&(!Array.isArray(battle.recentRecruits)||battle.recentRecruits.length>4||new Set(battle.recentRecruits).size!==battle.recentRecruits.length||battle.recentRecruits.some(id=>!Object.hasOwn(UNITS,id))))throw Error('Invalid recruitment shortcuts.');}
const rounded=n=>Math.round(n*100)/100;
export function battleUnitStats(id,rank,battle){const st={...unitStats(id,rank),healFactor:1};if(id==='bow'&&researchComplete(battle,'longbow')){st.reach=rounded(st.reach*1.25);st.cost+=5;}if(id==='shield'&&researchComplete(battle,'shield')){st.hp=Math.round(st.hp*1.25);st.damage=rounded(st.damage*1.2);st.cost+=5;}if(id==='pike'&&researchComplete(battle,'pike'))st.damage=rounded(st.damage*1.35);if(['lantern','pyre','frost','dawn'].includes(id)&&researchComplete(battle,'runic')){st.hp=Math.round(st.hp*1.15);st.damage=rounded(st.damage*1.25);st.healFactor=1.25;}return st;}
export function battleDefenseStats(id,rank,doctrine,battle){const st=defenseFiringStats(id,rank,doctrine);if(id==='gate'&&researchComplete(battle,'gate'))st.hp=Math.round(st.hp*1.2);if(['tower','ballista','cannon','mortar'].includes(id)&&researchComplete(battle,'windlass'))st.interval/=1.2;if(['ballista','cannon','mortar'].includes(id)&&researchComplete(battle,'payload'))st.damage=rounded(st.damage*1.25);if(['frost','storm','sanctuary'].includes(id)&&researchComplete(battle,'wards')){st.damage=rounded(st.damage*1.25);st.range=rounded(st.range*1.2);}return st;}
