import {MOUNTS,mountDefinition,mountUnlocked,stableUnlocked,hireMount,selectMount} from './mount-rules.js';
import {RARITIES} from './data.js';
import {HorsePreview} from './horse-art.js';
export function stablePage(ui){const s=ui.g.store.data,m=mountDefinition(ui.mountChoice)||MOUNTS[0],owned=s.mounts.owned.includes(m.id),open=mountUnlocked(s,m.id),selected=s.mounts.selected===m.id;
 return '<section class="stable-detail"><small>'+RARITIES[m.rarity].name.toUpperCase()+' · RIDING HORSE</small><h2>'+m.name+'</h2><div class="stable-stats">'+[['Health',m.hp],['Speed',m.speed+' m/s'],['Armor',m.armor],['Size',Math.round(m.scale*100)+'%']].map(([k,v])=>'<div><b>'+v+'</b><small>'+k+'</small></div>').join('')+'</div><p class="stable-bonus">'+m.bonus+'</p><p class="stable-purpose">Fight with your equipped weapons and spells. Your horse absorbs part of incoming damage; you still take damage. Injured horses recover when you return to Hearthwatch.</p><div class="stable-contract">'+(owned?ui.button('mount-select',m.id,selected?'Selected for riding':'Select horse',selected,true):ui.button('mount-hire',m.id,open?'Hire · '+m.cost.toLocaleString()+' Supplies':'Unlock · Defense '+m.gate,!open||s.supplies<m.cost,true))+'<small>'+(owned?'Permanent stable contract':open?'One-time contract · No Command cost':stableUnlocked(s)?'Complete '+m.gate+' main defenses.':'Defend the royal convoy in Defense XII to open the stables.')+'</small></div></section>';
}
export function stableList(ui){const s=ui.g.store.data;return '<div class="stable-list" aria-label="Horse tiers">'+MOUNTS.map(m=>'<button data-action="mount-inspect" data-id="'+m.id+'" class="'+((ui.mountChoice||MOUNTS[0].id)===m.id?'selected':'')+'"><b>'+m.name+'</b><small>'+RARITIES[m.rarity].name+(s.mounts.owned.includes(m.id)?' · Hired':mountUnlocked(s,m.id)?' · '+m.cost.toLocaleString():' · Defense '+m.gate)+'</small></button>').join('')+'</div>';}
export function previewHorse(ui){const m=mountDefinition(ui.mountChoice)||MOUNTS[0];ui.preview=new HorsePreview(m);ui.g.view.setPreview(ui.preview.root,'horse');ui.g.view.previewSpin=.85;ui.previewCaption();}
export function stableAction(ui,action,id){if(!action.startsWith('mount-'))return false;const g=ui.g,m=mountDefinition(id);if(!m)return true;if(action==='mount-inspect'){ui.mountChoice=id;ui.draw();ui.previewForTab();return true;}
 const finish=()=>{if(g.hero.mount){g.hero.character.setMount(null);g.hero.mount=null;g.physics.removeActor(g.hero.phys);g.hero.phys=g.physics.actor(g.hero,g.hero.pos);}ui.draw();ui.previewForTab();g.audio.play('upgrade');g.toast(m.name+' ready. Return to the courtyard and tap Mount (H).');};
 if(action==='mount-hire'){ui.confirm('Hire '+m.name+'?',m.cost.toLocaleString()+' Supplies for a permanent stable contract. '+m.hp+' health · '+m.speed+' m/s · '+m.armor+' armor. '+m.bonus,()=>{try{g.store.commit(s=>hireMount(s,id));finish();}catch(e){g.toast(e.message);}});}
 if(action==='mount-select'){g.store.commit(s=>selectMount(s,id));finish();}return true;
}
