import {SERVICES} from './data.js';
import {canUseService} from './town-services.js';

const PURPOSE={equipment:['Forge & armory','Equip and improve weapons & armor'],shop:['Provisions','Buy provisions and equipment'],troops:['Army training','Train regiments and choose doctrines'],defenses:['Castle defenses','Upgrade defenses and Command income'],campaign:['Your next mission','Scout the campaign at the war table'],stable:['Royal stables','Hire and select a riding horse']};
const mapPoint=p=>({x:Math.max(5,Math.min(95,(p.x+36)/72*100)),y:Math.max(8,Math.min(92,(p.z+16)/56*100))});
export function townDestinations(g){
 return SERVICES.filter(s=>s.tab!=='hero').map((s,index)=>({...s,number:index+1,distance:Math.round(Math.hypot(s.x-g.hero.pos.x,s.z-g.hero.pos.z)),nearby:canUseService(g,s.tab),selected:g.store.data.guide.homeTask===s.tab}));
}
export function renderTownGuide(ui,sigil){
 const g=ui.g,services=townDestinations(g),player=mapPoint(g.hero.pos),selected=services.find(s=>s.selected),mission=services.find(s=>s.tab==='campaign');
 const marker=s=>{const p=mapPoint(s);return '<span aria-hidden="true" class="town-pin '+(s.selected?'selected ':'')+(s.nearby?'nearby':'')+'" style="left:'+p.x+'%;top:'+p.y+'%">'+s.number+'</span>';};
 return '<div class="town-guide-layout"><section class="town-map-panel" aria-label="Map of Hearthwatch"><div class="town-map-heading"><small>YOUR HOME BETWEEN BATTLES</small><h2>Hearthwatch</h2><p>Prepare your hero. Gather your people.</p></div><div class="town-plan"><svg viewBox="-36 -16 72 56" preserveAspectRatio="none" aria-hidden="true"><defs><pattern id="town-grid" width="4" height="4" patternUnits="userSpaceOnUse"><path d="M4 0H0V4" fill="none" stroke="#8e765a" stroke-width=".1" opacity=".24"/></pattern></defs><rect x="-36" y="-16" width="72" height="56" fill="url(#town-grid)"/><path class="town-wall" d="M-31 34V-9H-8V-13H8V-9H31V34H7M-7 34H-31"/><path class="town-road" d="M0 40V-9M-24 8H25M-20 -4H24M-10 23H24"/><path class="town-keep" d="M-7 -10V-6H-4V-10H-1V-6H2V-10H5V-6H8V-1H-7Z"/><g class="town-building">'+services.filter(s=>s.tab!=='campaign').map(s=>'<rect x="'+(s.x-3.5)+'" y="'+(s.z-3)+'" width="7" height="6" rx=".4"/><path d="M'+(s.x-4)+' '+(s.z-3)+'l4 -2 4 2"/>').join('')+'</g><path class="town-garden" d="M-24 21l4 4-4 4-4-4Z M12 25l3 3-3 3-3-3Z"/><text x="0" y="4" text-anchor="middle">COURTYARD</text><text x="0" y="32" text-anchor="middle">SOUTH GATE</text><text x="-31" y="-12">N ↑</text></svg>'+services.map(marker).join('')+'<span class="town-player" style="left:'+player.x+'%;top:'+player.y+'%" aria-label="Your position"></span></div><div class="town-map-legend"><span><i></i> You are here</span><span>1–6 · Town services</span></div><div class="town-route-note"><small>'+(selected?'CURRENT DESTINATION':'READY FOR THE ROAD?')+'</small><b>'+(selected?selected.name:'Sera · War table')+'</b><span>'+(selected?selected.distance+'m away · Follow the marker in town.':mission.distance+'m away · Choose your next mission with Sera.')+'</span></div></section><section class="town-destinations" aria-label="Town services"><p class="town-directions">Choose a destination to follow its marker. Speak to the person when you arrive.</p><div class="town-service-list">'+services.map(s=>'<button class="destination-tile town-destination '+(s.selected?'selected ':'')+(s.nearby?'nearby':'')+'" data-action="'+(s.nearby?'navigate':'find-service')+'" data-id="'+s.tab+'"><span class="town-number">'+s.number+'</span><span class="town-service-copy"><small class="town-role">'+PURPOSE[s.tab][0]+'</small><b>'+s.name+'</b><small>'+PURPOSE[s.tab][1]+'</small><span class="town-travel">'+(s.nearby?'● Nearby · Speak now':s.selected?'◆ Following · '+s.distance+'m':'Set destination · '+s.distance+'m')+'</span></span>'+sigil(s.tab)+'</button>').join('')+'</div></section></div>';
}
