import {sack,burlap,forgeCraft} from './market-craft.js';
import {masonry,cutStone,oak,slate,paving as courtyardPaving} from './building-materials.js';
import {architecturalDetail} from './architectural-detail.js';
import {atmosphere} from './atmosphere.js';
import {buildSiegeValley} from './siege-valley.js';
import {craftedRoof} from './architecture.js';
import {buildScenography,updateScenography} from './world-scenography.js';
import {buildEnemyFortress,enrichHearthwatch} from './fortress-art.js';
import {castleReserved,SIEGE_OFFSET,SIEGE_MIN_Z} from './siege-rules.js';
import {livingWorld,distantRanges} from './living-world.js';
import {dressCastle} from './castle-atelier.js';
import {royalCourtyard} from './royal-courtyard.js';
import {fortificationModel,updateFortification} from './fortifications.js';
import {EMPLACEMENTS,DEFAULT_LAYOUT} from './roster.js';
import * as T from 'three';
import {stoneSurface,groundSurface} from './surfaces.js';
import {ART,material,worldMaterial} from './materials.js';
import {flameVolume,refineCastle,createBeacon,detailedTree,plantLeaves,mountainRidges} from './environment-design.js';
import {mat,mesh,box,cyl,sphere,beam,sunBadge,mergeStatic,stoneTexture,woodTexture,weapon,shield} from './art.js';
import {BIOMES,SERVICES,seeded} from './data.js';
export class Landscape{
 constructor(scene,physics){this.scene=scene;this.physics=physics;this.root=new T.Group();scene.add(this.root);this.dynamic=new T.Group();scene.add(this.dynamic);this.props=[];this.flags=[];this.fireplaces=[];this.treasures=[];this.towerObjects=[];this.rocks=[];this.nav=[];this.interactables=[];this.time=0;this.seed=1;this.biome='plain';}
 height(x,z){if(z>-27)return 0;const fade=Math.min(1,(-z-27)/24);let y=(Math.sin(x*.033+z*.014)*1.8+Math.cos(z*.037-x*.012)*1.6)*fade;const hill=Math.exp(-((x+48)**2/850+(z+76)**2/1200))*5;if(this.biome==='quarry')y+=Math.exp(-((x-47)**2/850+(z+88)**2/2100))*7;else y+=hill;if(this.biome==='river'){const riverX=12+Math.sin(z*.045)*15;y-=Math.exp(-((x-riverX)**2)/45)*2.6;}if(this.siegeMode){const d=Math.max(Math.abs(x)-43,Math.abs(z+165-SIEGE_OFFSET)-40,0),f=1-Math.min(1,d/16);y+=(3-y)*f*f*(3-2*f);}return y;}
 build(biome='plain',seed=1,defenses={gate:1,tower:1,ballista:1},layout=DEFAULT_LAYOUT,siegeMission=null){this.siegeMode=siegeMission;this.minZ=siegeMission?SIEGE_MIN_Z:-229;this.biome=biome;this.seed=seed;this.clear();this.physics.reset();const b=BIOMES[biome],r=seeded(seed);this.scene.background=ART.panoramas?.[biome]||ART.panoramas?.plain||ART.sky;this.scene.backgroundRotation.y=.7;this.scene.environmentRotation.y=Math.PI;this.scene.backgroundIntensity=.88;this.scene.fog=new T.FogExp2(biome==='snow'?0xb4c2cd:biome==='desert'?0xcdb391:0xbbbec1,.00135);this.materials={stone:masonry(),stoneDark:masonry(0x9c998b),cap:cutStone(0xbeb49f),wood:oak(),roof:slate(0x535e69),teal:material('cloth',0x153c43,{side:T.DoubleSide}),gold:material('steel',0xb79b68,{roughness:.7,metalness:.6}),iron:material('steel',0x5b6668,{roughness:.8,metalness:.65}),flame:mat(0xffa632,.2,.1,{emissive:0xff751c,emissiveIntensity:2.5}),dark:mat(0x1d2b29,.94),leaf:mat(b.grass,.95)};

 this.ground();this.castle(defenses,layout);this.village();this.courtyardDetails();refineCastle(this);dressCastle(this);this.scenery(r);livingWorld(this);royalCourtyard(this);enrichHearthwatch(this);buildScenography(this);architecturalDetail(this);if(siegeMission){buildSiegeValley(this);buildEnemyFortress(this,siegeMission);}plantLeaves(this);distantRanges(this);atmosphere(this);this.placeTreasures();this.river();this.scene.updateMatrixWorld(true);const merged=mergeStatic(this.static,96);this.static.removeFromParent();this.root.add(merged);this.static=merged;
 for(const x of [-124,124])this.physics.addBox(x,10,(54+this.minZ)/2,2,40,54-this.minZ,'boundary');this.physics.addBox(0,10,this.minZ,250,40,2,'boundary');this.physics.addBox(0,10,54,250,30,2,'boundary');
 }
 clear(){for(const p of [this.root,this.dynamic]){const geometries=new Set(),materials=new Set(),textures=new Set();p.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.customDepthMaterial)materials.add(o.customDepthMaterial);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const v of Object.values(m))if(v?.isTexture)textures.add(v);}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>{if(!t.userData.shared)t.dispose();});while(p.children.length)p.remove(p.children[0]);}this.static=new T.Group();this.root.add(this.static);this.props=[];this.flags=[];this.fireplaces=[];this.treasures=[];this.towerObjects=[];this.rocks=[];this.nav=[];this.interactables=[];this.leafInstances=[];this.leafShader=null;this.scenicMotion=[];this.enemyFortress=null;this.scenography=null;this.authoredMaterials=new Map();}
 ground(){const w=250,d=57-this.minZ,nx=100,nz=this.siegeMode?Math.ceil(d/2.5):116,pos=[],colors=[],uv=[],idx=[],b=BIOMES[this.biome],r=seeded(this.seed+8),base=new T.Color(b.ground),road=new T.Color(this.biome==='snow'?0xb7c5c5:0xa79978);for(let j=0;j<=nz;j++)for(let i=0;i<=nx;i++){const x=-w/2+i*w/nx,z=55-j*d/nz,y=this.height(x,z);pos.push(x,y,z);uv.push(x*.05,z*.05);let c=base.clone();const isRoad=Math.abs(x-Math.sin(z*.025)*4)<4&&z<20;let factor=.89+r()*.2;c.multiplyScalar(factor);if(isRoad)c.lerp(road,.78);if(z>-17&&Math.abs(x)<33)c.setHex(0x9eaa98).multiplyScalar(factor);colors.push(c.r,c.g,c.b);if(i<nx&&j<nz){const a=j*(nx+1)+i;idx.push(a,a+1,a+nx+1,a+1,a+nx+2,a+nx+1);}}
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();const m=mesh(g,groundSurface(this.biome),this.root);m.castShadow=false;m.userData.disposeGeometry=true;this.physics.terrain(new Float32Array(pos),new Uint32Array(idx));const paving=mesh(new T.PlaneGeometry(66,49),courtyardPaving(),this.root,0,.015,8);paving.rotation.x=-Math.PI/2;paving.castShadow=false;
 }
 solid(size,pos,material=this.materials.stone,kind='wall',angle=0,parent=this.static){const m=box(parent,size,pos,material);m.rotation.y=angle;this.physics.addBox(...pos,...size,kind,angle);this.nav.push({x:pos[0],z:pos[2],hx:size[0]/2+.6,hz:size[2]/2+.6,top:pos[1]+size[1]/2});return m;}
 merlons(x,z,length,axis='x',y=5.6){const count=Math.floor(length/2.6);for(let i=0;i<=count;i++){const off=-length/2+i*length/count;box(this.static,axis==='x'?[1.25,.95,1.1]:[1.1,.95,1.25],[x+(axis==='x'?off:0),y,z+(axis==='z'?off:0)],this.materials.cap);}}
 flag(x,y,z,scale=1){const g=new T.Group();g.position.set(x,y,z);g.scale.setScalar(scale);beam(g,[0,0,0],[0,3.8,0],.055,this.materials.gold);const f=mesh(new T.PlaneGeometry(1.25,1.65,8,8),this.materials.teal,g,.63,2.65,0);f.userData.base=new Float32Array(f.geometry.attributes.position.array);const badge=sunBadge(g,.30,this.materials.gold);badge.position.set(.63,2.65,.025);this.flags.push(f);this.dynamic.add(g);return g;}
 torch(x,y,z,large=false){const g=new T.Group();g.position.set(x,y,z);cyl(g,.13,.19,large?1.3:.8,[0,(large?1.3:.8)/2,0],this.materials.iron);const basket=cyl(g,large?.35:.22,.12,.24,[0,large?1.4:.9,0],this.materials.iron);const flame=flameVolume(large?.50:.30);flame.position.y=large?1.48:1.0;g.add(flame);this.dynamic.add(g);this.fireplaces.push({g,flame,base:flame.position.y});if(this.fireplaces.length<5){const light=new T.PointLight(0xff9b47,large?7:3,large?10:6,2);light.position.y=large?1.8:1.2;g.add(light);}return g;}
 tower(x,z,level=1,kind='tower'){const g=this.defenseModel(kind,level);g.position.set(x,0,z);this.dynamic.add(g);const height=kind==='tower'?6:['frost','storm','sanctuary'].includes(kind)?3.7:2.6,collider=this.physics.addBox(x,height/2,z,kind==='tower'?4.2:3.6,height,kind==='tower'?4.2:3.6,kind);this.towerObjects.push({id:kind,x,z,model:g,level,collider});return g;}
 refit(defenses,layout=DEFAULT_LAYOUT){for(const t of this.towerObjects){t.model.removeFromParent();t.model.traverse(o=>o.geometry?.dispose());this.physics.remove(t.collider);}this.towerObjects=[];EMPLACEMENTS.forEach((p,i)=>this.tower(p.x,p.z,defenses[layout[i]],layout[i]));this.upgradeGate(defenses.gate);}
 defenseModel(kind,level){let m=this.materials||{wood:mat(0x735d40),stone:mat(0xaeb3a7,.9),cap:mat(0xb9bdab),iron:mat(0x5b7377,.4,.7),gold:mat(0xc5a667,.35,.6),teal:mat(0x487c78),roof:mat(0x496361),flame:mat(0xffc16b,.3,.1,{emissive:0xf37523,emissiveIntensity:.8})},g=new T.Group();
 if(level>=5){const accent=level>=9?(['frost','storm'].includes(kind)?0x643896:0x993c46):(['tower','ballista'].includes(kind)?0x2d5184:0x8c5a32);m={...m,teal:material('cloth',accent,{side:T.DoubleSide}),gold:material('steel',level>=9?0xdbb663:0xba9c61,{roughness:.5}),roof:worldMaterial('stone',level>=9?0x293044:0x43546a,1.3)};}
 if(!['tower','ballista','gate'].includes(kind))return fortificationModel(kind,level,m);
 if(kind==='tower'){
  const h=4+level*.15;const stone=level>=5;if(stone)cyl(g,1.65,1.95,h,[0,h/2,0],m.stone,level>=8?8:4);else{for(const x of [-1.3,1.3])for(const z of [-1.3,1.3]){box(g,[.30,h,.30],[x,h/2,z],m.wood);if(level>=2)beam(g,[x,.2,z],[x>0?-1.3:1.3,h*.68,z],.09,m.wood);if(level>=3)box(g,[.55,.7,.55],[x,.35,z],m.stone);}}
  box(g,[3.6,.3,3.6],[0,h,0],m.wood);for(const side of [-1,1]){box(g,[3.7,.65,.24],[0,h+.5,side*1.7],stone?m.stone:m.wood);box(g,[.24,.65,3.7],[side*1.7,h+.5,0],stone?m.stone:m.wood);}if(level>=3){const roof=cyl(g,0,2.7,1.2,[0,h+2.2,0],m.roof,4);roof.rotation.y=Math.PI/4;for(const x of [-1.3,1.3])for(const z of [-1.3,1.3])box(g,[.13,1.7,.13],[x,h+.85,z],m.wood);}
  if(level>=4)for(let i=0;i<9;i++)box(g,[.8,.14,.35],[1.9,i*.45,-1.5+i*.2],m.wood);
  if(level>=6)for(const x of [-1,1])box(g,[.6,.7,.07],[x,h+.9,-1.68],m.wood);
  if(level>=7)for(const x of [-1.65,1.65])for(const z of [-1.65,1.65])cyl(g,.25,.6,h*.5,[x,h*.25,z],m.stone,4);
  if(level>=8)cyl(g,.7,.85,h+1,[2.2,(h+1)/2,.8],m.stone,8);
  if(level>=9){const b=sunBadge(g,.6,m.gold);b.position.set(0,h*.65,-1.76);b.rotation.y=Math.PI;}
  if(level>=10){for(const x of [-1.8,1.8]){beam(g,[x,h,0],[x,h+3.4,0],.055,m.gold);box(g,[.7,1,.06],[x+.35,h+2.6,0],m.teal);}cyl(g,.12,.30,1,[0,h+3,0],m.gold,6);}
  g.userData.muzzle=new T.Vector3(0,h+1,-1.8);
 }else if(kind==='ballista'){
  const base=level>=4?m.stone:m.wood;cyl(g,1.6,1.9,.38,[0,.19,0],base,8);for(const x of [-.9,.9])for(const z of [-.65,.65])beam(g,[x,.25,z],[x*.45,1.6,z*.45],.11,m.wood);const aim=new T.Group();aim.position.y=1.55;g.add(aim);g.userData.aim=aim;box(aim,[.33,.28,2.7],[0,0,0],m.wood);for(const side of [-1,1])beam(aim,[side*1.7,0,-.35],[0,0,-1],level>=5?.12:.09,level>=3?m.iron:m.wood);beam(aim,[-1.7,0,-.35],[0,0,.65],.018,m.wood);beam(aim,[1.7,0,-.35],[0,0,.65],.018,m.wood);
  cyl(aim,.04,.04,2.5,[0,.2,0],m.iron).rotation.x=Math.PI/2;const bolt=cyl(aim,0,.15,.35,[0,.2,-1.4],m.iron,4);bolt.rotation.x=-Math.PI/2;
  if(level>=2)for(const x of [-1,1])box(g,[.3,.2,1.8],[x,.35,0],m.iron);
  if(level>=3){const wheel=cyl(aim,.3,.3,.2,[0,0,.8],m.gold,12);wheel.rotation.z=Math.PI/2;g.userData.crank=wheel;}
  if(level>=4)for(const x of [-.5,.5])box(aim,[.08,.18,1.8],[x,.05,0],m.iron);
  if(level>=5)for(const x of [-1,1])box(g,[.16,.45,.6],[x,1.2,.8],m.iron);
  if(level>=6){box(g,[1.3,.8,.16],[0,1.35,-.8],m.teal);for(let i=0;i<5;i++)beam(g,[-1.25+i*.11,.6,.7],[-1.25+i*.11,1.8,.7],.025,m.wood);}
  if(level>=7)for(const x of [-.6,.6])cyl(aim,.28,.28,.55,[x,.05,-.2],m.gold,10);
  if(level>=8)for(const x of [-1.3,1.3]){beam(g,[x,1.8,.7],[x,2.7,.7],.04,m.iron);box(g,[.45,.6,.4],[x,1.85,.7],m.stone);}
  if(level>=9)for(const x of [-1.7,1.7]){beam(g,[x,.2,1],[x,3.5,1],.055,m.gold);box(g,[.6,1.1,.06],[x,2.6,1],m.teal);}
  if(level>=10){const b=sunBadge(g,.65,m.gold);b.position.set(0,2.9,.8);box(aim,[.09,.07,2.4],[0,.25,0],m.flame);}
  g.userData.muzzle=new T.Vector3(0,1.75,-1.8);
 }else{
  for(const x of [-3,3])box(g,[2,6,2],[x,3,0],m.stone);box(g,[6,1.2,2],[0,5.5,0],m.stone);for(const side of [-1,1])box(g,[1.7,4.4,.30],[side*.95,2.2,0],m.wood);for(let i=0;i<level;i++)box(g,[3.8,.09,.07],[0,.5+i*.33,-.2],i>=5?m.gold:m.iron);if(level>=5)for(let i=0;i<8;i++)cyl(g,.035,.035,4.5,[-1.6+i*.46,2.3,-.28],m.iron,6);if(level>=7)for(const side of [-1,1])box(g,[1,1.6,3],[side*3,5.3,0],m.cap);if(level>=9){const b=sunBadge(g,.65,m.gold);b.position.set(0,5.5,-1.05);b.rotation.y=Math.PI;}g.userData.muzzle=new T.Vector3();}
 return g;
 }
 castle(defenses,layout=DEFAULT_LAYOUT){const m=this.materials;for(const x of [-20.8,19.5])this.solid([Math.abs(x)<20?29:32,5.1,3],[x,2.55,-17],m.stone); // central gate opening
 // Right postern leaves a real opening between front wall and side tower.
 this.solid([3,5.1,50],[-35,2.55,8],m.stone);this.solid([3,5.1,50],[35,2.55,8],m.stone);this.solid([70,5.1,3],[0,2.55,34],m.stone);
 this.merlons(-20.8,-17,31);this.merlons(19.5,-17,29);this.merlons(-35,8,50,'z');this.merlons(35,8,50,'z');this.merlons(0,34,70);
 // A substantial gatehouse with an open central passage, rather than a solid box facade.
 for(const x of [-6.4,6.4]){this.solid([4.2,8,5],[x,4,-17],m.stone);this.merlons(x,-17,4.2,'x',8.2);cyl(this.static,2.4,2.7,.3,[x,8,-17],m.cap,8);this.flag(x,8.3,-17,.85);}
 this.solid([8.5,2.1,4.8],[0,7.2,-17],m.stone);
 this.gate=new T.Group();for(const side of [-1,1])box(this.gate,[3.8,5.0,.36],[side*1.98,2.5,0],m.wood);for(let i=0;i<2+defenses.gate;i++)box(this.gate,[7.7,.14,.15],[0,.65+i*.35,-.23],m.iron);this.gate.position.z=-17;this.dynamic.add(this.gate);this.gate.visible=false;this.gateCollider=null;this.upgradeGate(defenses.gate);
 for(const x of [-33,33])for(const z of [-17,34]){cyl(this.static,3.0,3.35,6.5,[x,3.25,z],m.stone,10);this.physics.addBox(x,3.1,z,5.4,6.2,5.4,'tower');for(let i=0;i<10;i++){let a=i*Math.PI/5;box(this.static,[.9,.95,.9],[x+Math.sin(a)*2.5,6.9,z+Math.cos(a)*2.5],m.cap);}}
 // Walkable stairs and parapet platform: the visual steps are the collision steps.
 for(let i=0;i<18;i++)this.solid([3.2,(i+1)*.28,.70],[-30,(i+1)*.14,-8+i*.7],m.stone,'stair');this.solid([4,.4,24.4],[-30,5.0,16.3],m.cap,'rampart');this.solid([.8,1.0,24.4],[-32.2,5.7,16.3],m.stone,'parapet');
 for(const x of [-11,11]){this.solid([1.6,11,15],[x,5.5,26],m.stone);for(const z of [20,26,32]){box(this.static,[.08,2.4,.8],[x>0?10.15:-10.15,6,z],m.dark);}}
 this.solid([7.3,10,1.4],[-7,5,19],m.stone);this.solid([7.3,10,1.4],[7,5,19],m.stone);this.solid([8,3,1.4],[0,8.5,19],m.stone);this.solid([23,11,1.5],[0,5.5,33],m.stone);craftedRoof(this.static,m,{x:0,y:11,z:26,width:24.5,depth:16.7,rise:5.8,dormers:3,tint:0x3c4b64});
 cyl(this.static,3.7,4.2,19,[0,9.5,30],m.stone,10);cyl(this.static,0,4.7,4.8,[0,21.1,30],m.roof,10);this.flag(0,23.5,30,1.15);for(let i=0;i<5;i++){box(this.static,[1.3,1.8,.12],[0,4+i*3.1,25.8],m.dark);}this.torch(-4,0,17,true);this.torch(4,0,17,true);
 this.beacon=createBeacon(this);this.dynamic.add(this.beacon);this.physics.addBox(0,.7,6,2.2,1.4,2.2,'beacon');
 EMPLACEMENTS.forEach((p,i)=>this.tower(p.x,p.z,defenses[layout[i]]||1,layout[i]));
 for(const x of [-28,28])this.flag(x,0,-25,1.2);
 }

 upgradeGate(level){if(this.gateDecor)this.gateDecor.removeFromParent();const g=new T.Group(),m=this.materials;g.position.z=-17;for(let i=1;i<level;i++){const side=i%2?-1:1,y=1+Math.floor((i-1)/2)*1.6;box(g,[4.4,.23,5.25],[side*6.4,y,0],i>=7?m.gold:m.cap);}if(level>=3)for(const x of [-8.6,8.6]){box(g,[.65,5,5.8],[x,2.5,0],m.stone);box(g,[.85,.3,6],[x,5,0],m.cap);}if(level>=5)for(const x of [-6.4,6.4])box(g,[1.7,1.2,1.7],[x,8.6,0],m.stone);if(level>=7)for(const x of [-6.4,6.4])cyl(g,0,2.9,1.8,[x,9.4,0],m.roof,8);if(level>=9){for(const z of [-2.6,2.6]){const badge=sunBadge(g,.8,m.gold);badge.position.set(0,7.2,z);if(z<0)badge.rotation.y=Math.PI;}}if(level>=10)for(const x of [-9,9]){beam(g,[x,0,0],[x,10.5,0],.08,m.gold);box(g,[1,2,.05],[x+.5,9,0],m.teal);}this.dynamic.add(g);this.gateDecor=g;}
 setGate(closed){this.gate.visible=closed;if(closed&&!this.gateCollider)this.gateCollider=this.physics.addBox(0,2.5,-17,7.9,5,.6,'gate');else if(!closed&&this.gateCollider){this.physics.remove(this.gateCollider);this.gateCollider=null;}}
 hut(x,z,w=8,d=6,angle=0){const g=new T.Group();g.position.set(x,0,z);g.rotation.y=angle;box(g,[w,3.8,d],[0,1.9,0],this.materials.stone);box(g,[w+.6,.25,d+.5],[0,3.8,0],this.materials.wood);if(z<0)craftedRoof(g,this.materials,{y:3.9,width:w+.8,depth:d+.8,rise:2.4,dormers:1,tint:x<0?0x77503f:0x3d5566});for(const xx of [-w*.4,0,w*.4])box(g,[.15,3.8,.12],[xx,1.9,d*.51],this.materials.wood);box(g,[1.3,2.4,.09],[0,1.2,d*.516],this.materials.dark);for(const xx of [-w*.29,w*.29]){box(g,[1,1,.1],[xx,2.1,d*.52],this.materials.dark);box(g,[1.1,.1,.18],[xx,2.0,d*.53],this.materials.wood);}this.static.add(g);this.physics.addBox(x,1.9,z,w,3.8,d,'building',angle);this.nav.push({x,z,hx:w/2+.5,hz:d/2+.5,top:3.8});}
 village(){const m=this.materials;this.hut(-24,12,11,6);this.hut(25,13,10,6);this.hut(-25,25,8,7);this.hut(25,26,8,7);this.hut(-25,-4,8,5);this.hut(26,-4,7,5);
 // Forge, anvil and merchandise are world objects next to their vendors.
 this.solid([2,1.2,1.7],[-22,.6,7],m.stone,'forge');this.torch(-22,1.2,7,true);forgeCraft(this);
 for(let i=0;i<5;i++){const sword=weapon(i%2?'spear':'sword',i+1);sword.position.set(-24+i*.7,1.5,9);sword.rotation.z=.2;this.static.add(sword);}
 for(let i=0;i<3;i++){const x=-16+i*3;beam(this.static,[x,0,-10],[x,1.2,-10],.09,m.wood);const target=cyl(this.static,.50,.50,.12,[x,1.3,-10],m.wood,20);target.rotation.x=Math.PI/2;for(const radius of [.37,.20]){const tor=mesh(new T.TorusGeometry(radius,.022,4,20),m.teal,this.static,x,1.3,-9.92);}}
 this.solid([3,1.1,2],[0,.55,15.5],m.wood,'war-table');box(this.static,[2.7,.05,1.7],[0,1.12,15.5],mat(0xb8a779));for(let i=0;i<6;i++)cyl(this.static,.055,.08,.3,[-1+i*.4,1.3,15.5+(i%2)*.4],m.teal,6);
 for(const s of SERVICES){const p={...s,y:0};this.interactables.push({kind:'vendor',...p});}
 // Crates, paving and gardens leave generous walkable routes.
 for(const [x,z]of [[29,4],[28,20],[-28,18],[-15,29]]){this.solid([1.2,1.2,1.2],[x,.6,z],m.wood,'crate');box(this.static,[1.25,.12,.12],[x,1,z+.61],m.iron);}
 for(let z=-13;z<19;z+=2.4)for(const x of [-1.5,1.5])box(this.static,[2.8,.025,2.2],[x,-.03,z],m.cap);
 // Crypt entrance outside the east wall.
 this.solid([4.5,2.8,5.5],[53,1.4,-2],m.stone,'crypt');box(this.static,[1.8,2.2,.12],[53,1.1,1],m.dark);this.torch(50.8,0,1);this.interactables.push({kind:'crypt',id:'crypt',name:'The oathkeeper’s crypt',x:53,z:3,y:0});
 }

 courtyardDetails(){const m=this.materials,r=seeded(93),bag=burlap(),leaf=mat(0x4d6338,.98),flower=mat(0xb49b62,.8),cloth=material('cloth',0x173e42,{side:T.DoubleSide});
 // Projecting buttresses, wall courses and suspended standards break the long facade.
 for(const x of [-29,-23,-17,-11,11,17,23,29]){box(this.static,[.85,5.1,4.0],[x,2.55,-17],m.stoneDark);box(this.static,[1.1,.25,4.2],[x,4.7,-17],m.cap);}
 for(const z of [-18.55,-15.4])for(const y of [.4,4.7])for(const x of [-19,19])box(this.static,[28,.25,.3],[x,y,z],m.cap);
 for(const x of [-19,19,-6.4,6.4]){const y=Math.abs(x)<8?6.0:3.7;const banner=mesh(new T.PlaneGeometry(1.4,2.6,6,8),cloth,this.dynamic,x,y,-14.94);banner.userData.base=new Float32Array(banner.geometry.attributes.position.array);this.flags.push(banner);const badge=sunBadge(this.static,.34,m.gold);badge.position.set(x,y+.3,-14.89);beam(this.static,[x-.85,y+1.4,-14.89],[x+.85,y+1.4,-14.89],.045,m.gold);}
 for(const [x,z] of [[-13,4],[13,4],[-14,20],[14,20],[-28,-11],[28,-11]]){box(this.static,[3.2,.45,2],[x,.22,z],m.stoneDark);box(this.static,[2.9,.08,1.7],[x,.46,z],mat(0x524e36));for(let i=0;i<9;i++){const xx=x+(r()-.5)*2.7,zz=z+(r()-.5)*1.5;this.leafInstances ||= [];for(let k=0;k<22;k++)this.leafInstances.push({x:xx+(r()-.5)*.65,y:.5+r()*.43,z:zz+(r()-.5)*.65,rx:r()*6,ry:r()*6,rz:r()*6,s:.9+r()*.5,v:r()});for(let j=0;j<3;j++)sphere(this.static,.045,[xx+(r()-.5)*.4,.83+r()*.12,zz+(r()-.5)*.4],flower,6);}}
 // Barrels, sacks, carts and stools make the vendors places to visit.
 for(const [x,z] of [[-26,7],[-26,8.2],[27,7],[28,8],[-20,-2],[22,-8],[24,23],[-24,20]]){cyl(this.static,.42,.40,1.0,[x,.5,z],m.wood,12);for(const y of [.14,.82]){const band=mesh(new T.TorusGeometry(.405,.035,4,12),m.iron,this.static,x,y,z);band.rotation.x=Math.PI/2;}}
 for(const x of [-16,17]){box(this.static,[2.8,.6,1.8],[x,.85,13],m.wood);for(const side of [-1,1])for(const dz of [-.6,.6]){const wheel=cyl(this.static,.55,.55,.10,[x+side*1.45,.58,13+dz],m.wood,12);wheel.rotation.z=Math.PI/2;const rim=mesh(new T.TorusGeometry(.51,.045,4,16),m.iron,this.static,x+side*1.51,.58,13+dz);rim.rotation.y=Math.PI/2;}for(let j=0;j<4;j++){const b=sack(this.static,[x+(j%2-.5)*.8,1.16,12.6+Math.floor(j/2)*.7],bag,.85);b.rotation.y=j*.8;}}
 // Hanging lanterns catch the sunset under the market awnings.
 for(const x of [-25,-19,19,25]){beam(this.static,[x,3.25,5],[x,2.6,5],.022,m.iron);box(this.static,[.24,.36,.24],[x,2.43,5],m.gold);box(this.static,[.16,.25,.16],[x,2.43,5],m.flame);}
 // Roof shingles and chimney stacks are visible from the rampart.
 for(const x of [-24,25]){box(this.static,[.75,3,.85],[x+2.7,5.4,12],m.stone);for(let i=0;i<5;i++)box(this.static,[10.8,.045,.055],[x,4.2+i*.33,14.8-i*.52],m.wood);}
 }
 scenery(r){const m=this.materials,b=BIOMES[this.biome];const rockmat=worldMaterial('rock',0xc6c5b8,2.5,{normalScale:new T.Vector2(.8,.8)});for(let i=0;i<85;i++){let x=(r()-.5)*224,z=-33-r()*180;if(castleReserved(this,x,z,6)||Math.abs(x)<9||Math.hypot(x,z+35)<10)continue;let radius=1+r()*3.0,y=this.height(x,z);const g=new T.IcosahedronGeometry(radius,1);const p=g.attributes.position;for(let k=0;k<p.count;k++){p.setXYZ(k,p.getX(k)*(1+(r()-.5)*.3),p.getY(k)*(.45+r()*.16),p.getZ(k)*(1+(r()-.5)*.3));}g.computeVertexNormals();const ob=mesh(g,rockmat,this.static,x,y+radius*.22,z);this.physics.addHull(new Float32Array(p.array),[x,y+radius*.22,z],'rock');this.rocks.push({x,y,z,r:radius});this.nav.push({x,z,hx:radius+.45,hz:radius+.45,top:y+radius*.8});}
 // A specific low rock near the gate is a reliable jump/collision practice object.
 const rock=mesh(new T.DodecahedronGeometry(1.55,0),rockmat,this.static,8,.45,-32);rock.scale.set(1,.6,1);const points=new Float32Array(rock.geometry.attributes.position.array);for(let i=1;i<points.length;i+=3)points[i]*=.6;this.physics.addHull(points,[8,.45,-32],'rock');this.rocks.push({x:8,y:0,z:-32,r:1.55,test:true});this.nav.push({x:8,z:-32,hx:1.9,hz:1.9,top:1.4});
 const treeCount=this.biome==='forest'?108:this.biome==='desert'?30:75;for(let i=0;i<treeCount;i++){let x=(r()-.5)*235,z=-35-r()*180;if(castleReserved(this,x,z,8)||Math.abs(x)<13||this.rocks.some(o=>Math.hypot(o.x-x,o.z-z)<o.r+1))continue;const y=this.height(x,z),h=5+r()*6;this.tree(x,y,z,h,this.biome==='snow',r);}
 // Instanced grass, flowers and small stones keep draw calls low.
 const n=this.biome==='snow'?500:this.biome==='desert'?2200:12000,blade=new T.BufferGeometry(),bp=[],uv=[],bi=[];for(let b=0;b<2;b++){const a=b*Math.PI/2,c=Math.cos(a),ss=Math.sin(a),off=bp.length/3;for(const [xx,yy,u,v]of [[-.44,0,0,0],[.44,0,1,0],[-.44,.55,0,1],[.44,.55,1,1]]){bp.push(xx*c,yy-.055,xx*ss);uv.push(u,v);}bi.push(off,off+1,off+2,off+1,off+3,off+2);}blade.setAttribute('position',new T.Float32BufferAttribute(bp,3));blade.setAttribute('uv',new T.Float32BufferAttribute(uv,2));blade.setIndex(bi);blade.computeVertexNormals();const grassmat=mat(0xffffff,.96,0,{map:ART.textures.meadow,alphaTest:.35,alphaToCoverage:true,side:T.DoubleSide});grassmat.onBeforeCompile=s=>{s.uniforms.uWind={value:0};this.grassShader=s;s.vertexShader='uniform float uWind;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.x += sin(uWind * 1.8 + instanceMatrix[3].x * .6 + instanceMatrix[3].z * .4) * position.y * .18;');};const grass=new T.InstancedMesh(blade,grassmat,n),dummy=new T.Object3D(),color=new T.Color();for(let i=0;i<n;i++){let x=(r()-.5)*235,z=-26-r()*195;if(Math.abs(x)<6)x+=x<0?-9:9;if(castleReserved(this,x,z,2))x=x<0?-65:65;let y=this.height(x,z);dummy.position.set(x,y+.01,z);dummy.rotation.set(0,r()*Math.PI,0);dummy.scale.set(.8+r()*1.1,.6+r()*.7,.8+r()*1.1);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix);color.setHex(this.biome==='snow'?0xcad3cc:this.biome==='desert'?0xdcc6a4:r()>.7?0xe6d8ae:0xd1dcc0).multiplyScalar(.84+r()*.25);grass.setColorAt(i,color);}grass.receiveShadow=true;this.root.add(grass);
 // Distant sculpted ridges and islands shape a believable horizon.

 if(this.biome==='quarry'){for(let i=0;i<5;i++){const x=55+i*5,z=-93-i*7,y=this.height(x,z);box(this.static,[11,3,7],[x,y+1,z],m.stone);this.physics.addBox(x,y+1,z,11,3,7,'quarry');this.nav.push({x,z,hx:6,hz:4,top:y+2.5});}}
 if(this.biome==='forest'||this.biome==='desert')for(let i=0;i<12;i++){const x=45+(i%4)*5,z=-75-Math.floor(i/4)*8,y=this.height(x,z);cyl(this.static,.7,1,3+r()*3,[x,y+2,z],m.stone,8);this.physics.addBox(x,y+2,z,1.4,4,1.4,'ruin');this.nav.push({x,z,hx:1.15,hz:1.15,top:y+4});}
 this.flag(-48,this.height(-48,-70),-70,.9);this.interactables.push({kind:'camp',id:'ridge',name:'Capture ridge supply camp',x:-48,z:-70,y:this.height(-48,-70)});
 }
 tree(x,y,z,h,pine,r){const start=this.leafInstances.length;detailedTree(this,x,y,z,h,pine,r);for(let i=start;i<this.leafInstances.length;i++)this.leafInstances[i].s*=1.28;}
 river(){const b=BIOMES[this.biome],length=this.siegeMode?-this.minZ-15:220,geo=new T.PlaneGeometry(this.biome==='river'?13:17,length,4,Math.ceil(length/3.66));geo.rotateX(-Math.PI/2);const p=geo.attributes.position;for(let i=0;i<p.count;i++){const z=p.getZ(i)-(this.siegeMode?-this.minZ/2+10:120),x=this.biome==='river'?12+Math.sin(z*.045)*15:-85+Math.sin(z*.032)*9;p.setXYZ(i,p.getX(i)+x,this.biome==='river'?-1.3:-1.4,z);}const material=new T.MeshPhysicalMaterial({color:b.water,metalness:.26,roughness:.24,transparent:true,opacity:.78,side:T.DoubleSide,clearcoat:.8});const water=mesh(geo,material,this.dynamic);water.castShadow=false;water.receiveShadow=true;this.water=water;if(this.biome==='river'){for(const z of [-63,-126]){const x=12+Math.sin(z*.045)*15;for(let i=0;i<16;i++){let xx=x-8+i;const y=this.height(xx,z)+.12;box(this.static,[.92,.16,4],[xx,y,z],this.materials.wood);this.physics.addBox(xx,y,z,.92,.16,4,'bridge');}}}}
 placeTreasures(){const positions=[{id:'ivy-stair',name:'The ivy stair cache',x:-29,z:27,y:5.25,hub:true},{id:'mill-cache',name:'The mill’s forgotten chest',x:58,z:-38,y:this.height(58,-38),hub:true},{id:'ridge-cache',name:'A scout’s hidden cache',x:-58,z:-86,y:this.height(-58,-86)},{id:'ruin-cache',name:'The buried oath chest',x:65,z:-133,y:this.height(65,-133)}];for(const t of positions){const g=new T.Group();g.position.set(t.x,t.y,t.z);box(g,[1.1,.65,.70],[0,.325,0],this.materials.wood);for(const x of [-.39,.39])box(g,[.075,.68,.74],[x,.34,0],this.materials.gold);const lid=new T.Group();lid.position.set(0,.65,-.35);box(lid,[1.12,.19,.72],[0,.095,.35],this.materials.wood);box(lid,[.14,.20,.08],[0,.04,.73],this.materials.gold);g.add(lid);this.dynamic.add(g);const o={...t,kind:'treasure',model:g,lid};this.treasures.push(o);this.interactables.push(o);}}
 update(dt,time){this.time=time;updateScenography(this,dt,time);for(const p of this.scenicMotion||[])p.object.rotation[p.axis]+=dt*p.speed;for(const t of this.towerObjects){t.recoil=Math.max(0,(t.recoil||0)-dt);if(t.model.userData.aim)t.model.userData.aim.position.z=Math.sin(t.recoil/.35*Math.PI)*.24;updateFortification(t,time);if(t.model.userData.crank&&t.recoil>0)t.model.userData.crank.rotation.x+=dt*12;}for(const f of this.flags){const p=f.geometry.attributes.position,b=f.userData.base;for(let i=0;i<p.count;i++){const x=b[i*3];p.array[i*3+2]=Math.sin(time*2.1+x*3+b[i*3+1]*1.5)*.14*(x+.65);}p.needsUpdate=true;}for(const f of this.fireplaces){f.flame.scale.y=1+Math.sin(time*9+f.g.position.x)*.13;if(f.flame.userData.flameMaterial)f.flame.userData.flameMaterial.uniforms.time.value=time;f.flame.position.y=f.base+Math.sin(time*6)*.03;}if(this.grassShader)this.grassShader.uniforms.uWind.value=time;if(this.leafShader)this.leafShader.uniforms.uWind.value=time;if(this.water){this.water.material.roughness=.21+Math.sin(time*.8)*.025;}}
}
